package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* compiled from: r8-map-id-f21f5e89e3d3d92eca33bfe12a7775f49cadfb54340e756eb509706243ac6f5c */
/* loaded from: classes.dex */
public final class uc {
    public int a;
    public final xc b;
    public final wc c;
    public final vc d;
    public final yc e;
    public HashMap f;

    public uc() {
        xc xcVar = new xc();
        xcVar.a = 0;
        xcVar.b = 0;
        xcVar.c = 1.0f;
        xcVar.d = Float.NaN;
        this.b = xcVar;
        wc wcVar = new wc();
        wcVar.a = -1;
        wcVar.b = 0;
        wcVar.c = -1;
        wcVar.d = Float.NaN;
        wcVar.e = Float.NaN;
        wcVar.f = Float.NaN;
        wcVar.g = -1;
        wcVar.h = null;
        wcVar.i = -1;
        this.c = wcVar;
        vc vcVar = new vc();
        vcVar.a = false;
        vcVar.d = -1;
        vcVar.e = -1;
        vcVar.f = -1.0f;
        vcVar.g = true;
        vcVar.h = -1;
        vcVar.i = -1;
        vcVar.j = -1;
        vcVar.k = -1;
        vcVar.l = -1;
        vcVar.m = -1;
        vcVar.n = -1;
        vcVar.o = -1;
        vcVar.p = -1;
        vcVar.q = -1;
        vcVar.r = -1;
        vcVar.s = -1;
        vcVar.t = -1;
        vcVar.u = -1;
        vcVar.v = -1;
        vcVar.w = 0.5f;
        vcVar.x = 0.5f;
        vcVar.y = null;
        vcVar.z = -1;
        vcVar.A = 0;
        vcVar.B = 0.0f;
        vcVar.C = -1;
        vcVar.D = -1;
        vcVar.E = -1;
        vcVar.F = 0;
        vcVar.G = 0;
        vcVar.H = 0;
        vcVar.I = 0;
        vcVar.J = 0;
        vcVar.K = 0;
        vcVar.L = 0;
        vcVar.M = Integer.MIN_VALUE;
        vcVar.N = Integer.MIN_VALUE;
        vcVar.O = Integer.MIN_VALUE;
        vcVar.P = Integer.MIN_VALUE;
        vcVar.Q = Integer.MIN_VALUE;
        vcVar.R = Integer.MIN_VALUE;
        vcVar.S = Integer.MIN_VALUE;
        vcVar.T = -1.0f;
        vcVar.U = -1.0f;
        vcVar.V = 0;
        vcVar.W = 0;
        vcVar.X = 0;
        vcVar.Y = 0;
        vcVar.Z = 0;
        vcVar.a0 = 0;
        vcVar.b0 = 0;
        vcVar.c0 = 0;
        vcVar.d0 = 1.0f;
        vcVar.e0 = 1.0f;
        vcVar.f0 = -1;
        vcVar.g0 = 0;
        vcVar.h0 = -1;
        vcVar.l0 = false;
        vcVar.m0 = false;
        vcVar.n0 = true;
        vcVar.o0 = 0;
        this.d = vcVar;
        yc ycVar = new yc();
        ycVar.a = 0.0f;
        ycVar.b = 0.0f;
        ycVar.c = 0.0f;
        ycVar.d = 1.0f;
        ycVar.e = 1.0f;
        ycVar.f = Float.NaN;
        ycVar.g = Float.NaN;
        ycVar.h = -1;
        ycVar.i = 0.0f;
        ycVar.j = 0.0f;
        ycVar.k = 0.0f;
        ycVar.l = false;
        ycVar.m = 0.0f;
        this.e = ycVar;
        this.f = new HashMap();
    }

    public final void a(pc pcVar) {
        vc vcVar = this.d;
        pcVar.e = vcVar.h;
        pcVar.f = vcVar.i;
        pcVar.g = vcVar.j;
        pcVar.h = vcVar.k;
        pcVar.i = vcVar.l;
        pcVar.j = vcVar.m;
        pcVar.k = vcVar.n;
        pcVar.l = vcVar.o;
        pcVar.m = vcVar.p;
        pcVar.n = vcVar.q;
        pcVar.o = vcVar.r;
        pcVar.s = vcVar.s;
        pcVar.t = vcVar.t;
        pcVar.u = vcVar.u;
        pcVar.v = vcVar.v;
        ((ViewGroup.MarginLayoutParams) pcVar).leftMargin = vcVar.F;
        ((ViewGroup.MarginLayoutParams) pcVar).rightMargin = vcVar.G;
        ((ViewGroup.MarginLayoutParams) pcVar).topMargin = vcVar.H;
        ((ViewGroup.MarginLayoutParams) pcVar).bottomMargin = vcVar.I;
        pcVar.A = vcVar.R;
        pcVar.B = vcVar.Q;
        pcVar.x = vcVar.N;
        pcVar.z = vcVar.P;
        pcVar.E = vcVar.w;
        pcVar.F = vcVar.x;
        pcVar.p = vcVar.z;
        pcVar.q = vcVar.A;
        pcVar.r = vcVar.B;
        pcVar.G = vcVar.y;
        pcVar.T = vcVar.C;
        pcVar.U = vcVar.D;
        pcVar.I = vcVar.T;
        pcVar.H = vcVar.U;
        pcVar.K = vcVar.W;
        pcVar.J = vcVar.V;
        pcVar.W = vcVar.l0;
        pcVar.X = vcVar.m0;
        pcVar.L = vcVar.X;
        pcVar.M = vcVar.Y;
        pcVar.P = vcVar.Z;
        pcVar.Q = vcVar.a0;
        pcVar.N = vcVar.b0;
        pcVar.O = vcVar.c0;
        pcVar.R = vcVar.d0;
        pcVar.S = vcVar.e0;
        pcVar.V = vcVar.E;
        pcVar.c = vcVar.f;
        pcVar.a = vcVar.d;
        pcVar.b = vcVar.e;
        ((ViewGroup.MarginLayoutParams) pcVar).width = vcVar.b;
        ((ViewGroup.MarginLayoutParams) pcVar).height = vcVar.c;
        String str = vcVar.k0;
        if (str != null) {
            pcVar.Y = str;
        }
        pcVar.Z = vcVar.o0;
        pcVar.setMarginStart(vcVar.K);
        pcVar.setMarginEnd(vcVar.J);
        pcVar.a();
    }

    public final Object clone() {
        uc ucVar = new uc();
        vc vcVar = ucVar.d;
        vcVar.getClass();
        vc vcVar2 = this.d;
        vcVar.a = vcVar2.a;
        vcVar.b = vcVar2.b;
        vcVar.c = vcVar2.c;
        vcVar.d = vcVar2.d;
        vcVar.e = vcVar2.e;
        vcVar.f = vcVar2.f;
        vcVar.g = vcVar2.g;
        vcVar.h = vcVar2.h;
        vcVar.i = vcVar2.i;
        vcVar.j = vcVar2.j;
        vcVar.k = vcVar2.k;
        vcVar.l = vcVar2.l;
        vcVar.m = vcVar2.m;
        vcVar.n = vcVar2.n;
        vcVar.o = vcVar2.o;
        vcVar.p = vcVar2.p;
        vcVar.q = vcVar2.q;
        vcVar.r = vcVar2.r;
        vcVar.s = vcVar2.s;
        vcVar.t = vcVar2.t;
        vcVar.u = vcVar2.u;
        vcVar.v = vcVar2.v;
        vcVar.w = vcVar2.w;
        vcVar.x = vcVar2.x;
        vcVar.y = vcVar2.y;
        vcVar.z = vcVar2.z;
        vcVar.A = vcVar2.A;
        vcVar.B = vcVar2.B;
        vcVar.C = vcVar2.C;
        vcVar.D = vcVar2.D;
        vcVar.E = vcVar2.E;
        vcVar.F = vcVar2.F;
        vcVar.G = vcVar2.G;
        vcVar.H = vcVar2.H;
        vcVar.I = vcVar2.I;
        vcVar.J = vcVar2.J;
        vcVar.K = vcVar2.K;
        vcVar.L = vcVar2.L;
        vcVar.M = vcVar2.M;
        vcVar.N = vcVar2.N;
        vcVar.O = vcVar2.O;
        vcVar.P = vcVar2.P;
        vcVar.Q = vcVar2.Q;
        vcVar.R = vcVar2.R;
        vcVar.S = vcVar2.S;
        vcVar.T = vcVar2.T;
        vcVar.U = vcVar2.U;
        vcVar.V = vcVar2.V;
        vcVar.W = vcVar2.W;
        vcVar.X = vcVar2.X;
        vcVar.Y = vcVar2.Y;
        vcVar.Z = vcVar2.Z;
        vcVar.a0 = vcVar2.a0;
        vcVar.b0 = vcVar2.b0;
        vcVar.c0 = vcVar2.c0;
        vcVar.d0 = vcVar2.d0;
        vcVar.e0 = vcVar2.e0;
        vcVar.f0 = vcVar2.f0;
        vcVar.g0 = vcVar2.g0;
        vcVar.h0 = vcVar2.h0;
        vcVar.k0 = vcVar2.k0;
        int[] iArr = vcVar2.i0;
        if (iArr == null || vcVar2.j0 != null) {
            vcVar.i0 = null;
        } else {
            vcVar.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        vcVar.j0 = vcVar2.j0;
        vcVar.l0 = vcVar2.l0;
        vcVar.m0 = vcVar2.m0;
        vcVar.n0 = vcVar2.n0;
        vcVar.o0 = vcVar2.o0;
        wc wcVar = ucVar.c;
        wcVar.getClass();
        wc wcVar2 = this.c;
        wcVar2.getClass();
        wcVar.a = wcVar2.a;
        wcVar.c = wcVar2.c;
        wcVar.e = wcVar2.e;
        wcVar.d = wcVar2.d;
        xc xcVar = this.b;
        int i = xcVar.a;
        xc xcVar2 = ucVar.b;
        xcVar2.a = i;
        xcVar2.c = xcVar.c;
        xcVar2.d = xcVar.d;
        xcVar2.b = xcVar.b;
        yc ycVar = ucVar.e;
        ycVar.getClass();
        yc ycVar2 = this.e;
        ycVar2.getClass();
        ycVar.a = ycVar2.a;
        ycVar.b = ycVar2.b;
        ycVar.c = ycVar2.c;
        ycVar.d = ycVar2.d;
        ycVar.e = ycVar2.e;
        ycVar.f = ycVar2.f;
        ycVar.g = ycVar2.g;
        ycVar.h = ycVar2.h;
        ycVar.i = ycVar2.i;
        ycVar.j = ycVar2.j;
        ycVar.k = ycVar2.k;
        ycVar.l = ycVar2.l;
        ycVar.m = ycVar2.m;
        ucVar.a = this.a;
        return ucVar;
    }
}
