package b0;

/* loaded from: classes.dex */
public abstract class m {

    /* renamed from: a, reason: collision with root package name */
    public static final C0156b f2465a;

    /* renamed from: b, reason: collision with root package name */
    public static final C0156b f2466b;

    /* renamed from: c, reason: collision with root package name */
    public static final C0156b f2467c;

    /* renamed from: d, reason: collision with root package name */
    public static final C0156b f2468d;

    static {
        new C0156b("VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK", 0);
        new C0156b("OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER", 0);
        new C0156b("SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE", 4);
        new C0156b("DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS", 1);
        new C0156b("START_SAFE_BROWSING", "START_SAFE_BROWSING", 5);
        new C0156b("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST", 5);
        new C0156b("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST", 5);
        new C0156b("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST", 5);
        new C0156b("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST", 5);
        new C0156b("SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL", 5);
        new C0156b("SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE", 1);
        new C0156b("SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE", 1);
        new C0156b("SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS", 1);
        new C0156b("SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS", 1);
        new C0156b("SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS", 1);
        new C0156b("SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", 1);
        new C0156b("RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR", 0);
        new C0156b("RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR", 0);
        new C0156b("SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS", 1);
        new C0156b("SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT", 5);
        new C0156b("WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT", 1);
        new C0156b("WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION", 0);
        new C0156b("WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE", 0);
        new C0156b("SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", 5);
        new C0156b("SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED", 5);
        new C0156b("SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", 5);
        new C0156b("WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE", 0);
        new C0156b("WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE", 0);
        f2465a = new C0156b("WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER", 2);
        new C0156b("WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", 0);
        new C0156b("CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL", 0);
        new C0156b("POST_WEB_MESSAGE", "POST_WEB_MESSAGE", 0);
        new C0156b("WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE", 0);
        new C0156b("GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT", 4);
        new C0156b("GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT", 4);
        new C0156b("GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER", 7);
        new C0156b("WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE", 7);
        new C0156b("TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE", 6);
        new C0162h();
        new C0162h();
        new C0162h();
        new C0156b("WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", 7);
        new k();
        new C0156b("PROXY_OVERRIDE", "PROXY_OVERRIDE:3", 2);
        f2466b = new C0156b("MULTI_PROCESS", "MULTI_PROCESS_QUERY", 2);
        new C0156b("FORCE_DARK", "FORCE_DARK", 7);
        new C0156b("FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR", 2);
        f2467c = new C0156b("WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER", 2);
        new C0156b("DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1", 2);
        new C0156b("PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS", 2);
        new C0156b("GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER", 2);
        new C0156b("ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", 2);
        new C0156b("GET_COOKIE_INFO", "GET_COOKIE_INFO", 2);
        new C0156b("REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST", 2);
        new C0156b("USER_AGENT_METADATA", "USER_AGENT_METADATA", 2);
        new l("USER_AGENT_METADATA_FORM_FACTORS", "USER_AGENT_METADATA", 0);
        new l("MULTI_PROFILE", "MULTI_PROFILE", 1);
        new C0156b("ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR", 2);
        new C0156b("WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS", 2);
        new C0156b("MUTE_AUDIO", "MUTE_AUDIO", 2);
        new C0156b("WEB_AUTHENTICATION", "WEB_AUTHENTICATION", 2);
        new C0156b("SPECULATIVE_LOADING_STATUS", "SPECULATIVE_LOADING", 2);
        new C0156b("BACK_FORWARD_CACHE", "BACK_FORWARD_CACHE", 2);
        new C0156b("BACK_FORWARD_CACHE_SETTINGS", "BACK_FORWARD_CACHE_SETTINGS", 2);
        new C0156b("BACK_FORWARD_CACHE_SETTINGS_EXPERIMENTAL_V3", "BACK_FORWARD_CACHE_SETTINGS_V3", 2);
        new C0156b("BACK_FORWARD_CACHE_SETTINGS_EXPERIMENTAL_V4", "BACK_FORWARD_CACHE_SETTINGS_V4", 2);
        new C0156b("DELETE_BROWSING_DATA", "WEB_STORAGE_DELETE_BROWSING_DATA", 2);
        new l("PREFETCH_URL_V5", "PREFETCH_URL_V5", 2);
        new C0156b("ASYNC_WEBVIEW_STARTUP_V2");
        new C0156b("ASYNC_WEBVIEW_STARTUP");
        new C0156b("ASYNC_WEBVIEW_STARTUP_ASYNC_STARTUP_LOCATIONS");
        new C0156b("DEFAULT_TRAFFICSTATS_TAGGING", "DEFAULT_TRAFFICSTATS_TAGGING", 2);
        new C0156b("PRERENDER_URL_V2", "PRERENDER_URL_V3", 2);
        new C0156b("SPECULATIVE_LOADING_CONFIG_V2", "SPECULATIVE_LOADING_CONFIG_V2", 2);
        new C0156b("PREFETCH_CACHE_V1", "PREFETCH_CACHE_V1", 2);
        new C0156b("SET_MAX_PRERENDERS_V1", "SET_MAX_PRERENDERS_V1", 2);
        new C0156b("SAVE_STATE", "SAVE_STATE", 2);
        new C0156b("NAVIGATION_GET_WEB_RESOURCE_ERROR", "NAVIGATION_GET_WEB_RESOURCE_ERROR", 2);
        new C0156b("NAVIGATION_LISTENER", "PAGE_GET_URL", 2);
        f2468d = new C0156b("PROVIDER_WEAKLY_REF_WEBVIEW", "PROVIDER_WEAKLY_REF_WEBVIEW", 2);
        new C0156b("PAYMENT_REQUEST", "PAYMENT_REQUEST", 2);
        new C0156b("WEBVIEW_BUILDER_EXPERIMENTAL_V1", "WEBVIEW_BUILDER_V1", 2);
        new C0156b("WEBVIEW_BUILDER_EXPERIMENTAL_V2", "WEBVIEW_BUILDER_V2", 2);
        new C0156b("COOKIE_INTERCEPT", "COOKIE_INTERCEPT", 2);
        new C0156b("WARM_UP_RENDERER_PROCESS", "WARM_UP_RENDERER_PROCESS", 2);
        new C0156b("CUSTOM_REQUEST_HEADERS", "CUSTOM_REQUEST_HEADERS", 2);
        new C0162h();
        new C0162h();
        new C0162h();
        new C0156b("PRECONNECT", "PRECONNECT", 2);
        new C0156b("ADD_QUIC_HINTS", "ADD_QUIC_HINTS_V1", 2);
        new C0156b("HYPERLINK_CONTEXT_MENU_ITEMS", "HYPERLINK_CONTEXT_MENU_ITEMS", 2);
        new C0156b("JS_INJECTION_IN_FRAME_AND_WORLD", "JS_INJECTION_IN_FRAME_AND_WORLD", 2);
        new C0156b("WEBVIEW_NAVIGATE_EXPERIMENTAL_V1", "WEBVIEW_NAVIGATE_V1", 2);
    }
}
