package defpackage;

import android.content.Context;
import com.yandex.go.taxi.tariffs.repository.g;
import ru.yandex.taxi.activity.MainActivity;
import ru.yandex.taxi.delivery.interactors.m;
import ru.yandex.taxi.logistics.payment.a;
import ru.yandex.taxi.logistics.sdk.management.j;

/* loaded from: classes5.dex */
public final class a6i {
    public final j A;
    public final xku0 B;
    public final t8i C;
    public final l8i D;
    public final wt90 E;
    public final uq1 F;
    public final g G;
    public final s14 H;
    public final a I;
    public final m J;
    public final ru.yandex.taxi.design.utils.a K;
    public final b8r L;
    public final c4r0 M;
    public final dci N;
    public final fvt O;
    public final elb0 P;
    public final k3i Q;
    public final o3i R;
    public final cq40 S;
    public final ru.yandex.taxi.logistics.address.g T;
    public final qht0 U;
    public final iev0 V;
    public final oep0 W;
    public final pho X;
    public final w030 a;
    public final i130 b;
    public final zuj0 c;
    public final y5i d;
    public final lx4 e;
    public final ru.yandex.taxi.logistics.delivery_form.repository.a f;
    public final dqe0 g;
    public final gsi h;
    public final wiq0 i;
    public final ru.yandex.taxi.activity.g j;
    public final tt2 k;
    public final tse l;
    public final Context m;
    public final MainActivity n;
    public final pav o;
    public final ynj0 p;
    public final k7x0 q;
    public final v7j0 r;
    public final ru.yandex.taxi.preorder.repositories.g s;
    public final y50 t;
    public final k9i u;
    public final apf v;
    public final rqo w;
    public final ljz x;
    public final pwy0 y;
    public final hit z;

    public a6i(w030 w030Var, i130 i130Var, zuj0 zuj0Var, y5i y5iVar, lx4 lx4Var, ru.yandex.taxi.logistics.delivery_form.repository.a aVar, dqe0 dqe0Var, gsi gsiVar, wiq0 wiq0Var, ru.yandex.taxi.activity.g gVar, tt2 tt2Var, tse tseVar, Context context, MainActivity mainActivity, pav pavVar, ynj0 ynj0Var, k7x0 k7x0Var, v7j0 v7j0Var, ru.yandex.taxi.preorder.repositories.g gVar2, y50 y50Var, k9i k9iVar, apf apfVar, rqo rqoVar, ljz ljzVar, pwy0 pwy0Var, hit hitVar, j jVar, xku0 xku0Var, t8i t8iVar, l8i l8iVar, wt90 wt90Var, uq1 uq1Var, g gVar3, s14 s14Var, a aVar2, m mVar, ru.yandex.taxi.design.utils.a aVar3, b8r b8rVar, c4r0 c4r0Var, dci dciVar, fvt fvtVar, elb0 elb0Var, k3i k3iVar, o3i o3iVar, cq40 cq40Var, ru.yandex.taxi.logistics.address.g gVar4, qht0 qht0Var, iev0 iev0Var, oep0 oep0Var, pho phoVar) {
        this.a = w030Var;
        this.b = i130Var;
        this.c = zuj0Var;
        this.d = y5iVar;
        this.e = lx4Var;
        this.f = aVar;
        this.g = dqe0Var;
        this.h = gsiVar;
        this.i = wiq0Var;
        this.j = gVar;
        this.k = tt2Var;
        this.l = tseVar;
        this.m = context;
        this.n = mainActivity;
        this.o = pavVar;
        this.p = ynj0Var;
        this.q = k7x0Var;
        this.r = v7j0Var;
        this.s = gVar2;
        this.t = y50Var;
        this.u = k9iVar;
        this.v = apfVar;
        this.w = rqoVar;
        this.x = ljzVar;
        this.y = pwy0Var;
        this.z = hitVar;
        this.A = jVar;
        this.B = xku0Var;
        this.C = t8iVar;
        this.D = l8iVar;
        this.E = wt90Var;
        this.F = uq1Var;
        this.G = gVar3;
        this.H = s14Var;
        this.I = aVar2;
        this.J = mVar;
        this.K = aVar3;
        this.L = b8rVar;
        this.M = c4r0Var;
        this.N = dciVar;
        this.O = fvtVar;
        this.P = elb0Var;
        this.Q = k3iVar;
        this.R = o3iVar;
        this.S = cq40Var;
        this.T = gVar4;
        this.U = qht0Var;
        this.V = iev0Var;
        this.W = oep0Var;
        this.X = phoVar;
    }
}
