package defpackage;

import android.content.Context;
import com.yandex.go.navigator.domain.b0;
import com.yandex.go.navigator.domain.e;
import com.yandex.go.navigator.domain.t;
import com.yandex.go.navigator.driving.speaker.d;
import com.yandex.go.navigator.gas_stations.experiment.c;
import com.yandex.go.navigator.repository.f;
import com.yandex.go.navigator.repository.o;
import com.yandex.go.navigator.search.a;
import com.yandex.go.taxi.experiments.q;
import ru.yandex.taxi.design.utils.b;

/* loaded from: classes12.dex */
public final class bus implements v7p {
    public final xvf0 A;
    public final xvf0 B;
    public final xvf0 C;
    public final xvf0 D;
    public final xvf0 E;
    public final xvf0 F;
    public final xvf0 G;
    public final xvf0 H;
    public final xvf0 I;
    public final xvf0 J;
    public final xvf0 K;
    public final xvf0 L;
    public final xvf0 M;
    public final xvf0 N;
    public final xvf0 O;
    public final xvf0 P;
    public final xvf0 Q;
    public final xvf0 R;
    public final xvf0 S;
    public final xvf0 T;
    public final xvf0 U;
    public final xvf0 V;
    public final xvf0 W;
    public final xvf0 X;
    public final xvf0 Y;
    public final xvf0 Z;
    public final xvf0 a;
    public final xvf0 a0;
    public final xvf0 b;
    public final xvf0 b0;
    public final xvf0 c;
    public final xvf0 c0;
    public final xvf0 d;
    public final xvf0 d0;
    public final xvf0 e;
    public final xvf0 e0;
    public final xvf0 f;
    public final xvf0 f0;
    public final xvf0 g;
    public final xvf0 g0;
    public final xvf0 h;
    public final xvf0 h0;
    public final xvf0 i;
    public final xvf0 i0;
    public final xvf0 j;
    public final xvf0 j0;
    public final xvf0 k;
    public final xvf0 k0;
    public final xvf0 l;
    public final xvf0 l0;
    public final xvf0 m;
    public final xvf0 m0;
    public final xvf0 n;
    public final xvf0 n0;
    public final xvf0 o;
    public final xvf0 o0;
    public final xvf0 p;
    public final pp0 p0;
    public final xvf0 q;
    public final xvf0 q0;
    public final xvf0 r;
    public final xvf0 r0;
    public final xvf0 s;
    public final xvf0 s0;
    public final xvf0 t;
    public final x0z t0;
    public final xvf0 u;
    public final xvf0 u0;
    public final xvf0 v;
    public final xvf0 v0;
    public final xvf0 w;
    public final k4g w0;
    public final xvf0 x;
    public final xvf0 x0;
    public final xvf0 y;
    public final xvf0 y0;
    public final xvf0 z;
    public final xvf0 z0;

    public bus(h4g h4gVar, h4g h4gVar2, k4g k4gVar, j4g j4gVar, j4g j4gVar2, xvf0 xvf0Var, xvf0 xvf0Var2, h4g h4gVar3, j4g j4gVar3, xvf0 xvf0Var3, j4g j4gVar4, l4g l4gVar, j4g j4gVar5, k4g k4gVar2, l4g l4gVar2, h4g h4gVar4, k4g k4gVar3, l4g l4gVar3, l4g l4gVar4, mg11 mg11Var, k4g k4gVar4, l4g l4gVar5, xvf0 xvf0Var4, xvf0 xvf0Var5, k4g k4gVar5, xvf0 xvf0Var6, xvf0 xvf0Var7, xvf0 xvf0Var8, xvf0 xvf0Var9, k4g k4gVar6, k4g k4gVar7, k4g k4gVar8, l4g l4gVar6, h4g h4gVar5, h4g h4gVar6, k4g k4gVar9, k4g k4gVar10, k4g k4gVar11, k4g k4gVar12, k4g k4gVar13, j4g j4gVar6, j4g j4gVar7, xvf0 xvf0Var10, l4g l4gVar7, xvf0 xvf0Var11, j4g j4gVar8, j4g j4gVar9, xvf0 xvf0Var12, j4g j4gVar10, k4g k4gVar14, j4g j4gVar11, k4g k4gVar15, xvf0 xvf0Var13, l4g l4gVar8, k4g k4gVar16, l4g l4gVar9, l4g l4gVar10, h4g h4gVar7, l4g l4gVar11, l4g l4gVar12, l4g l4gVar13, k4g k4gVar17, k4g k4gVar18, l4g l4gVar14, xvf0 xvf0Var14, l4g l4gVar15, j4g j4gVar12, pp0 pp0Var, j4g j4gVar13, j4g j4gVar14, xvf0 xvf0Var15, x0z x0zVar, e840 e840Var, h4g h4gVar8, k4g k4gVar19, xvf0 xvf0Var16, xvf0 xvf0Var17, l4g l4gVar16) {
        this.a = h4gVar;
        this.b = h4gVar2;
        this.c = k4gVar;
        this.d = j4gVar;
        this.e = j4gVar2;
        this.f = xvf0Var;
        this.g = xvf0Var2;
        this.h = h4gVar3;
        this.i = j4gVar3;
        this.j = xvf0Var3;
        this.k = j4gVar4;
        this.l = l4gVar;
        this.m = j4gVar5;
        this.n = k4gVar2;
        this.o = l4gVar2;
        this.p = h4gVar4;
        this.q = k4gVar3;
        this.r = l4gVar3;
        this.s = l4gVar4;
        this.t = mg11Var;
        this.u = k4gVar4;
        this.v = l4gVar5;
        this.w = xvf0Var4;
        this.x = xvf0Var5;
        this.y = k4gVar5;
        this.z = xvf0Var6;
        this.A = xvf0Var7;
        this.B = xvf0Var8;
        this.C = xvf0Var9;
        this.D = k4gVar6;
        this.E = k4gVar7;
        this.F = k4gVar8;
        this.G = l4gVar6;
        this.H = h4gVar5;
        this.I = h4gVar6;
        this.J = k4gVar9;
        this.K = k4gVar10;
        this.L = k4gVar11;
        this.M = k4gVar12;
        this.N = k4gVar13;
        this.O = j4gVar6;
        this.P = j4gVar7;
        this.Q = xvf0Var10;
        this.R = l4gVar7;
        this.S = xvf0Var11;
        this.T = j4gVar8;
        this.U = j4gVar9;
        this.V = xvf0Var12;
        this.W = j4gVar10;
        this.X = k4gVar14;
        this.Y = j4gVar11;
        this.Z = k4gVar15;
        this.a0 = xvf0Var13;
        this.b0 = l4gVar8;
        this.c0 = k4gVar16;
        this.d0 = l4gVar9;
        this.e0 = l4gVar10;
        this.f0 = h4gVar7;
        this.g0 = l4gVar11;
        this.h0 = l4gVar12;
        this.i0 = l4gVar13;
        this.j0 = k4gVar17;
        this.k0 = k4gVar18;
        this.l0 = l4gVar14;
        this.m0 = xvf0Var14;
        this.n0 = l4gVar15;
        this.o0 = j4gVar12;
        this.p0 = pp0Var;
        this.q0 = j4gVar13;
        this.r0 = j4gVar14;
        this.s0 = xvf0Var15;
        this.t0 = x0zVar;
        this.u0 = e840Var;
        this.v0 = h4gVar8;
        this.w0 = k4gVar19;
        this.x0 = xvf0Var16;
        this.y0 = xvf0Var17;
        this.z0 = l4gVar16;
    }

    @Override // defpackage.yvf0
    public final Object get() {
        Context context = (Context) this.a.get();
        Context context2 = (Context) this.b.get();
        w030 w030Var = (w030) this.c.get();
        uyd uydVar = (uyd) this.d.get();
        hbp0 hbp0Var = (hbp0) this.e.get();
        e eVar = (e) this.f.get();
        o oVar = (o) this.g.get();
        b bVar = (b) this.h.get();
        vff vffVar = (vff) this.i.get();
        c cVar = (c) this.j.get();
        f fVar = (f) this.k.get();
        pwy0 pwy0Var = (pwy0) this.l.get();
        t tVar = (t) this.m.get();
        ah00 ah00Var = (ah00) this.n.get();
        a aVar = (a) this.o.get();
        tt2 tt2Var = (tt2) this.p.get();
        ru.yandex.taxi.deeplinks.e eVar2 = (ru.yandex.taxi.deeplinks.e) this.q.get();
        po21 po21Var = (po21) this.r.get();
        zuj0 zuj0Var = (zuj0) this.s.get();
        b0 b0Var = (b0) this.t.get();
        tts ttsVar = (tts) this.u.get();
        ip11 ip11Var = (ip11) this.v.get();
        wb50 wb50Var = (wb50) this.w.get();
        kts ktsVar = (kts) this.x.get();
        pho phoVar = (pho) this.y.get();
        z950 z950Var = (z950) this.z.get();
        com.yandex.go.navigator.map_interactions.parkings.c cVar2 = (com.yandex.go.navigator.map_interactions.parkings.c) this.A.get();
        m901 m901Var = (m901) this.B.get();
        gcc0 gcc0Var = (gcc0) this.D.get();
        el00 el00Var = (el00) this.E.get();
        pav pavVar = (pav) this.G.get();
        lx4 lx4Var = (lx4) this.H.get();
        wnt wntVar = (wnt) this.J.get();
        ney neyVar = (ney) this.K.get();
        jyx jyxVar = (jyx) this.L.get();
        ru.yandex.taxi.multiorder.e eVar3 = (ru.yandex.taxi.multiorder.e) this.M.get();
        ywj ywjVar = (ywj) this.N.get();
        liq0 liq0Var = (liq0) this.O.get();
        com.yandex.go.navigator.domain.o oVar2 = (com.yandex.go.navigator.domain.o) this.P.get();
        lc50 lc50Var = (lc50) this.Q.get();
        lg50 lg50Var = (lg50) this.S.get();
        par parVar = (par) this.T.get();
        bf50 bf50Var = (bf50) this.U.get();
        com.yandex.go.navigator.user_placemark.c cVar3 = (com.yandex.go.navigator.user_placemark.c) this.V.get();
        d dVar = (d) this.W.get();
        re50 re50Var = (re50) this.Y.get();
        oc50 oc50Var = (oc50) this.Z.get();
        pyv pyvVar = (pyv) this.a0.get();
        ck31 ck31Var = (ck31) this.b0.get();
        rqo rqoVar = (rqo) this.c0.get();
        sgu0 sgu0Var = (sgu0) this.d0.get();
        uo21 uo21Var = (uo21) this.e0.get();
        com.yandex.go.navigation.screen.c cVar4 = (com.yandex.go.navigation.screen.c) this.f0.get();
        lk31 lk31Var = (lk31) this.g0.get();
        pb31 pb31Var = (pb31) this.h0.get();
        q qVar = (q) this.i0.get();
        i6r i6rVar = (i6r) this.j0.get();
        i6r i6rVar2 = (i6r) this.k0.get();
        y9y0 y9y0Var = (y9y0) this.l0.get();
        bzw bzwVar = (bzw) this.m0.get();
        return new aus(context, context2, w030Var, uydVar, hbp0Var, eVar, oVar, bVar, vffVar, cVar, fVar, pwy0Var, tVar, ah00Var, aVar, tt2Var, eVar2, po21Var, zuj0Var, b0Var, ttsVar, ip11Var, wb50Var, ktsVar, phoVar, z950Var, cVar2, m901Var, gcc0Var, el00Var, pavVar, lx4Var, wntVar, neyVar, jyxVar, eVar3, ywjVar, liq0Var, oVar2, lc50Var, lg50Var, parVar, bf50Var, cVar3, dVar, re50Var, oc50Var, pyvVar, ck31Var, rqoVar, sgu0Var, uo21Var, cVar4, lk31Var, pb31Var, qVar, i6rVar, i6rVar2, y9y0Var, bzwVar, (e621) this.o0.get(), (uj00) this.p0.get(), (df50) this.q0.get(), (com.yandex.go.navigator.settings.debug_panel.domain.b) this.r0.get(), (eb50) this.s0.get(), (com.yandex.go.navigator.gas_stations.analytics.a) this.t0.get(), (com.yandex.go.navigator.analitycs.a) this.u0.get(), (o41) this.v0.get(), (fu00) this.w0.get(), (uyw) this.x0.get(), (com.yandex.go.navigator.notifications.cartech.b) this.y0.get(), (com.yandex.go.navigator.events.f) this.z0.get());
    }
}
