package defpackage;

import android.content.Context;
import com.yandex.go.chargers.offer.data.ChargersOfferApi;
import com.yandex.go.navigation.screen.c;
import ru.yandex.taxi.TaxiApplication;
import ru.yandex.taxi.am.g;
import ru.yandex.taxi.design.utils.a;
import ru.yandex.taxi.design.utils.b;
import ru.yandex.taxi.widget.utils.e;

/* loaded from: classes12.dex */
public final class d8a {
    public final Object A;
    public final Object B;
    public final Object C;
    public final Object D;
    public final Object E;
    public final Object F;
    public final Object G;
    public final Object H;
    public final Object I;
    public final Object J;
    public final Object K;
    public final Object L;
    public final Object M;
    public final Object N;
    public final Object O;
    public final Object a;
    public final Object b;
    public final Object c;
    public final Object d;
    public final Object e;
    public final Object f;
    public final Object g;
    public final Object h;
    public final Object i;
    public final Object j;
    public final Object k;
    public final Object l;
    public final Object m;
    public final Object n;
    public final Object o;
    public final Object p;
    public final Object q;
    public final Object r;
    public final Object s;
    public final Object t;
    public final Object u;
    public final Object v;
    public final Object w;
    public final Object x;
    public final Object y;
    public final Object z;

    public d8a(i6r i6rVar, ouw0 ouw0Var, nuw0 nuw0Var, gvz0 gvz0Var) {
        this.a = i6rVar;
        this.b = ouw0Var;
        nag nagVar = new nag(i6rVar, 27);
        this.c = nagVar;
        rag ragVar = new rag(i6rVar, 5);
        int i = 25;
        nag nagVar2 = new nag(i6rVar, i);
        this.d = nagVar2;
        int i2 = 4;
        this.e = dhs0.a(new w7u(nagVar, ragVar, nagVar2, new rag(i6rVar, i2), 27));
        this.f = new rag(i6rVar, 13);
        this.g = new rag(i6rVar, 10);
        this.h = new rag(i6rVar, 16);
        int i3 = 1;
        this.i = new rag(i6rVar, i3);
        this.j = n3w.a(new ssw0(new ki9((nag) this.c, (rag) this.f, (rag) this.i, (nag) this.d, n3w.a(gvz0Var))));
        int i4 = 29;
        rag ragVar2 = new rag(i6rVar, i4);
        nag nagVar3 = new nag(i6rVar, 23);
        this.k = nagVar3;
        rag ragVar3 = new rag(i6rVar, i);
        this.l = ragVar3;
        int i5 = 6;
        vd vdVar = new vd(new sag(i6rVar, i5), new rag(i6rVar, 19), new rag(i6rVar, 7), new rag(i6rVar, 8), new rag(i6rVar, i5), new rag(i6rVar, 17), nagVar3, new rag(i6rVar, 15), 4);
        int i6 = 21;
        rag ragVar4 = new rag(i6rVar, i6);
        sag sagVar = new sag(i6rVar, i3);
        this.m = sagVar;
        nag nagVar4 = (nag) this.c;
        kpp0 kpp0Var = new kpp0(nagVar4, nagVar3, (rag) this.f, 11);
        rag ragVar5 = new rag(i6rVar, 22);
        int i7 = 0;
        rag ragVar6 = new rag(i6rVar, i7);
        nag nagVar5 = new nag(i6rVar, i4);
        xvf0 xvf0Var = (xvf0) this.e;
        nag nagVar6 = (nag) this.d;
        suw0 suw0Var = ruw0.a;
        int i8 = 11;
        ubq0 ubq0Var = new ubq0(ragVar2, nagVar3, ragVar3, vdVar, ragVar4, sagVar, new jpn0(nagVar4, xvf0Var, nagVar6, kpp0Var, ragVar5, ragVar6, nagVar5, suw0Var), 8);
        sag sagVar2 = new sag(i6rVar, i2);
        int i9 = 2;
        p7w0 p7w0Var = new p7w0(new rag(i6rVar, i9), i6);
        this.n = p7w0Var;
        rag ragVar7 = new rag(i6rVar, 20);
        this.o = ragVar7;
        this.p = n3w.a(new ysw0(new uio0((xvf0) ubq0Var, (xvf0) sagVar2, (xvf0) p7w0Var, (xvf0) ragVar7, (xvf0) ragVar3, (xvf0) sge.a)));
        int i10 = 24;
        nag nagVar7 = new nag(i6rVar, i10);
        rag ragVar8 = new rag(i6rVar, 27);
        this.q = ragVar8;
        int i11 = 18;
        m5v0 m5v0Var = new m5v0(nagVar7, ragVar8, (p7w0) this.n, i11);
        this.r = m5v0Var;
        this.s = new gzn0((xvf0) this.g, (xvf0) this.c, (xvf0) m5v0Var, 25);
        int i12 = 26;
        this.t = new rag(i6rVar, i12);
        this.u = new sag(i6rVar, 7);
        int i13 = 28;
        this.v = new rag(i6rVar, i13);
        int i14 = 3;
        this.w = new rag(i6rVar, i14);
        this.x = new nag(i6rVar, 22);
        this.y = new rag(i6rVar, 9);
        this.z = new rag(i6rVar, 14);
        this.A = new rag(i6rVar, i10);
        this.B = new sag(i6rVar, i14);
        this.C = new nag(i6rVar, i13);
        this.D = n3w.a(nuw0Var);
        eqh eqhVar = new eqh();
        this.E = eqhVar;
        ut utVar = new ut((rag) this.t, (rag) this.l, (sag) this.u, (rag) this.v, (rag) this.w, (nag) this.x, (rag) this.y, (rag) this.z, (rag) this.A, (sag) this.B, (nag) this.C, (n3w) this.D, new eu0(eqhVar, 10), new rag(i6rVar, 23), 18);
        this.F = utVar;
        uzu0 uzu0Var = new uzu0(new sag(i6rVar, i7), i8);
        this.G = uzu0Var;
        nag nagVar8 = (nag) this.c;
        this.H = new l9t0((xvf0) this.g, (v7p) new xat(nagVar8, i6), (xvf0) utVar, (v7p) new fat0(uzu0Var, (m5v0) this.r, 15), 27);
        this.I = n3w.a(new uuw0(new y94(nagVar8)));
        nag nagVar9 = (nag) this.k;
        rag ragVar9 = (rag) this.l;
        xvf0 xvf0Var2 = (xvf0) this.e;
        rag ragVar10 = (rag) this.o;
        this.J = n3w.a(new xuw0(new kob0((nag) this.c, new t4v0(nagVar9, ragVar9, xvf0Var2, ragVar10, 6), ragVar10, ragVar9, suw0Var, new rag(i6rVar, i8), (rag) this.q)));
        d441 d441Var = new d441(dhs0.a(new d441(new sag(i6rVar, 8), 15)), 6);
        rag ragVar11 = new rag(i6rVar, 12);
        sag sagVar3 = new sag(i6rVar, 5);
        rag ragVar12 = (rag) this.g;
        ahu ahuVar = new ahu(ragVar12, d441Var, ragVar11, (nag) this.k, sagVar3, 12);
        this.K = ahuVar;
        nag nagVar10 = new nag(i6rVar, i12);
        this.L = nagVar10;
        this.M = new ubq0(ragVar12, (n3w) this.I, (n3w) this.J, (ut) this.F, (rag) this.q, ahuVar, nagVar10, 9, false);
        this.N = n3w.a(new gpw0(new rw8((nag) this.c)));
        n3w a = n3w.a(new jpw0(new zxs0(new sit0((nag) this.k, (sag) this.m, (xvf0) this.e, 15), (rag) this.q)));
        rag ragVar13 = (rag) this.g;
        n3w n3wVar = (n3w) this.N;
        ut utVar2 = (ut) this.F;
        eqh.a((eqh) this.E, new h0l0(ragVar13, (rag) this.h, (n3w) this.j, (n3w) this.p, (gzn0) this.s, utVar2, (uzu0) this.G, (l9t0) this.H, (ubq0) this.M, new k4a(ragVar13, n3wVar, a, utVar2, (ahu) this.K, (nag) this.L), 16));
        this.O = dhs0.a(new yvr0((v7p) new nup0(new sag(i6rVar, i9), 10), (xvf0) new rag(i6rVar, i11), i12));
    }

    public grv0 a() {
        c0g c0gVar = (c0g) ((i6r) this.a);
        c S = c0gVar.S();
        q5z.h(S);
        wiq0 c6 = c0gVar.c6();
        q5z.h(c6);
        a A0 = c0gVar.A0();
        q5z.h(A0);
        tt2 k = c0gVar.k();
        q5z.h(k);
        e eVar = (e) ((xvf0) this.e).get();
        Context H1 = c0gVar.H1();
        q5z.h(H1);
        pwy0 w6 = c0gVar.w6();
        q5z.h(w6);
        zzf zzfVar = c0gVar.z;
        yp2 yp2Var = (yp2) zzfVar.kk.get();
        q5z.h(yp2Var);
        trv0 trv0Var = new trv0(S, c6, A0, k, eVar, H1, w6, yp2Var);
        Context H12 = c0gVar.H1();
        q5z.h(H12);
        tt2 k2 = c0gVar.k();
        q5z.h(k2);
        b bVar = new b(H12, k2, i5m.a((rag) this.f));
        c S2 = c0gVar.S();
        q5z.h(S2);
        hww0 hww0Var = (hww0) zzfVar.br.get();
        q5z.h(hww0Var);
        tt2 k3 = c0gVar.k();
        q5z.h(k3);
        Context H13 = c0gVar.H1();
        q5z.h(H13);
        rqo l1 = c0gVar.l1();
        q5z.h(l1);
        ru.yandex.taxi.surge.interactor.e eVar2 = new ru.yandex.taxi.surge.interactor.e(bVar, S2, hww0Var, k3, H13, l1);
        eqh eqhVar = (eqh) this.E;
        oep0 a6 = c0gVar.a6();
        q5z.h(a6);
        tt2 k4 = c0gVar.k();
        q5z.h(k4);
        lx4 y1 = c0gVar.y1();
        q5z.h(y1);
        xcv0 x1 = zzfVar.x1();
        pho T1 = c0gVar.T1();
        q5z.h(T1);
        vpw0 vpw0Var = new vpw0(y1, x1, new zow0(T1));
        TaxiApplication taxiApplication = zzfVar.a;
        y72 y72Var = (y72) zzfVar.R.get();
        zh11 zh11Var = (zh11) ((xvf0) this.O).get();
        v9h v9hVar = (v9h) zzfVar.I1.get();
        q5z.h(v9hVar);
        lrv0 lrv0Var = new lrv0(trv0Var, eVar2, eqhVar, a6, k4, vpw0Var, new n3h(taxiApplication, y72Var, zh11Var, v9hVar), (ouw0) this.b);
        fva0 fva0Var = (fva0) zzfVar.F1.get();
        q5z.h(fva0Var);
        return new grv0(lrv0Var, fva0Var);
    }

    public d8a(Context context, pav pavVar, kuo0 kuo0Var, tt2 tt2Var, pdc pdcVar, g gVar, tse tseVar, k7x0 k7x0Var, ChargersOfferApi chargersOfferApi, xdf xdfVar, em9 em9Var, zya zyaVar, vp21 vp21Var, fva0 fva0Var, ru.yandex.taxi.launch.c cVar, w030 w030Var, pwy0 pwy0Var, iya iyaVar, ru.yandex.taxi.widget.c cVar2, po21 po21Var, fn9 fn9Var, iwa iwaVar, lw9 lw9Var, kb20 kb20Var, rqo rqoVar, xma xmaVar, com.yandex.go.chargers.error.data.a aVar, j6a j6aVar, vn9 vn9Var, kxa kxaVar, rea0 rea0Var, com.yandex.go.chargers.payments.navigation.a aVar2, g6a g6aVar, tla tlaVar, lpa lpaVar, sx9 sx9Var, r9a r9aVar, rpa rpaVar, com.yandex.go.chargers.payments.data.a aVar3, saa saaVar, com.yandex.go.chargers.data.a aVar4) {
        this.a = context;
        this.b = pavVar;
        this.c = kuo0Var;
        this.d = tt2Var;
        this.e = pdcVar;
        this.f = gVar;
        this.g = tseVar;
        this.h = k7x0Var;
        this.i = chargersOfferApi;
        this.j = xdfVar;
        this.k = em9Var;
        this.l = zyaVar;
        this.m = vp21Var;
        this.n = fva0Var;
        this.o = cVar;
        this.p = w030Var;
        this.q = pwy0Var;
        this.r = iyaVar;
        this.s = cVar2;
        this.t = po21Var;
        this.u = fn9Var;
        this.v = iwaVar;
        this.w = lw9Var;
        this.x = kb20Var;
        this.y = rqoVar;
        this.z = xmaVar;
        this.A = aVar;
        this.B = j6aVar;
        this.C = vn9Var;
        this.D = kxaVar;
        this.E = rea0Var;
        this.F = aVar2;
        this.G = g6aVar;
        this.H = tlaVar;
        this.I = lpaVar;
        this.J = sx9Var;
        this.K = r9aVar;
        this.L = rpaVar;
        this.M = aVar3;
        this.N = saaVar;
        this.O = aVar4;
    }
}
