package defpackage;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* loaded from: classes12.dex */
public final class s3g {
    public final xvf0 A;
    public final c0j B;
    public final ba9 C;
    public final m3g D;
    public final m3g E;
    public final gaq0 F;
    public final ssj G;
    public final r3g H;
    public final m3g I;
    public final r3g J;
    public final m3g K;
    public final r3g L;
    public final r3g M;
    public final m3g N;
    public final m3g O;
    public final r3g P;
    public final m3g Q;
    public final m3g R;
    public final xvf0 S;
    public final m3g T;
    public final i6r a;
    public final m3g b;
    public final m3g c;
    public final m3g d;
    public final m3g e;
    public final xvf0 f;
    public final aos g;
    public final r3g h;
    public final n3w i;
    public final xvf0 j;
    public final ret k;
    public final di20 l;
    public final srb m;
    public final xvf0 n;
    public final ba9 o;
    public final lq40 p;
    public final m3g q;
    public final m3g r;
    public final m3g s;
    public final m3g t;
    public final gaq0 u;
    public final r3g v;
    public final m3g w;
    public final m3g x;
    public final m3g y;
    public final eqh z;

    /* JADX WARN: Multi-variable type inference failed */
    public s3g(i6r i6rVar, l6x l6xVar) {
        this.a = i6rVar;
        int i = 16;
        this.b = new m3g(i6rVar, i);
        int i2 = 8;
        this.c = new m3g(i6rVar, i2);
        int i3 = 6;
        this.d = new m3g(i6rVar, i3);
        int i4 = 9;
        this.e = new m3g(i6rVar, i4);
        int i5 = 15;
        xvf0 b = i5m.b(new jl00(new jl00(new m3g(i6rVar, i5), i), i5));
        this.f = b;
        int i6 = 17;
        this.g = new aos(n3w.a(new u730(new y94(b))), i6);
        this.h = new r3g(i6rVar, 4);
        this.i = n3w.a(i6rVar);
        int i7 = 18;
        xvf0 b2 = i5m.b(new aos(n3w.a(l6xVar), i7));
        this.j = b2;
        r3g r3gVar = this.h;
        n3w n3wVar = this.i;
        this.k = new ret(r3gVar, n3wVar, b2, 22);
        int i8 = 24;
        this.l = new di20(new m3g(i6rVar, i8), n3wVar, b2, i2);
        int i9 = 5;
        this.m = new srb(new dx9(this.f, new m3g(i6rVar, i7), i, false), i9);
        xvf0 b3 = i5m.b(o830.a);
        this.n = b3;
        ig7 ig7Var = new ig7(b3, i8);
        int i10 = 10;
        this.o = new ba9(ig7Var, i10);
        this.p = new lq40(i, new ge50((xvf0) this.i, (xvf0) e830.a, this.j, (xvf0) new r3g(i6rVar, 3), 7, (byte) 0));
        m3g m3gVar = new m3g(i6rVar, 12);
        this.q = m3gVar;
        int i11 = 7;
        r3g r3gVar2 = new r3g(i6rVar, i11);
        m3g m3gVar2 = new m3g(i6rVar, 14);
        this.r = m3gVar2;
        m3g m3gVar3 = new m3g(i6rVar, i6);
        this.s = m3gVar3;
        int i12 = 26;
        m3g m3gVar4 = new m3g(i6rVar, i12);
        this.t = m3gVar4;
        this.u = new gaq0(new zmm0(m3gVar, r3gVar2, m3gVar2, m3gVar3, m3gVar4, 23), i3);
        this.v = new r3g(i6rVar, i3);
        this.w = new m3g(i6rVar, 21);
        this.x = new m3g(i6rVar, i11);
        this.y = new m3g(i6rVar, 20);
        this.z = new eqh();
        xvf0 b4 = i5m.b(j830.a);
        this.A = b4;
        this.B = new c0j(this.x, this.y, this.z, b4, 28);
        this.C = new ba9(new kj7((xvf0) this.t, (xvf0) this.r, (xvf0) new r3g(i6rVar, 1), 17, (char) 0), i11);
        m3g m3gVar5 = new m3g(i6rVar, 27);
        this.D = m3gVar5;
        m3g m3gVar6 = new m3g(i6rVar, 29);
        this.E = m3gVar6;
        this.F = new gaq0(new gzn0(m3gVar5, m3gVar6, new r3g(i6rVar, i10), i12), i11);
        n3w n3wVar2 = y2r0.c;
        ArrayList arrayList = new ArrayList(11);
        List list = Collections.EMPTY_LIST;
        arrayList.add(this.k);
        arrayList.add(this.l);
        arrayList.add(this.m);
        arrayList.add(this.o);
        arrayList.add(this.p);
        arrayList.add(this.u);
        arrayList.add(this.v);
        arrayList.add(this.w);
        arrayList.add(this.B);
        arrayList.add(this.C);
        arrayList.add(this.F);
        this.G = new ssj(this.g, new y2r0(arrayList, list), 1);
        this.H = new r3g(i6rVar, i4);
        this.I = new m3g(i6rVar, 19);
        this.J = new r3g(i6rVar, 0 == true ? 1 : 0);
        this.K = new m3g(i6rVar, 23);
        this.L = new r3g(i6rVar, 2);
        this.M = new r3g(i6rVar, i2);
        this.N = new m3g(i6rVar, 25);
        this.O = new m3g(i6rVar, 28);
        this.P = new r3g(i6rVar, i9);
        this.Q = new m3g(i6rVar, 11);
        ArrayList arrayList2 = new ArrayList(1);
        List list2 = Collections.EMPTY_LIST;
        arrayList2.add(y730.a);
        eqh.a(this.z, new xki(this.c, this.d, this.e, this.G, this.f, this.A, this.H, this.D, this.I, this.n, this.J, this.K, this.L, this.j, this.M, this.t, this.q, this.s, this.N, this.E, this.O, this.P, this.Q, new y2r0(arrayList2, list2)));
        this.R = new m3g(i6rVar, 10);
        this.S = i5m.b(new di20(this.d, new m3g(i6rVar, 22), this.j, 9));
        this.T = new m3g(i6rVar, 13);
    }
}
