package defpackage;

import com.yandex.go.summary.interactor.core.t;
import com.yandex.go.taxi.tariffs.interactor.mapselection.a;
import ru.yandex.taxi.deeplinks.b;
import ru.yandex.taxi.preorder.summary.solid.interactors.c0;
import ru.yandex.taxi.preorder.summary.solid.interactors.g;
import ru.yandex.taxi.preorder.summary.solid.interactors.l;
import ru.yandex.taxi.preorder.summary.solid.interactors.p0;
import ru.yandex.taxi.preorder.summary.solid.interactors.q0;
import ru.yandex.taxi.preorder.summary.solid.interactors.s;
import ru.yandex.taxi.preorder.summary.solid.interactors.v;
import ru.yandex.taxi.preorder.summary.solid.interactors.y;
import ru.yandex.taxi.preorder.summary.solid.interactors.z;
import ru.yandex.taxi.requirements.repository.RequirementsChangedNotifier;
import ru.yandex.taxi.routestats.prefetch.m;
import ru.yandex.taxi.summary.personalaction.popup.e;
import ru.yandex.taxi.summary.requirements.list.interactors.u0;
import ru.yandex.taxi.summary.solid.repository.f;
import ru.yandex.taxi.summary.topnotification.plus.c;
import ru.yandex.taxi.summary.topnotification.plus.d;

/* loaded from: classes14.dex */
public final class thv0 implements v7p {
    public final xvf0 A;
    public final xvf0 B;
    public final xvf0 C;
    public final xvf0 D;
    public final xvf0 E;
    public final xvf0 F;
    public final xvf0 G;
    public final xvf0 H;
    public final xvf0 I;
    public final xvf0 J;
    public final xvf0 K;
    public final rx4 L;
    public final xvf0 M;
    public final qcb N;
    public final p8k0 O;
    public final ahu P;
    public final xvf0 Q;
    public final xvf0 R;
    public final xvf0 S;
    public final y101 T;
    public final xvf0 U;
    public final zfa V;
    public final rs0 W;
    public final xvf0 X;
    public final xvf0 Y;
    public final xvf0 Z;
    public final w0g a;
    public final xvf0 a0;
    public final xvf0 b;
    public final xvf0 b0;
    public final xvf0 c;
    public final xvf0 c0;
    public final xvf0 d;
    public final xvf0 d0;
    public final w0g e;
    public final xvf0 e0;
    public final xvf0 f;
    public final xvf0 f0;
    public final xvf0 g;
    public final xvf0 g0;
    public final xvf0 h;
    public final xvf0 h0;
    public final xvf0 i;
    public final xvf0 i0;
    public final xvf0 j;
    public final xvf0 k;
    public final xvf0 l;
    public final xvf0 m;
    public final xvf0 n;
    public final xvf0 o;
    public final xvf0 p;
    public final xvf0 q;
    public final xvf0 r;
    public final mg11 s;
    public final xvf0 t;
    public final xvf0 u;
    public final xvf0 v;
    public final xvf0 w;
    public final xvf0 x;
    public final xvf0 y;
    public final xvf0 z;

    public thv0(w0g w0gVar, w0g w0gVar2, x0g x0gVar, y0g y0gVar, w0g w0gVar3, t0g t0gVar, xvf0 xvf0Var, x0g x0gVar2, xvf0 xvf0Var2, fwc fwcVar, t0g t0gVar2, xvf0 xvf0Var3, xvf0 xvf0Var4, xvf0 xvf0Var5, xvf0 xvf0Var6, s90 s90Var, kpp0 kpp0Var, xvf0 xvf0Var7, mg11 mg11Var, x0g x0gVar3, w0g w0gVar4, zi60 zi60Var, cta0 cta0Var, gpx0 gpx0Var, xvf0 xvf0Var8, v0g v0gVar, zo0 zo0Var, xvf0 xvf0Var9, wi7 wi7Var, u6o0 u6o0Var, y101 y101Var, mz70 mz70Var, xvf0 xvf0Var10, nt0 nt0Var, vfg0 vfg0Var, s90 s90Var2, wi7 wi7Var2, rx4 rx4Var, z0g z0gVar, qcb qcbVar, p8k0 p8k0Var, ahu ahuVar, c1g c1gVar, b1g b1gVar, g0g g0gVar, y101 y101Var2, x0g x0gVar4, zfa zfaVar, rs0 rs0Var, mz70 mz70Var2, xvf0 xvf0Var11, nwf nwfVar, xvf0 xvf0Var12, a1g a1gVar, s0g s0gVar, a1g a1gVar2, x0g x0gVar5, l9t0 l9t0Var, xvf0 xvf0Var13, a1g a1gVar3, ubq0 ubq0Var) {
        this.a = w0gVar;
        this.b = w0gVar2;
        this.c = x0gVar;
        this.d = y0gVar;
        this.e = w0gVar3;
        this.f = t0gVar;
        this.g = xvf0Var;
        this.h = x0gVar2;
        this.i = xvf0Var2;
        this.j = fwcVar;
        this.k = t0gVar2;
        this.l = xvf0Var3;
        this.m = xvf0Var4;
        this.n = xvf0Var5;
        this.o = xvf0Var6;
        this.p = s90Var;
        this.q = kpp0Var;
        this.r = xvf0Var7;
        this.s = mg11Var;
        this.t = x0gVar3;
        this.u = w0gVar4;
        this.v = zi60Var;
        this.w = cta0Var;
        this.x = gpx0Var;
        this.y = xvf0Var8;
        this.z = v0gVar;
        this.A = zo0Var;
        this.B = xvf0Var9;
        this.C = wi7Var;
        this.D = u6o0Var;
        this.E = y101Var;
        this.F = mz70Var;
        this.G = xvf0Var10;
        this.H = nt0Var;
        this.I = vfg0Var;
        this.J = s90Var2;
        this.K = wi7Var2;
        this.L = rx4Var;
        this.M = z0gVar;
        this.N = qcbVar;
        this.O = p8k0Var;
        this.P = ahuVar;
        this.Q = c1gVar;
        this.R = b1gVar;
        this.S = g0gVar;
        this.T = y101Var2;
        this.U = x0gVar4;
        this.V = zfaVar;
        this.W = rs0Var;
        this.X = mz70Var2;
        this.Y = xvf0Var11;
        this.Z = nwfVar;
        this.a0 = xvf0Var12;
        this.b0 = a1gVar;
        this.c0 = s0gVar;
        this.d0 = a1gVar2;
        this.e0 = x0gVar5;
        this.f0 = l9t0Var;
        this.g0 = xvf0Var13;
        this.h0 = a1gVar3;
        this.i0 = ubq0Var;
    }

    @Override // defpackage.yvf0
    public final Object get() {
        return new t((wiq0) this.a.get(), (hpr0) this.b.get(), (f) this.c.get(), (ck31) this.d.get(), (dqe0) this.e.get(), (tt2) this.f.get(), (g580) this.g.get(), (qiv0) this.h.get(), (crd) this.i.get(), (c) this.j.get(), (hrd) this.k.get(), (eid0) this.l.get(), (d) this.m.get(), (j610) this.n.get(), (h610) this.o.get(), (l) this.p.get(), (dmq0) this.q.get(), (mnv0) this.r.get(), (hk31) this.s.get(), (a) this.t.get(), (RequirementsChangedNotifier) this.u.get(), (l3b0) this.v.get(), (e) this.w.get(), (fpx0) this.x.get(), (p0) this.y.get(), (aw70) this.z.get(), (g) this.A.get(), (v) this.B.get(), i5m.a(this.C), (ru.yandex.taxi.summary.solid.preview_card.interactor.a) this.D.get(), (c521) this.E.get(), (iox0) this.F.get(), (c0) this.G.get(), i5m.a(this.H), i5m.a(this.I), (wa1) this.J.get(), (com.yandex.go.summary.interactor.core.v) this.K.get(), (ru.yandex.taxi.logistics.safe_flow.a) this.L.get(), (ru.yandex.taxi.logistics.payment_method_selector.c) this.M.get(), (y) this.N.get(), (z) this.O.get(), (ru.yandex.taxi.preorder.summary.selector.analytics.a) this.P.get(), (com.yandex.go.taxi.summary.map.walkingroute.e) this.Q.get(), (com.yandex.go.route.interactor.c) this.R.get(), (b) this.S.get(), (q0) this.T.get(), (tiv0) this.U.get(), (ru.yandex.taxi.summary.requirements.list.interactors.d) this.V.get(), (s) this.W.get(), (xfv0) this.X.get(), (com.yandex.go.taxi.summary.shared.lifecycle.a) this.Y.get(), (fwu0) this.Z.get(), (vqv0) this.a0.get(), (rft0) this.b0.get(), (pcm) this.c0.get(), (krq0) this.d0.get(), (nex0) this.e0.get(), (mov0) this.f0.get(), (com.yandex.go.taxi.summary.shared.lifecycle.a) this.g0.get(), (m) this.h0.get(), (u0) this.i0.get());
    }
}
