package defpackage;

import com.yandex.go.payments.domain.m0;
import com.yandex.go.tariffcard.interactor.a;
import com.yandex.go.tariffcard.interactor.g;
import com.yandex.go.tariffcard.interactor.x;
import com.yandex.go.tariffcard.ui.b;
import com.yandex.go.tariffcard.ui.e;
import ru.yandex.taxi.orderbutton.summary.base.interactors.i;
import ru.yandex.taxi.preorder.summary.tariffpage.badge.j;
import ru.yandex.taxi.summary.requirements.list.interactors.k0;
import ru.yandex.taxi.widget.c;

/* loaded from: classes14.dex */
public final class tix0 {
    public final g A;
    public final b B;
    public final com.yandex.go.taxi.tariffs.repository.g C;
    public final x7t0 D;
    public final nw70 E;
    public final a F;
    public final x G;
    public final hhs0 H;
    public final vlx0 I;
    public final oxu0 J;
    public final e a;
    public final tt2 b;
    public final wiq0 c;
    public final vfx0 d;
    public final yfx0 e;
    public final i f;
    public final m0 g;
    public final adx0 h;
    public final uze0 i;
    public final pwy0 j;
    public final x1f k;
    public final j l;
    public final ru.yandex.taxi.delivery.impl.badges.a m;
    public final c n;
    public final x421 o;
    public final viv0 p;
    public final dip0 q;
    public final nix0 r;
    public final caj0 s;
    public final rpi t;
    public final u1n u;
    public final k0 v;
    public final ru.yandex.taxi.summary.requirements.list.recycler.i w;
    public final wpy0 x;
    public final ru.yandex.taxi.summary.requirements.list.carousel.interactor.a y;
    public final qw11 z;

    public tix0(e eVar, tt2 tt2Var, wiq0 wiq0Var, vfx0 vfx0Var, yfx0 yfx0Var, i iVar, m0 m0Var, adx0 adx0Var, uze0 uze0Var, pwy0 pwy0Var, x1f x1fVar, j jVar, ru.yandex.taxi.delivery.impl.badges.a aVar, c cVar, x421 x421Var, viv0 viv0Var, dip0 dip0Var, nix0 nix0Var, caj0 caj0Var, rpi rpiVar, u1n u1nVar, k0 k0Var, ru.yandex.taxi.summary.requirements.list.recycler.i iVar2, wpy0 wpy0Var, ru.yandex.taxi.summary.requirements.list.carousel.interactor.a aVar2, qw11 qw11Var, g gVar, b bVar, com.yandex.go.taxi.tariffs.repository.g gVar2, x7t0 x7t0Var, nw70 nw70Var, a aVar3, x xVar, hhs0 hhs0Var, vlx0 vlx0Var, oxu0 oxu0Var) {
        this.a = eVar;
        this.b = tt2Var;
        this.c = wiq0Var;
        this.d = vfx0Var;
        this.e = yfx0Var;
        this.f = iVar;
        this.g = m0Var;
        this.h = adx0Var;
        this.i = uze0Var;
        this.j = pwy0Var;
        this.k = x1fVar;
        this.l = jVar;
        this.m = aVar;
        this.n = cVar;
        this.o = x421Var;
        this.p = viv0Var;
        this.q = dip0Var;
        this.r = nix0Var;
        this.s = caj0Var;
        this.t = rpiVar;
        this.u = u1nVar;
        this.v = k0Var;
        this.w = iVar2;
        this.x = wpy0Var;
        this.y = aVar2;
        this.z = qw11Var;
        this.A = gVar;
        this.B = bVar;
        this.C = gVar2;
        this.D = x7t0Var;
        this.E = nw70Var;
        this.F = aVar3;
        this.G = xVar;
        this.H = hhs0Var;
        this.I = vlx0Var;
        this.J = oxu0Var;
    }
}
