package defpackage;

import ru.CryptoPro.JCP.tools.CertReader.Extension;

/* loaded from: classes4.dex */
public final class yom {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final wls J;
    public final wls K;
    public final wls L;
    public final wls M;
    public final wls N;
    public final wls O;
    public final wls P;
    public final wls Q;
    public final lzr R;
    public final lzr S;
    public final lzr T;
    public final lzr U;
    public final lzr V;
    public final lzr W;
    public final lzr X;
    public final lzr Y;
    public final lzr Z;
    public final long a;
    public final long a0;
    public final long b;
    public final long b0;
    public final long c;
    public final long c0;
    public final long d;
    public final long d0;
    public final long e;
    public final long e0;
    public final long f;
    public final long g;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final long l;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public yom(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, wls wlsVar, wls wlsVar2, wls wlsVar3, wls wlsVar4, wls wlsVar5, wls wlsVar6, wls wlsVar7, wls wlsVar8, lzr lzrVar, lzr lzrVar2, lzr lzrVar3, lzr lzrVar4, lzr lzrVar5, lzr lzrVar6, lzr lzrVar7, lzr lzrVar8, lzr lzrVar9, long j36, long j37, long j38, long j39, long j40) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = wlsVar;
        this.K = wlsVar2;
        this.L = wlsVar3;
        this.M = wlsVar4;
        this.N = wlsVar5;
        this.O = wlsVar6;
        this.P = wlsVar7;
        this.Q = wlsVar8;
        this.R = lzrVar;
        this.S = lzrVar2;
        this.T = lzrVar3;
        this.U = lzrVar4;
        this.V = lzrVar5;
        this.W = lzrVar6;
        this.X = lzrVar7;
        this.Y = lzrVar8;
        this.Z = lzrVar9;
        this.a0 = j36;
        this.b0 = j37;
        this.c0 = j38;
        this.d0 = j39;
        this.e0 = j40;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof yom)) {
            return false;
        }
        yom yomVar = (yom) obj;
        return sty0.a(this.a, yomVar.a) && sty0.a(this.b, yomVar.b) && sty0.a(this.c, yomVar.c) && sty0.a(this.d, yomVar.d) && sty0.a(this.e, yomVar.e) && sty0.a(this.f, yomVar.f) && sty0.a(this.g, yomVar.g) && sty0.a(this.h, yomVar.h) && sty0.a(this.i, yomVar.i) && sty0.a(this.j, yomVar.j) && sty0.a(this.k, yomVar.k) && sty0.a(this.l, yomVar.l) && sty0.a(this.m, yomVar.m) && sty0.a(this.n, yomVar.n) && sty0.a(this.o, yomVar.o) && sty0.a(this.p, yomVar.p) && sty0.a(this.q, yomVar.q) && sty0.a(this.r, yomVar.r) && sty0.a(this.s, yomVar.s) && sty0.a(this.t, yomVar.t) && sty0.a(this.u, yomVar.u) && sty0.a(this.v, yomVar.v) && sty0.a(this.w, yomVar.w) && sty0.a(this.x, yomVar.x) && sty0.a(this.y, yomVar.y) && sty0.a(this.z, yomVar.z) && sty0.a(this.A, yomVar.A) && sty0.a(this.B, yomVar.B) && sty0.a(this.C, yomVar.C) && sty0.a(this.D, yomVar.D) && sty0.a(this.E, yomVar.E) && sty0.a(this.F, yomVar.F) && sty0.a(this.G, yomVar.G) && sty0.a(this.H, yomVar.H) && sty0.a(this.I, yomVar.I) && jl40.l(this.J, yomVar.J) && jl40.l(this.K, yomVar.K) && jl40.l(this.L, yomVar.L) && jl40.l(this.M, yomVar.M) && jl40.l(this.N, yomVar.N) && jl40.l(this.O, yomVar.O) && jl40.l(this.P, yomVar.P) && jl40.l(this.Q, yomVar.Q) && this.R.equals(yomVar.R) && this.S.equals(yomVar.S) && this.T.equals(yomVar.T) && this.U.equals(yomVar.U) && this.V.equals(yomVar.V) && this.W.equals(yomVar.W) && this.X.equals(yomVar.X) && this.Y.equals(yomVar.Y) && this.Z.equals(yomVar.Z) && sty0.a(this.a0, yomVar.a0) && sty0.a(this.b0, yomVar.b0) && sty0.a(this.c0, yomVar.c0) && sty0.a(this.d0, yomVar.d0) && sty0.a(this.e0, yomVar.e0);
    }

    public final int hashCode() {
        tty0[] tty0VarArr = sty0.b;
        return Long.hashCode(this.e0) + qv10.c(qv10.c(qv10.c(qv10.c((((((((((((((((((((this.Q.hashCode() + ((this.P.hashCode() + ((this.O.hashCode() + ((this.N.hashCode() + ((this.M.hashCode() + ((this.L.hashCode() + ((this.K.hashCode() + ((this.J.hashCode() + qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(qv10.c(Long.hashCode(this.a) * 31, 31, this.b), 31, this.c), 31, this.d), 31, this.e), 31, this.f), 31, this.g), 31, this.h), 31, this.i), 31, this.j), 31, this.k), 31, this.l), 31, this.m), 31, this.n), 31, this.o), 31, this.p), 31, this.q), 31, this.r), 31, this.s), 31, this.t), 31, this.u), 31, this.v), 31, this.w), 31, this.x), 31, this.y), 31, this.z), 31, this.A), 31, this.B), 31, this.C), 31, this.D), 31, this.E), 31, this.F), 31, this.G), 31, this.H), 31, this.I)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31) + this.R.a) * 31) + this.S.a) * 31) + this.T.a) * 31) + this.U.a) * 31) + this.V.a) * 31) + this.W.a) * 31) + this.X.a) * 31) + this.Y.a) * 31) + this.Z.a) * 31, 31, this.a0), 31, this.b0), 31, this.c0), 31, this.d0);
    }

    public final String toString() {
        String e = sty0.e(this.a);
        String e2 = sty0.e(this.b);
        String e3 = sty0.e(this.c);
        String e4 = sty0.e(this.d);
        String e5 = sty0.e(this.e);
        String e6 = sty0.e(this.f);
        String e7 = sty0.e(this.g);
        String e8 = sty0.e(this.h);
        String e9 = sty0.e(this.i);
        String e10 = sty0.e(this.j);
        String e11 = sty0.e(this.k);
        String e12 = sty0.e(this.l);
        String e13 = sty0.e(this.m);
        String e14 = sty0.e(this.n);
        String e15 = sty0.e(this.o);
        String e16 = sty0.e(this.p);
        String e17 = sty0.e(this.q);
        String e18 = sty0.e(this.r);
        String e19 = sty0.e(this.s);
        String e20 = sty0.e(this.t);
        String e21 = sty0.e(this.u);
        String e22 = sty0.e(this.v);
        String e23 = sty0.e(this.w);
        String e24 = sty0.e(this.x);
        String e25 = sty0.e(this.y);
        String e26 = sty0.e(this.z);
        String e27 = sty0.e(this.A);
        String e28 = sty0.e(this.B);
        String e29 = sty0.e(this.C);
        String e30 = sty0.e(this.D);
        String e31 = sty0.e(this.E);
        String e32 = sty0.e(this.F);
        String e33 = sty0.e(this.G);
        String e34 = sty0.e(this.H);
        String e35 = sty0.e(this.I);
        String e36 = sty0.e(this.a0);
        String e37 = sty0.e(this.b0);
        String e38 = sty0.e(this.c0);
        String e39 = sty0.e(this.d0);
        String e40 = sty0.e(this.e0);
        StringBuilder v = b64.v("DsBrandTypography(TypoHeadingFontSizeXl=", e, ", TypoHeadingFontSizeLg=", e2, ", TypoHeadingFontSizeMd=");
        g8e.D(v, e3, ", TypoHeadingFontSizeSm=", e4, ", TypoHeadingFontSizeXs=");
        g8e.D(v, e5, ", TypoBodyFontSizeLg=", e6, ", TypoBodyFontSizeMd=");
        g8e.D(v, e7, ", TypoCaptionFontSizeMd=", e8, ", TypoCaptionFontSizeSm=");
        g8e.D(v, e9, ", TypoMonoFontSizeLg=", e10, ", TypoMonoFontSizeMd=");
        g8e.D(v, e11, ", TypoMonoFontSizeSm=", e12, ", TypoHotkeysFontSizeLg=");
        g8e.D(v, e13, ", TypoHotkeysFontSizeMd=", e14, ", TypoHotkeysFontSizeSm=");
        g8e.D(v, e15, ", TypoHeadingLineHeightXl=", e16, ", TypoHeadingLineHeightLg=");
        g8e.D(v, e17, ", TypoHeadingLineHeightMd=", e18, ", TypoHeadingLineHeightSm=");
        g8e.D(v, e19, ", TypoHeadingLineHeightXs=", e20, ", TypoBodyLineHeightLg=");
        g8e.D(v, e21, ", TypoBodyLineHeightMd=", e22, ", TypoBodyShortLineHeightLg=");
        g8e.D(v, e23, ", TypoBodyShortLineHeightMd=", e24, ", TypoCaptionLineHeightMd=");
        g8e.D(v, e25, ", TypoCaptionLineHeightSm=", e26, ", TypoMonoLineHeightLg=");
        g8e.D(v, e27, ", TypoMonoLineHeightMd=", e28, ", TypoMonoLineHeightSm=");
        g8e.D(v, e29, ", TypoMonoShortLineHeightLg=", e30, ", TypoMonoShortLineHeightMd=");
        g8e.D(v, e31, ", TypoMonoShortLineHeightSm=", e32, ", TypoHotkeysLineHeightLg=");
        g8e.D(v, e33, ", TypoHotkeysLineHeightMd=", e34, ", TypoHotkeysLineHeightSm=");
        v.append(e35);
        v.append(", TypoHeadingFont=");
        v.append(this.J);
        v.append(", TypoHeadingFontXs=");
        v.append(this.K);
        v.append(", TypoBodyFontRegular=");
        v.append(this.L);
        v.append(", TypoBodyFontMedium=");
        v.append(this.M);
        v.append(", TypoBodyFontBold=");
        v.append(this.N);
        v.append(", TypoCaptionFontRegular=");
        v.append(this.O);
        v.append(", TypoCaptionFontMedium=");
        v.append(this.P);
        v.append(", TypoMonoFontRegular=");
        v.append(this.Q);
        v.append(", TypoHeadingFontWeight=");
        v.append(this.R);
        v.append(", TypoHeadingFontWeightXs=");
        v.append(this.S);
        v.append(", TypoBodyFontWeightRegular=");
        v.append(this.T);
        v.append(", TypoBodyFontWeightMedium=");
        v.append(this.U);
        v.append(", TypoBodyFontWeightBold=");
        v.append(this.V);
        v.append(", TypoCaptionFontWeightRegular=");
        v.append(this.W);
        v.append(", TypoCaptionFontWeightMedium=");
        v.append(this.X);
        v.append(", TypoMonoFontWeightRegular=");
        v.append(this.Y);
        v.append(", TypoHotkeysFontWeightRegular=");
        v.append(this.Z);
        v.append(", TypoHeadingLetterSpacing=");
        g8e.D(v, e36, ", TypoBodyLetterSpacing=", e37, ", TypoCaptionLetterSpacing=");
        g8e.D(v, e38, ", TypoMonoLetterSpacing=", e39, ", TypoHotkeysLetterSpacing=");
        return oyr.t(v, e40, Extension.C_BRAKE);
    }
}
