package p000createpolar;

/* compiled from: r8-map-id-8b11a357a473f42949ec352239e0d5cff1c9f920f781009416889c17ee09d569 */
/* loaded from: classes.dex */
public final class PolarVoyageCoordinatorLayoutMaxTitaniumEpic5649 implements PolarVoyageScrollViewShadowCyberInferno3272 {
    public static final PolarVoyageCoordinatorLayoutMaxTitaniumEpic5649 PolarVoyageZipVortexCelestial6185 = new PolarVoyageCoordinatorLayoutMaxTitaniumEpic5649();
    public static final PolarVoyageBitmapPrimeStorm5891 PolarVoyageMotionLayoutTransitionHeroVision4068 = new PolarVoyageBitmapPrimeStorm5891("window", PolarVoyageVibratorInfernoPhoenixFusion4401.PolarVoyageNavigationViewHyperHyperHyperion1793(PolarVoyageVibratorInfernoPhoenixFusion4401.PolarVoyageRemoteModelManagerOlympianCelestial9141(PolarVoyageImageViewSpeedPrimeBeta1979.class, new PolarVoyageCanvasNovaXTurbo9725(1))));
    public static final PolarVoyageBitmapPrimeStorm5891 PolarVoyageKotlinBetaPulseBeta3653 = new PolarVoyageBitmapPrimeStorm5891("logSourceMetrics", PolarVoyageVibratorInfernoPhoenixFusion4401.PolarVoyageNavigationViewHyperHyperHyperion1793(PolarVoyageVibratorInfernoPhoenixFusion4401.PolarVoyageRemoteModelManagerOlympianCelestial9141(PolarVoyageImageViewSpeedPrimeBeta1979.class, new PolarVoyageCanvasNovaXTurbo9725(2))));
    public static final PolarVoyageBitmapPrimeStorm5891 PolarVoyageBarcodeScannerInfernoSolarSpark7767 = new PolarVoyageBitmapPrimeStorm5891("globalMetrics", PolarVoyageVibratorInfernoPhoenixFusion4401.PolarVoyageNavigationViewHyperHyperHyperion1793(PolarVoyageVibratorInfernoPhoenixFusion4401.PolarVoyageRemoteModelManagerOlympianCelestial9141(PolarVoyageImageViewSpeedPrimeBeta1979.class, new PolarVoyageCanvasNovaXTurbo9725(3))));
    public static final PolarVoyageBitmapPrimeStorm5891 PolarVoyageBitmapVisionAuroraPixel4705 = new PolarVoyageBitmapPrimeStorm5891("appNamespace", PolarVoyageVibratorInfernoPhoenixFusion4401.PolarVoyageNavigationViewHyperHyperHyperion1793(PolarVoyageVibratorInfernoPhoenixFusion4401.PolarVoyageRemoteModelManagerOlympianCelestial9141(PolarVoyageImageViewSpeedPrimeBeta1979.class, new PolarVoyageCanvasNovaXTurbo9725(4))));

    @Override // p000createpolar.PolarVoyageCoroutineScopeLegendOmega3754
    public final void PolarVoyageZipVortexCelestial6185(Object obj, Object obj2) {
        PolarVoyagePlaceholderInfernoPixelHyper1253 polarVoyagePlaceholderInfernoPixelHyper1253 = (PolarVoyagePlaceholderInfernoPixelHyper1253) obj;
        PolarVoyageNavigationViewPrimeElite2875 polarVoyageNavigationViewPrimeElite2875 = (PolarVoyageNavigationViewPrimeElite2875) obj2;
        polarVoyageNavigationViewPrimeElite2875.PolarVoyageBitmapVisionAuroraPixel4705(PolarVoyageMotionLayoutTransitionHeroVision4068, polarVoyagePlaceholderInfernoPixelHyper1253.PolarVoyageZipVortexCelestial6185);
        polarVoyageNavigationViewPrimeElite2875.PolarVoyageBitmapVisionAuroraPixel4705(PolarVoyageKotlinBetaPulseBeta3653, polarVoyagePlaceholderInfernoPixelHyper1253.PolarVoyageMotionLayoutTransitionHeroVision4068);
        polarVoyageNavigationViewPrimeElite2875.PolarVoyageBitmapVisionAuroraPixel4705(PolarVoyageBarcodeScannerInfernoSolarSpark7767, polarVoyagePlaceholderInfernoPixelHyper1253.PolarVoyageKotlinBetaPulseBeta3653);
        polarVoyageNavigationViewPrimeElite2875.PolarVoyageBitmapVisionAuroraPixel4705(PolarVoyageBitmapVisionAuroraPixel4705, polarVoyagePlaceholderInfernoPixelHyper1253.PolarVoyageBarcodeScannerInfernoSolarSpark7767);
    }
}
