package defpackage;

/* loaded from: classes3.dex */
public abstract class zr9 {
    public static final tct A;
    public static final hm9 B;
    public static final hm9 C;
    public static final hm9 D;
    public static final hm9 E;
    public static final hm9 F;
    public static final hm9 G;
    public static final hm9 H;
    public static final hm9 I;
    public static final y19 J;
    public static final sm8 a;
    public static final ozb b;
    public static final ozb c;
    public static final ozb d;
    public static final ozb e;
    public static final ak9 f;
    public static final ozb g;
    public static final ozb h;
    public static final ozb i;
    public static final ozb j;
    public static final ozb k;
    public static final ozb l;
    public static final ozb m;
    public static final ozb n;
    public static final ozb o;
    public static final ozb p;
    public static final zj9 q;
    public static final tct r;
    public static final tct s;
    public static final tct t;
    public static final tct u;
    public static final tct v;
    public static final tct w;
    public static final tct x;
    public static final tct y;
    public static final tct z;

    static {
        ozb L = e3s.L(100L);
        ozb L2 = e3s.L(Double.valueOf(0.6d));
        ozb L3 = e3s.L(rm8.FADE);
        Double valueOf = Double.valueOf(1.0d);
        a = new sm8(L, L2, L3, e3s.L(valueOf));
        b = e3s.L(valueOf);
        c = e3s.L(Boolean.TRUE);
        d = e3s.L(12L);
        jk9 jk9Var = jk9.SP;
        e = e3s.L(jk9Var);
        f = new ak9(new x1a(null, null, null));
        g = e3s.L(Double.valueOf(0.0d));
        Boolean bool = Boolean.FALSE;
        h = e3s.L(bool);
        e89 e89Var = e89.NONE;
        i = e3s.L(e89Var);
        om8 om8Var = om8.START;
        j = e3s.L(om8Var);
        pm8 pm8Var = pm8.TOP;
        k = e3s.L(pm8Var);
        l = e3s.L(-16777216);
        m = e3s.L(bool);
        wq9 wq9Var = wq9.END;
        n = e3s.L(wq9Var);
        o = e3s.L(e89Var);
        k1a k1aVar = k1a.VISIBLE;
        p = e3s.L(k1aVar);
        q = new zj9(new a99(null, null, null));
        r = new tct(vq9.y, xz0.y(om8.values()));
        s = new tct(vq9.z, xz0.y(pm8.values()));
        t = new tct(vq9.A, jk9Var);
        u = new tct(vq9.B, xz0.y(e09.values()));
        v = new tct(vq9.C, e89Var);
        w = new tct(vq9.D, om8Var);
        x = new tct(vq9.E, pm8Var);
        y = new tct(vq9.F, wq9Var);
        z = new tct(vq9.G, e89Var);
        A = new tct(vq9.H, k1aVar);
        B = new hm9(20);
        C = new hm9(21);
        D = new hm9(22);
        E = new hm9(23);
        F = new hm9(24);
        G = new hm9(25);
        H = new hm9(26);
        I = new hm9(27);
        J = new y19(24);
    }
}
