package b0;

/* renamed from: b0.m, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public abstract class AbstractC0182m {

    /* renamed from: a, reason: collision with root package name */
    public static final C0171b f2535a;

    /* renamed from: b, reason: collision with root package name */
    public static final C0171b f2536b;

    /* renamed from: c, reason: collision with root package name */
    public static final C0171b f2537c;

    /* renamed from: d, reason: collision with root package name */
    public static final C0171b f2538d;

    /* renamed from: e, reason: collision with root package name */
    public static final C0171b f2539e;

    static {
        new C0171b("VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK", 0);
        new C0171b("OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER", 0);
        new C0171b("SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE", 3);
        new C0171b("DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS", 1);
        new C0171b("START_SAFE_BROWSING", "START_SAFE_BROWSING", 4);
        new C0171b("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST", 4);
        new C0171b("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST", 4);
        new C0171b("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST", 4);
        new C0171b("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST", 4);
        new C0171b("SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL", 4);
        new C0171b("SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE", 1);
        new C0171b("SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE", 1);
        new C0171b("SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS", 1);
        new C0171b("SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS", 1);
        new C0171b("SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS", 1);
        new C0171b("SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", 1);
        new C0171b("RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR", 0);
        new C0171b("RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR", 0);
        new C0171b("SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS", 1);
        new C0171b("SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT", 4);
        new C0171b("WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT", 1);
        new C0171b("WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION", 0);
        new C0171b("WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE", 0);
        new C0171b("SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", 4);
        new C0171b("SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED", 4);
        new C0171b("SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", 4);
        new C0171b("WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE", 0);
        new C0171b("WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE", 0);
        f2535a = new C0171b("WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER", 2);
        new C0171b("WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", 0);
        new C0171b("CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL", 0);
        new C0171b("POST_WEB_MESSAGE", "POST_WEB_MESSAGE", 0);
        new C0171b("WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE", 0);
        new C0171b("GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT", 3);
        new C0171b("GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT", 3);
        new C0171b("GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER", 6);
        new C0171b("WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE", 6);
        new C0171b("TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE", 5);
        new C0177h();
        new C0177h();
        new C0177h();
        new C0171b("WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", 6);
        new C0180k();
        new C0171b("PROXY_OVERRIDE", "PROXY_OVERRIDE:3", 2);
        f2536b = new C0171b("MULTI_PROCESS", "MULTI_PROCESS_QUERY", 2);
        new C0171b("FORCE_DARK", "FORCE_DARK", 6);
        new C0171b("FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR", 2);
        f2537c = new C0171b("WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER", 2);
        new C0171b("DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1", 2);
        new C0171b("PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS", 2);
        new C0171b("GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER", 2);
        new C0171b("ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", 2);
        new C0171b("GET_COOKIE_INFO", "GET_COOKIE_INFO", 2);
        new C0171b("REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST", 2);
        new C0171b("USER_AGENT_METADATA", "USER_AGENT_METADATA", 2);
        new C0181l("USER_AGENT_METADATA_FORM_FACTORS", "USER_AGENT_METADATA", 0);
        new C0181l("MULTI_PROFILE", "MULTI_PROFILE", 1);
        new C0171b("ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR", 2);
        new C0171b("WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS", 2);
        new C0171b("MUTE_AUDIO", "MUTE_AUDIO", 2);
        new C0171b("WEB_AUTHENTICATION", "WEB_AUTHENTICATION", 2);
        new C0171b("SPECULATIVE_LOADING_STATUS", "SPECULATIVE_LOADING", 2);
        new C0171b("BACK_FORWARD_CACHE", "BACK_FORWARD_CACHE", 2);
        new C0171b("BACK_FORWARD_CACHE_SETTINGS", "BACK_FORWARD_CACHE_SETTINGS", 2);
        new C0171b("DELETE_BROWSING_DATA", "WEB_STORAGE_DELETE_BROWSING_DATA", 2);
        new C0181l("PREFETCH_URL_V5", "PREFETCH_URL_V5", 2);
        new C0171b("IMPLEMENTATION_ONLY_FEATURE", "ASYNC_WEBVIEW_STARTUP", 2);
        new C0171b("IMPLEMENTATION_ONLY_FEATURE", "ASYNC_WEBVIEW_STARTUP_ASYNC_STARTUP_LOCATIONS", 2);
        new C0171b("DEFAULT_TRAFFICSTATS_TAGGING", "DEFAULT_TRAFFICSTATS_TAGGING", 2);
        new C0171b("PRERENDER_URL_V2", "PRERENDER_URL_V3", 2);
        new C0171b("SPECULATIVE_LOADING_CONFIG_V2", "SPECULATIVE_LOADING_CONFIG_V2", 2);
        new C0171b("SAVE_STATE", "SAVE_STATE", 2);
        new C0171b("WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE", "WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE", 2);
        new C0171b("NAVIGATION_LISTENER_V1", "WEB_VIEW_NAVIGATION_LISTENER_V1", 2);
        f2538d = new C0171b("PROVIDER_WEAKLY_REF_WEBVIEW", "PROVIDER_WEAKLY_REF_WEBVIEW", 2);
        f2539e = new C0171b("PAYMENT_REQUEST", "PAYMENT_REQUEST", 2);
        new C0171b("WEBVIEW_BUILDER_EXPERIMENTAL_V1", "WEBVIEW_BUILDER_V1", 2);
        new C0171b("COOKIE_INTERCEPT", "COOKIE_INTERCEPT", 2);
        new C0171b("WARM_UP_RENDERER_PROCESS", "WARM_UP_RENDERER_PROCESS", 2);
        new C0171b("ORIGIN_MATCHED_HEADERS", "EXTRA_HEADER_FOR_ORIGINS", 2);
        new C0171b("CUSTOM_REQUEST_HEADERS", "CUSTOM_REQUEST_HEADERS", 2);
        new C0177h();
        new C0177h();
        new C0177h();
        new C0171b("PRECONNECT", "PRECONNECT", 2);
        new C0171b("ADD_QUIC_HINTS", "ADD_QUIC_HINTS_V1", 2);
        new C0171b("HYPERLINK_CONTEXT_MENU_ITEMS", "HYPERLINK_CONTEXT_MENU_ITEMS", 2);
    }
}
