package com.sofascore.model.mvvm.model;

import androidx.core.app.NotificationCompat;
import com.ironsource.U3;
import com.ironsource.mediationsdk.metadata.a;
import com.mbridge.msdk.playercommon.exoplayer2.C;
import com.mbridge.msdk.playercommon.exoplayer2.source.ExtractorMediaSource;
import com.sofascore.model.network.response.SearchResponseKt;
import com.sofascore.model.network.response.serializers.ServerTypeSerializer;
import defpackage.a7a;
import defpackage.dy4;
import defpackage.gz1;
import defpackage.iw8;
import defpackage.joa;
import defpackage.l98;
import defpackage.lkb;
import defpackage.uf3;
import defpackage.uhi;
import defpackage.uye;
import defpackage.wf3;
import defpackage.wx4;
import defpackage.yhk;
import defpackage.z8e;
import java.util.HashSet;
import java.util.List;
import kotlin.Metadata;
import kotlin.Unit;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import org.jetbrains.annotations.NotNull;

/* compiled from: r8-map-id-820aebbf04e3f76f83859749e000e999e94bc7aa15ea120a09e9f3ed9aa09d5a */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/sofascore/model/mvvm/model/Stage.$serializer", "Liw8;", "Lcom/sofascore/model/mvvm/model/Stage;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", U3.i.X, "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/sofascore/model/mvvm/model/Stage;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/sofascore/model/mvvm/model/Stage;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "model_release"}, k = 1, mv = {2, 3, 0}, xi = 48)
@wx4
/* loaded from: classes5.dex */
public final /* synthetic */ class Stage$$serializer implements iw8 {

    @NotNull
    public static final Stage$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        Stage$$serializer stage$$serializer = new Stage$$serializer();
        INSTANCE = stage$$serializer;
        uye uyeVar = new uye("com.sofascore.model.mvvm.model.Stage", stage$$serializer, 36);
        uyeVar.j(SearchResponseKt.UNIQUE_STAGE_ENTITY, false);
        uyeVar.j("description", false);
        uyeVar.j("slug", false);
        uyeVar.j("type", false);
        uyeVar.j("status", false);
        uyeVar.j("currentSubstage", false);
        uyeVar.j("substage", false);
        uyeVar.j("substageStartDateTimestamps", false);
        uyeVar.j("year", false);
        uyeVar.j("id", false);
        uyeVar.j("country", false);
        uyeVar.j("info", false);
        uyeVar.j("startTimestamp", false);
        uyeVar.j("startDateTimestamp", false);
        uyeVar.j("endDateTimestamp", false);
        uyeVar.j("winner", false);
        uyeVar.j("partSubstages", false);
        uyeVar.j("sequence", false);
        uyeVar.j("flag", false);
        uyeVar.j("stageParent", true);
        uyeVar.j("hasBet365LiveStream", false);
        uyeVar.j("bet365ExcludedCountryCodes", false);
        uyeVar.j("substages", false);
        uyeVar.j("raceStage", false);
        uyeVar.j("category", false);
        uyeVar.j("shortName", false);
        uyeVar.j("typeList", true);
        uyeVar.j("allSubStages", true);
        uyeVar.j("parentEvent", true);
        uyeVar.j("lastUpdate", true);
        uyeVar.j("stageEvent", true);
        uyeVar.j("stageDiscipline", true);
        uyeVar.j("stageSeason", true);
        uyeVar.j("isMuted", true);
        uyeVar.j("isHidden", true);
        uyeVar.j("isRecent", true);
        descriptor = uyeVar;
    }

    private Stage$$serializer() {
    }

    @Override // defpackage.iw8
    @NotNull
    public final KSerializer[] childSerializers() {
        joa[] joaVarArr;
        joaVarArr = Stage.$childSerializers;
        KSerializer W = l98.W(UniqueStage$$serializer.INSTANCE);
        uhi uhiVar = uhi.a;
        KSerializer W2 = l98.W(uhiVar);
        KSerializer W3 = l98.W(ServerTypeSerializer.INSTANCE);
        KSerializer W4 = l98.W(Status$$serializer.INSTANCE);
        Stage$$serializer stage$$serializer = INSTANCE;
        KSerializer W5 = l98.W(stage$$serializer);
        KSerializer W6 = l98.W(stage$$serializer);
        KSerializer W7 = l98.W((KSerializer) joaVarArr[7].getValue());
        KSerializer W8 = l98.W(uhiVar);
        a7a a7aVar = a7a.a;
        KSerializer W9 = l98.W(Country$$serializer.INSTANCE);
        KSerializer W10 = l98.W(StageInfo$$serializer.INSTANCE);
        lkb lkbVar = lkb.a;
        KSerializer W11 = l98.W(lkbVar);
        KSerializer W12 = l98.W(lkbVar);
        KSerializer W13 = l98.W(lkbVar);
        KSerializer W14 = l98.W(StageWinner$$serializer.INSTANCE);
        KSerializer W15 = l98.W((KSerializer) joaVarArr[16].getValue());
        KSerializer W16 = l98.W(a7aVar);
        KSerializer W17 = l98.W(uhiVar);
        KSerializer W18 = l98.W(stage$$serializer);
        gz1 gz1Var = gz1.a;
        return new KSerializer[]{W, uhiVar, W2, W3, W4, W5, W6, W7, W8, a7aVar, W9, W10, W11, W12, W13, W14, W15, W16, W17, W18, l98.W(gz1Var), l98.W((KSerializer) joaVarArr[21].getValue()), l98.W((KSerializer) joaVarArr[22].getValue()), l98.W(stage$$serializer), l98.W(Category$$serializer.INSTANCE), l98.W(uhiVar), l98.W((KSerializer) joaVarArr[26].getValue()), l98.W((KSerializer) joaVarArr[27].getValue()), l98.W(StageEvent$$serializer.INSTANCE), lkbVar, l98.W(stage$$serializer), l98.W(StageDiscipline$$serializer.INSTANCE), l98.W(StageSeason$$serializer.INSTANCE), gz1Var, gz1Var, gz1Var};
    }

    @Override // defpackage.dy4
    @NotNull
    public final Stage deserialize(@NotNull Decoder decoder) {
        joa[] joaVarArr;
        Category category;
        Stage stage;
        String str;
        UniqueStage uniqueStage;
        int i;
        Long l;
        Stage stage2;
        Integer num;
        List list;
        StageWinner stageWinner;
        Long l2;
        Category category2;
        Stage stage3;
        String str2;
        Long l3;
        int i2;
        Category category3;
        Stage stage4;
        String str3;
        Long l4;
        int i3;
        Stage stage5;
        String str4;
        int i4;
        String str5;
        int i5;
        decoder.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        uf3 b = decoder.b(serialDescriptor);
        joaVarArr = Stage.$childSerializers;
        long j = 0;
        Category category4 = null;
        Stage stage6 = null;
        List list2 = null;
        List list3 = null;
        String str6 = null;
        Stage stage7 = null;
        Boolean bool = null;
        List list4 = null;
        HashSet hashSet = null;
        Stage stage8 = null;
        StageEvent stageEvent = null;
        StageDiscipline stageDiscipline = null;
        StageSeason stageSeason = null;
        String str7 = null;
        boolean z = true;
        int i6 = 0;
        int i7 = 0;
        String str8 = null;
        UniqueStage uniqueStage2 = null;
        String str9 = null;
        ServerType serverType = null;
        Status status = null;
        Stage stage9 = null;
        Stage stage10 = null;
        List list5 = null;
        String str10 = null;
        Country country = null;
        StageInfo stageInfo = null;
        Long l5 = null;
        Long l6 = null;
        int i8 = 0;
        Long l7 = null;
        StageWinner stageWinner2 = null;
        List list6 = null;
        Integer num2 = null;
        boolean z2 = false;
        boolean z3 = false;
        boolean z4 = false;
        while (z) {
            int o = b.o(serialDescriptor);
            switch (o) {
                case -1:
                    category = category4;
                    stage = stage7;
                    str = str7;
                    uniqueStage = uniqueStage2;
                    i = i8;
                    l = l7;
                    stage2 = stage6;
                    Unit unit = Unit.a;
                    z = false;
                    str7 = str;
                    uniqueStage2 = uniqueStage;
                    num = num2;
                    category4 = category;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l;
                    i8 = i;
                    stage7 = stage;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 0:
                    category = category4;
                    stage = stage7;
                    str = str7;
                    int i9 = i8;
                    l = l7;
                    stage2 = stage6;
                    uniqueStage = (UniqueStage) b.i(serialDescriptor, 0, UniqueStage$$serializer.INSTANCE, uniqueStage2);
                    i = i9 | 1;
                    Unit unit2 = Unit.a;
                    str9 = str9;
                    str7 = str;
                    uniqueStage2 = uniqueStage;
                    num = num2;
                    category4 = category;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l;
                    i8 = i;
                    stage7 = stage;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 1:
                    stage = stage7;
                    String str11 = str7;
                    int i10 = i8;
                    l = l7;
                    stage2 = stage6;
                    String n = b.n(serialDescriptor, 1);
                    i = i10 | 2;
                    Unit unit3 = Unit.a;
                    str8 = n;
                    str7 = str11;
                    category4 = category4;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l;
                    i8 = i;
                    stage7 = stage;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 2:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i11 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    String str12 = (String) b.i(serialDescriptor, 2, uhi.a, str9);
                    i2 = i11 | 4;
                    Unit unit4 = Unit.a;
                    str9 = str12;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 3:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i12 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    ServerType serverType2 = (ServerType) b.i(serialDescriptor, 3, ServerTypeSerializer.INSTANCE, serverType);
                    i2 = i12 | 8;
                    Unit unit5 = Unit.a;
                    serverType = serverType2;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 4:
                    category3 = category4;
                    stage4 = stage7;
                    str3 = str7;
                    int i13 = i8;
                    l4 = l7;
                    stage2 = stage6;
                    Status status2 = (Status) b.i(serialDescriptor, 4, Status$$serializer.INSTANCE, status);
                    i3 = i13 | 16;
                    Unit unit6 = Unit.a;
                    status = status2;
                    str7 = str3;
                    stage7 = stage4;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l4;
                    i8 = i3;
                    category4 = category3;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 5:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i14 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    Stage stage11 = (Stage) b.i(serialDescriptor, 5, INSTANCE, stage9);
                    i2 = i14 | 32;
                    Unit unit7 = Unit.a;
                    stage9 = stage11;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 6:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i15 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    Stage stage12 = (Stage) b.i(serialDescriptor, 6, INSTANCE, stage10);
                    i2 = i15 | 64;
                    Unit unit8 = Unit.a;
                    stage10 = stage12;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 7:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i16 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    List list7 = (List) b.i(serialDescriptor, 7, (dy4) joaVarArr[7].getValue(), list5);
                    i2 = i16 | 128;
                    Unit unit9 = Unit.a;
                    list5 = list7;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 8:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i17 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    String str13 = (String) b.i(serialDescriptor, 8, uhi.a, str10);
                    i2 = i17 | NotificationCompat.FLAG_LOCAL_ONLY;
                    Unit unit10 = Unit.a;
                    str10 = str13;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 9:
                    category3 = category4;
                    stage4 = stage7;
                    int i18 = i8;
                    l4 = l7;
                    stage2 = stage6;
                    i7 = b.l(serialDescriptor, 9);
                    i3 = i18 | 512;
                    Unit unit11 = Unit.a;
                    stage7 = stage4;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l4;
                    i8 = i3;
                    category4 = category3;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 10:
                    category3 = category4;
                    stage4 = stage7;
                    str3 = str7;
                    int i19 = i8;
                    l4 = l7;
                    stage2 = stage6;
                    Country country2 = (Country) b.i(serialDescriptor, 10, Country$$serializer.INSTANCE, country);
                    i3 = i19 | 1024;
                    Unit unit12 = Unit.a;
                    country = country2;
                    str7 = str3;
                    stage7 = stage4;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l4;
                    i8 = i3;
                    category4 = category3;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 11:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i20 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    StageInfo stageInfo2 = (StageInfo) b.i(serialDescriptor, 11, StageInfo$$serializer.INSTANCE, stageInfo);
                    i2 = i20 | a.o;
                    Unit unit13 = Unit.a;
                    stageInfo = stageInfo2;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 12:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i21 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    Long l8 = (Long) b.i(serialDescriptor, 12, lkb.a, l5);
                    i2 = i21 | 4096;
                    Unit unit14 = Unit.a;
                    l5 = l8;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 13:
                    category2 = category4;
                    stage3 = stage7;
                    str2 = str7;
                    int i22 = i8;
                    l3 = l7;
                    stage2 = stage6;
                    Long l9 = (Long) b.i(serialDescriptor, 13, lkb.a, l6);
                    i2 = i22 | 8192;
                    Unit unit15 = Unit.a;
                    l6 = l9;
                    str7 = str2;
                    stage7 = stage3;
                    category4 = category2;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l3;
                    i8 = i2;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 14:
                    category3 = category4;
                    String str14 = str7;
                    Long l10 = (Long) b.i(serialDescriptor, 14, lkb.a, l7);
                    Unit unit16 = Unit.a;
                    stage2 = stage6;
                    i8 |= 16384;
                    str7 = str14;
                    stage7 = stage7;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l10;
                    category4 = category3;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 15:
                    category3 = category4;
                    String str15 = str7;
                    StageWinner stageWinner3 = (StageWinner) b.i(serialDescriptor, 15, StageWinner$$serializer.INSTANCE, stageWinner2);
                    Unit unit17 = Unit.a;
                    i8 |= 32768;
                    l2 = l7;
                    str7 = str15;
                    stage7 = stage7;
                    stage2 = stage6;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner3;
                    category4 = category3;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 16:
                    Category category5 = category4;
                    Stage stage13 = stage7;
                    String str16 = str7;
                    List list8 = (List) b.i(serialDescriptor, 16, (dy4) joaVarArr[16].getValue(), list6);
                    int i23 = i8 | C.DEFAULT_BUFFER_SEGMENT_SIZE;
                    Unit unit18 = Unit.a;
                    i8 = i23;
                    stageWinner = stageWinner2;
                    str7 = str16;
                    stage7 = stage13;
                    l2 = l7;
                    num = num2;
                    list = list8;
                    stage2 = stage6;
                    category4 = category5;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 17:
                    Category category6 = category4;
                    String str17 = str7;
                    Integer num3 = (Integer) b.i(serialDescriptor, 17, a7a.a, num2);
                    Unit unit19 = Unit.a;
                    i8 |= 131072;
                    list = list6;
                    str7 = str17;
                    stage7 = stage7;
                    num = num3;
                    stageWinner = stageWinner2;
                    category4 = category6;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 18:
                    Category category7 = category4;
                    Stage stage14 = stage7;
                    str7 = (String) b.i(serialDescriptor, 18, uhi.a, str7);
                    Unit unit20 = Unit.a;
                    i8 |= 262144;
                    num = num2;
                    stage7 = stage14;
                    category4 = category7;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 19:
                    String str18 = str7;
                    stage7 = (Stage) b.i(serialDescriptor, 19, INSTANCE, stage7);
                    Unit unit21 = Unit.a;
                    i8 |= 524288;
                    str7 = str18;
                    category4 = category4;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 20:
                    stage5 = stage7;
                    str4 = str7;
                    bool = (Boolean) b.i(serialDescriptor, 20, gz1.a, bool);
                    i4 = ExtractorMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES;
                    Unit unit22 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 21:
                    stage5 = stage7;
                    str4 = str7;
                    list3 = (List) b.i(serialDescriptor, 21, (dy4) joaVarArr[21].getValue(), list3);
                    i4 = 2097152;
                    Unit unit222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 22:
                    stage5 = stage7;
                    str4 = str7;
                    list2 = (List) b.i(serialDescriptor, 22, (dy4) joaVarArr[22].getValue(), list2);
                    i4 = 4194304;
                    Unit unit2222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 23:
                    stage5 = stage7;
                    str4 = str7;
                    stage6 = (Stage) b.i(serialDescriptor, 23, INSTANCE, stage6);
                    i4 = 8388608;
                    Unit unit22222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 24:
                    stage5 = stage7;
                    str4 = str7;
                    category4 = (Category) b.i(serialDescriptor, 24, Category$$serializer.INSTANCE, category4);
                    i4 = C.DEFAULT_MUXED_BUFFER_SIZE;
                    Unit unit222222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 25:
                    stage5 = stage7;
                    str4 = str7;
                    str6 = (String) b.i(serialDescriptor, 25, uhi.a, str6);
                    i4 = 33554432;
                    Unit unit2222222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 26:
                    stage5 = stage7;
                    str4 = str7;
                    hashSet = (HashSet) b.i(serialDescriptor, 26, (dy4) joaVarArr[26].getValue(), hashSet);
                    i4 = 67108864;
                    Unit unit22222222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 27:
                    stage5 = stage7;
                    str4 = str7;
                    list4 = (List) b.i(serialDescriptor, 27, (dy4) joaVarArr[27].getValue(), list4);
                    i4 = 134217728;
                    Unit unit222222222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 28:
                    stage5 = stage7;
                    str4 = str7;
                    stageEvent = (StageEvent) b.i(serialDescriptor, 28, StageEvent$$serializer.INSTANCE, stageEvent);
                    i4 = 268435456;
                    Unit unit2222222222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 29:
                    stage5 = stage7;
                    str4 = str7;
                    j = b.g(serialDescriptor, 29);
                    i4 = 536870912;
                    Unit unit22222222222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 30:
                    stage5 = stage7;
                    str4 = str7;
                    stage8 = (Stage) b.i(serialDescriptor, 30, INSTANCE, stage8);
                    i4 = 1073741824;
                    Unit unit222222222222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 31:
                    stage5 = stage7;
                    str4 = str7;
                    stageDiscipline = (StageDiscipline) b.i(serialDescriptor, 31, StageDiscipline$$serializer.INSTANCE, stageDiscipline);
                    i4 = Integer.MIN_VALUE;
                    Unit unit2222222222222 = Unit.a;
                    i8 |= i4;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 32:
                    str4 = str7;
                    stage5 = stage7;
                    stageSeason = (StageSeason) b.i(serialDescriptor, 32, StageSeason$$serializer.INSTANCE, stageSeason);
                    Unit unit23 = Unit.a;
                    i6 |= 1;
                    str7 = str4;
                    stage7 = stage5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 33:
                    str5 = str7;
                    z2 = b.B(serialDescriptor, 33);
                    i5 = i6 | 2;
                    Unit unit24 = Unit.a;
                    i6 = i5;
                    str7 = str5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 34:
                    str5 = str7;
                    z3 = b.B(serialDescriptor, 34);
                    i5 = i6 | 4;
                    Unit unit242 = Unit.a;
                    i6 = i5;
                    str7 = str5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                case 35:
                    str5 = str7;
                    z4 = b.B(serialDescriptor, 35);
                    i5 = i6 | 8;
                    Unit unit2422 = Unit.a;
                    i6 = i5;
                    str7 = str5;
                    num = num2;
                    list = list6;
                    stageWinner = stageWinner2;
                    l2 = l7;
                    stage2 = stage6;
                    stage6 = stage2;
                    l7 = l2;
                    stageWinner2 = stageWinner;
                    list6 = list;
                    num2 = num;
                default:
                    yhk.e(o);
                    return null;
            }
        }
        Category category8 = category4;
        Stage stage15 = stage7;
        UniqueStage uniqueStage3 = uniqueStage2;
        String str19 = str9;
        int i24 = i8;
        Long l11 = l7;
        Stage stage16 = stage6;
        b.c(serialDescriptor);
        return new Stage(i24, i6, uniqueStage3, str8, str19, serverType, status, stage9, stage10, list5, str10, i7, country, stageInfo, l5, l6, l11, stageWinner2, list6, num2, str7, stage15, bool, list3, list2, stage16, category8, str6, hashSet, list4, stageEvent, j, stage8, stageDiscipline, stageSeason, z2, z3, z4, null);
    }

    @Override // defpackage.dy4
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull Stage value) {
        encoder.getClass();
        value.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        wf3 b = encoder.b(serialDescriptor);
        Stage.write$Self$model_release(value, b, serialDescriptor);
        b.c(serialDescriptor);
    }

    @Override // defpackage.iw8
    @NotNull
    public /* bridge */ KSerializer[] typeParametersSerializers() {
        return z8e.e;
    }
}
