package com.google.android.libraries.places.internal;

/* loaded from: classes8.dex */
final class zzaab implements com.google.android.libraries.places.internal.zzbdw {
    static final com.google.android.libraries.places.internal.zzbdw zza = new com.google.android.libraries.places.internal.zzaab();

    @Override // com.google.android.libraries.places.internal.zzbdw
    public final boolean zza(int i) {
        switch (i) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
            case 9:
            case 10:
            case 11:
            case 12:
            case 13:
            case 14:
            case 15:
            case 16:
            case 17:
            case 18:
            case 19:
            case 20:
            case 21:
            case 22:
            case 23:
            case 24:
            case 25:
            case 26:
            case 27:
            case 28:
            case 29:
            case 30:
            case 31:
            case 32:
            case 33:
            case 34:
            case 35:
            case 36:
            case 37:
            case 38:
            case 39:
            case 40:
            case 41:
            case 42:
            case 43:
            case 44:
            case 45:
            case 46:
            case 47:
            case 48:
            case 49:
            case 50:
            case 51:
            case 52:
            case 53:
            case 54:
            case 55:
            case 56:
            case 57:
            case 58:
            case 59:
            case 60:
            case 61:
            case 62:
            case 63:
            case 64:
            case 65:
            case 66:
            case 67:
            case 68:
            case 69:
            case 70:
            case 71:
            case 72:
            case 73:
            case 74:
            case 75:
            case 76:
            case 77:
            case 78:
            case 79:
            case 80:
            case 81:
            case 82:
            case 83:
            case 84:
            case 85:
            case 86:
            case 87:
            case 88:
            case 89:
            case 90:
            case 91:
            case 92:
            case 93:
            case 94:
            case 95:
            case 96:
            case 97:
            case 98:
            case 99:
            case 100:
            case 101:
            case 102:
            case 103:
            case 104:
            case 105:
            case 106:
            case 107:
            case 108:
            case 109:
            case 110:
            case 111:
            case 112:
            case 113:
            case 114:
            case 115:
            case 116:
            case 117:
            case 118:
            case 119:
            case 120:
            case 121:
            case SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE:
            case SDK_ASSET_ILLUSTRATION_CALENDAR_VALUE:
            case SDK_ASSET_ILLUSTRATION_SIGNATURE_VALUE:
            case 125:
            case 126:
            case 127:
            case 128:
            case 129:
            case 130:
            case 131:
            case 132:
            case SDK_ASSET_ILLUSTRATION_DEV_FAULTY_DATA_VALUE:
            case 134:
            case 135:
            case 136:
            case 137:
            case 138:
            case SDK_ASSET_ILLUSTRATION_SPOT_PX_FEATURE_01_VALUE:
            case 140:
            case 141:
            case 142:
            case 143:
            case 144:
            case 145:
            case 146:
            case 147:
            case 148:
            case 149:
            case 150:
            case 151:
            case 152:
            case 153:
            case 154:
            case 155:
            case 156:
            case 157:
            case SDK_ASSET_ILLUSTRATION_WALLET_VALUE:
            case 159:
            case 160:
            case 161:
            case SDK_ASSET_ILLUSTRATION_SUPPORT_VALUE:
            case 163:
            case SDK_ASSET_ILLUSTRATION_SIGNIN_HEADER_VALUE:
            case 165:
            case 166:
            case 167:
            case SDK_ASSET_ILLUSTRATION_CODE_ACCOUNT_VERIFICATION_VALUE:
            case SDK_ASSET_HEADER_CARD_COLLECT_VALUE:
            case SDK_ASSET_ILLUSTRATION_INCOME_PAYROLL_URL_VALUE:
            case 171:
            case SDK_ASSET_ILLUSTRATION_CONSENT_HEADER_WEB3_DARK_APPEARANCE_VALUE:
            case SDK_ASSET_HEADER_FINAL_ERROR_DARK_APPEARANCE_VALUE:
            case 174:
            case 175:
            case 176:
            case SDK_ASSET_HEADER_FINAL_SUCCESS_DARK_APPEARANCE_VALUE:
            case SDK_ASSET_ILLUSTRATION_DEPOSIT_SWITCH_IDENTITY_DARK_APPEARANCE_VALUE:
            case 179:
            case SDK_ASSET_HEADER_NOT_LISTED_ERROR_VALUE:
            case 181:
            case SDK_ASSET_ILLUSTRATION_PINWHEEL_LOGO_VALUE:
            case 183:
            case SDK_ASSET_ILLUSTRATION_PLAID_PINWHEEL_TEXT_VALUE:
            case 185:
            case 186:
            case 187:
            case 188:
            case SDK_ASSET_ILLUSTRATION_CODE_ACCOUNT_VERIFICATION_2_VALUE:
            case SDK_ASSET_ILLUSTRATION_MD_ERROR_ATTEMPT_1_NEW_VALUE:
            case SDK_ASSET_ILLUSTRATION_MD_ERROR_ATTEMPT_2_NEW_VALUE:
            case 192:
            case 193:
            case SDK_ASSET_ICON_EXTERNAL_VALUE:
            case SDK_ASSET_ICON_ALERT_WARNING_VALUE:
            case SDK_ASSET_ICON_ARROW_DOWN_VALUE:
            case 197:
            case SDK_ASSET_ICON_ARROW_UP_VALUE:
            case 199:
            case 200:
                return true;
            default:
                return false;
        }
    }

    private zzaab() {
    }
}
