package com.frosthunter.arcticwildlands.frozenexpedition.adventure;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class anim {
        public static final int fragment_fast_out_extra_slow_in = 0x7f010000;
    }

    public static final class animator {
        public static final int fragment_close_enter = 0x7f020000;
        public static final int fragment_close_exit = 0x7f020001;
        public static final int fragment_fade_enter = 0x7f020002;
        public static final int fragment_fade_exit = 0x7f020003;
        public static final int fragment_open_enter = 0x7f020004;
        public static final int fragment_open_exit = 0x7f020005;
    }

    public static final class attr {
        public static final int alpha = 0x7f030000;
        public static final int buttonSize = 0x7f030001;
        public static final int circleCrop = 0x7f030002;
        public static final int colorScheme = 0x7f030003;
        public static final int font = 0x7f030004;
        public static final int fontProviderAuthority = 0x7f030005;
        public static final int fontProviderCerts = 0x7f030006;
        public static final int fontProviderFallbackQuery = 0x7f030007;
        public static final int fontProviderFetchStrategy = 0x7f030008;
        public static final int fontProviderFetchTimeout = 0x7f030009;
        public static final int fontProviderPackage = 0x7f03000a;
        public static final int fontProviderQuery = 0x7f03000b;
        public static final int fontProviderSystemFontFamily = 0x7f03000c;
        public static final int fontStyle = 0x7f03000d;
        public static final int fontVariationSettings = 0x7f03000e;
        public static final int fontWeight = 0x7f03000f;
        public static final int imageAspectRatio = 0x7f030010;
        public static final int imageAspectRatioAdjust = 0x7f030011;
        public static final int lStar = 0x7f030012;
        public static final int nestedScrollViewStyle = 0x7f030013;
        public static final int queryPatterns = 0x7f030014;
        public static final int scopeUris = 0x7f030015;
        public static final int shortcutMatchRequired = 0x7f030016;
        public static final int ttcIndex = 0x7f030017;
    }

    public static final class color {
        public static final int androidx_core_ripple_material_light = 0x7f040000;
        public static final int androidx_core_secondary_text_default_material_light = 0x7f040001;
        public static final int black = 0x7f040002;
        public static final int browser_actions_bg_grey = 0x7f040003;
        public static final int browser_actions_divider_color = 0x7f040004;
        public static final int browser_actions_text_color = 0x7f040005;
        public static final int browser_actions_title_color = 0x7f040006;
        public static final int call_notification_answer_color = 0x7f040007;
        public static final int call_notification_decline_color = 0x7f040008;
        public static final int common_google_signin_btn_text_dark = 0x7f040009;
        public static final int common_google_signin_btn_text_dark_default = 0x7f04000a;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f04000b;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f04000c;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f04000d;
        public static final int common_google_signin_btn_text_light = 0x7f04000e;
        public static final int common_google_signin_btn_text_light_default = 0x7f04000f;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f040010;
        public static final int common_google_signin_btn_text_light_focused = 0x7f040011;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f040012;
        public static final int common_google_signin_btn_tint = 0x7f040013;
        public static final int notification_action_color_filter = 0x7f040014;
        public static final int notification_icon_bg_color = 0x7f040015;
        public static final int purple_200 = 0x7f040016;
        public static final int purple_500 = 0x7f040017;
        public static final int purple_700 = 0x7f040018;
        public static final int teal_200 = 0x7f040019;
        public static final int teal_700 = 0x7f04001a;
        public static final int vector_tint_color = 0x7f04001b;
        public static final int vector_tint_theme_color = 0x7f04001c;
        public static final int white = 0x7f04001d;
    }

    public static final class dimen {
        public static final int browser_actions_context_menu_max_width = 0x7f050000;
        public static final int browser_actions_context_menu_min_padding = 0x7f050001;
        public static final int compat_button_inset_horizontal_material = 0x7f050002;
        public static final int compat_button_inset_vertical_material = 0x7f050003;
        public static final int compat_button_padding_horizontal_material = 0x7f050004;
        public static final int compat_button_padding_vertical_material = 0x7f050005;
        public static final int compat_control_corner_material = 0x7f050006;
        public static final int compat_notification_large_icon_max_height = 0x7f050007;
        public static final int compat_notification_large_icon_max_width = 0x7f050008;
        public static final int notification_action_icon_size = 0x7f050009;
        public static final int notification_action_text_size = 0x7f05000a;
        public static final int notification_big_circle_margin = 0x7f05000b;
        public static final int notification_content_margin_start = 0x7f05000c;
        public static final int notification_large_icon_height = 0x7f05000d;
        public static final int notification_large_icon_width = 0x7f05000e;
        public static final int notification_main_column_padding_top = 0x7f05000f;
        public static final int notification_media_narrow_margin = 0x7f050010;
        public static final int notification_right_icon_size = 0x7f050011;
        public static final int notification_right_side_padding_top = 0x7f050012;
        public static final int notification_small_icon_background_padding = 0x7f050013;
        public static final int notification_small_icon_size_as_large = 0x7f050014;
        public static final int notification_subtext_size = 0x7f050015;
        public static final int notification_top_pad = 0x7f050016;
        public static final int notification_top_pad_large_text = 0x7f050017;
    }

    public static final class drawable {
        public static final int _ic_launcher_foreground__0_res_0x7f060000 = 0x7f060000;
        public static final int abc_vector_test = 0x7f060001;
        public static final int btn_primary = 0x7f060002;
        public static final int common_google_signin_btn_icon_dark = 0x7f060004;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f060005;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f060006;
        public static final int common_google_signin_btn_icon_disabled = 0x7f060008;
        public static final int common_google_signin_btn_icon_light = 0x7f060009;
        public static final int common_google_signin_btn_icon_light_focused = 0x7f06000a;
        public static final int common_google_signin_btn_icon_light_normal = 0x7f06000b;
        public static final int common_google_signin_btn_text_dark = 0x7f06000d;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f06000e;
        public static final int common_google_signin_btn_text_dark_normal = 0x7f06000f;
        public static final int common_google_signin_btn_text_disabled = 0x7f060011;
        public static final int common_google_signin_btn_text_light = 0x7f060012;
        public static final int common_google_signin_btn_text_light_focused = 0x7f060013;
        public static final int common_google_signin_btn_text_light_normal = 0x7f060014;
        public static final int frost_bg = 0x7f060016;
        public static final int ic_call_answer = 0x7f060019;
        public static final int ic_call_answer_low = 0x7f06001a;
        public static final int ic_call_answer_video = 0x7f06001b;
        public static final int ic_call_answer_video_low = 0x7f06001c;
        public static final int ic_call_decline = 0x7f06001d;
        public static final int ic_call_decline_low = 0x7f06001e;
        public static final int ic_launcher_background = 0x7f06001f;
        public static final int ic_launcher_foreground = 0x7f060020;
        public static final int ice_center = 0x7f060021;
        public static final int ice_start_bg = 0x7f060022;
        public static final int item_bobber = 0x7f060023;
        public static final int item_helicopter = 0x7f060024;
        public static final int item_hook = 0x7f060025;
        public static final int item_lunchbox = 0x7f060026;
        public static final int item_net = 0x7f060027;
        public static final int item_rod = 0x7f060028;
        public static final int item_tackle = 0x7f060029;
        public static final int menu_logo = 0x7f06002a;
        public static final int notification_action_background = 0x7f06002b;
        public static final int notification_bg = 0x7f06002c;
        public static final int notification_bg_low = 0x7f06002d;
        public static final int notification_icon_background = 0x7f060032;
        public static final int notification_oversize_large_icon_bg = 0x7f060033;
        public static final int notification_template_icon_bg = 0x7f060034;
        public static final int notification_template_icon_low_bg = 0x7f060035;
        public static final int notification_tile_bg = 0x7f060036;
    }

    public static final class font {
        public static final int frost_font = 0x7f070000;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f080000;
        public static final int accessibility_custom_action_0 = 0x7f080001;
        public static final int accessibility_custom_action_1 = 0x7f080002;
        public static final int accessibility_custom_action_10 = 0x7f080003;
        public static final int accessibility_custom_action_11 = 0x7f080004;
        public static final int accessibility_custom_action_12 = 0x7f080005;
        public static final int accessibility_custom_action_13 = 0x7f080006;
        public static final int accessibility_custom_action_14 = 0x7f080007;
        public static final int accessibility_custom_action_15 = 0x7f080008;
        public static final int accessibility_custom_action_16 = 0x7f080009;
        public static final int accessibility_custom_action_17 = 0x7f08000a;
        public static final int accessibility_custom_action_18 = 0x7f08000b;
        public static final int accessibility_custom_action_19 = 0x7f08000c;
        public static final int accessibility_custom_action_2 = 0x7f08000d;
        public static final int accessibility_custom_action_20 = 0x7f08000e;
        public static final int accessibility_custom_action_21 = 0x7f08000f;
        public static final int accessibility_custom_action_22 = 0x7f080010;
        public static final int accessibility_custom_action_23 = 0x7f080011;
        public static final int accessibility_custom_action_24 = 0x7f080012;
        public static final int accessibility_custom_action_25 = 0x7f080013;
        public static final int accessibility_custom_action_26 = 0x7f080014;
        public static final int accessibility_custom_action_27 = 0x7f080015;
        public static final int accessibility_custom_action_28 = 0x7f080016;
        public static final int accessibility_custom_action_29 = 0x7f080017;
        public static final int accessibility_custom_action_3 = 0x7f080018;
        public static final int accessibility_custom_action_30 = 0x7f080019;
        public static final int accessibility_custom_action_31 = 0x7f08001a;
        public static final int accessibility_custom_action_4 = 0x7f08001b;
        public static final int accessibility_custom_action_5 = 0x7f08001c;
        public static final int accessibility_custom_action_6 = 0x7f08001d;
        public static final int accessibility_custom_action_7 = 0x7f08001e;
        public static final int accessibility_custom_action_8 = 0x7f08001f;
        public static final int accessibility_custom_action_9 = 0x7f080020;
        public static final int action_container = 0x7f080021;
        public static final int action_divider = 0x7f080022;
        public static final int action_image = 0x7f080023;
        public static final int action_text = 0x7f080024;
        public static final int actions = 0x7f080025;
        public static final int adjust_height = 0x7f080026;
        public static final int adjust_width = 0x7f080027;
        public static final int androidx_compose_ui_view_composition_context = 0x7f080028;
        public static final int async = 0x7f080029;
        public static final int auto = 0x7f08002a;
        public static final int blocking = 0x7f08002b;
        public static final int browser_actions_header_text = 0x7f08002c;
        public static final int browser_actions_menu_item_icon = 0x7f08002d;
        public static final int browser_actions_menu_item_text = 0x7f08002e;
        public static final int browser_actions_menu_items = 0x7f08002f;
        public static final int browser_actions_menu_view = 0x7f080030;
        public static final int chronometer = 0x7f080031;
        public static final int coil3_request_manager = 0x7f080032;
        public static final int compose_prefetch_scheduler = 0x7f080033;
        public static final int compose_view_saveable_id_tag = 0x7f080034;
        public static final int consume_window_insets_tag = 0x7f080035;
        public static final int dark = 0x7f080036;
        public static final int dialog_button = 0x7f080037;
        public static final int edit_text_id = 0x7f080038;
        public static final int forever = 0x7f080039;
        public static final int fragment_container_view_tag = 0x7f08003a;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f08003b;
        public static final int hide_ime_id = 0x7f08003c;
        public static final int hide_in_inspector_tag = 0x7f08003d;
        public static final int icon = 0x7f08003e;
        public static final int icon_group = 0x7f08003f;
        public static final int icon_only = 0x7f080040;
        public static final int info = 0x7f080041;
        public static final int inspection_slot_table_set = 0x7f080042;
        public static final int is_pooling_container_tag = 0x7f080043;
        public static final int italic = 0x7f080044;
        public static final int light = 0x7f080045;
        public static final int line1 = 0x7f080046;
        public static final int line3 = 0x7f080047;
        public static final int none = 0x7f080048;
        public static final int normal = 0x7f080049;
        public static final int notification_background = 0x7f08004a;
        public static final int notification_main_column = 0x7f08004b;
        public static final int notification_main_column_container = 0x7f08004c;
        public static final int pooling_container_listener_holder_tag = 0x7f08004d;
        public static final int report_drawn = 0x7f08004e;
        public static final int right_icon = 0x7f08004f;
        public static final int right_side = 0x7f080050;
        public static final int special_effects_controller_view_tag = 0x7f080051;
        public static final int standard = 0x7f080052;
        public static final int tag_accessibility_actions = 0x7f080053;
        public static final int tag_accessibility_clickable_spans = 0x7f080054;
        public static final int tag_accessibility_heading = 0x7f080055;
        public static final int tag_accessibility_pane_title = 0x7f080056;
        public static final int tag_compat_insets_dispatch = 0x7f080057;
        public static final int tag_on_apply_window_listener = 0x7f080058;
        public static final int tag_on_receive_content_listener = 0x7f080059;
        public static final int tag_on_receive_content_mime_types = 0x7f08005a;
        public static final int tag_screen_reader_focusable = 0x7f08005b;
        public static final int tag_state_description = 0x7f08005c;
        public static final int tag_system_bar_state_monitor = 0x7f08005d;
        public static final int tag_transition_group = 0x7f08005e;
        public static final int tag_unhandled_key_event_manager = 0x7f08005f;
        public static final int tag_unhandled_key_listeners = 0x7f080060;
        public static final int tag_window_insets_animation_callback = 0x7f080061;
        public static final int text = 0x7f080062;
        public static final int text2 = 0x7f080063;
        public static final int time = 0x7f080064;
        public static final int title = 0x7f080065;
        public static final int view_tree_disjoint_parent = 0x7f080066;
        public static final int view_tree_lifecycle_owner = 0x7f080067;
        public static final int view_tree_navigation_event_dispatcher_owner = 0x7f080068;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f080069;
        public static final int view_tree_saved_state_registry_owner = 0x7f08006a;
        public static final int view_tree_view_model_store_owner = 0x7f08006b;
        public static final int visible_removing_fragment_view_tag = 0x7f08006c;
        public static final int wide = 0x7f08006d;
        public static final int wrapped_composition_tag = 0x7f08006e;
    }

    public static final class integer {
        public static final int google_play_services_version = 0x7f090000;
        public static final int m3c_window_layout_in_display_cutout_mode = 0x7f090001;
        public static final int status_bar_notification_info_maxnum = 0x7f090002;
    }

    public static final class layout {
        public static final int browser_actions_context_menu_page = 0x7f0a0000;
        public static final int browser_actions_context_menu_row = 0x7f0a0001;
        public static final int custom_dialog = 0x7f0a0002;
        public static final int ime_base_split_test_activity = 0x7f0a0003;
        public static final int ime_secondary_split_test_activity = 0x7f0a0004;
        public static final int notification_action = 0x7f0a0005;
        public static final int notification_action_tombstone = 0x7f0a0006;
        public static final int notification_template_custom_big = 0x7f0a0007;
        public static final int notification_template_icon_group = 0x7f0a0008;
        public static final int notification_template_part_chronometer = 0x7f0a0009;
        public static final int notification_template_part_time = 0x7f0a000a;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f0b0000;
        public static final int ic_launcher_foreground = 0x7f0b0001;
        public static final int ic_launcher_monochrome = 0x7f0b0002;
        public static final int ic_launcher_round = 0x7f0b0003;
    }

    public static final class raw {
        public static final int bg_music = 0x7f0c0000;
        public static final int firebase_common_keep = 0x7f0c0001;
        public static final int sfx_correct = 0x7f0c0002;
        public static final int sfx_lose = 0x7f0c0003;
        public static final int sfx_miss = 0x7f0c0004;
        public static final int sfx_tap = 0x7f0c0005;
        public static final int sfx_win = 0x7f0c0006;
        public static final int sfx_wrong = 0x7f0c0007;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f0d0000;
        public static final int app_name = 0x7f0d0001;
        public static final int autofill = 0x7f0d0002;
        public static final int call_notification_answer_action = 0x7f0d0003;
        public static final int call_notification_answer_video_action = 0x7f0d0004;
        public static final int call_notification_decline_action = 0x7f0d0005;
        public static final int call_notification_hang_up_action = 0x7f0d0006;
        public static final int call_notification_incoming_text = 0x7f0d0007;
        public static final int call_notification_ongoing_text = 0x7f0d0008;
        public static final int call_notification_screening_text = 0x7f0d0009;
        public static final int close_drawer = 0x7f0d000a;
        public static final int close_sheet = 0x7f0d000b;
        public static final int common_google_play_services_enable_button = 0x7f0d000c;
        public static final int common_google_play_services_enable_text = 0x7f0d000d;
        public static final int common_google_play_services_enable_title = 0x7f0d000e;
        public static final int common_google_play_services_install_button = 0x7f0d000f;
        public static final int common_google_play_services_install_text = 0x7f0d0010;
        public static final int common_google_play_services_install_title = 0x7f0d0011;
        public static final int common_google_play_services_notification_channel_name = 0x7f0d0012;
        public static final int common_google_play_services_notification_ticker = 0x7f0d0013;
        public static final int common_google_play_services_unknown_issue = 0x7f0d0014;
        public static final int common_google_play_services_unsupported_text = 0x7f0d0015;
        public static final int common_google_play_services_update_button = 0x7f0d0016;
        public static final int common_google_play_services_update_text = 0x7f0d0017;
        public static final int common_google_play_services_update_title = 0x7f0d0018;
        public static final int common_google_play_services_updating_text = 0x7f0d0019;
        public static final int common_google_play_services_wear_update_text = 0x7f0d001a;
        public static final int common_open_on_phone = 0x7f0d001b;
        public static final int common_signin_button_text = 0x7f0d001c;
        public static final int common_signin_button_text_long = 0x7f0d001d;
        public static final int copy_toast_msg = 0x7f0d001e;
        public static final int default_error_message = 0x7f0d001f;
        public static final int default_popup_window_title = 0x7f0d0020;
        public static final int dropdown_menu = 0x7f0d0021;
        public static final int exo_download_completed = 0x7f0d0022;
        public static final int exo_download_description = 0x7f0d0023;
        public static final int exo_download_downloading = 0x7f0d0024;
        public static final int exo_download_failed = 0x7f0d0025;
        public static final int exo_download_notification_channel_name = 0x7f0d0026;
        public static final int exo_download_paused = 0x7f0d0027;
        public static final int exo_download_paused_for_network = 0x7f0d0028;
        public static final int exo_download_paused_for_wifi = 0x7f0d0029;
        public static final int exo_download_removing = 0x7f0d002a;
        public static final int fallback_menu_item_copy_link = 0x7f0d002b;
        public static final int fallback_menu_item_open_in_browser = 0x7f0d002c;
        public static final int fallback_menu_item_share_link = 0x7f0d002d;
        public static final int fcm_fallback_notification_channel_label = 0x7f0d002e;
        public static final int gcm_defaultSenderId = 0x7f0d002f;
        public static final int google_api_key = 0x7f0d0030;
        public static final int google_app_id = 0x7f0d0031;
        public static final int google_crash_reporting_api_key = 0x7f0d0032;
        public static final int google_storage_bucket = 0x7f0d0033;
        public static final int in_progress = 0x7f0d0034;
        public static final int indeterminate = 0x7f0d0035;
        public static final int m3c_bottom_sheet_collapse_description = 0x7f0d0036;
        public static final int m3c_bottom_sheet_dismiss_description = 0x7f0d0037;
        public static final int m3c_bottom_sheet_drag_handle_description = 0x7f0d0038;
        public static final int m3c_bottom_sheet_expand_description = 0x7f0d0039;
        public static final int m3c_bottom_sheet_pane_title = 0x7f0d003a;
        public static final int m3c_date_input_headline = 0x7f0d003b;
        public static final int m3c_date_input_headline_description = 0x7f0d003c;
        public static final int m3c_date_input_invalid_for_pattern = 0x7f0d003d;
        public static final int m3c_date_input_invalid_not_allowed = 0x7f0d003e;
        public static final int m3c_date_input_invalid_year_range = 0x7f0d003f;
        public static final int m3c_date_input_label = 0x7f0d0040;
        public static final int m3c_date_input_no_input_description = 0x7f0d0041;
        public static final int m3c_date_input_title = 0x7f0d0042;
        public static final int m3c_date_picker_headline = 0x7f0d0043;
        public static final int m3c_date_picker_headline_description = 0x7f0d0044;
        public static final int m3c_date_picker_navigate_to_year_description = 0x7f0d0045;
        public static final int m3c_date_picker_no_selection_description = 0x7f0d0046;
        public static final int m3c_date_picker_scroll_to_earlier_years = 0x7f0d0047;
        public static final int m3c_date_picker_scroll_to_later_years = 0x7f0d0048;
        public static final int m3c_date_picker_switch_to_calendar_mode = 0x7f0d0049;
        public static final int m3c_date_picker_switch_to_day_selection = 0x7f0d004a;
        public static final int m3c_date_picker_switch_to_input_mode = 0x7f0d004b;
        public static final int m3c_date_picker_switch_to_next_month = 0x7f0d004c;
        public static final int m3c_date_picker_switch_to_previous_month = 0x7f0d004d;
        public static final int m3c_date_picker_switch_to_year_selection = 0x7f0d004e;
        public static final int m3c_date_picker_title = 0x7f0d004f;
        public static final int m3c_date_picker_today_description = 0x7f0d0050;
        public static final int m3c_date_picker_year_picker_pane_title = 0x7f0d0051;
        public static final int m3c_date_range_input_invalid_range_input = 0x7f0d0052;
        public static final int m3c_date_range_input_title = 0x7f0d0053;
        public static final int m3c_date_range_picker_day_in_range = 0x7f0d0054;
        public static final int m3c_date_range_picker_end_headline = 0x7f0d0055;
        public static final int m3c_date_range_picker_scroll_to_next_month = 0x7f0d0056;
        public static final int m3c_date_range_picker_scroll_to_previous_month = 0x7f0d0057;
        public static final int m3c_date_range_picker_start_headline = 0x7f0d0058;
        public static final int m3c_date_range_picker_title = 0x7f0d0059;
        public static final int m3c_dialog = 0x7f0d005a;
        public static final int m3c_dropdown_menu_collapsed = 0x7f0d005b;
        public static final int m3c_dropdown_menu_expanded = 0x7f0d005c;
        public static final int m3c_dropdown_menu_toggle = 0x7f0d005d;
        public static final int m3c_search_bar_search = 0x7f0d005e;
        public static final int m3c_snackbar_dismiss = 0x7f0d005f;
        public static final int m3c_suggestions_available = 0x7f0d0060;
        public static final int m3c_time_picker_am = 0x7f0d0061;
        public static final int m3c_time_picker_hour = 0x7f0d0062;
        public static final int m3c_time_picker_hour_24h_suffix = 0x7f0d0063;
        public static final int m3c_time_picker_hour_selection = 0x7f0d0064;
        public static final int m3c_time_picker_hour_suffix = 0x7f0d0065;
        public static final int m3c_time_picker_hour_text_field = 0x7f0d0066;
        public static final int m3c_time_picker_minute = 0x7f0d0067;
        public static final int m3c_time_picker_minute_selection = 0x7f0d0068;
        public static final int m3c_time_picker_minute_suffix = 0x7f0d0069;
        public static final int m3c_time_picker_minute_text_field = 0x7f0d006a;
        public static final int m3c_time_picker_period_toggle_description = 0x7f0d006b;
        public static final int m3c_time_picker_pm = 0x7f0d006c;
        public static final int m3c_tooltip_long_press_label = 0x7f0d006d;
        public static final int m3c_tooltip_pane_description = 0x7f0d006e;
        public static final int navigation_menu = 0x7f0d006f;
        public static final int not_selected = 0x7f0d0070;
        public static final int project_id = 0x7f0d0071;
        public static final int range_end = 0x7f0d0072;
        public static final int range_start = 0x7f0d0073;
        public static final int selected = 0x7f0d0074;
        public static final int snackbar_pane_title = 0x7f0d0075;
        public static final int state_empty = 0x7f0d0076;
        public static final int state_off = 0x7f0d0077;
        public static final int state_on = 0x7f0d0078;
        public static final int status_bar_notification_info_overflow = 0x7f0d0079;
        public static final int switch_role = 0x7f0d007a;
        public static final int tab = 0x7f0d007b;
        public static final int template_percent = 0x7f0d007c;
        public static final int title_activity_generator_state = 0x7f0d007d;
        public static final int title_activity_glass_new = 0x7f0d007e;
        public static final int tooltip_description = 0x7f0d007f;
        public static final int tooltip_label = 0x7f0d0080;
    }

    public static final class style {
        public static final int DialogWindowTheme = 0x7f0e0000;
        public static final int EdgeToEdgeFloatingDialogTheme = 0x7f0e0001;
        public static final int EdgeToEdgeFloatingDialogWindowTheme = 0x7f0e0002;
        public static final int FloatingDialogWindowTheme = 0x7f0e0003;
        public static final int TextAppearance_Compat_Notification = 0x7f0e0004;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0e0005;
        public static final int TextAppearance_Compat_Notification_Line2 = 0x7f0e0006;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0e0007;
        public static final int TextAppearance_Compat_Notification_Title = 0x7f0e0008;
        public static final int Theme_FrostHunter = 0x7f0e0009;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0e000a;
        public static final int Widget_Compat_NotificationActionText = 0x7f0e000b;
    }

    public static final class xml {
        public static final int backup_rules = 0x7f100000;
        public static final int data_extraction_rules = 0x7f100001;
        public static final int image_share_filepaths = 0x7f100002;
        public static final int splits0 = 0x7f100003;
    }
}
