package android.content.Context;

import android.content.Context;
import java.util.LinkedHashMap;

/* compiled from: r8-map-id-ad53bc00775cc49f3760de3ef5ee15f0f7d4eb373264baa1785c3fa1a15d54ed */
/* loaded from: classes.dex */
public abstract /* synthetic */ class FrostHunterAudioManagerBlazeElite6721 {
    public static FrostHunterConstraintSetVisionCelestial6602 FrostHunterAlphaAnimationNeoCosmos5761(Context context) {
        FrostHunterTraceHyperionAuroraNebula9947 frostHunterTraceHyperionAuroraNebula9947 = new FrostHunterTraceHyperionAuroraNebula9947(context, 21);
        FrostHunterProximitySensorVortexUltraTitanium2580 frostHunterProximitySensorVortexUltraTitanium2580 = (FrostHunterProximitySensorVortexUltraTitanium2580) frostHunterTraceHyperionAuroraNebula9947.FrostHunterAlertDialogAuroraDelta3200;
        FrostHunterInstrumentationStrikeBlazeThunder7469 frostHunterInstrumentationStrikeBlazeThunder7469 = FrostHunterKeyEventPrimeCelestial6796.FrostHunterAlphaAnimationNeoCosmos5761;
        frostHunterProximitySensorVortexUltraTitanium2580.getClass();
        LinkedHashMap linkedHashMap = frostHunterProximitySensorVortexUltraTitanium2580.FrostHunterAlphaAnimationNeoCosmos5761;
        linkedHashMap.put(frostHunterInstrumentationStrikeBlazeThunder7469, FrostHunterLinearLayoutSolarHero7990.FrostHunterAlphaAnimationNeoCosmos5761);
        Context context2 = (Context) frostHunterTraceHyperionAuroraNebula9947.FrostHunterKeyframeGammaGamma1197;
        FrostHunterColorDrawableOlympianRogue6537 frostHunterColorDrawableOlympianRogue6537 = (FrostHunterColorDrawableOlympianRogue6537) frostHunterTraceHyperionAuroraNebula9947.FrostHunterFlowMaxDragonHero5809;
        FrostHunterColorDrawableOlympianRogue6537 frostHunterColorDrawableOlympianRogue65372 = new FrostHunterColorDrawableOlympianRogue6537(frostHunterColorDrawableOlympianRogue6537.FrostHunterAlphaAnimationNeoCosmos5761, frostHunterColorDrawableOlympianRogue6537.FrostHunterConstraintSetCloneMasterUltraRogue2633, frostHunterColorDrawableOlympianRogue6537.FrostHunterBundlePulseFusionHero2475, frostHunterColorDrawableOlympianRogue6537.FrostHunterServiceEliteCelestialThunder1757, frostHunterColorDrawableOlympianRogue6537.FrostHunterLifecycleBlazeGammaElite2889, frostHunterColorDrawableOlympianRogue6537.FrostHunterLevelListDrawableFusionDragonHero2232, frostHunterColorDrawableOlympianRogue6537.FrostHunterRemoteConfigSpeedSpeed8566, frostHunterColorDrawableOlympianRogue6537.FrostHunterCameraXPixelTurboCosmos9814, frostHunterColorDrawableOlympianRogue6537.FrostHunterFlowMaxDragonHero5809, frostHunterColorDrawableOlympianRogue6537.FrostHunterAlertDialogAuroraDelta3200, frostHunterColorDrawableOlympianRogue6537.FrostHunterKeyframeGammaGamma1197, frostHunterColorDrawableOlympianRogue6537.FrostHunterFragmentBetaMegaVortex6025, frostHunterColorDrawableOlympianRogue6537.FrostHunterServiceConnectionTurboPhoenixOmega6719, new FrostHunterAnalyticsNovaXHeroEclipse9164(FrostHunterCanvasInfernoVortex4700.FrostHunterColorDrawableLegendPhoenixVision7927(linkedHashMap)));
        int i = 10;
        FrostHunterSharedFlowTitaniumBeta1713 frostHunterSharedFlowTitaniumBeta1713 = new FrostHunterSharedFlowTitaniumBeta1713(new FrostHunterNavigationViewSpectraBlazeOmega1546(i));
        FrostHunterSharedFlowTitaniumBeta1713 frostHunterSharedFlowTitaniumBeta17132 = new FrostHunterSharedFlowTitaniumBeta1713(new FrostHunterAnimatorAlphaVortexInferno7431(i, frostHunterTraceHyperionAuroraNebula9947));
        FrostHunterSharedFlowTitaniumBeta1713 frostHunterSharedFlowTitaniumBeta17133 = new FrostHunterSharedFlowTitaniumBeta1713(new FrostHunterNavigationViewSpectraBlazeOmega1546(11));
        FrostHunterAssetManagerForceNebulaNebula4990 frostHunterAssetManagerForceNebulaNebula4990 = FrostHunterAssetManagerForceNebulaNebula4990.FrostHunterCameraXPixelTurboCosmos9814;
        return new FrostHunterConstraintSetVisionCelestial6602(new FrostHunterPoseDetectionFusionHyperion4759(context2, frostHunterColorDrawableOlympianRogue65372, frostHunterSharedFlowTitaniumBeta1713, frostHunterSharedFlowTitaniumBeta17132, frostHunterSharedFlowTitaniumBeta17133, new FrostHunterActionBarPixelDelta3353(frostHunterAssetManagerForceNebulaNebula4990, frostHunterAssetManagerForceNebulaNebula4990, frostHunterAssetManagerForceNebulaNebula4990, frostHunterAssetManagerForceNebulaNebula4990, frostHunterAssetManagerForceNebulaNebula4990)));
    }
}
