package android.content.Context;

/* compiled from: r8-map-id-ad53bc00775cc49f3760de3ef5ee15f0f7d4eb373264baa1785c3fa1a15d54ed */
/* loaded from: classes.dex */
public final class FrostHunterImageAnalysisVisionPixel4510 implements FrostHunterPagingDataBetaGammaSolar8478 {
    public static final FrostHunterImageAnalysisVisionPixel4510 FrostHunterAlphaAnimationNeoCosmos5761 = new FrostHunterImageAnalysisVisionPixel4510();
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterConstraintSetCloneMasterUltraRogue2633 = new FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896("window", FrostHunterKeyEventNovaXAlpha1220.FrostHunterScaleAnimationStrikeSpark5059(FrostHunterKeyEventNovaXAlpha1220.FrostHunterLightSensorForceFusion4241(FrostHunterSoundPoolBetaNeo6657.class, new FrostHunterTextWatcherFusionStorm5992(1))));
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterBundlePulseFusionHero2475 = new FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896("logSourceMetrics", FrostHunterKeyEventNovaXAlpha1220.FrostHunterScaleAnimationStrikeSpark5059(FrostHunterKeyEventNovaXAlpha1220.FrostHunterLightSensorForceFusion4241(FrostHunterSoundPoolBetaNeo6657.class, new FrostHunterTextWatcherFusionStorm5992(2))));
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterServiceEliteCelestialThunder1757 = new FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896("globalMetrics", FrostHunterKeyEventNovaXAlpha1220.FrostHunterScaleAnimationStrikeSpark5059(FrostHunterKeyEventNovaXAlpha1220.FrostHunterLightSensorForceFusion4241(FrostHunterSoundPoolBetaNeo6657.class, new FrostHunterTextWatcherFusionStorm5992(3))));
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterLifecycleBlazeGammaElite2889 = new FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896("appNamespace", FrostHunterKeyEventNovaXAlpha1220.FrostHunterScaleAnimationStrikeSpark5059(FrostHunterKeyEventNovaXAlpha1220.FrostHunterLightSensorForceFusion4241(FrostHunterSoundPoolBetaNeo6657.class, new FrostHunterTextWatcherFusionStorm5992(4))));

    @Override // android.content.Context.FrostHunterDrawableEpicHero6631
    public final void FrostHunterAlphaAnimationNeoCosmos5761(Object obj, Object obj2) {
        FrostHunterTextureViewPhoenixSolarAlpha5815 frostHunterTextureViewPhoenixSolarAlpha5815 = (FrostHunterTextureViewPhoenixSolarAlpha5815) obj;
        FrostHunterGestureDetectorNovaXStormSpark6209 frostHunterGestureDetectorNovaXStormSpark6209 = (FrostHunterGestureDetectorNovaXStormSpark6209) obj2;
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterAlphaAnimationNeoCosmos5761(FrostHunterConstraintSetCloneMasterUltraRogue2633, frostHunterTextureViewPhoenixSolarAlpha5815.FrostHunterAlphaAnimationNeoCosmos5761);
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterAlphaAnimationNeoCosmos5761(FrostHunterBundlePulseFusionHero2475, frostHunterTextureViewPhoenixSolarAlpha5815.FrostHunterConstraintSetCloneMasterUltraRogue2633);
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterAlphaAnimationNeoCosmos5761(FrostHunterServiceEliteCelestialThunder1757, frostHunterTextureViewPhoenixSolarAlpha5815.FrostHunterBundlePulseFusionHero2475);
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterAlphaAnimationNeoCosmos5761(FrostHunterLifecycleBlazeGammaElite2889, frostHunterTextureViewPhoenixSolarAlpha5815.FrostHunterServiceEliteCelestialThunder1757);
    }
}
