package defpackage;

import java.util.LinkedHashMap;

/* compiled from: r8-map-id-99198b194f64cf930afe678846937ee242c378eb2e5d7167669b3ca844d0162b */
/* loaded from: classes.dex */
public final class yj {
    public static final yj BRwzKIf41E4i;
    public static final xj Companion;
    public static final yj OPXfSBeufaJ8;
    public static final yj QrzZRwfaDlRX;
    public static final yj RAsUl2FVSrh6;
    public static final yj RfyTYNmI9Srp;
    public static final LinkedHashMap TSizfFm2Yiuu;
    public static final yj XL4ISE6Oc65B;
    public static final yj Y1f8riQaR6yg;
    public static final yj a92UlCVFR9N8;
    public static final yj cpQdD2nAriOS;
    public static final yj dgRBjINgWbAK;
    public static final yj e9gEMXR7LXtO;
    public static final yj gPXPFXrUH4XX;
    public static final db0 lS5Rgt96tfkO;
    public static final yj r3s1LDPKFs1S;
    public static final yj rtx2ld2ELZv4;
    public static final yj wdg6QnbFHrFF;
    public static final yj x50lh2ztY7Y5;
    public final String PxuCJdSBwIXG;

    static {
        xj xjVar = new xj();
        Companion = xjVar;
        lS5Rgt96tfkO = new db0(7);
        TSizfFm2Yiuu = new LinkedHashMap();
        xj.PxuCJdSBwIXG(xjVar, "SSL_RSA_WITH_NULL_MD5");
        xj.PxuCJdSBwIXG(xjVar, "SSL_RSA_WITH_NULL_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_RSA_EXPORT_WITH_RC4_40_MD5");
        xj.PxuCJdSBwIXG(xjVar, "SSL_RSA_WITH_RC4_128_MD5");
        xj.PxuCJdSBwIXG(xjVar, "SSL_RSA_WITH_RC4_128_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_RSA_WITH_DES_CBC_SHA");
        Y1f8riQaR6yg = xj.PxuCJdSBwIXG(xjVar, "SSL_RSA_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DHE_DSS_WITH_DES_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DHE_RSA_WITH_DES_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DH_anon_WITH_RC4_128_MD5");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DH_anon_WITH_DES_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_WITH_DES_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_WITH_RC4_128_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_WITH_DES_CBC_MD5");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_WITH_RC4_128_MD5");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5");
        xj.PxuCJdSBwIXG(xjVar, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5");
        e9gEMXR7LXtO = xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DH_anon_WITH_AES_128_CBC_SHA");
        a92UlCVFR9N8 = xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DH_anon_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_NULL_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_AES_128_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_AES_256_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DH_anon_WITH_AES_128_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DH_anon_WITH_AES_256_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_PSK_WITH_RC4_128_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_PSK_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_PSK_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_PSK_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_SEED_CBC_SHA");
        RAsUl2FVSrh6 = xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_AES_128_GCM_SHA256");
        rtx2ld2ELZv4 = xj.PxuCJdSBwIXG(xjVar, "TLS_RSA_WITH_AES_256_GCM_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DH_anon_WITH_AES_128_GCM_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DH_anon_WITH_AES_256_GCM_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV");
        xj.PxuCJdSBwIXG(xjVar, "TLS_FALLBACK_SCSV");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_NULL_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_NULL_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_NULL_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_RC4_128_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_NULL_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_RC4_128_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA");
        OPXfSBeufaJ8 = xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA");
        wdg6QnbFHrFF = xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_anon_WITH_NULL_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_anon_WITH_RC4_128_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384");
        dgRBjINgWbAK = xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256");
        x50lh2ztY7Y5 = xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384");
        cpQdD2nAriOS = xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
        r3s1LDPKFs1S = xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA");
        QrzZRwfaDlRX = xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        gPXPFXrUH4XX = xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        BRwzKIf41E4i = xj.PxuCJdSBwIXG(xjVar, "TLS_AES_128_GCM_SHA256");
        XL4ISE6Oc65B = xj.PxuCJdSBwIXG(xjVar, "TLS_AES_256_GCM_SHA384");
        RfyTYNmI9Srp = xj.PxuCJdSBwIXG(xjVar, "TLS_CHACHA20_POLY1305_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_AES_128_CCM_SHA256");
        xj.PxuCJdSBwIXG(xjVar, "TLS_AES_128_CCM_8_SHA256");
    }

    public yj(String str) {
        this.PxuCJdSBwIXG = str;
    }

    public final String toString() {
        return this.PxuCJdSBwIXG;
    }
}
