package com.gamericefishpro.space.n3;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-020a1517951ead57be77a6b773195444ecc812bf491d4c7c9fe6933b01540740 */
/* JADX INFO: loaded from: classes.dex */
public final class j {
    public int a;
    public final m b;
    public final l c;
    public final k d;
    public final n e;
    public HashMap f;

    public j() {
        m mVar = new m();
        mVar.a = 0;
        mVar.b = 0;
        mVar.c = 1.0f;
        mVar.d = Float.NaN;
        this.b = mVar;
        l lVar = new l();
        lVar.a = -1;
        lVar.b = 0;
        lVar.c = -1;
        lVar.d = Float.NaN;
        lVar.e = Float.NaN;
        lVar.f = Float.NaN;
        lVar.g = -1;
        lVar.h = null;
        lVar.i = -1;
        this.c = lVar;
        k kVar = new k();
        kVar.a = false;
        kVar.d = -1;
        kVar.e = -1;
        kVar.f = -1.0f;
        kVar.g = -1;
        kVar.h = -1;
        kVar.i = -1;
        kVar.j = -1;
        kVar.k = -1;
        kVar.l = -1;
        kVar.m = -1;
        kVar.n = -1;
        kVar.o = -1;
        kVar.p = -1;
        kVar.q = -1;
        kVar.r = -1;
        kVar.s = -1;
        kVar.t = -1;
        kVar.u = -1;
        kVar.v = 0.5f;
        kVar.w = 0.5f;
        kVar.x = null;
        kVar.y = -1;
        kVar.z = 0;
        kVar.A = 0.0f;
        kVar.B = -1;
        kVar.C = -1;
        kVar.D = -1;
        kVar.E = 0;
        kVar.F = 0;
        kVar.G = 0;
        kVar.H = 0;
        kVar.I = 0;
        kVar.J = 0;
        kVar.K = 0;
        kVar.L = Integer.MIN_VALUE;
        kVar.M = Integer.MIN_VALUE;
        kVar.N = Integer.MIN_VALUE;
        kVar.O = Integer.MIN_VALUE;
        kVar.P = Integer.MIN_VALUE;
        kVar.Q = Integer.MIN_VALUE;
        kVar.R = Integer.MIN_VALUE;
        kVar.S = -1.0f;
        kVar.T = -1.0f;
        kVar.U = 0;
        kVar.V = 0;
        kVar.W = 0;
        kVar.X = 0;
        kVar.Y = -1;
        kVar.Z = -1;
        kVar.a0 = -1;
        kVar.b0 = -1;
        kVar.c0 = 1.0f;
        kVar.d0 = 1.0f;
        kVar.e0 = -1;
        kVar.f0 = 0;
        kVar.g0 = -1;
        kVar.k0 = false;
        kVar.l0 = false;
        kVar.m0 = true;
        kVar.n0 = 0;
        this.d = kVar;
        n nVar = new n();
        nVar.a = 0.0f;
        nVar.b = 0.0f;
        nVar.c = 0.0f;
        nVar.d = 1.0f;
        nVar.e = 1.0f;
        nVar.f = Float.NaN;
        nVar.g = Float.NaN;
        nVar.h = -1;
        nVar.i = 0.0f;
        nVar.j = 0.0f;
        nVar.k = 0.0f;
        nVar.l = false;
        nVar.m = 0.0f;
        this.e = nVar;
        this.f = new HashMap();
    }

    public final void a(e eVar) {
        k kVar = this.d;
        eVar.d = kVar.g;
        eVar.e = kVar.h;
        eVar.f = kVar.i;
        eVar.g = kVar.j;
        eVar.h = kVar.k;
        eVar.i = kVar.l;
        eVar.j = kVar.m;
        eVar.k = kVar.n;
        eVar.l = kVar.o;
        eVar.m = kVar.p;
        eVar.n = kVar.q;
        eVar.r = kVar.r;
        eVar.s = kVar.s;
        eVar.t = kVar.t;
        eVar.u = kVar.u;
        ((ViewGroup.MarginLayoutParams) eVar).leftMargin = kVar.E;
        ((ViewGroup.MarginLayoutParams) eVar).rightMargin = kVar.F;
        ((ViewGroup.MarginLayoutParams) eVar).topMargin = kVar.G;
        ((ViewGroup.MarginLayoutParams) eVar).bottomMargin = kVar.H;
        eVar.z = kVar.Q;
        eVar.A = kVar.P;
        eVar.w = kVar.M;
        eVar.y = kVar.O;
        eVar.D = kVar.v;
        eVar.E = kVar.w;
        eVar.o = kVar.y;
        eVar.p = kVar.z;
        eVar.q = kVar.A;
        eVar.F = kVar.x;
        eVar.S = kVar.B;
        eVar.T = kVar.C;
        eVar.H = kVar.S;
        eVar.G = kVar.T;
        eVar.J = kVar.V;
        eVar.I = kVar.U;
        eVar.V = kVar.k0;
        eVar.W = kVar.l0;
        eVar.K = kVar.W;
        eVar.L = kVar.X;
        eVar.O = kVar.Y;
        eVar.P = kVar.Z;
        eVar.M = kVar.a0;
        eVar.N = kVar.b0;
        eVar.Q = kVar.c0;
        eVar.R = kVar.d0;
        eVar.U = kVar.D;
        eVar.c = kVar.f;
        eVar.a = kVar.d;
        eVar.b = kVar.e;
        ((ViewGroup.MarginLayoutParams) eVar).width = kVar.b;
        ((ViewGroup.MarginLayoutParams) eVar).height = kVar.c;
        String str = kVar.j0;
        if (str != null) {
            eVar.X = str;
        }
        eVar.Y = kVar.n0;
        eVar.setMarginStart(kVar.J);
        eVar.setMarginEnd(kVar.I);
        eVar.a();
    }

    public final Object clone() {
        j jVar = new j();
        k kVar = jVar.d;
        kVar.getClass();
        k kVar2 = this.d;
        kVar.a = kVar2.a;
        kVar.b = kVar2.b;
        kVar.c = kVar2.c;
        kVar.d = kVar2.d;
        kVar.e = kVar2.e;
        kVar.f = kVar2.f;
        kVar.g = kVar2.g;
        kVar.h = kVar2.h;
        kVar.i = kVar2.i;
        kVar.j = kVar2.j;
        kVar.k = kVar2.k;
        kVar.l = kVar2.l;
        kVar.m = kVar2.m;
        kVar.n = kVar2.n;
        kVar.o = kVar2.o;
        kVar.p = kVar2.p;
        kVar.q = kVar2.q;
        kVar.r = kVar2.r;
        kVar.s = kVar2.s;
        kVar.t = kVar2.t;
        kVar.u = kVar2.u;
        kVar.v = kVar2.v;
        kVar.w = kVar2.w;
        kVar.x = kVar2.x;
        kVar.y = kVar2.y;
        kVar.z = kVar2.z;
        kVar.A = kVar2.A;
        kVar.B = kVar2.B;
        kVar.C = kVar2.C;
        kVar.D = kVar2.D;
        kVar.E = kVar2.E;
        kVar.F = kVar2.F;
        kVar.G = kVar2.G;
        kVar.H = kVar2.H;
        kVar.I = kVar2.I;
        kVar.J = kVar2.J;
        kVar.K = kVar2.K;
        kVar.L = kVar2.L;
        kVar.M = kVar2.M;
        kVar.N = kVar2.N;
        kVar.O = kVar2.O;
        kVar.P = kVar2.P;
        kVar.Q = kVar2.Q;
        kVar.R = kVar2.R;
        kVar.S = kVar2.S;
        kVar.T = kVar2.T;
        kVar.U = kVar2.U;
        kVar.V = kVar2.V;
        kVar.W = kVar2.W;
        kVar.X = kVar2.X;
        kVar.Y = kVar2.Y;
        kVar.Z = kVar2.Z;
        kVar.a0 = kVar2.a0;
        kVar.b0 = kVar2.b0;
        kVar.c0 = kVar2.c0;
        kVar.d0 = kVar2.d0;
        kVar.e0 = kVar2.e0;
        kVar.f0 = kVar2.f0;
        kVar.g0 = kVar2.g0;
        kVar.j0 = kVar2.j0;
        int[] iArr = kVar2.h0;
        if (iArr != null) {
            kVar.h0 = Arrays.copyOf(iArr, iArr.length);
        } else {
            kVar.h0 = null;
        }
        kVar.i0 = kVar2.i0;
        kVar.k0 = kVar2.k0;
        kVar.l0 = kVar2.l0;
        kVar.m0 = kVar2.m0;
        kVar.n0 = kVar2.n0;
        l lVar = jVar.c;
        lVar.getClass();
        l lVar2 = this.c;
        lVar2.getClass();
        lVar.a = lVar2.a;
        lVar.c = lVar2.c;
        lVar.e = lVar2.e;
        lVar.d = lVar2.d;
        m mVar = this.b;
        int i = mVar.a;
        m mVar2 = jVar.b;
        mVar2.a = i;
        mVar2.c = mVar.c;
        mVar2.d = mVar.d;
        mVar2.b = mVar.b;
        n nVar = jVar.e;
        nVar.getClass();
        n nVar2 = this.e;
        nVar2.getClass();
        nVar.a = nVar2.a;
        nVar.b = nVar2.b;
        nVar.c = nVar2.c;
        nVar.d = nVar2.d;
        nVar.e = nVar2.e;
        nVar.f = nVar2.f;
        nVar.g = nVar2.g;
        nVar.h = nVar2.h;
        nVar.i = nVar2.i;
        nVar.j = nVar2.j;
        nVar.k = nVar2.k;
        nVar.l = nVar2.l;
        nVar.m = nVar2.m;
        jVar.a = this.a;
        return jVar;
    }
}
