package ae;

import kotlin.jvm.internal.Intrinsics;

/* compiled from: r8-map-id-1007347d93e945b62163496d2b3d545e4cec50eb5f7054b93987970dfadb4b15 */
/* loaded from: classes.dex */
public final class a {

    /* renamed from: a, reason: collision with root package name */
    public final String[] f132a = {"Betting is a very exciting thing with good possibilities for income. However, many beginners in this field lose their many so fast and don’t even understand how this could happen to them. Let’s speak about some typical mistakes made by beginners.", "", "Superficial understanding of bookmaker’s rules. We set it as first mistake, because really think, when you don’t find out deeply how bookmaker works, it will bring you many problems in future;", "Fast income awaiting. This problem is very clear in live-betting, where player wants to increase his income right now, but it usually goes to nothing due to game unpredictability;", "Small odds. Many beginners think: if odds are small, there are more chances for win. It’s true partly only, because in long-term distance your budget will be empty. When you use bets with small odds, your income will be not big – once favorite team loses, all your previous total income will bite the dust;", "Poor financial management. Sometimes player has many winning bets in long-term distance, but small total income – it become true due to poor financial management;", "Big excitement and reaction. These two things interfere player to be good at betting very often. When they have winning streak, they think it will never end. When they’ve got losing streak – player does everything to bring his money back. It’s not a good idea;", "Non-independent behavior. Analysis ignoring, dark deals, lack of personal game-strategy bring problems with your income. Betting is about permanent analysis and self-development.", "", "If you don’t want to lose all your money in first gaming day or week, follow some basic rules:", "Choose right bookmaker;", "Manage your finances correctly. Use under 2% of your bank for one bet;", "Follow your strategy. There are lot of famous gaming-strategies helping player to save his money. You should follow it no matter what;", "Do it yourself! Personal analysis and understanding of sports will definitely help you to increase your income. All successful persons in betting actively use their own knowledge mixed with expert’s predictions and opinions."};

    /* renamed from: b, reason: collision with root package name */
    public final String[] f133b = {"Беттинг - довольно захватывающее хобби, которое может приносить доход. Казалось бы, всё просто - ставь и жди прибыли. Однако многие начинающие беттеры теряют деньги настолько быстро, что не успевают понять и осознать, как такое произошло. Приведем ниже типичные ошибки новичков, а далее поделимся некоторыми советами, как избежать опустошения личного игрового банка.", "Частые ошибки", "Поверхностное изучение правил букмекерской конторы. Мы решили поставить это самой первой ошибкой, потому что зачастую именно неполноценное изучение правил и особенностей приводят к проигрышу;", "Желание заработать быстро. Особенно эта ошибка встречается в live-ставках, когда игрок вливает сумму денег по ходу матча. Часто такая история заканчивается провалом из-за непредсказуемости игры;", "Ставки с низкими коэффициентами. Многие считают, что если коэффициент низкий, значит, велика вероятность захода. Это верно лишь отчасти, поскольку на дистанции с такой стратегией вы все равно останетесь в минусе. Поскольку из-за низкого коэффициента прибыль тоже будет низкая, любое поражение фаворита (а оно может случиться в любой момент) сведет к нулю весь ваш заработок за предыдущее время;", "Неудачное управление банком. Часто бывает так, что вроде у игрока много заходов, а денег все равно в итоге меньше, чем было. Это происходит из-за того, что новичок неправильно соотносит сумму ставки с коэффициентом;", "Излишне эмоциональная реакция и азарт. Очень часто эти две составляющие мешают начинающему беттеру взглянуть на ситуацию трезво. Когда идет череда плюсов, многие верят, что так будет всегда, и начинают ставить более крупные суммы. Когда начинаются минусы - стараются всеми силами отыграть упущенное;", "Нежелание размышлять самостоятельно. Покупка “договорных” матчей, игнорирование анализа и разработки собственной стратегии игры приводят к тому, что рано или поздно банк опустошается. Беттинг - это постоянный анализ, изучение и саморазвитие, без этого нельзя заработать на дистанции.", "Базовые правила", "Чтобы не допускать ранее упомянутых ошибок, начинающим беттерам стоит следовать нескольким базовым правилам:", "Правильный выбор букмекера. Изучите правила досконально, выберите подходящий для вас вариант;", "Корректное управление банком. В самом начале рекомендуем ставить не более 2% от общего банка. Так вы сможете обкатать свою игровую стратегию, понять, какой тип ставок вам подходит больше, и при этом потерять лишь какую-то часть своего капитала;", "Придерживайтесь стратегии. Существует большое количество стратегий, которые помогают игроку со ставками. Необходимо постоянно им придерживаться, несмотря на взлеты и падения;", "Самостоятельный анализ. Это одно из самых важных вещей в беттинге, поскольку те капперы, которые сейчас в плюсе, достигли этого исключительно благодаря умению думать своей головой, самостоятельно анализировать, использовать чужие данные для принятия собственных решений."};

    /* renamed from: c, reason: collision with root package name */
    public final String[] f134c = {"Les paris sportifs sont une activité très excitante offrant de bonnes possibilités de gains. Cependant, de nombreux débutants perdent leur argent très rapidement sans même comprendre comment cela a pu leur arriver. Parlons de quelques erreurs typiques commises par les débutants.", "", "Compréhension superficielle des règles du bookmaker. Nous plaçons cela en première position, car sans une bonne compréhension du fonctionnement d’un bookmaker, de nombreux problèmes apparaîtront à l’avenir ;", "Attente de gains rapides. Ce problème est particulièrement visible dans les paris en direct, où le joueur souhaite augmenter ses gains immédiatement, mais cela conduit souvent à des pertes en raison de l’imprévisibilité du jeu ;", "Cotes trop faibles. Beaucoup de débutants pensent que de faibles cotes signifient plus de chances de gagner. C’est partiellement vrai, mais à long terme votre capital s’épuisera. Une seule défaite d’un favori peut annuler tous les gains précédents ;", "Mauvaise gestion financière. Il arrive qu’un joueur ait beaucoup de paris gagnants sur une longue période, mais un faible bénéfice total — en raison d’une mauvaise gestion du capital ;", "Excès d’émotions et réactions impulsives. Ces deux facteurs empêchent souvent de réussir. En série de victoires, le joueur pense que cela ne finira jamais. En série de défaites, il essaie de récupérer son argent à tout prix. Ce n’est pas une bonne idée ;", "Manque d’indépendance. Ignorer l’analyse, suivre des accords douteux et ne pas avoir de stratégie personnelle entraînent des problèmes de rentabilité. Les paris reposent sur l’analyse constante et le développement personnel.", "", "Si vous ne voulez pas perdre tout votre argent dès le premier jour ou la première semaine, suivez quelques règles de base :", "Choisissez le bon bookmaker ;", "Gérez correctement vos finances. Utilisez moins de 2 % de votre capital pour un seul pari ;", "Suivez votre stratégie. Il existe de nombreuses stratégies connues qui aident à préserver le capital. Vous devez vous y tenir quoi qu’il arrive ;", "Faites-le vous-même ! L’analyse personnelle et la compréhension du sport vous aideront certainement à augmenter vos gains. Tous les parieurs à succès utilisent leurs propres connaissances combinées aux avis d’experts."};

    /* renamed from: d, reason: collision with root package name */
    public final String[] f135d = {"Sportwetten sind sehr spannend und bieten gute Einkommensmöglichkeiten. Dennoch verlieren viele Anfänger ihr Geld sehr schnell, ohne zu verstehen, wie es dazu kommen konnte. Schauen wir uns einige typische Anfängerfehler an.", "", "Oberflächliches Verständnis der Buchmacherregeln. Dies ist der wichtigste Fehler, denn ohne ein tiefes Verständnis der Funktionsweise eines Buchmachers entstehen in Zukunft viele Probleme;", "Erwartung schneller Gewinne. Dieses Problem ist besonders im Live-Wetten sichtbar, wenn der Spieler sofort Gewinne erzielen möchte, was jedoch oft aufgrund der Unberechenbarkeit des Spiels scheitert;", "Zu niedrige Quoten. Viele Anfänger glauben, niedrige Quoten bedeuteten höhere Gewinnchancen. Das stimmt nur teilweise, denn langfristig wird das Kapital aufgebraucht. Eine Niederlage des Favoriten kann alle vorherigen Gewinne zunichtemachen;", "Schlechtes Finanzmanagement. Manchmal hat ein Spieler viele gewonnene Wetten über einen längeren Zeitraum, aber nur einen geringen Gesamtgewinn — aufgrund falscher Budgetverwaltung;", "Zu große Emotionen und impulsives Verhalten. Beides hindert Spieler häufig am Erfolg. Bei Siegesserien glauben sie, diese würden nie enden. Bei Verlustserien versuchen sie verzweifelt, das Geld zurückzugewinnen. Das ist keine gute Idee;", "Unselbstständiges Verhalten. Ignorierte Analysen, dubiose Tipps und das Fehlen einer eigenen Strategie führen zu finanziellen Problemen. Wetten erfordern ständige Analyse und Weiterentwicklung.", "", "Wenn Sie nicht Ihr gesamtes Geld am ersten Tag oder in der ersten Woche verlieren möchten, befolgen Sie einige grundlegende Regeln:", "Wählen Sie den richtigen Buchmacher;", "Verwalten Sie Ihr Kapital korrekt. Setzen Sie weniger als 2 % Ihres Guthabens pro Wette;", "Halten Sie sich an Ihre Strategie. Es gibt viele bekannte Wettstrategien, die helfen, das Kapital zu schützen. Bleiben Sie dabei, egal was passiert;", "Machen Sie es selbst! Eigene Analysen und Sportverständnis helfen Ihnen definitiv, Ihre Gewinne zu steigern. Erfolgreiche Wetter kombinieren ihr Wissen mit Expertenmeinungen."};

    /* renamed from: e, reason: collision with root package name */
    public final String[] f136e = {"Las apuestas deportivas son muy emocionantes y ofrecen buenas oportunidades de ingresos. Sin embargo, muchos principiantes pierden su dinero muy rápido sin entender cómo ocurrió. Veamos algunos errores típicos de los novatos.", "", "Comprensión superficial de las reglas del bookmaker. Este es el primer error, ya que no entender bien cómo funciona una casa de apuestas traerá muchos problemas en el futuro;", "Esperar ganancias rápidas. Este problema es muy común en las apuestas en vivo, donde el jugador quiere aumentar sus ingresos de inmediato, pero la imprevisibilidad del juego suele llevar a pérdidas;", "Cuotas bajas. Muchos principiantes creen que cuotas bajas significan más probabilidades de ganar. Esto es solo parcialmente cierto, ya que a largo plazo el capital se agotará. Una sola derrota del favorito puede eliminar todas las ganancias anteriores;", "Mala gestión financiera. A veces el jugador tiene muchas apuestas ganadoras a largo plazo, pero un beneficio total bajo debido a una mala administración del dinero;", "Exceso de emoción y reacciones impulsivas. Estos factores suelen perjudicar al jugador. En rachas ganadoras, piensan que nunca terminarán; en rachas perdedoras, intentan recuperar el dinero a toda costa. No es una buena idea;", "Falta de independencia. Ignorar el análisis, seguir acuerdos dudosos y no tener una estrategia personal genera problemas de rentabilidad. Apostar requiere análisis constante y desarrollo personal.", "", "Si no quieres perder todo tu dinero el primer día o la primera semana, sigue algunas reglas básicas:", "Elige el bookmaker adecuado;", "Gestiona correctamente tus finanzas. Usa menos del 2 % de tu banca en una sola apuesta;", "Sigue tu estrategia. Existen muchas estrategias conocidas que ayudan a conservar el dinero. Debes seguirlas pase lo que pase;", "Hazlo tú mismo. El análisis personal y el conocimiento del deporte te ayudarán a aumentar tus ingresos. Los apostadores exitosos combinan su conocimiento con opiniones de expertos."};

    /* renamed from: f, reason: collision with root package name */
    public final String[] f137f = {"As apostas esportivas são muito emocionantes e oferecem boas possibilidades de ganho. No entanto, muitos iniciantes perdem seu dinheiro muito rápido sem entender como isso aconteceu. Vamos falar sobre alguns erros típicos dos iniciantes.", "", "Compreensão superficial das regras do bookmaker. Colocamos isso como o primeiro erro, pois não entender bem como uma casa de apostas funciona trará muitos problemas no futuro;", "Expectativa de ganhos rápidos. Esse problema é comum nas apostas ao vivo, quando o jogador quer lucrar imediatamente, mas a imprevisibilidade do jogo geralmente leva a perdas;", "Odds baixas. Muitos iniciantes acreditam que odds baixas significam mais chances de vitória. Isso é apenas parcialmente verdade, pois no longo prazo o capital se esgota. Uma única derrota do favorito pode anular todos os ganhos anteriores;", "Má gestão financeira. Às vezes o jogador tem muitas apostas vencedoras no longo prazo, mas pouco lucro total devido a uma gestão inadequada do dinheiro;", "Excesso de emoção e reações impulsivas. Esses fatores frequentemente atrapalham o sucesso. Em sequências de vitórias, o jogador acha que nunca vai acabar; em sequências de derrotas, tenta recuperar o dinheiro a qualquer custo. Isso não é uma boa ideia;", "Comportamento não independente. Ignorar análises, seguir esquemas duvidosos e não ter uma estratégia própria leva a problemas de rentabilidade. Apostar exige análise constante e desenvolvimento pessoal.", "", "Se você não quer perder todo o seu dinheiro no primeiro dia ou semana, siga algumas regras básicas:", "Escolha o bookmaker certo;", "Gerencie suas finanças corretamente. Use menos de 2% da sua banca em uma aposta;", "Siga sua estratégia. Existem muitas estratégias conhecidas que ajudam a preservar o capital. Você deve segui-las independentemente da situação;", "Faça você mesmo! A análise pessoal e o conhecimento esportivo certamente ajudarão a aumentar seus ganhos. Apostadores bem-sucedidos combinam seu conhecimento com opiniões de especialistas."};

    /* renamed from: g, reason: collision with root package name */
    public final String[] f138g = {"Bahis yapmak oldukça heyecanlıdır ve iyi kazanç fırsatları sunar. Ancak bu alana yeni giren birçok kişi parasını çok hızlı kaybeder ve bunun nasıl olduğunu bile anlayamaz. Yeni başlayanların yaptığı bazı tipik hatalardan bahsedelim.", "", "Bahis sitesinin kurallarını yüzeysel şekilde anlamak. Bunu ilk hata olarak görüyoruz, çünkü bir bahis sitesinin nasıl çalıştığını derinlemesine anlamazsanız ileride birçok sorun yaşarsınız;", "Hızlı kazanç beklentisi. Bu sorun özellikle canlı bahislerde görülür; oyuncu hemen kazanmak ister, ancak maçların öngörülemezliği genellikle kayıpla sonuçlanır;", "Düşük oranlar. Birçok yeni başlayan, düşük oranların kazanma şansını artırdığını düşünür. Bu yalnızca kısmen doğrudur; uzun vadede banka tükenir. Favori bir takımın tek bir yenilgisi önceki tüm kazançları silebilir;", "Zayıf finansal yönetim. Bazen oyuncunun uzun vadede birçok kazanan bahsi olur, ancak kötü bütçe yönetimi nedeniyle toplam kazanç düşük kalır;", "Aşırı heyecan ve tepkisel davranışlar. Bu iki unsur sıkça başarıyı engeller. Kazanç serilerinde oyuncu bunun hiç bitmeyeceğini düşünür; kayıp serilerinde ise parasını geri almaya çalışır. Bu iyi bir fikir değildir;", "Bağımsız davranmamak. Analizi göz ardı etmek, karanlık anlaşmalar ve kişisel strateji eksikliği kazanç sorunlarına yol açar. Bahis, sürekli analiz ve kendini geliştirme gerektirir.", "", "Eğer ilk gün veya ilk hafta tüm paranızı kaybetmek istemiyorsanız, bazı temel kurallara uyun:", "Doğru bahis sitesini seçin;", "Finansmanınızı doğru yönetin. Tek bir bahis için bankanızın %2’sinden azını kullanın;", "Stratejinize sadık kalın. Paranızı korumanıza yardımcı olan birçok bilinen bahis stratejisi vardır. Ne olursa olsun bunlara uyun;", "Kendiniz yapın! Kişisel analiz ve spor bilgisi kazancınızı artırmanıza kesinlikle yardımcı olur. Başarılı bahisçiler kendi bilgilerini uzman görüşleriyle birleştirir."};

    public final String a(int i5, String language) {
        String[] strArr;
        Intrinsics.checkNotNullParameter(language, "language");
        int hashCode = language.hashCode();
        if (hashCode == 3201) {
            if (language.equals("de")) {
                strArr = this.f135d;
            }
            strArr = this.f132a;
        } else if (hashCode == 3246) {
            if (language.equals("es")) {
                strArr = this.f136e;
            }
            strArr = this.f132a;
        } else if (hashCode == 3276) {
            if (language.equals("fr")) {
                strArr = this.f134c;
            }
            strArr = this.f132a;
        } else if (hashCode == 3588) {
            if (language.equals("pt")) {
                strArr = this.f137f;
            }
            strArr = this.f132a;
        } else if (hashCode != 3651) {
            if (hashCode == 3710 && language.equals("tr")) {
                strArr = this.f138g;
            }
            strArr = this.f132a;
        } else {
            if (language.equals("ru")) {
                strArr = this.f133b;
            }
            strArr = this.f132a;
        }
        int i10 = i5 - 1;
        return (i10 >= strArr.length || i10 < 0) ? "" : strArr[i10];
    }
}
