package com.skytonedarps.arskthrp;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int activityAction = 0x7f030000;
        public static final int activityName = 0x7f030001;
        public static final int alpha = 0x7f030002;
        public static final int alwaysExpand = 0x7f030003;
        public static final int animationBackgroundColor = 0x7f030004;
        public static final int buttonSize = 0x7f030005;
        public static final int circleCrop = 0x7f030006;
        public static final int clearTop = 0x7f030007;
        public static final int colorScheme = 0x7f030008;
        public static final int finishPrimaryWithPlaceholder = 0x7f030009;
        public static final int finishPrimaryWithSecondary = 0x7f03000a;
        public static final int finishSecondaryWithPrimary = 0x7f03000b;
        public static final int font = 0x7f03000c;
        public static final int fontProviderAuthority = 0x7f03000d;
        public static final int fontProviderCerts = 0x7f03000e;
        public static final int fontProviderFetchStrategy = 0x7f03000f;
        public static final int fontProviderFetchTimeout = 0x7f030010;
        public static final int fontProviderPackage = 0x7f030011;
        public static final int fontProviderQuery = 0x7f030012;
        public static final int fontProviderSystemFontFamily = 0x7f030013;
        public static final int fontStyle = 0x7f030014;
        public static final int fontVariationSettings = 0x7f030015;
        public static final int fontWeight = 0x7f030016;
        public static final int imageAspectRatio = 0x7f030017;
        public static final int imageAspectRatioAdjust = 0x7f030018;
        public static final int lStar = 0x7f030019;
        public static final int nestedScrollViewStyle = 0x7f03001a;
        public static final int placeholderActivityName = 0x7f03001b;
        public static final int primaryActivityName = 0x7f03001c;
        public static final int queryPatterns = 0x7f03001d;
        public static final int scopeUris = 0x7f03001e;
        public static final int secondaryActivityAction = 0x7f03001f;
        public static final int secondaryActivityName = 0x7f030020;
        public static final int shortcutMatchRequired = 0x7f030021;
        public static final int splitLayoutDirection = 0x7f030022;
        public static final int splitMaxAspectRatioInLandscape = 0x7f030023;
        public static final int splitMaxAspectRatioInPortrait = 0x7f030024;
        public static final int splitMinHeightDp = 0x7f030025;
        public static final int splitMinSmallestWidthDp = 0x7f030026;
        public static final int splitMinWidthDp = 0x7f030027;
        public static final int splitRatio = 0x7f030028;
        public static final int stickyPlaceholder = 0x7f030029;
        public static final int tag = 0x7f03002a;
        public static final int ttcIndex = 0x7f03002b;
    }

    public static final class color {
        public static final int androidx_core_ripple_material_light = 0x7f040000;
        public static final int androidx_core_secondary_text_default_material_light = 0x7f040001;
        public static final int call_notification_answer_color = 0x7f040006;
        public static final int call_notification_decline_color = 0x7f040007;
        public static final int notification_action_color_filter = 0x7f040013;
        public static final int notification_icon_bg_color = 0x7f040014;
    }

    public static final class dimen {
        public static final int browser_actions_context_menu_max_width = 0x7f050000;
        public static final int browser_actions_context_menu_min_padding = 0x7f050001;
        public static final int compat_button_inset_horizontal_material = 0x7f050002;
        public static final int compat_button_inset_vertical_material = 0x7f050003;
        public static final int compat_button_padding_horizontal_material = 0x7f050004;
        public static final int compat_button_padding_vertical_material = 0x7f050005;
        public static final int compat_control_corner_material = 0x7f050006;
        public static final int notification_action_icon_size = 0x7f050009;
        public static final int notification_action_text_size = 0x7f05000a;
        public static final int notification_big_circle_margin = 0x7f05000b;
        public static final int notification_content_margin_start = 0x7f05000c;
        public static final int notification_large_icon_height = 0x7f05000d;
        public static final int notification_large_icon_width = 0x7f05000e;
        public static final int notification_main_column_padding_top = 0x7f05000f;
        public static final int notification_media_narrow_margin = 0x7f050010;
        public static final int notification_right_icon_size = 0x7f050011;
        public static final int notification_right_side_padding_top = 0x7f050012;
        public static final int notification_small_icon_background_padding = 0x7f050013;
        public static final int notification_small_icon_size_as_large = 0x7f050014;
        public static final int notification_subtext_size = 0x7f050015;
        public static final int notification_top_pad = 0x7f050016;
        public static final int notification_top_pad_large_text = 0x7f050017;
    }

    public static final class drawable {
        public static final int ic_launcher_background = 0x7f06001b;
        public static final int launch_background = 0x7f06001c;
        public static final int notification_action_background = 0x7f06001d;
        public static final int notification_bg = 0x7f06001e;
        public static final int notification_bg_low = 0x7f06001f;
        public static final int notification_icon_background = 0x7f060024;
        public static final int notification_oversize_large_icon_bg = 0x7f060025;
        public static final int notification_template_icon_bg = 0x7f060026;
        public static final int notification_template_icon_low_bg = 0x7f060027;
        public static final int notification_tile_bg = 0x7f060028;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f070000;
        public static final int accessibility_custom_action_0 = 0x7f070001;
        public static final int accessibility_custom_action_1 = 0x7f070002;
        public static final int accessibility_custom_action_10 = 0x7f070003;
        public static final int accessibility_custom_action_11 = 0x7f070004;
        public static final int accessibility_custom_action_12 = 0x7f070005;
        public static final int accessibility_custom_action_13 = 0x7f070006;
        public static final int accessibility_custom_action_14 = 0x7f070007;
        public static final int accessibility_custom_action_15 = 0x7f070008;
        public static final int accessibility_custom_action_16 = 0x7f070009;
        public static final int accessibility_custom_action_17 = 0x7f07000a;
        public static final int accessibility_custom_action_18 = 0x7f07000b;
        public static final int accessibility_custom_action_19 = 0x7f07000c;
        public static final int accessibility_custom_action_2 = 0x7f07000d;
        public static final int accessibility_custom_action_20 = 0x7f07000e;
        public static final int accessibility_custom_action_21 = 0x7f07000f;
        public static final int accessibility_custom_action_22 = 0x7f070010;
        public static final int accessibility_custom_action_23 = 0x7f070011;
        public static final int accessibility_custom_action_24 = 0x7f070012;
        public static final int accessibility_custom_action_25 = 0x7f070013;
        public static final int accessibility_custom_action_26 = 0x7f070014;
        public static final int accessibility_custom_action_27 = 0x7f070015;
        public static final int accessibility_custom_action_28 = 0x7f070016;
        public static final int accessibility_custom_action_29 = 0x7f070017;
        public static final int accessibility_custom_action_3 = 0x7f070018;
        public static final int accessibility_custom_action_30 = 0x7f070019;
        public static final int accessibility_custom_action_31 = 0x7f07001a;
        public static final int accessibility_custom_action_4 = 0x7f07001b;
        public static final int accessibility_custom_action_5 = 0x7f07001c;
        public static final int accessibility_custom_action_6 = 0x7f07001d;
        public static final int accessibility_custom_action_7 = 0x7f07001e;
        public static final int accessibility_custom_action_8 = 0x7f07001f;
        public static final int accessibility_custom_action_9 = 0x7f070020;
        public static final int action_container = 0x7f070021;
        public static final int action_divider = 0x7f070022;
        public static final int action_image = 0x7f070023;
        public static final int action_text = 0x7f070024;
        public static final int actions = 0x7f070025;
        public static final int adjacent = 0x7f070026;
        public static final int adjust_height = 0x7f070027;
        public static final int adjust_width = 0x7f070028;
        public static final int always = 0x7f070029;
        public static final int alwaysAllow = 0x7f07002a;
        public static final int alwaysDisallow = 0x7f07002b;
        public static final int androidx_window_activity_scope = 0x7f07002c;
        public static final int async = 0x7f07002d;
        public static final int auto = 0x7f07002e;
        public static final int blocking = 0x7f07002f;
        public static final int bottomToTop = 0x7f070030;
        public static final int browser_actions_header_text = 0x7f070031;
        public static final int browser_actions_menu_item_icon = 0x7f070032;
        public static final int browser_actions_menu_item_text = 0x7f070033;
        public static final int browser_actions_menu_items = 0x7f070034;
        public static final int browser_actions_menu_view = 0x7f070035;
        public static final int chronometer = 0x7f070036;
        public static final int dark = 0x7f070037;
        public static final int dialog_button = 0x7f070038;
        public static final int edit_text_id = 0x7f070039;
        public static final int forever = 0x7f07003a;
        public static final int fragment_container_view_tag = 0x7f07003b;
        public static final int hide_ime_id = 0x7f07003c;
        public static final int icon = 0x7f07003d;
        public static final int icon_group = 0x7f07003e;
        public static final int icon_only = 0x7f07003f;
        public static final int info = 0x7f070040;
        public static final int italic = 0x7f070041;
        public static final int light = 0x7f070042;
        public static final int line1 = 0x7f070043;
        public static final int line3 = 0x7f070044;
        public static final int locale = 0x7f070045;
        public static final int ltr = 0x7f070046;
        public static final int never = 0x7f070047;
        public static final int none = 0x7f070048;
        public static final int normal = 0x7f070049;
        public static final int notification_background = 0x7f07004a;
        public static final int notification_main_column = 0x7f07004b;
        public static final int notification_main_column_container = 0x7f07004c;
        public static final int report_drawn = 0x7f07004d;
        public static final int right_icon = 0x7f07004e;
        public static final int right_side = 0x7f07004f;
        public static final int rtl = 0x7f070050;
        public static final int special_effects_controller_view_tag = 0x7f070051;
        public static final int standard = 0x7f070052;
        public static final int tag_accessibility_actions = 0x7f070053;
        public static final int tag_accessibility_clickable_spans = 0x7f070054;
        public static final int tag_accessibility_heading = 0x7f070055;
        public static final int tag_accessibility_pane_title = 0x7f070056;
        public static final int tag_on_apply_window_listener = 0x7f070057;
        public static final int tag_on_receive_content_listener = 0x7f070058;
        public static final int tag_on_receive_content_mime_types = 0x7f070059;
        public static final int tag_screen_reader_focusable = 0x7f07005a;
        public static final int tag_state_description = 0x7f07005b;
        public static final int tag_transition_group = 0x7f07005c;
        public static final int tag_unhandled_key_event_manager = 0x7f07005d;
        public static final int tag_unhandled_key_listeners = 0x7f07005e;
        public static final int tag_window_insets_animation_callback = 0x7f07005f;
        public static final int text = 0x7f070060;
        public static final int text2 = 0x7f070061;
        public static final int time = 0x7f070062;
        public static final int title = 0x7f070063;
        public static final int topToBottom = 0x7f070064;
        public static final int view_tree_lifecycle_owner = 0x7f070065;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f070066;
        public static final int view_tree_saved_state_registry_owner = 0x7f070067;
        public static final int view_tree_view_model_store_owner = 0x7f070068;
        public static final int visible_removing_fragment_view_tag = 0x7f070069;
        public static final int wide = 0x7f07006a;
    }

    public static final class integer {
        public static final int google_play_services_version = 0x7f080000;
        public static final int status_bar_notification_info_maxnum = 0x7f080001;
    }

    public static final class layout {
        public static final int notification_action = 0x7f090005;
        public static final int notification_action_tombstone = 0x7f090006;
        public static final int notification_template_custom_big = 0x7f090007;
        public static final int notification_template_icon_group = 0x7f090008;
        public static final int notification_template_part_chronometer = 0x7f090009;
        public static final int notification_template_part_time = 0x7f09000a;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f0a0000;
        public static final int ic_launcher_foreground = 0x7f0a0001;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f0b0000;
        public static final int call_notification_answer_action = 0x7f0b0001;
        public static final int call_notification_answer_video_action = 0x7f0b0002;
        public static final int call_notification_decline_action = 0x7f0b0003;
        public static final int call_notification_hang_up_action = 0x7f0b0004;
        public static final int call_notification_incoming_text = 0x7f0b0005;
        public static final int call_notification_ongoing_text = 0x7f0b0006;
        public static final int call_notification_screening_text = 0x7f0b0007;
        public static final int common_google_play_services_enable_button = 0x7f0b0008;
        public static final int common_google_play_services_enable_text = 0x7f0b0009;
        public static final int common_google_play_services_enable_title = 0x7f0b000a;
        public static final int common_google_play_services_install_button = 0x7f0b000b;
        public static final int common_google_play_services_install_text = 0x7f0b000c;
        public static final int common_google_play_services_install_title = 0x7f0b000d;
        public static final int common_google_play_services_notification_channel_name = 0x7f0b000e;
        public static final int common_google_play_services_notification_ticker = 0x7f0b000f;
        public static final int common_google_play_services_unknown_issue = 0x7f0b0010;
        public static final int common_google_play_services_unsupported_text = 0x7f0b0011;
        public static final int common_google_play_services_update_button = 0x7f0b0012;
        public static final int common_google_play_services_update_text = 0x7f0b0013;
        public static final int common_google_play_services_update_title = 0x7f0b0014;
        public static final int common_google_play_services_updating_text = 0x7f0b0015;
        public static final int common_google_play_services_wear_update_text = 0x7f0b0016;
        public static final int common_open_on_phone = 0x7f0b0017;
        public static final int copy_toast_msg = 0x7f0b001a;
        public static final int status_bar_notification_info_overflow = 0x7f0b001e;
    }

    public static final class style {
        public static final int LaunchTheme = 0x7f0c0000;
        public static final int NormalTheme = 0x7f0c0001;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0c0003;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0c0005;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0c0007;
        public static final int Widget_Compat_NotificationActionText = 0x7f0c0008;
    }

    public static final class xml {
        public static final int splits0 = 0x7f0e0000;
    }
}
