package com.yandex.div2;

import com.yandex.plus.home.feature.webviews.internal.container.ModalContentViewContainer;
import defpackage.i8l;
import defpackage.i9l;
import defpackage.j73;
import defpackage.j9l;
import defpackage.kvo;
import defpackage.lql;
import defpackage.ngd0;
import defpackage.nzk;
import defpackage.pdk;
import defpackage.qkj;

/* loaded from: classes.dex */
public abstract class w2 {
    public static final qkj A;
    public static final i8l B;
    public static final i8l C;
    public static final i8l D;
    public static final i8l E;
    public static final i8l F;
    public static final i8l G;
    public static final i8l H;
    public static final i8l I;
    public static final i8l J;
    public static final pdk a;
    public static final kvo b;
    public static final kvo c;
    public static final kvo d;
    public static final kvo e;
    public static final j9l f;
    public static final kvo g;
    public static final kvo h;
    public static final kvo i;
    public static final kvo j;
    public static final kvo k;
    public static final kvo l;
    public static final kvo m;
    public static final kvo n;
    public static final kvo o;
    public static final kvo p;
    public static final i9l q;
    public static final qkj r;
    public static final qkj s;
    public static final qkj t;
    public static final qkj u;
    public static final qkj v;
    public static final qkj w;
    public static final qkj x;
    public static final qkj y;
    public static final qkj z;

    static {
        kvo m2 = ngd0.m(100L);
        kvo m3 = ngd0.m(Double.valueOf(0.6d));
        kvo m4 = ngd0.m(DivAnimation$Name.FADE);
        Double valueOf = Double.valueOf(1.0d);
        a = new pdk(m2, m3, m4, ngd0.m(valueOf));
        b = ngd0.m(valueOf);
        c = ngd0.m(Boolean.TRUE);
        d = ngd0.m(12L);
        DivSizeUnit divSizeUnit = DivSizeUnit.SP;
        e = ngd0.m(divSizeUnit);
        f = new j9l(new lql(null, null, null));
        g = ngd0.m(Double.valueOf(0.0d));
        Boolean bool = Boolean.FALSE;
        h = ngd0.m(bool);
        DivLineStyle divLineStyle = DivLineStyle.NONE;
        i = ngd0.m(divLineStyle);
        DivAlignmentHorizontal divAlignmentHorizontal = DivAlignmentHorizontal.START;
        j = ngd0.m(divAlignmentHorizontal);
        DivAlignmentVertical divAlignmentVertical = DivAlignmentVertical.TOP;
        k = ngd0.m(divAlignmentVertical);
        l = ngd0.m(Integer.valueOf(ModalContentViewContainer.BASE_SHADOW_COLOR));
        m = ngd0.m(bool);
        DivText$Truncate divText$Truncate = DivText$Truncate.END;
        n = ngd0.m(divText$Truncate);
        o = ngd0.m(divLineStyle);
        DivVisibility divVisibility = DivVisibility.VISIBLE;
        p = ngd0.m(divVisibility);
        q = new i9l(new nzk(null, null, null));
        r = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_ALIGNMENT_HORIZONTAL$1.w, j73.C(DivAlignmentHorizontal.values()));
        s = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_ALIGNMENT_VERTICAL$1.w, j73.C(DivAlignmentVertical.values()));
        t = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_FONT_SIZE_UNIT$1.w, divSizeUnit);
        u = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_FONT_WEIGHT$1.w, j73.C(DivFontWeight.values()));
        v = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_STRIKE$1.w, divLineStyle);
        w = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_TEXT_ALIGNMENT_HORIZONTAL$1.w, divAlignmentHorizontal);
        x = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_TEXT_ALIGNMENT_VERTICAL$1.w, divAlignmentVertical);
        y = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_TRUNCATE$1.w, divText$Truncate);
        z = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_UNDERLINE$1.w, divLineStyle);
        A = new qkj(DivTextJsonParser$Companion$TYPE_HELPER_VISIBILITY$1.w, divVisibility);
        B = new i8l(15);
        C = new i8l(16);
        D = new i8l(17);
        E = new i8l(18);
        F = new i8l(19);
        G = new i8l(20);
        H = new i8l(21);
        I = new i8l(22);
        J = new i8l(23);
    }
}
