package com.squareup.protos.franklin.common;

import androidx.room.TransactorKt;
import com.plaid.internal.EnumC0170g;
import com.squareup.protos.cash.activity.api.v1.ActivityScope;
import com.squareup.protos.cash.activity.api.v1.ActivityToken;
import com.squareup.protos.cash.commerce.CommerceOrderRenderData;
import com.squareup.protos.cash.local.activity.CashAppLocalOrderRenderData;
import com.squareup.protos.cash.local.activity.CashAppLocalPaymentRenderData;
import com.squareup.protos.cash.localization.LocalizableString;
import com.squareup.protos.cash.pay.CashAppPayOrderRenderData;
import com.squareup.protos.cash.pay.CashAppPayPaymentRenderData;
import com.squareup.protos.cash.pay.CashAppPayPaymentScheduleRenderData;
import com.squareup.protos.cash.pay.CashAppPayPayoutRenderData;
import com.squareup.protos.cash.pay.CashAppPayRefundRenderData;
import com.squareup.protos.cash.pay.CashAppPayRenderData;
import com.squareup.protos.common.Money;
import com.squareup.protos.common.countries.Country;
import com.squareup.protos.franklin.api.CashInstrumentType;
import com.squareup.protos.franklin.api.DepositPreference;
import com.squareup.protos.franklin.api.Instrument;
import com.squareup.protos.franklin.api.Payment$CancellationReason;
import com.squareup.protos.franklin.api.Payment$CancellationReason$Companion$ADAPTER$1;
import com.squareup.protos.franklin.api.Payment$State;
import com.squareup.protos.franklin.api.RatePlan;
import com.squareup.protos.franklin.api.Role;
import com.squareup.protos.franklin.common.PaymentRenderData;
import com.squareup.protos.franklin.common.scenarios.ScenarioPlan;
import com.squareup.protos.franklin.data.ExplicitConfirmationReason;
import com.squareup.protos.franklin.ui.PaymentHistoryButton;
import com.squareup.protos.franklin.ui.RequestRefundReason;
import com.squareup.protos.franklin.ui.ScenarioPlanMap;
import com.squareup.protos.repeatedly.common.RecurringSchedule;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import java.util.ArrayList;
import java.util.List;
import okio.ByteString;

/* loaded from: classes8.dex */
public final class PaymentRenderData$Companion$ADAPTER$1 extends ProtoAdapter {
    /*  JADX ERROR: Type inference failed
        jadx.core.utils.exceptions.JadxOverflowException: Type update terminated with stack overflow, arg: (r160v117 java.lang.Object), method size: 9370
        	at jadx.core.utils.ErrorsCounter.addError(ErrorsCounter.java:59)
        	at jadx.core.utils.ErrorsCounter.error(ErrorsCounter.java:31)
        	at jadx.core.dex.attributes.nodes.NotificationAttrNode.addError(NotificationAttrNode.java:19)
        	at jadx.core.dex.visitors.typeinference.TypeInferenceVisitor.visit(TypeInferenceVisitor.java:77)
        */
    @Override // com.squareup.wire.ProtoAdapter
    public final java.lang.Object decode(com.squareup.wire.ProtoReader r163) {
        /*
            Method dump skipped, instructions count: 9370
            To view this dump add '--comments-level debug' option
        */
        throw new UnsupportedOperationException("Method not decompiled: com.squareup.protos.franklin.common.PaymentRenderData$Companion$ADAPTER$1.decode(com.squareup.wire.ProtoReader):java.lang.Object");
    }

    @Override // com.squareup.wire.ProtoAdapter
    public final void encode(ReverseProtoWriter reverseProtoWriter, Object obj) {
        PaymentRenderData paymentRenderData = (PaymentRenderData) obj;
        reverseProtoWriter.getClass();
        paymentRenderData.getClass();
        reverseProtoWriter.writeBytes(paymentRenderData.unknownFields());
        ProtoAdapter protoAdapter = ProtoAdapter.BOOL;
        protoAdapter.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SUPPORT_VALUE, paymentRenderData.is_send_to_cashtag_oct);
        CashLiteCardTransactionRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_WARNING_EXIT_SPOT_VALUE, paymentRenderData.cash_lite_card_transaction_render_data);
        ProtoAdapter protoAdapter2 = ProtoAdapter.INT64;
        protoAdapter2.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SECURE_TOKENIZATION_VALUE, paymentRenderData.counterparty_viewed_at);
        CashAppTagRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_INCOME_VALUE, paymentRenderData.cash_app_tag_render_data);
        RestrictedCashInTransferRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_WALLET_VALUE, paymentRenderData.restricted_cash_in_transfer_render_data);
        LiftedRestrictionTransferRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_FALLBACK_INSTITUTION_VALUE, paymentRenderData.lifted_restriction_transfer_render_data);
        RecurringTransferRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_MANAGE_CONNECTIONS_VALUE, paymentRenderData.recurring_transfer_render_data);
        StablecoinRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_UPLOAD_VALUE, paymentRenderData.stablecoin_render_data);
        CustomerAdjustmentRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 153, paymentRenderData.customer_adjustment_render_data);
        P2pPoolContributionRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 151, paymentRenderData.p2p_pool_contribution_render_data);
        ProtoAdapter protoAdapter3 = Money.ADAPTER;
        protoAdapter3.encodeWithTag(reverseProtoWriter, 150, paymentRenderData.current_balance);
        protoAdapter3.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SDK_EMPTY_SVG_VALUE, paymentRenderData.impact);
        ActivityRowRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ICON_CHECKMARK_GREEN_SQUARE_CASH_VALUE, paymentRenderData.activity_row_render_data);
        P2pPoolMemberRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 147, paymentRenderData.p2p_pool_member_render_data);
        P2pPoolRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_PLAID_OVERLAY_ACCOUNT_VALUE, paymentRenderData.p2p_pool_render_data);
        BitcoinLightningRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 144, paymentRenderData.bitcoin_lightning_render_data);
        AchRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ICON_ALERT_ERROR_BLACK_VALUE, paymentRenderData.ach_render_data);
        CashAppLocalOrderRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_CONNECTIVITY_WARNING_ILLUSTRATION_VALUE, paymentRenderData.cash_app_local_order_render_data);
        CashAppLocalPaymentRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_CONNECTIVITY_DOWN_ILLUSTRATION_VALUE, paymentRenderData.cash_app_local_payment_render_data);
        ProtoAdapter protoAdapter4 = ProtoAdapter.STRING;
        protoAdapter4.encodeWithTag(reverseProtoWriter, 140, paymentRenderData.raw_merchant_descriptor);
        LendingCardRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SHARE_YOUR_DATA_VALUE, paymentRenderData.lending_card_render_data);
        protoAdapter.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_INSTITUTION_CIRCLE_VALUE, paymentRenderData.is_deposit_reversal);
        BitcoinOnchainRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 136, paymentRenderData.bitcoin_onchain_render_data);
        protoAdapter.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_RAISE_INSTITUTION_VALUE, paymentRenderData.is_recurring);
        protoAdapter.encodeWithTag(reverseProtoWriter, 131, paymentRenderData.has_error_context);
        protoAdapter.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_CONSUMER_VALUE, paymentRenderData.is_background);
        BillPayRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_FORM_VALUE, paymentRenderData.bill_pay_render_data);
        AutoAllocationRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, paymentRenderData.auto_allocation_render_data);
        PersonalizationRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 125, paymentRenderData.personalization_render_data);
        TTPPaymentRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SIGNATURE_VALUE, paymentRenderData.ttp_payment_render_data);
        FeatureInvitationRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_CALENDAR_VALUE, paymentRenderData.feature_invitation_render_data);
        PaymentPlanEligibilityRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, paymentRenderData.payment_plan_eligibility_render_data);
        OverdraftRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 121, paymentRenderData.overdraft_render_data);
        LocalizableString.ADAPTER.encodeWithTag(reverseProtoWriter, 120, paymentRenderData.localizable_note);
        CheckDepositRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 119, paymentRenderData.check_deposit_render_data);
        FiatP2pRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 116, paymentRenderData.fiat_p2p_render_data);
        InvestCorrectionRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 115, paymentRenderData.invest_correction_render_data);
        CouponActivityRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 114, paymentRenderData.coupon_activity_render_data);
        BalanceImpact.ADAPTER.asRepeated().encodeWithTag(reverseProtoWriter, 113, paymentRenderData.balance_impacts);
        TransactionAuthRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 112, paymentRenderData.transaction_auth_render_data);
        ActivityScope.ADAPTER.encodeWithTag(reverseProtoWriter, 110, paymentRenderData.activity_scope);
        ActivityToken.ADAPTER.encodeWithTag(reverseProtoWriter, 109, paymentRenderData.activity_token);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 108, paymentRenderData.caller_customer_token);
        GroupActivityRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 111, paymentRenderData.group_activity_render_data);
        RemittancePaymentRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 105, paymentRenderData.remittance_payment_render_data);
        SavingsInterestPaymentRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 128, paymentRenderData.savings_interest_payment_render_data);
        SavingsTransferRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 104, paymentRenderData.savings_transfer_render_data);
        GenericNonPaymentRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 103, paymentRenderData.generic_non_payment_render_data);
        ViewContextRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 102, paymentRenderData.view_context_render_data);
        CashAppPayRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 107, paymentRenderData.cash_app_pay_render_data);
        CommerceOrderRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_PLAID_OVERLAY_PERSON_VALUE, paymentRenderData.commerce_order_render_data);
        CashAppPayPayoutRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_RAISE_INSTITUTION_CENTERED_VALUE, paymentRenderData.cash_app_pay_payout_render_data);
        CashAppPayPaymentScheduleRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SPOT_PX_FEATURE_01_VALUE, paymentRenderData.cash_app_pay_payment_schedule_render_data);
        CashAppPayRefundRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_LOGS_VALUE, paymentRenderData.cash_app_pay_refund_render_data);
        CashAppPayPaymentRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_FAULTY_DATA_VALUE, paymentRenderData.cash_app_pay_payment_render_data);
        CashAppPayOrderRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_IN_CONTROL_VALUE, paymentRenderData.cash_app_pay_order_render_data);
        AfterPayRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 101, paymentRenderData.afterpay_render_data);
        InvestingAutomationExecutionRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 100, paymentRenderData.investing_automation_execution_render_data);
        InvestingAutomationTriggerRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 99, paymentRenderData.investing_automation_trigger_render_data);
        DisputedTransactionRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 98, paymentRenderData.disputed_transaction_render_data);
        TimelineRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 97, paymentRenderData.timeline_render_data);
        NewDeviceLoginRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 96, paymentRenderData.new_device_login_render_data);
        GiftCardRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 95, paymentRenderData.gift_card_render_data);
        InstantPayRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 94, paymentRenderData.instant_pay_render_data);
        SponsoredAccountRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 93, paymentRenderData.sponsored_account_render_data);
        PaperCashDepositRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 92, paymentRenderData.paper_cash_deposit_render_data);
        CryptoOrderRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 91, paymentRenderData.crypto_order_render_data);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 90, paymentRenderData.outstanding_until);
        TransactionAmountHistory.ADAPTER.encodeWithTag(reverseProtoWriter, 89, paymentRenderData.transaction_amount_history);
        InvestPaymentRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 88, paymentRenderData.invest_payment_render_data);
        LoyaltyActivityRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 87, paymentRenderData.loyalty_activity_render_data);
        PaymentRenderData.CrossCurrencyRewardInfo.ADAPTER.encodeWithTag(reverseProtoWriter, 86, paymentRenderData.cross_currency_reward_info);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 84, paymentRenderData.btc_limit);
        ExplicitConfirmationReason.ADAPTER.encodeWithTag(reverseProtoWriter, 83, paymentRenderData.explicit_confirmation_reason);
        PendingReferralRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 81, paymentRenderData.pending_referral_render_data);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 80, paymentRenderData.check_reference_token);
        ProtoAdapter.INT32.asRepeated().encodeWithTag(reverseProtoWriter, 78, paymentRenderData.days_of_period);
        RecurringSchedule.Frequency.ADAPTER.encodeWithTag(reverseProtoWriter, 77, paymentRenderData.frequency);
        RequestRefundReason.ADAPTER.encodeWithTag(reverseProtoWriter, 75, paymentRenderData.request_refund_reason);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 79, paymentRenderData.request_refund_available_until);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 74, paymentRenderData.refund_request_declined_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 73, paymentRenderData.refund_requested_at);
        protoAdapter.encodeWithTag(reverseProtoWriter, 72, paymentRenderData.is_app_purchase);
        LendingRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 71, paymentRenderData.lending_render_data);
        Country.ADAPTER.encodeWithTag(reverseProtoWriter, 70, paymentRenderData.sender_country);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 67, paymentRenderData.movement_exchange_rate);
        ReimbursedAmounts.ADAPTER.encodeWithTag(reverseProtoWriter, 65, paymentRenderData.reimbursed_amounts);
        protoAdapter.encodeWithTag(reverseProtoWriter, 64, paymentRenderData.can_unlock_free_atm_status);
        protoAdapter.encodeWithTag(reverseProtoWriter, 62, paymentRenderData.is_bitcoin_transaction);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 61, paymentRenderData.crypto_transfer_status);
        protoAdapter.encodeWithTag(reverseProtoWriter, 60, paymentRenderData.will_refund_to_balance);
        FeeAmounts.ADAPTER.encodeWithTag(reverseProtoWriter, 59, paymentRenderData.fee_amounts);
        protoAdapter.encodeWithTag(reverseProtoWriter, 57, paymentRenderData.idv_in_progress);
        protoAdapter.encodeWithTag(reverseProtoWriter, 56, paymentRenderData.verification_required);
        ReactionRenderData.ADAPTER.encodeWithTag(reverseProtoWriter, 55, paymentRenderData.reaction_data);
        protoAdapter.encodeWithTag(reverseProtoWriter, 54, paymentRenderData.refunded_to_balance);
        protoAdapter.encodeWithTag(reverseProtoWriter, 53, paymentRenderData.is_scheduled_reload);
        protoAdapter.encodeWithTag(reverseProtoWriter, 52, paymentRenderData.in_cash_boost_experiment);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 51, paymentRenderData.supports_reporting_boost_until);
        PaymentHistoryButton.ButtonAction.ADAPTER.asRepeated().encodeWithTag(reverseProtoWriter, 48, paymentRenderData.hidden_receipt_buttons);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 45, paymentRenderData.target_wallet_address);
        Instrument.ADAPTER.encodeWithTag(reverseProtoWriter, 41, paymentRenderData.instrument);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 43, paymentRenderData.supports_reporting_missing_reward_until);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 36, paymentRenderData.transaction_reason_code);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 32, paymentRenderData.deposit_instantly_valid_until);
        DepositPreference.ADAPTER.encodeWithTag(reverseProtoWriter, 29, paymentRenderData.deposit_preference);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 63, paymentRenderData.scheduled_for);
        protoAdapter.encodeWithTag(reverseProtoWriter, 82, paymentRenderData.is_pwc_payment);
        protoAdapter.encodeWithTag(reverseProtoWriter, 46, paymentRenderData.is_scheduled_payment);
        protoAdapter.encodeWithTag(reverseProtoWriter, 26, paymentRenderData.is_banking_transaction);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 118, paymentRenderData.estimated_withdrawal_date);
        protoAdapter.encodeWithTag(reverseProtoWriter, 106, paymentRenderData.is_prefunded_transfer);
        protoAdapter.encodeWithTag(reverseProtoWriter, 25, paymentRenderData.is_transfer);
        ScenarioPlanMap.ADAPTER.encodeWithTag(reverseProtoWriter, 33, paymentRenderData.scenario_plan_map);
        ScenarioPlan.ADAPTER.encodeWithTag(reverseProtoWriter, 24, paymentRenderData.scenario_plan);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 37, paymentRenderData.display_date);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 20, paymentRenderData.failed_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 85, paymentRenderData.refund_request_expires_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 22, paymentRenderData.refund_deposited_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 18, paymentRenderData.refunded_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 17, paymentRenderData.deposited_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 16, paymentRenderData.paid_out_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 44, paymentRenderData.passed_customer_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 35, paymentRenderData.reached_customer_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 15, paymentRenderData.captured_at);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 14, paymentRenderData.created_at);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 21, paymentRenderData.transaction_id);
        CashInstrumentType.ADAPTER.encodeWithTag(reverseProtoWriter, 27, paymentRenderData.instrument_type);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 13, paymentRenderData.display_instrument);
        protoAdapter.encodeWithTag(reverseProtoWriter, 30, paymentRenderData.sent_via_imessage);
        protoAdapter.encodeWithTag(reverseProtoWriter, 23, paymentRenderData.sent_via_watch);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 12, paymentRenderData.note);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 11, paymentRenderData.client_display_name);
        Payment$CancellationReason$Companion$ADAPTER$1 payment$CancellationReason$Companion$ADAPTER$1 = Payment$CancellationReason.ADAPTER;
        payment$CancellationReason$Companion$ADAPTER$1.encodeWithTag(reverseProtoWriter, 10, paymentRenderData.refund_cancellation_reason);
        payment$CancellationReason$Companion$ADAPTER$1.encodeWithTag(reverseProtoWriter, 9, paymentRenderData.cancellation_reason);
        Payment$State.ADAPTER.encodeWithTag(reverseProtoWriter, 8, paymentRenderData.state);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 50, paymentRenderData.boost_basis_points);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 127, paymentRenderData.settled_amount);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 49, paymentRenderData.boost_amount);
        protoAdapter2.encodeWithTag(reverseProtoWriter, 39, paymentRenderData.reward_basis_points);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 38, paymentRenderData.reward_amount);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 28, paymentRenderData.refund_amount);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 42, paymentRenderData.fee_amount);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 69, paymentRenderData.recipient_payment_amount_in_default_currency);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 68, paymentRenderData.sender_payment_amount_in_default_currency);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 7, paymentRenderData.push_amount);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 6, paymentRenderData.pull_amount);
        protoAdapter3.encodeWithTag(reverseProtoWriter, 5, paymentRenderData.amount);
        RatePlan.ADAPTER.encodeWithTag(reverseProtoWriter, 4, paymentRenderData.rate_plan);
        Role.ADAPTER.encodeWithTag(reverseProtoWriter, 3, paymentRenderData.role);
        Orientation.ADAPTER.encodeWithTag(reverseProtoWriter, 2, paymentRenderData.orientation);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 117, paymentRenderData.receipt_token);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 34, paymentRenderData.auth_token);
        protoAdapter4.encodeWithTag(reverseProtoWriter, 1, paymentRenderData.token);
    }

    @Override // com.squareup.wire.ProtoAdapter
    public final int encodedSize(Object obj) {
        PaymentRenderData paymentRenderData = (PaymentRenderData) obj;
        paymentRenderData.getClass();
        int size$okio = paymentRenderData.unknownFields().getSize$okio();
        ProtoAdapter protoAdapter = ProtoAdapter.STRING;
        int encodedSizeWithTag = RatePlan.ADAPTER.encodedSizeWithTag(4, paymentRenderData.rate_plan) + Role.ADAPTER.encodedSizeWithTag(3, paymentRenderData.role) + Orientation.ADAPTER.encodedSizeWithTag(2, paymentRenderData.orientation) + protoAdapter.encodedSizeWithTag(117, paymentRenderData.receipt_token) + protoAdapter.encodedSizeWithTag(34, paymentRenderData.auth_token) + protoAdapter.encodedSizeWithTag(1, paymentRenderData.token) + size$okio;
        ProtoAdapter protoAdapter2 = Money.ADAPTER;
        int encodedSizeWithTag2 = protoAdapter2.encodedSizeWithTag(38, paymentRenderData.reward_amount) + protoAdapter2.encodedSizeWithTag(28, paymentRenderData.refund_amount) + protoAdapter2.encodedSizeWithTag(42, paymentRenderData.fee_amount) + protoAdapter2.encodedSizeWithTag(69, paymentRenderData.recipient_payment_amount_in_default_currency) + protoAdapter2.encodedSizeWithTag(68, paymentRenderData.sender_payment_amount_in_default_currency) + protoAdapter2.encodedSizeWithTag(7, paymentRenderData.push_amount) + protoAdapter2.encodedSizeWithTag(6, paymentRenderData.pull_amount) + protoAdapter2.encodedSizeWithTag(5, paymentRenderData.amount) + encodedSizeWithTag;
        ProtoAdapter protoAdapter3 = ProtoAdapter.INT64;
        int encodedSizeWithTag3 = Payment$State.ADAPTER.encodedSizeWithTag(8, paymentRenderData.state) + protoAdapter3.encodedSizeWithTag(50, paymentRenderData.boost_basis_points) + protoAdapter2.encodedSizeWithTag(127, paymentRenderData.settled_amount) + protoAdapter2.encodedSizeWithTag(49, paymentRenderData.boost_amount) + protoAdapter3.encodedSizeWithTag(39, paymentRenderData.reward_basis_points) + encodedSizeWithTag2;
        Payment$CancellationReason$Companion$ADAPTER$1 payment$CancellationReason$Companion$ADAPTER$1 = Payment$CancellationReason.ADAPTER;
        int encodedSizeWithTag4 = protoAdapter.encodedSizeWithTag(12, paymentRenderData.note) + protoAdapter.encodedSizeWithTag(11, paymentRenderData.client_display_name) + payment$CancellationReason$Companion$ADAPTER$1.encodedSizeWithTag(10, paymentRenderData.refund_cancellation_reason) + payment$CancellationReason$Companion$ADAPTER$1.encodedSizeWithTag(9, paymentRenderData.cancellation_reason) + encodedSizeWithTag3;
        ProtoAdapter protoAdapter4 = ProtoAdapter.BOOL;
        return protoAdapter4.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_SUPPORT_VALUE, paymentRenderData.is_send_to_cashtag_oct) + CashLiteCardTransactionRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_WARNING_EXIT_SPOT_VALUE, paymentRenderData.cash_lite_card_transaction_render_data) + protoAdapter3.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_SECURE_TOKENIZATION_VALUE, paymentRenderData.counterparty_viewed_at) + CashAppTagRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_INCOME_VALUE, paymentRenderData.cash_app_tag_render_data) + RestrictedCashInTransferRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_WALLET_VALUE, paymentRenderData.restricted_cash_in_transfer_render_data) + LiftedRestrictionTransferRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_FALLBACK_INSTITUTION_VALUE, paymentRenderData.lifted_restriction_transfer_render_data) + RecurringTransferRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_MANAGE_CONNECTIONS_VALUE, paymentRenderData.recurring_transfer_render_data) + StablecoinRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_UPLOAD_VALUE, paymentRenderData.stablecoin_render_data) + CustomerAdjustmentRenderData.ADAPTER.encodedSizeWithTag(153, paymentRenderData.customer_adjustment_render_data) + P2pPoolContributionRenderData.ADAPTER.encodedSizeWithTag(151, paymentRenderData.p2p_pool_contribution_render_data) + protoAdapter2.encodedSizeWithTag(150, paymentRenderData.current_balance) + protoAdapter2.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_SDK_EMPTY_SVG_VALUE, paymentRenderData.impact) + ActivityRowRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ICON_CHECKMARK_GREEN_SQUARE_CASH_VALUE, paymentRenderData.activity_row_render_data) + P2pPoolMemberRenderData.ADAPTER.encodedSizeWithTag(147, paymentRenderData.p2p_pool_member_render_data) + P2pPoolRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_PLAID_OVERLAY_ACCOUNT_VALUE, paymentRenderData.p2p_pool_render_data) + BitcoinLightningRenderData.ADAPTER.encodedSizeWithTag(144, paymentRenderData.bitcoin_lightning_render_data) + AchRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ICON_ALERT_ERROR_BLACK_VALUE, paymentRenderData.ach_render_data) + CashAppLocalOrderRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_CONNECTIVITY_WARNING_ILLUSTRATION_VALUE, paymentRenderData.cash_app_local_order_render_data) + CashAppLocalPaymentRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_CONNECTIVITY_DOWN_ILLUSTRATION_VALUE, paymentRenderData.cash_app_local_payment_render_data) + protoAdapter.encodedSizeWithTag(140, paymentRenderData.raw_merchant_descriptor) + LendingCardRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_SHARE_YOUR_DATA_VALUE, paymentRenderData.lending_card_render_data) + protoAdapter4.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_INSTITUTION_CIRCLE_VALUE, paymentRenderData.is_deposit_reversal) + BitcoinOnchainRenderData.ADAPTER.encodedSizeWithTag(136, paymentRenderData.bitcoin_onchain_render_data) + protoAdapter4.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_RAISE_INSTITUTION_VALUE, paymentRenderData.is_recurring) + protoAdapter4.encodedSizeWithTag(131, paymentRenderData.has_error_context) + protoAdapter4.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_CONSUMER_VALUE, paymentRenderData.is_background) + BillPayRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_FORM_VALUE, paymentRenderData.bill_pay_render_data) + AutoAllocationRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, paymentRenderData.auto_allocation_render_data) + PersonalizationRenderData.ADAPTER.encodedSizeWithTag(125, paymentRenderData.personalization_render_data) + TTPPaymentRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_SIGNATURE_VALUE, paymentRenderData.ttp_payment_render_data) + FeatureInvitationRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_CALENDAR_VALUE, paymentRenderData.feature_invitation_render_data) + PaymentPlanEligibilityRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, paymentRenderData.payment_plan_eligibility_render_data) + OverdraftRenderData.ADAPTER.encodedSizeWithTag(121, paymentRenderData.overdraft_render_data) + LocalizableString.ADAPTER.encodedSizeWithTag(120, paymentRenderData.localizable_note) + CheckDepositRenderData.ADAPTER.encodedSizeWithTag(119, paymentRenderData.check_deposit_render_data) + FiatP2pRenderData.ADAPTER.encodedSizeWithTag(116, paymentRenderData.fiat_p2p_render_data) + InvestCorrectionRenderData.ADAPTER.encodedSizeWithTag(115, paymentRenderData.invest_correction_render_data) + CouponActivityRenderData.ADAPTER.encodedSizeWithTag(114, paymentRenderData.coupon_activity_render_data) + BalanceImpact.ADAPTER.asRepeated().encodedSizeWithTag(113, paymentRenderData.balance_impacts) + TransactionAuthRenderData.ADAPTER.encodedSizeWithTag(112, paymentRenderData.transaction_auth_render_data) + ActivityScope.ADAPTER.encodedSizeWithTag(110, paymentRenderData.activity_scope) + ActivityToken.ADAPTER.encodedSizeWithTag(109, paymentRenderData.activity_token) + protoAdapter.encodedSizeWithTag(108, paymentRenderData.caller_customer_token) + GroupActivityRenderData.ADAPTER.encodedSizeWithTag(111, paymentRenderData.group_activity_render_data) + RemittancePaymentRenderData.ADAPTER.encodedSizeWithTag(105, paymentRenderData.remittance_payment_render_data) + SavingsInterestPaymentRenderData.ADAPTER.encodedSizeWithTag(128, paymentRenderData.savings_interest_payment_render_data) + SavingsTransferRenderData.ADAPTER.encodedSizeWithTag(104, paymentRenderData.savings_transfer_render_data) + GenericNonPaymentRenderData.ADAPTER.encodedSizeWithTag(103, paymentRenderData.generic_non_payment_render_data) + ViewContextRenderData.ADAPTER.encodedSizeWithTag(102, paymentRenderData.view_context_render_data) + CashAppPayRenderData.ADAPTER.encodedSizeWithTag(107, paymentRenderData.cash_app_pay_render_data) + CommerceOrderRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_PLAID_OVERLAY_PERSON_VALUE, paymentRenderData.commerce_order_render_data) + CashAppPayPayoutRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_RAISE_INSTITUTION_CENTERED_VALUE, paymentRenderData.cash_app_pay_payout_render_data) + CashAppPayPaymentScheduleRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_SPOT_PX_FEATURE_01_VALUE, paymentRenderData.cash_app_pay_payment_schedule_render_data) + CashAppPayRefundRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_LOGS_VALUE, paymentRenderData.cash_app_pay_refund_render_data) + CashAppPayPaymentRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_FAULTY_DATA_VALUE, paymentRenderData.cash_app_pay_payment_render_data) + CashAppPayOrderRenderData.ADAPTER.encodedSizeWithTag(EnumC0170g.SDK_ASSET_ILLUSTRATION_IN_CONTROL_VALUE, paymentRenderData.cash_app_pay_order_render_data) + AfterPayRenderData.ADAPTER.encodedSizeWithTag(101, paymentRenderData.afterpay_render_data) + InvestingAutomationExecutionRenderData.ADAPTER.encodedSizeWithTag(100, paymentRenderData.investing_automation_execution_render_data) + InvestingAutomationTriggerRenderData.ADAPTER.encodedSizeWithTag(99, paymentRenderData.investing_automation_trigger_render_data) + DisputedTransactionRenderData.ADAPTER.encodedSizeWithTag(98, paymentRenderData.disputed_transaction_render_data) + TimelineRenderData.ADAPTER.encodedSizeWithTag(97, paymentRenderData.timeline_render_data) + NewDeviceLoginRenderData.ADAPTER.encodedSizeWithTag(96, paymentRenderData.new_device_login_render_data) + GiftCardRenderData.ADAPTER.encodedSizeWithTag(95, paymentRenderData.gift_card_render_data) + InstantPayRenderData.ADAPTER.encodedSizeWithTag(94, paymentRenderData.instant_pay_render_data) + SponsoredAccountRenderData.ADAPTER.encodedSizeWithTag(93, paymentRenderData.sponsored_account_render_data) + PaperCashDepositRenderData.ADAPTER.encodedSizeWithTag(92, paymentRenderData.paper_cash_deposit_render_data) + CryptoOrderRenderData.ADAPTER.encodedSizeWithTag(91, paymentRenderData.crypto_order_render_data) + protoAdapter3.encodedSizeWithTag(90, paymentRenderData.outstanding_until) + TransactionAmountHistory.ADAPTER.encodedSizeWithTag(89, paymentRenderData.transaction_amount_history) + InvestPaymentRenderData.ADAPTER.encodedSizeWithTag(88, paymentRenderData.invest_payment_render_data) + LoyaltyActivityRenderData.ADAPTER.encodedSizeWithTag(87, paymentRenderData.loyalty_activity_render_data) + PaymentRenderData.CrossCurrencyRewardInfo.ADAPTER.encodedSizeWithTag(86, paymentRenderData.cross_currency_reward_info) + protoAdapter.encodedSizeWithTag(84, paymentRenderData.btc_limit) + ExplicitConfirmationReason.ADAPTER.encodedSizeWithTag(83, paymentRenderData.explicit_confirmation_reason) + PendingReferralRenderData.ADAPTER.encodedSizeWithTag(81, paymentRenderData.pending_referral_render_data) + protoAdapter.encodedSizeWithTag(80, paymentRenderData.check_reference_token) + ProtoAdapter.INT32.asRepeated().encodedSizeWithTag(78, paymentRenderData.days_of_period) + RecurringSchedule.Frequency.ADAPTER.encodedSizeWithTag(77, paymentRenderData.frequency) + RequestRefundReason.ADAPTER.encodedSizeWithTag(75, paymentRenderData.request_refund_reason) + protoAdapter3.encodedSizeWithTag(79, paymentRenderData.request_refund_available_until) + protoAdapter3.encodedSizeWithTag(74, paymentRenderData.refund_request_declined_at) + protoAdapter3.encodedSizeWithTag(73, paymentRenderData.refund_requested_at) + protoAdapter4.encodedSizeWithTag(72, paymentRenderData.is_app_purchase) + LendingRenderData.ADAPTER.encodedSizeWithTag(71, paymentRenderData.lending_render_data) + Country.ADAPTER.encodedSizeWithTag(70, paymentRenderData.sender_country) + protoAdapter.encodedSizeWithTag(67, paymentRenderData.movement_exchange_rate) + ReimbursedAmounts.ADAPTER.encodedSizeWithTag(65, paymentRenderData.reimbursed_amounts) + protoAdapter4.encodedSizeWithTag(64, paymentRenderData.can_unlock_free_atm_status) + protoAdapter4.encodedSizeWithTag(62, paymentRenderData.is_bitcoin_transaction) + protoAdapter.encodedSizeWithTag(61, paymentRenderData.crypto_transfer_status) + protoAdapter4.encodedSizeWithTag(60, paymentRenderData.will_refund_to_balance) + FeeAmounts.ADAPTER.encodedSizeWithTag(59, paymentRenderData.fee_amounts) + protoAdapter4.encodedSizeWithTag(57, paymentRenderData.idv_in_progress) + protoAdapter4.encodedSizeWithTag(56, paymentRenderData.verification_required) + ReactionRenderData.ADAPTER.encodedSizeWithTag(55, paymentRenderData.reaction_data) + protoAdapter4.encodedSizeWithTag(54, paymentRenderData.refunded_to_balance) + protoAdapter4.encodedSizeWithTag(53, paymentRenderData.is_scheduled_reload) + protoAdapter4.encodedSizeWithTag(52, paymentRenderData.in_cash_boost_experiment) + protoAdapter3.encodedSizeWithTag(51, paymentRenderData.supports_reporting_boost_until) + PaymentHistoryButton.ButtonAction.ADAPTER.asRepeated().encodedSizeWithTag(48, paymentRenderData.hidden_receipt_buttons) + protoAdapter.encodedSizeWithTag(45, paymentRenderData.target_wallet_address) + Instrument.ADAPTER.encodedSizeWithTag(41, paymentRenderData.instrument) + protoAdapter3.encodedSizeWithTag(43, paymentRenderData.supports_reporting_missing_reward_until) + protoAdapter.encodedSizeWithTag(36, paymentRenderData.transaction_reason_code) + protoAdapter3.encodedSizeWithTag(32, paymentRenderData.deposit_instantly_valid_until) + DepositPreference.ADAPTER.encodedSizeWithTag(29, paymentRenderData.deposit_preference) + protoAdapter3.encodedSizeWithTag(63, paymentRenderData.scheduled_for) + protoAdapter4.encodedSizeWithTag(82, paymentRenderData.is_pwc_payment) + protoAdapter4.encodedSizeWithTag(46, paymentRenderData.is_scheduled_payment) + protoAdapter4.encodedSizeWithTag(26, paymentRenderData.is_banking_transaction) + protoAdapter.encodedSizeWithTag(118, paymentRenderData.estimated_withdrawal_date) + protoAdapter4.encodedSizeWithTag(106, paymentRenderData.is_prefunded_transfer) + protoAdapter4.encodedSizeWithTag(25, paymentRenderData.is_transfer) + ScenarioPlanMap.ADAPTER.encodedSizeWithTag(33, paymentRenderData.scenario_plan_map) + ScenarioPlan.ADAPTER.encodedSizeWithTag(24, paymentRenderData.scenario_plan) + protoAdapter3.encodedSizeWithTag(37, paymentRenderData.display_date) + protoAdapter3.encodedSizeWithTag(20, paymentRenderData.failed_at) + protoAdapter3.encodedSizeWithTag(85, paymentRenderData.refund_request_expires_at) + protoAdapter3.encodedSizeWithTag(22, paymentRenderData.refund_deposited_at) + protoAdapter3.encodedSizeWithTag(18, paymentRenderData.refunded_at) + protoAdapter3.encodedSizeWithTag(17, paymentRenderData.deposited_at) + protoAdapter3.encodedSizeWithTag(16, paymentRenderData.paid_out_at) + protoAdapter3.encodedSizeWithTag(44, paymentRenderData.passed_customer_at) + protoAdapter3.encodedSizeWithTag(35, paymentRenderData.reached_customer_at) + protoAdapter3.encodedSizeWithTag(15, paymentRenderData.captured_at) + protoAdapter3.encodedSizeWithTag(14, paymentRenderData.created_at) + protoAdapter.encodedSizeWithTag(21, paymentRenderData.transaction_id) + CashInstrumentType.ADAPTER.encodedSizeWithTag(27, paymentRenderData.instrument_type) + protoAdapter.encodedSizeWithTag(13, paymentRenderData.display_instrument) + protoAdapter4.encodedSizeWithTag(30, paymentRenderData.sent_via_imessage) + protoAdapter4.encodedSizeWithTag(23, paymentRenderData.sent_via_watch) + encodedSizeWithTag4;
    }

    @Override // com.squareup.wire.ProtoAdapter
    public final Object redact(Object obj) {
        PaymentRenderData paymentRenderData = (PaymentRenderData) obj;
        paymentRenderData.getClass();
        Money money = paymentRenderData.amount;
        Money money2 = money != null ? (Money) Money.ADAPTER.redact(money) : null;
        Money money3 = paymentRenderData.pull_amount;
        Money money4 = money3 != null ? (Money) Money.ADAPTER.redact(money3) : null;
        Money money5 = paymentRenderData.push_amount;
        Money money6 = money5 != null ? (Money) Money.ADAPTER.redact(money5) : null;
        Money money7 = paymentRenderData.sender_payment_amount_in_default_currency;
        Money money8 = money7 != null ? (Money) Money.ADAPTER.redact(money7) : null;
        Money money9 = paymentRenderData.recipient_payment_amount_in_default_currency;
        Money money10 = money9 != null ? (Money) Money.ADAPTER.redact(money9) : null;
        Money money11 = paymentRenderData.fee_amount;
        Money money12 = money11 != null ? (Money) Money.ADAPTER.redact(money11) : null;
        Money money13 = paymentRenderData.refund_amount;
        Money money14 = money13 != null ? (Money) Money.ADAPTER.redact(money13) : null;
        Money money15 = paymentRenderData.reward_amount;
        Money money16 = money15 != null ? (Money) Money.ADAPTER.redact(money15) : null;
        Money money17 = paymentRenderData.boost_amount;
        Money money18 = money17 != null ? (Money) Money.ADAPTER.redact(money17) : null;
        Money money19 = paymentRenderData.settled_amount;
        Money money20 = money19 != null ? (Money) Money.ADAPTER.redact(money19) : null;
        ScenarioPlan scenarioPlan = paymentRenderData.scenario_plan;
        ScenarioPlan scenarioPlan2 = scenarioPlan != null ? (ScenarioPlan) ScenarioPlan.ADAPTER.redact(scenarioPlan) : null;
        ScenarioPlanMap scenarioPlanMap = paymentRenderData.scenario_plan_map;
        ScenarioPlanMap scenarioPlanMap2 = scenarioPlanMap != null ? (ScenarioPlanMap) ScenarioPlanMap.ADAPTER.redact(scenarioPlanMap) : null;
        Instrument instrument = paymentRenderData.instrument;
        Instrument instrument2 = instrument != null ? (Instrument) Instrument.ADAPTER.redact(instrument) : null;
        ReactionRenderData reactionRenderData = paymentRenderData.reaction_data;
        ReactionRenderData reactionRenderData2 = reactionRenderData != null ? (ReactionRenderData) ReactionRenderData.ADAPTER.redact(reactionRenderData) : null;
        FeeAmounts feeAmounts = paymentRenderData.fee_amounts;
        FeeAmounts feeAmounts2 = feeAmounts != null ? (FeeAmounts) FeeAmounts.ADAPTER.redact(feeAmounts) : null;
        ReimbursedAmounts reimbursedAmounts = paymentRenderData.reimbursed_amounts;
        ReimbursedAmounts reimbursedAmounts2 = reimbursedAmounts != null ? (ReimbursedAmounts) ReimbursedAmounts.ADAPTER.redact(reimbursedAmounts) : null;
        LendingRenderData lendingRenderData = paymentRenderData.lending_render_data;
        LendingRenderData lendingRenderData2 = lendingRenderData != null ? (LendingRenderData) LendingRenderData.ADAPTER.redact(lendingRenderData) : null;
        PendingReferralRenderData pendingReferralRenderData = paymentRenderData.pending_referral_render_data;
        PendingReferralRenderData pendingReferralRenderData2 = pendingReferralRenderData != null ? (PendingReferralRenderData) PendingReferralRenderData.ADAPTER.redact(pendingReferralRenderData) : null;
        PaymentRenderData.CrossCurrencyRewardInfo crossCurrencyRewardInfo = paymentRenderData.cross_currency_reward_info;
        PaymentRenderData.CrossCurrencyRewardInfo crossCurrencyRewardInfo2 = crossCurrencyRewardInfo != null ? (PaymentRenderData.CrossCurrencyRewardInfo) PaymentRenderData.CrossCurrencyRewardInfo.ADAPTER.redact(crossCurrencyRewardInfo) : null;
        LoyaltyActivityRenderData loyaltyActivityRenderData = paymentRenderData.loyalty_activity_render_data;
        LoyaltyActivityRenderData loyaltyActivityRenderData2 = loyaltyActivityRenderData != null ? (LoyaltyActivityRenderData) LoyaltyActivityRenderData.ADAPTER.redact(loyaltyActivityRenderData) : null;
        InvestPaymentRenderData investPaymentRenderData = paymentRenderData.invest_payment_render_data;
        InvestPaymentRenderData investPaymentRenderData2 = investPaymentRenderData != null ? (InvestPaymentRenderData) InvestPaymentRenderData.ADAPTER.redact(investPaymentRenderData) : null;
        TransactionAmountHistory transactionAmountHistory = paymentRenderData.transaction_amount_history;
        TransactionAmountHistory transactionAmountHistory2 = transactionAmountHistory != null ? (TransactionAmountHistory) TransactionAmountHistory.ADAPTER.redact(transactionAmountHistory) : null;
        CryptoOrderRenderData cryptoOrderRenderData = paymentRenderData.crypto_order_render_data;
        CryptoOrderRenderData cryptoOrderRenderData2 = cryptoOrderRenderData != null ? (CryptoOrderRenderData) CryptoOrderRenderData.ADAPTER.redact(cryptoOrderRenderData) : null;
        PaperCashDepositRenderData paperCashDepositRenderData = paymentRenderData.paper_cash_deposit_render_data;
        PaperCashDepositRenderData paperCashDepositRenderData2 = paperCashDepositRenderData != null ? (PaperCashDepositRenderData) PaperCashDepositRenderData.ADAPTER.redact(paperCashDepositRenderData) : null;
        SponsoredAccountRenderData sponsoredAccountRenderData = paymentRenderData.sponsored_account_render_data;
        SponsoredAccountRenderData sponsoredAccountRenderData2 = sponsoredAccountRenderData != null ? (SponsoredAccountRenderData) SponsoredAccountRenderData.ADAPTER.redact(sponsoredAccountRenderData) : null;
        InstantPayRenderData instantPayRenderData = paymentRenderData.instant_pay_render_data;
        InstantPayRenderData instantPayRenderData2 = instantPayRenderData != null ? (InstantPayRenderData) InstantPayRenderData.ADAPTER.redact(instantPayRenderData) : null;
        GiftCardRenderData giftCardRenderData = paymentRenderData.gift_card_render_data;
        GiftCardRenderData giftCardRenderData2 = giftCardRenderData != null ? (GiftCardRenderData) GiftCardRenderData.ADAPTER.redact(giftCardRenderData) : null;
        NewDeviceLoginRenderData newDeviceLoginRenderData = paymentRenderData.new_device_login_render_data;
        NewDeviceLoginRenderData newDeviceLoginRenderData2 = newDeviceLoginRenderData != null ? (NewDeviceLoginRenderData) NewDeviceLoginRenderData.ADAPTER.redact(newDeviceLoginRenderData) : null;
        TimelineRenderData timelineRenderData = paymentRenderData.timeline_render_data;
        TimelineRenderData timelineRenderData2 = timelineRenderData != null ? (TimelineRenderData) TimelineRenderData.ADAPTER.redact(timelineRenderData) : null;
        DisputedTransactionRenderData disputedTransactionRenderData = paymentRenderData.disputed_transaction_render_data;
        DisputedTransactionRenderData disputedTransactionRenderData2 = disputedTransactionRenderData != null ? (DisputedTransactionRenderData) DisputedTransactionRenderData.ADAPTER.redact(disputedTransactionRenderData) : null;
        InvestingAutomationTriggerRenderData investingAutomationTriggerRenderData = paymentRenderData.investing_automation_trigger_render_data;
        InvestingAutomationTriggerRenderData investingAutomationTriggerRenderData2 = investingAutomationTriggerRenderData != null ? (InvestingAutomationTriggerRenderData) InvestingAutomationTriggerRenderData.ADAPTER.redact(investingAutomationTriggerRenderData) : null;
        InvestingAutomationExecutionRenderData investingAutomationExecutionRenderData = paymentRenderData.investing_automation_execution_render_data;
        InvestingAutomationExecutionRenderData investingAutomationExecutionRenderData2 = investingAutomationExecutionRenderData != null ? (InvestingAutomationExecutionRenderData) InvestingAutomationExecutionRenderData.ADAPTER.redact(investingAutomationExecutionRenderData) : null;
        AfterPayRenderData afterPayRenderData = paymentRenderData.afterpay_render_data;
        AfterPayRenderData afterPayRenderData2 = afterPayRenderData != null ? (AfterPayRenderData) AfterPayRenderData.ADAPTER.redact(afterPayRenderData) : null;
        CashAppPayOrderRenderData cashAppPayOrderRenderData = paymentRenderData.cash_app_pay_order_render_data;
        CashAppPayOrderRenderData cashAppPayOrderRenderData2 = cashAppPayOrderRenderData != null ? (CashAppPayOrderRenderData) CashAppPayOrderRenderData.ADAPTER.redact(cashAppPayOrderRenderData) : null;
        CashAppPayPaymentRenderData cashAppPayPaymentRenderData = paymentRenderData.cash_app_pay_payment_render_data;
        CashAppPayPaymentRenderData cashAppPayPaymentRenderData2 = cashAppPayPaymentRenderData != null ? (CashAppPayPaymentRenderData) CashAppPayPaymentRenderData.ADAPTER.redact(cashAppPayPaymentRenderData) : null;
        CashAppPayRefundRenderData cashAppPayRefundRenderData = paymentRenderData.cash_app_pay_refund_render_data;
        CashAppPayRefundRenderData cashAppPayRefundRenderData2 = cashAppPayRefundRenderData != null ? (CashAppPayRefundRenderData) CashAppPayRefundRenderData.ADAPTER.redact(cashAppPayRefundRenderData) : null;
        CashAppPayPaymentScheduleRenderData cashAppPayPaymentScheduleRenderData = paymentRenderData.cash_app_pay_payment_schedule_render_data;
        CashAppPayPaymentScheduleRenderData cashAppPayPaymentScheduleRenderData2 = cashAppPayPaymentScheduleRenderData != null ? (CashAppPayPaymentScheduleRenderData) CashAppPayPaymentScheduleRenderData.ADAPTER.redact(cashAppPayPaymentScheduleRenderData) : null;
        CashAppPayPayoutRenderData cashAppPayPayoutRenderData = paymentRenderData.cash_app_pay_payout_render_data;
        CashAppPayPayoutRenderData cashAppPayPayoutRenderData2 = cashAppPayPayoutRenderData != null ? (CashAppPayPayoutRenderData) CashAppPayPayoutRenderData.ADAPTER.redact(cashAppPayPayoutRenderData) : null;
        CommerceOrderRenderData commerceOrderRenderData = paymentRenderData.commerce_order_render_data;
        CommerceOrderRenderData commerceOrderRenderData2 = commerceOrderRenderData != null ? (CommerceOrderRenderData) CommerceOrderRenderData.ADAPTER.redact(commerceOrderRenderData) : null;
        CashAppPayRenderData cashAppPayRenderData = paymentRenderData.cash_app_pay_render_data;
        CashAppPayRenderData cashAppPayRenderData2 = cashAppPayRenderData != null ? (CashAppPayRenderData) CashAppPayRenderData.ADAPTER.redact(cashAppPayRenderData) : null;
        ViewContextRenderData viewContextRenderData = paymentRenderData.view_context_render_data;
        ViewContextRenderData viewContextRenderData2 = viewContextRenderData != null ? (ViewContextRenderData) ViewContextRenderData.ADAPTER.redact(viewContextRenderData) : null;
        GenericNonPaymentRenderData genericNonPaymentRenderData = paymentRenderData.generic_non_payment_render_data;
        GenericNonPaymentRenderData genericNonPaymentRenderData2 = genericNonPaymentRenderData != null ? (GenericNonPaymentRenderData) GenericNonPaymentRenderData.ADAPTER.redact(genericNonPaymentRenderData) : null;
        SavingsTransferRenderData savingsTransferRenderData = paymentRenderData.savings_transfer_render_data;
        SavingsTransferRenderData savingsTransferRenderData2 = savingsTransferRenderData != null ? (SavingsTransferRenderData) SavingsTransferRenderData.ADAPTER.redact(savingsTransferRenderData) : null;
        SavingsInterestPaymentRenderData savingsInterestPaymentRenderData = paymentRenderData.savings_interest_payment_render_data;
        SavingsInterestPaymentRenderData savingsInterestPaymentRenderData2 = savingsInterestPaymentRenderData != null ? (SavingsInterestPaymentRenderData) SavingsInterestPaymentRenderData.ADAPTER.redact(savingsInterestPaymentRenderData) : null;
        RemittancePaymentRenderData remittancePaymentRenderData = paymentRenderData.remittance_payment_render_data;
        RemittancePaymentRenderData remittancePaymentRenderData2 = remittancePaymentRenderData != null ? (RemittancePaymentRenderData) RemittancePaymentRenderData.ADAPTER.redact(remittancePaymentRenderData) : null;
        GroupActivityRenderData groupActivityRenderData = paymentRenderData.group_activity_render_data;
        GroupActivityRenderData groupActivityRenderData2 = groupActivityRenderData != null ? (GroupActivityRenderData) GroupActivityRenderData.ADAPTER.redact(groupActivityRenderData) : null;
        ActivityToken activityToken = paymentRenderData.activity_token;
        ActivityToken activityToken2 = activityToken != null ? (ActivityToken) ActivityToken.ADAPTER.redact(activityToken) : null;
        TransactionAuthRenderData transactionAuthRenderData = paymentRenderData.transaction_auth_render_data;
        TransactionAuthRenderData transactionAuthRenderData2 = transactionAuthRenderData != null ? (TransactionAuthRenderData) TransactionAuthRenderData.ADAPTER.redact(transactionAuthRenderData) : null;
        ArrayList m1169redactElements = TransactorKt.m1169redactElements(paymentRenderData.balance_impacts, BalanceImpact.ADAPTER);
        CouponActivityRenderData couponActivityRenderData = paymentRenderData.coupon_activity_render_data;
        CouponActivityRenderData couponActivityRenderData2 = couponActivityRenderData != null ? (CouponActivityRenderData) CouponActivityRenderData.ADAPTER.redact(couponActivityRenderData) : null;
        InvestCorrectionRenderData investCorrectionRenderData = paymentRenderData.invest_correction_render_data;
        InvestCorrectionRenderData investCorrectionRenderData2 = investCorrectionRenderData != null ? (InvestCorrectionRenderData) InvestCorrectionRenderData.ADAPTER.redact(investCorrectionRenderData) : null;
        FiatP2pRenderData fiatP2pRenderData = paymentRenderData.fiat_p2p_render_data;
        FiatP2pRenderData fiatP2pRenderData2 = fiatP2pRenderData != null ? (FiatP2pRenderData) FiatP2pRenderData.ADAPTER.redact(fiatP2pRenderData) : null;
        CheckDepositRenderData checkDepositRenderData = paymentRenderData.check_deposit_render_data;
        CheckDepositRenderData checkDepositRenderData2 = checkDepositRenderData != null ? (CheckDepositRenderData) CheckDepositRenderData.ADAPTER.redact(checkDepositRenderData) : null;
        LocalizableString localizableString = paymentRenderData.localizable_note;
        LocalizableString localizableString2 = localizableString != null ? (LocalizableString) LocalizableString.ADAPTER.redact(localizableString) : null;
        OverdraftRenderData overdraftRenderData = paymentRenderData.overdraft_render_data;
        OverdraftRenderData overdraftRenderData2 = overdraftRenderData != null ? (OverdraftRenderData) OverdraftRenderData.ADAPTER.redact(overdraftRenderData) : null;
        PaymentPlanEligibilityRenderData paymentPlanEligibilityRenderData = paymentRenderData.payment_plan_eligibility_render_data;
        PaymentPlanEligibilityRenderData paymentPlanEligibilityRenderData2 = paymentPlanEligibilityRenderData != null ? (PaymentPlanEligibilityRenderData) PaymentPlanEligibilityRenderData.ADAPTER.redact(paymentPlanEligibilityRenderData) : null;
        FeatureInvitationRenderData featureInvitationRenderData = paymentRenderData.feature_invitation_render_data;
        FeatureInvitationRenderData featureInvitationRenderData2 = featureInvitationRenderData != null ? (FeatureInvitationRenderData) FeatureInvitationRenderData.ADAPTER.redact(featureInvitationRenderData) : null;
        TTPPaymentRenderData tTPPaymentRenderData = paymentRenderData.ttp_payment_render_data;
        TTPPaymentRenderData tTPPaymentRenderData2 = tTPPaymentRenderData != null ? (TTPPaymentRenderData) TTPPaymentRenderData.ADAPTER.redact(tTPPaymentRenderData) : null;
        PersonalizationRenderData personalizationRenderData = paymentRenderData.personalization_render_data;
        PersonalizationRenderData personalizationRenderData2 = personalizationRenderData != null ? (PersonalizationRenderData) PersonalizationRenderData.ADAPTER.redact(personalizationRenderData) : null;
        AutoAllocationRenderData autoAllocationRenderData = paymentRenderData.auto_allocation_render_data;
        AutoAllocationRenderData autoAllocationRenderData2 = autoAllocationRenderData != null ? (AutoAllocationRenderData) AutoAllocationRenderData.ADAPTER.redact(autoAllocationRenderData) : null;
        BillPayRenderData billPayRenderData = paymentRenderData.bill_pay_render_data;
        BillPayRenderData billPayRenderData2 = billPayRenderData != null ? (BillPayRenderData) BillPayRenderData.ADAPTER.redact(billPayRenderData) : null;
        BitcoinOnchainRenderData bitcoinOnchainRenderData = paymentRenderData.bitcoin_onchain_render_data;
        BitcoinOnchainRenderData bitcoinOnchainRenderData2 = bitcoinOnchainRenderData != null ? (BitcoinOnchainRenderData) BitcoinOnchainRenderData.ADAPTER.redact(bitcoinOnchainRenderData) : null;
        LendingCardRenderData lendingCardRenderData = paymentRenderData.lending_card_render_data;
        LendingCardRenderData lendingCardRenderData2 = lendingCardRenderData != null ? (LendingCardRenderData) LendingCardRenderData.ADAPTER.redact(lendingCardRenderData) : null;
        CashAppLocalPaymentRenderData cashAppLocalPaymentRenderData = paymentRenderData.cash_app_local_payment_render_data;
        CashAppLocalPaymentRenderData cashAppLocalPaymentRenderData2 = cashAppLocalPaymentRenderData != null ? (CashAppLocalPaymentRenderData) CashAppLocalPaymentRenderData.ADAPTER.redact(cashAppLocalPaymentRenderData) : null;
        CashAppLocalOrderRenderData cashAppLocalOrderRenderData = paymentRenderData.cash_app_local_order_render_data;
        CashAppLocalOrderRenderData cashAppLocalOrderRenderData2 = cashAppLocalOrderRenderData != null ? (CashAppLocalOrderRenderData) CashAppLocalOrderRenderData.ADAPTER.redact(cashAppLocalOrderRenderData) : null;
        AchRenderData achRenderData = paymentRenderData.ach_render_data;
        AchRenderData achRenderData2 = achRenderData != null ? (AchRenderData) AchRenderData.ADAPTER.redact(achRenderData) : null;
        BitcoinLightningRenderData bitcoinLightningRenderData = paymentRenderData.bitcoin_lightning_render_data;
        BitcoinLightningRenderData bitcoinLightningRenderData2 = bitcoinLightningRenderData != null ? (BitcoinLightningRenderData) BitcoinLightningRenderData.ADAPTER.redact(bitcoinLightningRenderData) : null;
        P2pPoolRenderData p2pPoolRenderData = paymentRenderData.p2p_pool_render_data;
        P2pPoolRenderData p2pPoolRenderData2 = p2pPoolRenderData != null ? (P2pPoolRenderData) P2pPoolRenderData.ADAPTER.redact(p2pPoolRenderData) : null;
        P2pPoolMemberRenderData p2pPoolMemberRenderData = paymentRenderData.p2p_pool_member_render_data;
        P2pPoolMemberRenderData p2pPoolMemberRenderData2 = p2pPoolMemberRenderData != null ? (P2pPoolMemberRenderData) P2pPoolMemberRenderData.ADAPTER.redact(p2pPoolMemberRenderData) : null;
        ActivityRowRenderData activityRowRenderData = paymentRenderData.activity_row_render_data;
        ActivityRowRenderData activityRowRenderData2 = activityRowRenderData != null ? (ActivityRowRenderData) ActivityRowRenderData.ADAPTER.redact(activityRowRenderData) : null;
        Money money21 = paymentRenderData.impact;
        Money money22 = money21 != null ? (Money) Money.ADAPTER.redact(money21) : null;
        Money money23 = paymentRenderData.current_balance;
        Money money24 = money23 != null ? (Money) Money.ADAPTER.redact(money23) : null;
        P2pPoolContributionRenderData p2pPoolContributionRenderData = paymentRenderData.p2p_pool_contribution_render_data;
        P2pPoolContributionRenderData p2pPoolContributionRenderData2 = p2pPoolContributionRenderData != null ? (P2pPoolContributionRenderData) P2pPoolContributionRenderData.ADAPTER.redact(p2pPoolContributionRenderData) : null;
        CustomerAdjustmentRenderData customerAdjustmentRenderData = paymentRenderData.customer_adjustment_render_data;
        CustomerAdjustmentRenderData customerAdjustmentRenderData2 = customerAdjustmentRenderData != null ? (CustomerAdjustmentRenderData) CustomerAdjustmentRenderData.ADAPTER.redact(customerAdjustmentRenderData) : null;
        StablecoinRenderData stablecoinRenderData = paymentRenderData.stablecoin_render_data;
        StablecoinRenderData stablecoinRenderData2 = stablecoinRenderData != null ? (StablecoinRenderData) StablecoinRenderData.ADAPTER.redact(stablecoinRenderData) : null;
        RecurringTransferRenderData recurringTransferRenderData = paymentRenderData.recurring_transfer_render_data;
        RecurringTransferRenderData recurringTransferRenderData2 = recurringTransferRenderData != null ? (RecurringTransferRenderData) RecurringTransferRenderData.ADAPTER.redact(recurringTransferRenderData) : null;
        LiftedRestrictionTransferRenderData liftedRestrictionTransferRenderData = paymentRenderData.lifted_restriction_transfer_render_data;
        LiftedRestrictionTransferRenderData liftedRestrictionTransferRenderData2 = liftedRestrictionTransferRenderData != null ? (LiftedRestrictionTransferRenderData) LiftedRestrictionTransferRenderData.ADAPTER.redact(liftedRestrictionTransferRenderData) : null;
        RestrictedCashInTransferRenderData restrictedCashInTransferRenderData = paymentRenderData.restricted_cash_in_transfer_render_data;
        RestrictedCashInTransferRenderData restrictedCashInTransferRenderData2 = restrictedCashInTransferRenderData != null ? (RestrictedCashInTransferRenderData) RestrictedCashInTransferRenderData.ADAPTER.redact(restrictedCashInTransferRenderData) : null;
        CashAppTagRenderData cashAppTagRenderData = paymentRenderData.cash_app_tag_render_data;
        CashAppTagRenderData cashAppTagRenderData2 = cashAppTagRenderData != null ? (CashAppTagRenderData) CashAppTagRenderData.ADAPTER.redact(cashAppTagRenderData) : null;
        CashLiteCardTransactionRenderData cashLiteCardTransactionRenderData = paymentRenderData.cash_lite_card_transaction_render_data;
        CashLiteCardTransactionRenderData cashLiteCardTransactionRenderData2 = cashLiteCardTransactionRenderData != null ? (CashLiteCardTransactionRenderData) CashLiteCardTransactionRenderData.ADAPTER.redact(cashLiteCardTransactionRenderData) : null;
        ByteString byteString = ByteString.EMPTY;
        String str = paymentRenderData.token;
        String str2 = paymentRenderData.receipt_token;
        Orientation orientation = paymentRenderData.orientation;
        Role role = paymentRenderData.role;
        RatePlan ratePlan = paymentRenderData.rate_plan;
        Long l = paymentRenderData.reward_basis_points;
        Long l2 = paymentRenderData.boost_basis_points;
        Payment$State payment$State = paymentRenderData.state;
        Payment$CancellationReason payment$CancellationReason = paymentRenderData.cancellation_reason;
        Payment$CancellationReason payment$CancellationReason2 = paymentRenderData.refund_cancellation_reason;
        String str3 = paymentRenderData.client_display_name;
        String str4 = paymentRenderData.note;
        Boolean bool = paymentRenderData.sent_via_watch;
        Boolean bool2 = paymentRenderData.sent_via_imessage;
        String str5 = paymentRenderData.display_instrument;
        CashInstrumentType cashInstrumentType = paymentRenderData.instrument_type;
        String str6 = paymentRenderData.transaction_id;
        Long l3 = paymentRenderData.created_at;
        Long l4 = paymentRenderData.captured_at;
        Long l5 = paymentRenderData.reached_customer_at;
        Long l6 = paymentRenderData.passed_customer_at;
        Long l7 = paymentRenderData.paid_out_at;
        Long l8 = paymentRenderData.deposited_at;
        Long l9 = paymentRenderData.refunded_at;
        Long l10 = paymentRenderData.refund_deposited_at;
        Long l11 = paymentRenderData.refund_request_expires_at;
        Long l12 = paymentRenderData.failed_at;
        Long l13 = paymentRenderData.display_date;
        Boolean bool3 = paymentRenderData.is_transfer;
        Boolean bool4 = paymentRenderData.is_prefunded_transfer;
        String str7 = paymentRenderData.estimated_withdrawal_date;
        Boolean bool5 = paymentRenderData.is_banking_transaction;
        Boolean bool6 = paymentRenderData.is_scheduled_payment;
        Boolean bool7 = paymentRenderData.is_pwc_payment;
        Long l14 = paymentRenderData.scheduled_for;
        DepositPreference depositPreference = paymentRenderData.deposit_preference;
        Long l15 = paymentRenderData.deposit_instantly_valid_until;
        String str8 = paymentRenderData.transaction_reason_code;
        Long l16 = paymentRenderData.supports_reporting_missing_reward_until;
        String str9 = paymentRenderData.target_wallet_address;
        List list = paymentRenderData.hidden_receipt_buttons;
        Long l17 = paymentRenderData.supports_reporting_boost_until;
        Boolean bool8 = paymentRenderData.in_cash_boost_experiment;
        Boolean bool9 = paymentRenderData.is_scheduled_reload;
        Boolean bool10 = paymentRenderData.refunded_to_balance;
        Boolean bool11 = paymentRenderData.verification_required;
        Boolean bool12 = paymentRenderData.idv_in_progress;
        Boolean bool13 = paymentRenderData.will_refund_to_balance;
        String str10 = paymentRenderData.crypto_transfer_status;
        Boolean bool14 = paymentRenderData.is_bitcoin_transaction;
        Boolean bool15 = paymentRenderData.can_unlock_free_atm_status;
        String str11 = paymentRenderData.movement_exchange_rate;
        Country country = paymentRenderData.sender_country;
        Boolean bool16 = paymentRenderData.is_app_purchase;
        Long l18 = paymentRenderData.refund_requested_at;
        Long l19 = paymentRenderData.refund_request_declined_at;
        Long l20 = paymentRenderData.request_refund_available_until;
        RequestRefundReason requestRefundReason = paymentRenderData.request_refund_reason;
        RecurringSchedule.Frequency frequency = paymentRenderData.frequency;
        List list2 = paymentRenderData.days_of_period;
        String str12 = paymentRenderData.check_reference_token;
        ExplicitConfirmationReason explicitConfirmationReason = paymentRenderData.explicit_confirmation_reason;
        String str13 = paymentRenderData.btc_limit;
        Long l21 = paymentRenderData.outstanding_until;
        String str14 = paymentRenderData.caller_customer_token;
        ActivityScope activityScope = paymentRenderData.activity_scope;
        Boolean bool17 = paymentRenderData.is_background;
        Boolean bool18 = paymentRenderData.has_error_context;
        Boolean bool19 = paymentRenderData.is_recurring;
        Boolean bool20 = paymentRenderData.is_deposit_reversal;
        String str15 = paymentRenderData.raw_merchant_descriptor;
        Long l22 = paymentRenderData.counterparty_viewed_at;
        Boolean bool21 = paymentRenderData.is_send_to_cashtag_oct;
        list.getClass();
        list2.getClass();
        byteString.getClass();
        return new PaymentRenderData(str, null, str2, orientation, role, ratePlan, money2, money4, money6, money8, money10, money12, money14, money16, l, money18, money20, l2, payment$State, payment$CancellationReason, payment$CancellationReason2, str3, str4, bool, bool2, str5, cashInstrumentType, str6, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, scenarioPlan2, scenarioPlanMap2, bool3, bool4, str7, bool5, bool6, bool7, l14, depositPreference, l15, str8, l16, instrument2, str9, list, l17, bool8, bool9, bool10, reactionRenderData2, bool11, bool12, feeAmounts2, bool13, str10, bool14, bool15, reimbursedAmounts2, str11, country, lendingRenderData2, bool16, l18, l19, l20, requestRefundReason, frequency, list2, str12, pendingReferralRenderData2, explicitConfirmationReason, str13, crossCurrencyRewardInfo2, loyaltyActivityRenderData2, investPaymentRenderData2, transactionAmountHistory2, l21, cryptoOrderRenderData2, paperCashDepositRenderData2, sponsoredAccountRenderData2, instantPayRenderData2, giftCardRenderData2, newDeviceLoginRenderData2, timelineRenderData2, disputedTransactionRenderData2, investingAutomationTriggerRenderData2, investingAutomationExecutionRenderData2, afterPayRenderData2, cashAppPayOrderRenderData2, cashAppPayPaymentRenderData2, cashAppPayRefundRenderData2, cashAppPayPaymentScheduleRenderData2, cashAppPayPayoutRenderData2, commerceOrderRenderData2, cashAppPayRenderData2, viewContextRenderData2, genericNonPaymentRenderData2, savingsTransferRenderData2, savingsInterestPaymentRenderData2, remittancePaymentRenderData2, groupActivityRenderData2, str14, activityToken2, activityScope, transactionAuthRenderData2, m1169redactElements, couponActivityRenderData2, investCorrectionRenderData2, fiatP2pRenderData2, checkDepositRenderData2, localizableString2, overdraftRenderData2, paymentPlanEligibilityRenderData2, featureInvitationRenderData2, tTPPaymentRenderData2, personalizationRenderData2, autoAllocationRenderData2, billPayRenderData2, bool17, bool18, bool19, bitcoinOnchainRenderData2, bool20, lendingCardRenderData2, str15, cashAppLocalPaymentRenderData2, cashAppLocalOrderRenderData2, achRenderData2, bitcoinLightningRenderData2, p2pPoolRenderData2, p2pPoolMemberRenderData2, activityRowRenderData2, money22, money24, p2pPoolContributionRenderData2, customerAdjustmentRenderData2, stablecoinRenderData2, recurringTransferRenderData2, liftedRestrictionTransferRenderData2, restrictedCashInTransferRenderData2, cashAppTagRenderData2, l22, cashLiteCardTransactionRenderData2, bool21, byteString);
    }

    @Override // com.squareup.wire.ProtoAdapter
    public final void encode(ProtoWriter protoWriter, Object obj) {
        PaymentRenderData paymentRenderData = (PaymentRenderData) obj;
        paymentRenderData.getClass();
        ProtoAdapter protoAdapter = ProtoAdapter.STRING;
        protoAdapter.encodeWithTag(protoWriter, 1, paymentRenderData.token);
        protoAdapter.encodeWithTag(protoWriter, 34, paymentRenderData.auth_token);
        protoAdapter.encodeWithTag(protoWriter, 117, paymentRenderData.receipt_token);
        Orientation.ADAPTER.encodeWithTag(protoWriter, 2, paymentRenderData.orientation);
        Role.ADAPTER.encodeWithTag(protoWriter, 3, paymentRenderData.role);
        RatePlan.ADAPTER.encodeWithTag(protoWriter, 4, paymentRenderData.rate_plan);
        ProtoAdapter protoAdapter2 = Money.ADAPTER;
        protoAdapter2.encodeWithTag(protoWriter, 5, paymentRenderData.amount);
        protoAdapter2.encodeWithTag(protoWriter, 6, paymentRenderData.pull_amount);
        protoAdapter2.encodeWithTag(protoWriter, 7, paymentRenderData.push_amount);
        protoAdapter2.encodeWithTag(protoWriter, 68, paymentRenderData.sender_payment_amount_in_default_currency);
        protoAdapter2.encodeWithTag(protoWriter, 69, paymentRenderData.recipient_payment_amount_in_default_currency);
        protoAdapter2.encodeWithTag(protoWriter, 42, paymentRenderData.fee_amount);
        protoAdapter2.encodeWithTag(protoWriter, 28, paymentRenderData.refund_amount);
        protoAdapter2.encodeWithTag(protoWriter, 38, paymentRenderData.reward_amount);
        ProtoAdapter protoAdapter3 = ProtoAdapter.INT64;
        protoAdapter3.encodeWithTag(protoWriter, 39, paymentRenderData.reward_basis_points);
        protoAdapter2.encodeWithTag(protoWriter, 49, paymentRenderData.boost_amount);
        protoAdapter2.encodeWithTag(protoWriter, 127, paymentRenderData.settled_amount);
        protoAdapter3.encodeWithTag(protoWriter, 50, paymentRenderData.boost_basis_points);
        Payment$State.ADAPTER.encodeWithTag(protoWriter, 8, paymentRenderData.state);
        Payment$CancellationReason$Companion$ADAPTER$1 payment$CancellationReason$Companion$ADAPTER$1 = Payment$CancellationReason.ADAPTER;
        payment$CancellationReason$Companion$ADAPTER$1.encodeWithTag(protoWriter, 9, paymentRenderData.cancellation_reason);
        payment$CancellationReason$Companion$ADAPTER$1.encodeWithTag(protoWriter, 10, paymentRenderData.refund_cancellation_reason);
        protoAdapter.encodeWithTag(protoWriter, 11, paymentRenderData.client_display_name);
        protoAdapter.encodeWithTag(protoWriter, 12, paymentRenderData.note);
        ProtoAdapter protoAdapter4 = ProtoAdapter.BOOL;
        protoAdapter4.encodeWithTag(protoWriter, 23, paymentRenderData.sent_via_watch);
        protoAdapter4.encodeWithTag(protoWriter, 30, paymentRenderData.sent_via_imessage);
        protoAdapter.encodeWithTag(protoWriter, 13, paymentRenderData.display_instrument);
        CashInstrumentType.ADAPTER.encodeWithTag(protoWriter, 27, paymentRenderData.instrument_type);
        protoAdapter.encodeWithTag(protoWriter, 21, paymentRenderData.transaction_id);
        protoAdapter3.encodeWithTag(protoWriter, 14, paymentRenderData.created_at);
        protoAdapter3.encodeWithTag(protoWriter, 15, paymentRenderData.captured_at);
        protoAdapter3.encodeWithTag(protoWriter, 35, paymentRenderData.reached_customer_at);
        protoAdapter3.encodeWithTag(protoWriter, 44, paymentRenderData.passed_customer_at);
        protoAdapter3.encodeWithTag(protoWriter, 16, paymentRenderData.paid_out_at);
        protoAdapter3.encodeWithTag(protoWriter, 17, paymentRenderData.deposited_at);
        protoAdapter3.encodeWithTag(protoWriter, 18, paymentRenderData.refunded_at);
        protoAdapter3.encodeWithTag(protoWriter, 22, paymentRenderData.refund_deposited_at);
        protoAdapter3.encodeWithTag(protoWriter, 85, paymentRenderData.refund_request_expires_at);
        protoAdapter3.encodeWithTag(protoWriter, 20, paymentRenderData.failed_at);
        protoAdapter3.encodeWithTag(protoWriter, 37, paymentRenderData.display_date);
        ScenarioPlan.ADAPTER.encodeWithTag(protoWriter, 24, paymentRenderData.scenario_plan);
        ScenarioPlanMap.ADAPTER.encodeWithTag(protoWriter, 33, paymentRenderData.scenario_plan_map);
        protoAdapter4.encodeWithTag(protoWriter, 25, paymentRenderData.is_transfer);
        protoAdapter4.encodeWithTag(protoWriter, 106, paymentRenderData.is_prefunded_transfer);
        protoAdapter.encodeWithTag(protoWriter, 118, paymentRenderData.estimated_withdrawal_date);
        protoAdapter4.encodeWithTag(protoWriter, 26, paymentRenderData.is_banking_transaction);
        protoAdapter4.encodeWithTag(protoWriter, 46, paymentRenderData.is_scheduled_payment);
        protoAdapter4.encodeWithTag(protoWriter, 82, paymentRenderData.is_pwc_payment);
        protoAdapter3.encodeWithTag(protoWriter, 63, paymentRenderData.scheduled_for);
        DepositPreference.ADAPTER.encodeWithTag(protoWriter, 29, paymentRenderData.deposit_preference);
        protoAdapter3.encodeWithTag(protoWriter, 32, paymentRenderData.deposit_instantly_valid_until);
        protoAdapter.encodeWithTag(protoWriter, 36, paymentRenderData.transaction_reason_code);
        protoAdapter3.encodeWithTag(protoWriter, 43, paymentRenderData.supports_reporting_missing_reward_until);
        Instrument.ADAPTER.encodeWithTag(protoWriter, 41, paymentRenderData.instrument);
        protoAdapter.encodeWithTag(protoWriter, 45, paymentRenderData.target_wallet_address);
        PaymentHistoryButton.ButtonAction.ADAPTER.asRepeated().encodeWithTag(protoWriter, 48, paymentRenderData.hidden_receipt_buttons);
        protoAdapter3.encodeWithTag(protoWriter, 51, paymentRenderData.supports_reporting_boost_until);
        protoAdapter4.encodeWithTag(protoWriter, 52, paymentRenderData.in_cash_boost_experiment);
        protoAdapter4.encodeWithTag(protoWriter, 53, paymentRenderData.is_scheduled_reload);
        protoAdapter4.encodeWithTag(protoWriter, 54, paymentRenderData.refunded_to_balance);
        ReactionRenderData.ADAPTER.encodeWithTag(protoWriter, 55, paymentRenderData.reaction_data);
        protoAdapter4.encodeWithTag(protoWriter, 56, paymentRenderData.verification_required);
        protoAdapter4.encodeWithTag(protoWriter, 57, paymentRenderData.idv_in_progress);
        FeeAmounts.ADAPTER.encodeWithTag(protoWriter, 59, paymentRenderData.fee_amounts);
        protoAdapter4.encodeWithTag(protoWriter, 60, paymentRenderData.will_refund_to_balance);
        protoAdapter.encodeWithTag(protoWriter, 61, paymentRenderData.crypto_transfer_status);
        protoAdapter4.encodeWithTag(protoWriter, 62, paymentRenderData.is_bitcoin_transaction);
        protoAdapter4.encodeWithTag(protoWriter, 64, paymentRenderData.can_unlock_free_atm_status);
        ReimbursedAmounts.ADAPTER.encodeWithTag(protoWriter, 65, paymentRenderData.reimbursed_amounts);
        protoAdapter.encodeWithTag(protoWriter, 67, paymentRenderData.movement_exchange_rate);
        Country.ADAPTER.encodeWithTag(protoWriter, 70, paymentRenderData.sender_country);
        LendingRenderData.ADAPTER.encodeWithTag(protoWriter, 71, paymentRenderData.lending_render_data);
        protoAdapter4.encodeWithTag(protoWriter, 72, paymentRenderData.is_app_purchase);
        protoAdapter3.encodeWithTag(protoWriter, 73, paymentRenderData.refund_requested_at);
        protoAdapter3.encodeWithTag(protoWriter, 74, paymentRenderData.refund_request_declined_at);
        protoAdapter3.encodeWithTag(protoWriter, 79, paymentRenderData.request_refund_available_until);
        RequestRefundReason.ADAPTER.encodeWithTag(protoWriter, 75, paymentRenderData.request_refund_reason);
        RecurringSchedule.Frequency.ADAPTER.encodeWithTag(protoWriter, 77, paymentRenderData.frequency);
        ProtoAdapter.INT32.asRepeated().encodeWithTag(protoWriter, 78, paymentRenderData.days_of_period);
        protoAdapter.encodeWithTag(protoWriter, 80, paymentRenderData.check_reference_token);
        PendingReferralRenderData.ADAPTER.encodeWithTag(protoWriter, 81, paymentRenderData.pending_referral_render_data);
        ExplicitConfirmationReason.ADAPTER.encodeWithTag(protoWriter, 83, paymentRenderData.explicit_confirmation_reason);
        protoAdapter.encodeWithTag(protoWriter, 84, paymentRenderData.btc_limit);
        PaymentRenderData.CrossCurrencyRewardInfo.ADAPTER.encodeWithTag(protoWriter, 86, paymentRenderData.cross_currency_reward_info);
        LoyaltyActivityRenderData.ADAPTER.encodeWithTag(protoWriter, 87, paymentRenderData.loyalty_activity_render_data);
        InvestPaymentRenderData.ADAPTER.encodeWithTag(protoWriter, 88, paymentRenderData.invest_payment_render_data);
        TransactionAmountHistory.ADAPTER.encodeWithTag(protoWriter, 89, paymentRenderData.transaction_amount_history);
        protoAdapter3.encodeWithTag(protoWriter, 90, paymentRenderData.outstanding_until);
        CryptoOrderRenderData.ADAPTER.encodeWithTag(protoWriter, 91, paymentRenderData.crypto_order_render_data);
        PaperCashDepositRenderData.ADAPTER.encodeWithTag(protoWriter, 92, paymentRenderData.paper_cash_deposit_render_data);
        SponsoredAccountRenderData.ADAPTER.encodeWithTag(protoWriter, 93, paymentRenderData.sponsored_account_render_data);
        InstantPayRenderData.ADAPTER.encodeWithTag(protoWriter, 94, paymentRenderData.instant_pay_render_data);
        GiftCardRenderData.ADAPTER.encodeWithTag(protoWriter, 95, paymentRenderData.gift_card_render_data);
        NewDeviceLoginRenderData.ADAPTER.encodeWithTag(protoWriter, 96, paymentRenderData.new_device_login_render_data);
        TimelineRenderData.ADAPTER.encodeWithTag(protoWriter, 97, paymentRenderData.timeline_render_data);
        DisputedTransactionRenderData.ADAPTER.encodeWithTag(protoWriter, 98, paymentRenderData.disputed_transaction_render_data);
        InvestingAutomationTriggerRenderData.ADAPTER.encodeWithTag(protoWriter, 99, paymentRenderData.investing_automation_trigger_render_data);
        InvestingAutomationExecutionRenderData.ADAPTER.encodeWithTag(protoWriter, 100, paymentRenderData.investing_automation_execution_render_data);
        AfterPayRenderData.ADAPTER.encodeWithTag(protoWriter, 101, paymentRenderData.afterpay_render_data);
        CashAppPayOrderRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_IN_CONTROL_VALUE, paymentRenderData.cash_app_pay_order_render_data);
        CashAppPayPaymentRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_FAULTY_DATA_VALUE, paymentRenderData.cash_app_pay_payment_render_data);
        CashAppPayRefundRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_LOGS_VALUE, paymentRenderData.cash_app_pay_refund_render_data);
        CashAppPayPaymentScheduleRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SPOT_PX_FEATURE_01_VALUE, paymentRenderData.cash_app_pay_payment_schedule_render_data);
        CashAppPayPayoutRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_RAISE_INSTITUTION_CENTERED_VALUE, paymentRenderData.cash_app_pay_payout_render_data);
        CommerceOrderRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_PLAID_OVERLAY_PERSON_VALUE, paymentRenderData.commerce_order_render_data);
        CashAppPayRenderData.ADAPTER.encodeWithTag(protoWriter, 107, paymentRenderData.cash_app_pay_render_data);
        ViewContextRenderData.ADAPTER.encodeWithTag(protoWriter, 102, paymentRenderData.view_context_render_data);
        GenericNonPaymentRenderData.ADAPTER.encodeWithTag(protoWriter, 103, paymentRenderData.generic_non_payment_render_data);
        SavingsTransferRenderData.ADAPTER.encodeWithTag(protoWriter, 104, paymentRenderData.savings_transfer_render_data);
        SavingsInterestPaymentRenderData.ADAPTER.encodeWithTag(protoWriter, 128, paymentRenderData.savings_interest_payment_render_data);
        RemittancePaymentRenderData.ADAPTER.encodeWithTag(protoWriter, 105, paymentRenderData.remittance_payment_render_data);
        GroupActivityRenderData.ADAPTER.encodeWithTag(protoWriter, 111, paymentRenderData.group_activity_render_data);
        protoAdapter.encodeWithTag(protoWriter, 108, paymentRenderData.caller_customer_token);
        ActivityToken.ADAPTER.encodeWithTag(protoWriter, 109, paymentRenderData.activity_token);
        ActivityScope.ADAPTER.encodeWithTag(protoWriter, 110, paymentRenderData.activity_scope);
        TransactionAuthRenderData.ADAPTER.encodeWithTag(protoWriter, 112, paymentRenderData.transaction_auth_render_data);
        BalanceImpact.ADAPTER.asRepeated().encodeWithTag(protoWriter, 113, paymentRenderData.balance_impacts);
        CouponActivityRenderData.ADAPTER.encodeWithTag(protoWriter, 114, paymentRenderData.coupon_activity_render_data);
        InvestCorrectionRenderData.ADAPTER.encodeWithTag(protoWriter, 115, paymentRenderData.invest_correction_render_data);
        FiatP2pRenderData.ADAPTER.encodeWithTag(protoWriter, 116, paymentRenderData.fiat_p2p_render_data);
        CheckDepositRenderData.ADAPTER.encodeWithTag(protoWriter, 119, paymentRenderData.check_deposit_render_data);
        LocalizableString.ADAPTER.encodeWithTag(protoWriter, 120, paymentRenderData.localizable_note);
        OverdraftRenderData.ADAPTER.encodeWithTag(protoWriter, 121, paymentRenderData.overdraft_render_data);
        PaymentPlanEligibilityRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, paymentRenderData.payment_plan_eligibility_render_data);
        FeatureInvitationRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_CALENDAR_VALUE, paymentRenderData.feature_invitation_render_data);
        TTPPaymentRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SIGNATURE_VALUE, paymentRenderData.ttp_payment_render_data);
        PersonalizationRenderData.ADAPTER.encodeWithTag(protoWriter, 125, paymentRenderData.personalization_render_data);
        AutoAllocationRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, paymentRenderData.auto_allocation_render_data);
        BillPayRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_FORM_VALUE, paymentRenderData.bill_pay_render_data);
        protoAdapter4.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_CONSUMER_VALUE, paymentRenderData.is_background);
        protoAdapter4.encodeWithTag(protoWriter, 131, paymentRenderData.has_error_context);
        protoAdapter4.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_DEV_RAISE_INSTITUTION_VALUE, paymentRenderData.is_recurring);
        BitcoinOnchainRenderData.ADAPTER.encodeWithTag(protoWriter, 136, paymentRenderData.bitcoin_onchain_render_data);
        protoAdapter4.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_INSTITUTION_CIRCLE_VALUE, paymentRenderData.is_deposit_reversal);
        LendingCardRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SHARE_YOUR_DATA_VALUE, paymentRenderData.lending_card_render_data);
        protoAdapter.encodeWithTag(protoWriter, 140, paymentRenderData.raw_merchant_descriptor);
        CashAppLocalPaymentRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_CONNECTIVITY_DOWN_ILLUSTRATION_VALUE, paymentRenderData.cash_app_local_payment_render_data);
        CashAppLocalOrderRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_CONNECTIVITY_WARNING_ILLUSTRATION_VALUE, paymentRenderData.cash_app_local_order_render_data);
        AchRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ICON_ALERT_ERROR_BLACK_VALUE, paymentRenderData.ach_render_data);
        BitcoinLightningRenderData.ADAPTER.encodeWithTag(protoWriter, 144, paymentRenderData.bitcoin_lightning_render_data);
        P2pPoolRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_PLAID_OVERLAY_ACCOUNT_VALUE, paymentRenderData.p2p_pool_render_data);
        P2pPoolMemberRenderData.ADAPTER.encodeWithTag(protoWriter, 147, paymentRenderData.p2p_pool_member_render_data);
        ActivityRowRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ICON_CHECKMARK_GREEN_SQUARE_CASH_VALUE, paymentRenderData.activity_row_render_data);
        protoAdapter2.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SDK_EMPTY_SVG_VALUE, paymentRenderData.impact);
        protoAdapter2.encodeWithTag(protoWriter, 150, paymentRenderData.current_balance);
        P2pPoolContributionRenderData.ADAPTER.encodeWithTag(protoWriter, 151, paymentRenderData.p2p_pool_contribution_render_data);
        CustomerAdjustmentRenderData.ADAPTER.encodeWithTag(protoWriter, 153, paymentRenderData.customer_adjustment_render_data);
        StablecoinRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_UPLOAD_VALUE, paymentRenderData.stablecoin_render_data);
        RecurringTransferRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_MANAGE_CONNECTIONS_VALUE, paymentRenderData.recurring_transfer_render_data);
        LiftedRestrictionTransferRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_FALLBACK_INSTITUTION_VALUE, paymentRenderData.lifted_restriction_transfer_render_data);
        RestrictedCashInTransferRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_WALLET_VALUE, paymentRenderData.restricted_cash_in_transfer_render_data);
        CashAppTagRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_INCOME_VALUE, paymentRenderData.cash_app_tag_render_data);
        protoAdapter3.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SECURE_TOKENIZATION_VALUE, paymentRenderData.counterparty_viewed_at);
        CashLiteCardTransactionRenderData.ADAPTER.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_WARNING_EXIT_SPOT_VALUE, paymentRenderData.cash_lite_card_transaction_render_data);
        protoAdapter4.encodeWithTag(protoWriter, EnumC0170g.SDK_ASSET_ILLUSTRATION_SUPPORT_VALUE, paymentRenderData.is_send_to_cashtag_oct);
        protoWriter.writeBytes(paymentRenderData.unknownFields());
    }
}
