package com.combinations.spin.balbi;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class color {
        public static final int deep_sea = 0x7f040005;
    }

    public static final class drawable {
        public static final int ic_launcher_background = 0x7f060007;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f070000;
        public static final int accessibility_custom_action_0 = 0x7f070001;
        public static final int accessibility_custom_action_1 = 0x7f070002;
        public static final int accessibility_custom_action_10 = 0x7f070003;
        public static final int accessibility_custom_action_11 = 0x7f070004;
        public static final int accessibility_custom_action_12 = 0x7f070005;
        public static final int accessibility_custom_action_13 = 0x7f070006;
        public static final int accessibility_custom_action_14 = 0x7f070007;
        public static final int accessibility_custom_action_15 = 0x7f070008;
        public static final int accessibility_custom_action_16 = 0x7f070009;
        public static final int accessibility_custom_action_17 = 0x7f07000a;
        public static final int accessibility_custom_action_18 = 0x7f07000b;
        public static final int accessibility_custom_action_19 = 0x7f07000c;
        public static final int accessibility_custom_action_2 = 0x7f07000d;
        public static final int accessibility_custom_action_20 = 0x7f07000e;
        public static final int accessibility_custom_action_21 = 0x7f07000f;
        public static final int accessibility_custom_action_22 = 0x7f070010;
        public static final int accessibility_custom_action_23 = 0x7f070011;
        public static final int accessibility_custom_action_24 = 0x7f070012;
        public static final int accessibility_custom_action_25 = 0x7f070013;
        public static final int accessibility_custom_action_26 = 0x7f070014;
        public static final int accessibility_custom_action_27 = 0x7f070015;
        public static final int accessibility_custom_action_28 = 0x7f070016;
        public static final int accessibility_custom_action_29 = 0x7f070017;
        public static final int accessibility_custom_action_3 = 0x7f070018;
        public static final int accessibility_custom_action_30 = 0x7f070019;
        public static final int accessibility_custom_action_31 = 0x7f07001a;
        public static final int accessibility_custom_action_4 = 0x7f07001b;
        public static final int accessibility_custom_action_5 = 0x7f07001c;
        public static final int accessibility_custom_action_6 = 0x7f07001d;
        public static final int accessibility_custom_action_7 = 0x7f07001e;
        public static final int accessibility_custom_action_8 = 0x7f07001f;
        public static final int accessibility_custom_action_9 = 0x7f070020;
        public static final int action_container = 0x7f070021;
        public static final int action_divider = 0x7f070022;
        public static final int action_image = 0x7f070023;
        public static final int action_text = 0x7f070024;
        public static final int actions = 0x7f070025;
        public static final int adjacent = 0x7f070026;
        public static final int always = 0x7f070027;
        public static final int alwaysAllow = 0x7f070028;
        public static final int alwaysDisallow = 0x7f070029;
        public static final int androidx_compose_ui_view_compose_view_context = 0x7f07002a;
        public static final int androidx_compose_ui_view_composition_context = 0x7f07002b;
        public static final int androidx_window_activity_scope = 0x7f07002c;
        public static final int async = 0x7f07002d;
        public static final int auto_clear_focus_behavior_tag = 0x7f07002e;
        public static final int blocking = 0x7f07002f;
        public static final int bottomToTop = 0x7f070030;
        public static final int chronometer = 0x7f070031;
        public static final int compose_prefetch_scheduler = 0x7f070032;
        public static final int compose_view_saveable_id_tag = 0x7f070033;
        public static final int consume_window_insets_tag = 0x7f070034;
        public static final int dialog_button = 0x7f070035;
        public static final int draggable = 0x7f070036;
        public static final int edit_text_id = 0x7f070037;
        public static final int fixed = 0x7f070038;
        public static final int forever = 0x7f070039;
        public static final int fragment_container_view_tag = 0x7f07003a;
        public static final int ghost_view = 0x7f07003b;
        public static final int ghost_view_holder = 0x7f07003c;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f07003d;
        public static final int hide_ime_id = 0x7f07003e;
        public static final int hide_in_inspector_tag = 0x7f07003f;
        public static final int icon = 0x7f070040;
        public static final int icon_group = 0x7f070041;
        public static final int info = 0x7f070042;
        public static final int inspection_slot_table_set = 0x7f070043;
        public static final int is_pooling_container_tag = 0x7f070044;
        public static final int italic = 0x7f070045;
        public static final int jumpCut = 0x7f070046;
        public static final int line1 = 0x7f070047;
        public static final int line3 = 0x7f070048;
        public static final int locale = 0x7f070049;
        public static final int ltr = 0x7f07004a;
        public static final int nav_controller_view_tag = 0x7f07004b;
        public static final int never = 0x7f07004c;
        public static final int normal = 0x7f07004d;
        public static final int notification_background = 0x7f07004e;
        public static final int notification_main_column = 0x7f07004f;
        public static final int notification_main_column_container = 0x7f070050;
        public static final int parent_matrix = 0x7f070051;
        public static final int pooling_container_listener_holder_tag = 0x7f070052;
        public static final int report_drawn = 0x7f070053;
        public static final int right_icon = 0x7f070054;
        public static final int right_side = 0x7f070055;
        public static final int rtl = 0x7f070056;
        public static final int save_non_transition_alpha = 0x7f070057;
        public static final int save_overlay_view = 0x7f070058;
        public static final int special_effects_controller_view_tag = 0x7f070059;
        public static final int systemDefault = 0x7f07005a;
        public static final int tag_accessibility_actions = 0x7f07005b;
        public static final int tag_accessibility_clickable_spans = 0x7f07005c;
        public static final int tag_accessibility_heading = 0x7f07005d;
        public static final int tag_accessibility_pane_title = 0x7f07005e;
        public static final int tag_compat_insets_dispatch = 0x7f07005f;
        public static final int tag_on_apply_window_listener = 0x7f070060;
        public static final int tag_on_receive_content_listener = 0x7f070061;
        public static final int tag_on_receive_content_mime_types = 0x7f070062;
        public static final int tag_screen_reader_focusable = 0x7f070063;
        public static final int tag_state_description = 0x7f070064;
        public static final int tag_system_bar_state_monitor = 0x7f070065;
        public static final int tag_transition_group = 0x7f070066;
        public static final int tag_unhandled_key_event_manager = 0x7f070067;
        public static final int tag_unhandled_key_listeners = 0x7f070068;
        public static final int tag_window_insets_animation_callback = 0x7f070069;
        public static final int text = 0x7f07006a;
        public static final int text2 = 0x7f07006b;
        public static final int time = 0x7f07006c;
        public static final int title = 0x7f07006d;
        public static final int topToBottom = 0x7f07006e;
        public static final int transition_clip = 0x7f07006f;
        public static final int transition_current_scene = 0x7f070070;
        public static final int transition_image_transform = 0x7f070071;
        public static final int transition_layout_save = 0x7f070072;
        public static final int transition_pause_alpha = 0x7f070073;
        public static final int transition_position = 0x7f070074;
        public static final int transition_scene_layoutid_cache = 0x7f070075;
        public static final int transition_transform = 0x7f070076;
        public static final int view_tree_disjoint_parent = 0x7f070077;
        public static final int view_tree_lifecycle_owner = 0x7f070078;
        public static final int view_tree_navigation_event_dispatcher_owner = 0x7f070079;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f07007a;
        public static final int view_tree_saved_state_registry_owner = 0x7f07007b;
        public static final int view_tree_view_model_store_owner = 0x7f07007c;
        public static final int visible_removing_fragment_view_tag = 0x7f07007d;
        public static final int wrapped_composition_tag = 0x7f07007e;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f0a0000;
        public static final int ic_launcher_foreground = 0x7f0a0001;
        public static final int ic_launcher_round = 0x7f0a0002;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f0b0002;
        public static final int app_name = 0x7f0b0003;
        public static final int in_progress = 0x7f0b0010;
        public static final int indeterminate = 0x7f0b0011;
        public static final int m3c_dialog = 0x7f0b0036;
        public static final int not_selected = 0x7f0b0055;
        public static final int selected = 0x7f0b0058;
        public static final int state_empty = 0x7f0b005a;
        public static final int state_off = 0x7f0b005b;
        public static final int state_on = 0x7f0b005c;
        public static final int switch_role = 0x7f0b005e;
        public static final int tab = 0x7f0b005f;
        public static final int template_percent = 0x7f0b0060;
    }

    public static final class style {
        public static final int DialogWindowTheme = 0x7f0c0000;
        public static final int FloatingDialogWindowTheme = 0x7f0c0003;
        public static final int Theme_CorsairLedger = 0x7f0c0009;
    }

    public static final class xml {
        public static final int backup_rules = 0x7f0e0000;
        public static final int data_extraction_rules = 0x7f0e0001;
        public static final int splits0 = 0x7f0e0002;
    }
}
