package com.feathherdashh.dashgame;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int alpha = 0x7f010002;
        public static final int buttonSize = 0x7f010005;
        public static final int circleCrop = 0x7f010006;
        public static final int colorScheme = 0x7f010008;
        public static final int font = 0x7f010011;
        public static final int fontProviderAuthority = 0x7f010012;
        public static final int fontProviderCerts = 0x7f010013;
        public static final int fontProviderFallbackQuery = 0x7f010014;
        public static final int fontProviderFetchStrategy = 0x7f010015;
        public static final int fontProviderFetchTimeout = 0x7f010016;
        public static final int fontProviderPackage = 0x7f010017;
        public static final int fontProviderQuery = 0x7f010018;
        public static final int fontProviderSystemFontFamily = 0x7f010019;
        public static final int fontStyle = 0x7f01001a;
        public static final int fontVariationSettings = 0x7f01001b;
        public static final int fontWeight = 0x7f01001c;
        public static final int imageAspectRatio = 0x7f01001d;
        public static final int imageAspectRatioAdjust = 0x7f01001e;
        public static final int lStar = 0x7f010020;
        public static final int nestedScrollViewStyle = 0x7f010021;
        public static final int queryPatterns = 0x7f010024;
        public static final int scopeUris = 0x7f010025;
        public static final int shortcutMatchRequired = 0x7f010028;
        public static final int ttcIndex = 0x7f010035;
    }

    public static final class color {
        public static final int androidx_core_ripple_material_light = 0x7f020000;
        public static final int androidx_core_secondary_text_default_material_light = 0x7f020001;
        public static final int common_google_signin_btn_text_dark = 0x7f020005;
        public static final int common_google_signin_btn_text_dark_default = 0x7f020006;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f020007;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f020008;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f020009;
        public static final int common_google_signin_btn_text_light = 0x7f02000a;
        public static final int common_google_signin_btn_text_light_default = 0x7f02000b;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f02000c;
        public static final int common_google_signin_btn_text_light_focused = 0x7f02000d;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f02000e;
        public static final int common_google_signin_btn_tint = 0x7f02000f;
        public static final int notification_action_color_filter = 0x7f020010;
        public static final int notification_flame_red = 0x7f020011;
        public static final int notification_icon_bg_color = 0x7f020012;
    }

    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 0x7f030000;
        public static final int compat_button_inset_vertical_material = 0x7f030001;
        public static final int compat_button_padding_horizontal_material = 0x7f030002;
        public static final int compat_button_padding_vertical_material = 0x7f030003;
        public static final int compat_control_corner_material = 0x7f030004;
        public static final int compat_notification_large_icon_max_height = 0x7f030005;
        public static final int compat_notification_large_icon_max_width = 0x7f030006;
        public static final int notification_action_icon_size = 0x7f030007;
        public static final int notification_action_text_size = 0x7f030008;
        public static final int notification_big_circle_margin = 0x7f030009;
        public static final int notification_content_margin_start = 0x7f03000a;
        public static final int notification_large_icon_height = 0x7f03000b;
        public static final int notification_large_icon_width = 0x7f03000c;
        public static final int notification_main_column_padding_top = 0x7f03000d;
        public static final int notification_media_narrow_margin = 0x7f03000e;
        public static final int notification_right_icon_size = 0x7f03000f;
        public static final int notification_right_side_padding_top = 0x7f030010;
        public static final int notification_small_icon_background_padding = 0x7f030011;
        public static final int notification_small_icon_size_as_large = 0x7f030012;
        public static final int notification_subtext_size = 0x7f030013;
        public static final int notification_top_pad = 0x7f030014;
        public static final int notification_top_pad_large_text = 0x7f030015;
    }

    public static final class drawable {
        public static final int app_icon_android = 0x7f040001;
        public static final int badge_achievement_completed = 0x7f040002;
        public static final int badge_achievement_locked = 0x7f040003;
        public static final int bottom_nav_achievements = 0x7f040004;
        public static final int bottom_nav_history = 0x7f040005;
        public static final int bottom_nav_home = 0x7f040006;
        public static final int bottom_nav_panel = 0x7f040007;
        public static final int button_claim_achievement_reward = 0x7f040008;
        public static final int button_claim_daily_reward = 0x7f040009;
        public static final int button_collect_feathers = 0x7f04000a;
        public static final int button_continue_600_feathers = 0x7f04000b;
        public static final int button_dash = 0x7f04000c;
        public static final int button_play = 0x7f04000d;
        public static final int button_privacy_policy = 0x7f04000e;
        public static final int button_quit = 0x7f04000f;
        public static final int button_rate = 0x7f040010;
        public static final int button_share = 0x7f040011;
        public static final int button_start_road = 0x7f040012;
        public static final int common_google_signin_btn_icon_dark = 0x7f040014;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f040015;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f040016;
        public static final int common_google_signin_btn_icon_disabled = 0x7f040018;
        public static final int common_google_signin_btn_icon_light = 0x7f040019;
        public static final int common_google_signin_btn_icon_light_focused = 0x7f04001a;
        public static final int common_google_signin_btn_icon_light_normal = 0x7f04001b;
        public static final int common_google_signin_btn_text_dark = 0x7f04001d;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f04001e;
        public static final int common_google_signin_btn_text_dark_normal = 0x7f04001f;
        public static final int common_google_signin_btn_text_disabled = 0x7f040021;
        public static final int common_google_signin_btn_text_light = 0x7f040022;
        public static final int common_google_signin_btn_text_light_focused = 0x7f040023;
        public static final int common_google_signin_btn_text_light_normal = 0x7f040024;
        public static final int difficulty_easy = 0x7f040026;
        public static final int difficulty_hard = 0x7f040027;
        public static final int difficulty_normal = 0x7f040028;
        public static final int feather_dash_logo = 0x7f040029;
        public static final int gameplay_background_horizontal_road = 0x7f04002a;
        public static final int golden_feather_currency_icon = 0x7f04002b;
        public static final int home_background_countryside = 0x7f04002e;
        public static final int ic_launcher_background = 0x7f040035;
        public static final int ic_notification_feather = 0x7f040037;
        public static final int ic_notification_flame_large = 0x7f040038;
        public static final int icon_back = 0x7f040039;
        public static final int icon_close = 0x7f04003a;
        public static final int icon_pause = 0x7f04003b;
        public static final int icon_restart = 0x7f04003c;
        public static final int icon_resume = 0x7f04003d;
        public static final int icon_settings_gear = 0x7f04003e;
        public static final int notification_action_background = 0x7f04003f;
        public static final int notification_bg = 0x7f040040;
        public static final int notification_bg_low = 0x7f040041;
        public static final int notification_icon_background = 0x7f040046;
        public static final int notification_template_icon_bg = 0x7f040048;
        public static final int notification_template_icon_low_bg = 0x7f040049;
        public static final int notification_tile_bg = 0x7f04004a;
        public static final int panel_large = 0x7f040050;
        public static final int panel_medium = 0x7f040051;
        public static final int panel_small = 0x7f040052;
        public static final int rooster_runner = 0x7f040053;
        public static final int startup_bg_loading_landscape = 0x7f040054;
        public static final int startup_bg_loading_portrait = 0x7f040055;
        public static final int startup_bg_no_internet_landscape = 0x7f040056;
        public static final int startup_bg_no_internet_portrait = 0x7f040057;
        public static final int startup_bg_notification_landscape = 0x7f040058;
        public static final int startup_bg_notification_portrait = 0x7f040059;
        public static final int startup_button_blank = 0x7f04005a;
        public static final int startup_loading_word = 0x7f04005b;
        public static final int startup_no_internet_panel = 0x7f04005c;
        public static final int title_achievements = 0x7f04005d;
        public static final int title_fail = 0x7f04005e;
        public static final int title_history = 0x7f04005f;
        public static final int title_paused = 0x7f040060;
        public static final int title_privacy_policy = 0x7f040061;
        public static final int title_settings = 0x7f040062;
        public static final int title_victory = 0x7f040063;
        public static final int toggle_music_off = 0x7f040064;
        public static final int toggle_music_on = 0x7f040065;
        public static final int toggle_sound_off = 0x7f040066;
        public static final int toggle_sound_on = 0x7f040067;
        public static final int toggle_vibration_off = 0x7f040068;
        public static final int toggle_vibration_on = 0x7f040069;
        public static final int vehicle_compact_car = 0x7f04006a;
        public static final int vehicle_motorcycle = 0x7f04006b;
        public static final int vehicle_tractor = 0x7f04006c;
        public static final int vehicle_truck = 0x7f04006d;
        public static final int vehicle_van = 0x7f04006e;
    }

    public static final class font {
        public static final int brlnsdb = 0x7f050000;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f060000;
        public static final int accessibility_custom_action_0 = 0x7f060001;
        public static final int accessibility_custom_action_1 = 0x7f060002;
        public static final int accessibility_custom_action_10 = 0x7f060003;
        public static final int accessibility_custom_action_11 = 0x7f060004;
        public static final int accessibility_custom_action_12 = 0x7f060005;
        public static final int accessibility_custom_action_13 = 0x7f060006;
        public static final int accessibility_custom_action_14 = 0x7f060007;
        public static final int accessibility_custom_action_15 = 0x7f060008;
        public static final int accessibility_custom_action_16 = 0x7f060009;
        public static final int accessibility_custom_action_17 = 0x7f06000a;
        public static final int accessibility_custom_action_18 = 0x7f06000b;
        public static final int accessibility_custom_action_19 = 0x7f06000c;
        public static final int accessibility_custom_action_2 = 0x7f06000d;
        public static final int accessibility_custom_action_20 = 0x7f06000e;
        public static final int accessibility_custom_action_21 = 0x7f06000f;
        public static final int accessibility_custom_action_22 = 0x7f060010;
        public static final int accessibility_custom_action_23 = 0x7f060011;
        public static final int accessibility_custom_action_24 = 0x7f060012;
        public static final int accessibility_custom_action_25 = 0x7f060013;
        public static final int accessibility_custom_action_26 = 0x7f060014;
        public static final int accessibility_custom_action_27 = 0x7f060015;
        public static final int accessibility_custom_action_28 = 0x7f060016;
        public static final int accessibility_custom_action_29 = 0x7f060017;
        public static final int accessibility_custom_action_3 = 0x7f060018;
        public static final int accessibility_custom_action_30 = 0x7f060019;
        public static final int accessibility_custom_action_31 = 0x7f06001a;
        public static final int accessibility_custom_action_4 = 0x7f06001b;
        public static final int accessibility_custom_action_5 = 0x7f06001c;
        public static final int accessibility_custom_action_6 = 0x7f06001d;
        public static final int accessibility_custom_action_7 = 0x7f06001e;
        public static final int accessibility_custom_action_8 = 0x7f06001f;
        public static final int accessibility_custom_action_9 = 0x7f060020;
        public static final int action_container = 0x7f060021;
        public static final int action_divider = 0x7f060022;
        public static final int action_image = 0x7f060023;
        public static final int action_text = 0x7f060024;
        public static final int actions = 0x7f060025;
        public static final int adjacent = 0x7f060026;
        public static final int adjust_height = 0x7f060027;
        public static final int adjust_width = 0x7f060028;
        public static final int always = 0x7f060029;
        public static final int alwaysAllow = 0x7f06002a;
        public static final int alwaysDisallow = 0x7f06002b;
        public static final int androidx_compose_ui_view_composition_context = 0x7f06002c;
        public static final int androidx_window_activity_scope = 0x7f06002d;
        public static final int async = 0x7f06002e;
        public static final int auto = 0x7f06002f;
        public static final int auto_clear_focus_behavior_tag = 0x7f060030;
        public static final int blocking = 0x7f060031;
        public static final int bottomToTop = 0x7f060032;
        public static final int chronometer = 0x7f060033;
        public static final int compose_prefetch_scheduler = 0x7f060034;
        public static final int compose_view_saveable_id_tag = 0x7f060035;
        public static final int consume_window_insets_tag = 0x7f060036;
        public static final int dark = 0x7f060037;
        public static final int dialog_button = 0x7f060038;
        public static final int draggable = 0x7f060039;
        public static final int edit_text_id = 0x7f06003a;
        public static final int fixed = 0x7f06003b;
        public static final int forever = 0x7f06003c;
        public static final int ghost_view = 0x7f06003d;
        public static final int ghost_view_holder = 0x7f06003e;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f06003f;
        public static final int hide_ime_id = 0x7f060040;
        public static final int hide_in_inspector_tag = 0x7f060041;
        public static final int icon = 0x7f060042;
        public static final int icon_group = 0x7f060043;
        public static final int icon_only = 0x7f060044;
        public static final int info = 0x7f060045;
        public static final int inspection_slot_table_set = 0x7f060046;
        public static final int is_pooling_container_tag = 0x7f060047;
        public static final int italic = 0x7f060048;
        public static final int jumpCut = 0x7f060049;
        public static final int light = 0x7f06004a;
        public static final int line1 = 0x7f06004b;
        public static final int line3 = 0x7f06004c;
        public static final int locale = 0x7f06004d;
        public static final int ltr = 0x7f06004e;
        public static final int never = 0x7f06004f;
        public static final int none = 0x7f060050;
        public static final int normal = 0x7f060051;
        public static final int notification_background = 0x7f060052;
        public static final int notification_main_column = 0x7f060053;
        public static final int notification_main_column_container = 0x7f060054;
        public static final int parent_matrix = 0x7f060055;
        public static final int pooling_container_listener_holder_tag = 0x7f060056;
        public static final int report_drawn = 0x7f060057;
        public static final int right_icon = 0x7f060058;
        public static final int right_side = 0x7f060059;
        public static final int rtl = 0x7f06005a;
        public static final int save_non_transition_alpha = 0x7f06005b;
        public static final int save_overlay_view = 0x7f06005c;
        public static final int standard = 0x7f06005d;
        public static final int systemDefault = 0x7f06005e;
        public static final int tag_accessibility_actions = 0x7f06005f;
        public static final int tag_accessibility_clickable_spans = 0x7f060060;
        public static final int tag_accessibility_heading = 0x7f060061;
        public static final int tag_accessibility_pane_title = 0x7f060062;
        public static final int tag_compat_insets_dispatch = 0x7f060063;
        public static final int tag_on_apply_window_listener = 0x7f060064;
        public static final int tag_on_receive_content_listener = 0x7f060065;
        public static final int tag_on_receive_content_mime_types = 0x7f060066;
        public static final int tag_screen_reader_focusable = 0x7f060067;
        public static final int tag_state_description = 0x7f060068;
        public static final int tag_system_bar_state_monitor = 0x7f060069;
        public static final int tag_transition_group = 0x7f06006a;
        public static final int tag_unhandled_key_event_manager = 0x7f06006b;
        public static final int tag_unhandled_key_listeners = 0x7f06006c;
        public static final int tag_window_insets_animation_callback = 0x7f06006d;
        public static final int text = 0x7f06006e;
        public static final int text2 = 0x7f06006f;
        public static final int time = 0x7f060070;
        public static final int title = 0x7f060071;
        public static final int topToBottom = 0x7f060072;
        public static final int transition_clip = 0x7f060073;
        public static final int transition_current_scene = 0x7f060074;
        public static final int transition_image_transform = 0x7f060075;
        public static final int transition_layout_save = 0x7f060076;
        public static final int transition_pause_alpha = 0x7f060077;
        public static final int transition_position = 0x7f060078;
        public static final int transition_scene_layoutid_cache = 0x7f060079;
        public static final int transition_transform = 0x7f06007a;
        public static final int view_tree_disjoint_parent = 0x7f06007b;
        public static final int view_tree_lifecycle_owner = 0x7f06007c;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f06007d;
        public static final int view_tree_saved_state_registry_owner = 0x7f06007e;
        public static final int view_tree_view_model_store_owner = 0x7f06007f;
        public static final int wide = 0x7f060080;
        public static final int wrapped_composition_tag = 0x7f060081;
    }

    public static final class integer {
        public static final int google_play_services_version = 0x7f070000;
        public static final int status_bar_notification_info_maxnum = 0x7f070002;
    }

    public static final class layout {
        public static final int custom_dialog = 0x7f080000;
        public static final int notification_action = 0x7f080003;
        public static final int notification_action_tombstone = 0x7f080004;
        public static final int notification_template_custom_big = 0x7f080005;
        public static final int notification_template_icon_group = 0x7f080006;
        public static final int notification_template_part_chronometer = 0x7f080007;
        public static final int notification_template_part_time = 0x7f080008;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f090000;
        public static final int ic_launcher_round = 0x7f090001;
    }

    public static final class raw {
        public static final int bg_music = 0x7f0a0000;
        public static final int sfx_fail = 0x7f0a0002;
        public static final int sfx_jump = 0x7f0a0003;
        public static final int sfx_victory = 0x7f0a0004;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f0b0002;
        public static final int app_name = 0x7f0b0003;
        public static final int common_google_play_services_enable_button = 0x7f0b000d;
        public static final int common_google_play_services_enable_text = 0x7f0b000e;
        public static final int common_google_play_services_enable_title = 0x7f0b000f;
        public static final int common_google_play_services_install_button = 0x7f0b0010;
        public static final int common_google_play_services_install_text = 0x7f0b0011;
        public static final int common_google_play_services_install_title = 0x7f0b0012;
        public static final int common_google_play_services_notification_channel_name = 0x7f0b0013;
        public static final int common_google_play_services_notification_ticker = 0x7f0b0014;
        public static final int common_google_play_services_unknown_issue = 0x7f0b0015;
        public static final int common_google_play_services_unsupported_text = 0x7f0b0016;
        public static final int common_google_play_services_update_button = 0x7f0b0017;
        public static final int common_google_play_services_update_text = 0x7f0b0018;
        public static final int common_google_play_services_update_title = 0x7f0b0019;
        public static final int common_google_play_services_updating_text = 0x7f0b001a;
        public static final int common_google_play_services_wear_update_text = 0x7f0b001b;
        public static final int common_open_on_phone = 0x7f0b001c;
        public static final int common_signin_button_text = 0x7f0b001d;
        public static final int common_signin_button_text_long = 0x7f0b001e;
        public static final int default_notification_channel_id = 0x7f0b0020;
        public static final int fcm_fallback_notification_channel_label = 0x7f0b0023;
        public static final int gcm_defaultSenderId = 0x7f0b0024;
        public static final int google_api_key = 0x7f0b0025;
        public static final int google_app_id = 0x7f0b0026;
        public static final int google_storage_bucket = 0x7f0b0028;
        public static final int in_progress = 0x7f0b0029;
        public static final int indeterminate = 0x7f0b002a;
        public static final int not_selected = 0x7f0b006e;
        public static final int project_id = 0x7f0b006f;
        public static final int selected = 0x7f0b0072;
        public static final int state_empty = 0x7f0b0074;
        public static final int status_bar_notification_info_overflow = 0x7f0b0077;
        public static final int template_percent = 0x7f0b007a;
    }

    public static final class style {
        public static final int TextAppearance_Compat_Notification = 0x7f0c0004;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0c0005;
        public static final int TextAppearance_Compat_Notification_Line2 = 0x7f0c0006;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0c0007;
        public static final int TextAppearance_Compat_Notification_Title = 0x7f0c0008;
        public static final int Theme_FeatherDash = 0x7f0c0009;
        public static final int Theme_PlayCore_Transparent = 0x7f0c000a;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0c000b;
        public static final int Widget_Compat_NotificationActionText = 0x7f0c000c;
    }

    public static final class xml {
        public static final int appsflyer_backup_rules = 0x7f0e0000;
        public static final int appsflyer_data_extraction_rules = 0x7f0e0001;
        public static final int backup_rules = 0x7f0e0002;
        public static final int data_extraction_rules = 0x7f0e0003;
        public static final int file_paths = 0x7f0e0004;
        public static final int splits0 = 0x7f0e0005;
    }
}
