package com.vungle.ads.internal.model;

import com.ironsource.C4572od;
import java.util.List;
import java.util.Map;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.ArrayListSerializer;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LinkedHashMapSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.StringSerializer;

/* loaded from: classes7.dex */
public final class v1 implements GeneratedSerializer {

    /* renamed from: a, reason: collision with root package name */
    public static final v1 f12021a;
    public static final /* synthetic */ PluginGeneratedSerialDescriptor b;

    static {
        v1 v1Var = new v1();
        f12021a = v1Var;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.vungle.ads.internal.model.ConfigPayload", v1Var, 20);
        pluginGeneratedSerialDescriptor.addElement("reuse_assets", true);
        pluginGeneratedSerialDescriptor.addElement("config", true);
        pluginGeneratedSerialDescriptor.addElement("endpoints", true);
        pluginGeneratedSerialDescriptor.addElement("log_metrics", true);
        pluginGeneratedSerialDescriptor.addElement(C4572od.c, true);
        pluginGeneratedSerialDescriptor.addElement("user", true);
        pluginGeneratedSerialDescriptor.addElement("config_extension", true);
        pluginGeneratedSerialDescriptor.addElement("disable_ad_id", true);
        pluginGeneratedSerialDescriptor.addElement("ri_enabled", true);
        pluginGeneratedSerialDescriptor.addElement("session_timeout", true);
        pluginGeneratedSerialDescriptor.addElement("wait_for_connectivity_for_tpat", true);
        pluginGeneratedSerialDescriptor.addElement("sdk_session_timeout", true);
        pluginGeneratedSerialDescriptor.addElement("signals_disabled", true);
        pluginGeneratedSerialDescriptor.addElement("fpd_enabled", true);
        pluginGeneratedSerialDescriptor.addElement("rta_debugging", true);
        pluginGeneratedSerialDescriptor.addElement("config_last_validated_ts", true);
        pluginGeneratedSerialDescriptor.addElement("auto_redirect", true);
        pluginGeneratedSerialDescriptor.addElement("enable_ot", true);
        pluginGeneratedSerialDescriptor.addElement("prewarm_webview", true);
        pluginGeneratedSerialDescriptor.addElement("vm_templates", true);
        b = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer[] childSerializers() {
        return new KSerializer[]{BuiltinSerializersKt.getNullable(z1.f12032a), BuiltinSerializersKt.getNullable(d2.f11963a), BuiltinSerializersKt.getNullable(g2.f11972a), BuiltinSerializersKt.getNullable(q2.f12006a), BuiltinSerializersKt.getNullable(new ArrayListSerializer(h3.f11975a)), BuiltinSerializersKt.getNullable(t2.f12016a), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(w1.f12024a), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(new LinkedHashMapSerializer(StringSerializer.INSTANCE, IntSerializer.INSTANCE))};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    public final Object deserialize(Decoder decoder) {
        Object obj;
        Object obj2;
        Object obj3;
        Object obj4;
        Object obj5;
        Object obj6;
        Object obj7;
        Object obj8;
        Object obj9;
        Object obj10;
        Object obj11;
        Object obj12;
        Object obj13;
        Object obj14;
        Object obj15;
        Object obj16;
        Object obj17;
        int i;
        Object obj18;
        Object obj19;
        Object obj20;
        Object obj21;
        Object obj22;
        Object obj23;
        Object obj24;
        Object obj25;
        Object obj26;
        Object obj27;
        Object obj28;
        int i2;
        Object obj29;
        Object obj30;
        int i3;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = b;
        CompositeDecoder beginStructure = decoder.beginStructure(pluginGeneratedSerialDescriptor);
        char c = '\n';
        Object obj31 = null;
        if (beginStructure.decodeSequentially()) {
            Object decodeNullableSerializableElement = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 0, z1.f12032a, null);
            obj19 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 1, d2.f11963a, null);
            obj14 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 2, g2.f11972a, null);
            Object decodeNullableSerializableElement2 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 3, q2.f12006a, null);
            Object decodeNullableSerializableElement3 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 4, new ArrayListSerializer(h3.f11975a), null);
            obj15 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 5, t2.f12016a, null);
            obj16 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 6, StringSerializer.INSTANCE, null);
            obj17 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 7, BooleanSerializer.INSTANCE, null);
            obj12 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 8, BooleanSerializer.INSTANCE, null);
            obj18 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 9, IntSerializer.INSTANCE, null);
            obj13 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 10, BooleanSerializer.INSTANCE, null);
            obj2 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 11, IntSerializer.INSTANCE, null);
            Object decodeNullableSerializableElement4 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 12, BooleanSerializer.INSTANCE, null);
            Object decodeNullableSerializableElement5 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 13, BooleanSerializer.INSTANCE, null);
            Object decodeNullableSerializableElement6 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 14, BooleanSerializer.INSTANCE, null);
            obj8 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 15, LongSerializer.INSTANCE, null);
            obj9 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 16, w1.f12024a, null);
            obj10 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 17, BooleanSerializer.INSTANCE, null);
            obj11 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 18, BooleanSerializer.INSTANCE, null);
            obj20 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 19, new LinkedHashMapSerializer(StringSerializer.INSTANCE, IntSerializer.INSTANCE), null);
            obj6 = decodeNullableSerializableElement2;
            obj5 = decodeNullableSerializableElement3;
            i = 1048575;
            obj4 = decodeNullableSerializableElement6;
            obj = decodeNullableSerializableElement5;
            obj3 = decodeNullableSerializableElement4;
            obj7 = decodeNullableSerializableElement;
        } else {
            int i4 = 19;
            boolean z = true;
            int i5 = 0;
            Object obj32 = null;
            obj = null;
            Object obj33 = null;
            Object obj34 = null;
            Object obj35 = null;
            Object obj36 = null;
            Object obj37 = null;
            Object obj38 = null;
            obj2 = null;
            obj3 = null;
            Object obj39 = null;
            Object obj40 = null;
            Object obj41 = null;
            Object obj42 = null;
            Object obj43 = null;
            Object obj44 = null;
            Object obj45 = null;
            Object obj46 = null;
            Object obj47 = null;
            while (z) {
                int decodeElementIndex = beginStructure.decodeElementIndex(pluginGeneratedSerialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        z = false;
                        obj32 = obj32;
                        i4 = 19;
                        c = '\n';
                    case 0:
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj47 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 0, z1.f12032a, obj47);
                        obj32 = obj32;
                        obj33 = obj33;
                        obj28 = obj46;
                        i2 = 1;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 1:
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj32 = obj32;
                        obj33 = obj33;
                        obj28 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 1, d2.f11963a, obj46);
                        i2 = 2;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 2:
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 2, g2.f11972a, obj45);
                        obj32 = obj32;
                        obj28 = obj46;
                        obj33 = obj33;
                        i2 = 4;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 3:
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 3, q2.f12006a, obj44);
                        obj32 = obj32;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj33 = obj33;
                        i2 = 8;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 4:
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 4, new ArrayListSerializer(h3.f11975a), obj43);
                        obj32 = obj32;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj33 = obj33;
                        i2 = 16;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 5:
                        obj29 = obj33;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 5, t2.f12016a, obj42);
                        i2 = 32;
                        obj32 = obj32;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj33 = obj29;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 6:
                        obj29 = obj33;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 6, StringSerializer.INSTANCE, obj41);
                        i2 = 64;
                        obj32 = obj32;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj33 = obj29;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 7:
                        obj29 = obj33;
                        obj21 = obj39;
                        obj22 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 7, BooleanSerializer.INSTANCE, obj40);
                        i2 = 128;
                        obj32 = obj32;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj33 = obj29;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 8:
                        obj30 = obj33;
                        i2 = 256;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj21 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 8, BooleanSerializer.INSTANCE, obj39);
                        obj33 = obj30;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 9:
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj33 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 9, IntSerializer.INSTANCE, obj33);
                        i2 = 512;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 10:
                        obj30 = obj33;
                        i2 = 1024;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj38 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 10, BooleanSerializer.INSTANCE, obj38);
                        obj33 = obj30;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 11:
                        obj30 = obj33;
                        i2 = 2048;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj2 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 11, IntSerializer.INSTANCE, obj2);
                        obj33 = obj30;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 12:
                        obj30 = obj33;
                        i2 = 4096;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj3 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 12, BooleanSerializer.INSTANCE, obj3);
                        obj33 = obj30;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 13:
                        obj29 = obj33;
                        obj = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 13, BooleanSerializer.INSTANCE, obj);
                        i3 = 8192;
                        i2 = i3;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj33 = obj29;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 14:
                        obj29 = obj33;
                        obj32 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 14, BooleanSerializer.INSTANCE, obj32);
                        i3 = 16384;
                        i2 = i3;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj33 = obj29;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 15:
                        obj30 = obj33;
                        i2 = 32768;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj34 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 15, LongSerializer.INSTANCE, obj34);
                        obj33 = obj30;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 16:
                        obj30 = obj33;
                        i2 = 65536;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj35 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 16, w1.f12024a, obj35);
                        obj33 = obj30;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 17:
                        obj30 = obj33;
                        i2 = 131072;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj36 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 17, BooleanSerializer.INSTANCE, obj36);
                        obj33 = obj30;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 18:
                        obj30 = obj33;
                        i2 = 262144;
                        obj21 = obj39;
                        obj22 = obj40;
                        obj23 = obj41;
                        obj24 = obj42;
                        obj25 = obj43;
                        obj26 = obj44;
                        obj27 = obj45;
                        obj28 = obj46;
                        obj37 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, 18, BooleanSerializer.INSTANCE, obj37);
                        obj33 = obj30;
                        i5 |= i2;
                        obj39 = obj21;
                        obj45 = obj27;
                        obj44 = obj26;
                        obj43 = obj25;
                        obj42 = obj24;
                        obj41 = obj23;
                        obj40 = obj22;
                        obj46 = obj28;
                        i4 = 19;
                        c = '\n';
                    case 19:
                        obj31 = beginStructure.decodeNullableSerializableElement(pluginGeneratedSerialDescriptor, i4, new LinkedHashMapSerializer(StringSerializer.INSTANCE, IntSerializer.INSTANCE), obj31);
                        i5 |= 524288;
                        obj33 = obj33;
                        c = '\n';
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
            }
            obj4 = obj32;
            Object obj48 = obj33;
            obj5 = obj43;
            obj6 = obj44;
            obj7 = obj47;
            obj8 = obj34;
            obj9 = obj35;
            obj10 = obj36;
            obj11 = obj37;
            obj12 = obj39;
            obj13 = obj38;
            obj14 = obj45;
            obj15 = obj42;
            obj16 = obj41;
            obj17 = obj40;
            i = i5;
            obj18 = obj48;
            obj19 = obj46;
            obj20 = obj31;
        }
        beginStructure.endStructure(pluginGeneratedSerialDescriptor);
        return new w2(i, (b2) obj7, (f2) obj19, (i2) obj14, (s2) obj6, (List) obj5, (v2) obj15, (String) obj16, (Boolean) obj17, (Boolean) obj12, (Integer) obj18, (Boolean) obj13, (Integer) obj2, (Boolean) obj3, (Boolean) obj, (Boolean) obj4, (Long) obj8, (y1) obj9, (Boolean) obj10, (Boolean) obj11, (Map) obj20);
    }

    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return b;
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(Encoder encoder, Object obj) {
        w2 value = (w2) obj;
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = b;
        CompositeEncoder beginStructure = encoder.beginStructure(pluginGeneratedSerialDescriptor);
        w2.a(value, beginStructure, pluginGeneratedSerialDescriptor);
        beginStructure.endStructure(pluginGeneratedSerialDescriptor);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}
