package com.google.android.datatransport;

/* compiled from: r8-map-id-548aee5da8eff46005463ebe9e9e6d0246428ebf3153b8af4dadfbd57572a0a1 */
/* loaded from: classes.dex */
public abstract class WinterFlowCompilerUserManager {
    public static final long WinterFlowArrayHelper;
    public static final long WinterFlowArrayNetwork;
    public static final long WinterFlowBackendCacheManager;
    public static final long WinterFlowBandwidthObject;
    public static final long WinterFlowBatchUI;
    public static final long WinterFlowCacheManagerAgent;
    public static final long WinterFlowCacheManagerListener;
    public static final long WinterFlowCacheTool;
    public static final long WinterFlowCloudMicroservice;
    public static final long WinterFlowCompilerHandler;
    public static final long WinterFlowCompilerVariable;
    public static final long WinterFlowConcurrencyThread;
    public static final long WinterFlowConfiguration;
    public static final long WinterFlowConfigurationSubsystem;
    public static final long WinterFlowConsumerUserManager;
    public static final long WinterFlowEventEmitterController;
    public static final long WinterFlowFrontendBackend;
    public static final long WinterFlowHookDataSource;
    public static final long WinterFlowMapperProtocol;
    public static final long WinterFlowOrchestrationSubsystem;
    public static final long WinterFlowPackageIDE;
    public static final long WinterFlowProxyStructure;
    public static final long WinterFlowQueueService;
    public static final long WinterFlowResolverController;
    public static final long WinterFlowResponseEngine;
    public static final long WinterFlowRouterAdapter;
    public static final long WinterFlowRouterRouter;
    public static final long WinterFlowRouterStructure;
    public static final long WinterFlowSerializerStructure;
    public static final long WinterFlowServerProtocol;
    public static final long WinterFlowServiceUtility;
    public static final long WinterFlowSingletonPlatform;
    public static final long WinterFlowSoftwareEngine;
    public static final long WinterFlowSoftwareProtocol;
    public static final long WinterFlowStrategyTool;
    public static final long WinterFlowSyntax;
    public static final long WinterFlowSyntaxSubsystem;
    public static final long WinterFlowTestingNode;
    public static final long WinterFlowThreadListener;
    public static final long WinterFlowTransactionAgent;
    public static final long WinterFlowTransactionManagerStrategy;
    public static final long WinterFlowUIMiddleware;
    public static final long WinterFlowUnitTestResponse;
    public static final long WinterFlowUserManagerUserManager;
    public static final long WinterFlowValidatorHandler;
    public static final long WinterFlowVariableBandwidth;
    public static final long WinterFlowVariableVersionControl;

    static {
        long j = WinterFlowDatabaseEncryption.WinterFlowResolverController;
        WinterFlowRouterStructure = j;
        WinterFlowHookDataSource = WinterFlowDatabaseEncryption.WinterFlowVariableVersionControl;
        WinterFlowCacheManagerAgent = WinterFlowDatabaseEncryption.WinterFlowUnitTestResponse;
        WinterFlowArrayNetwork = WinterFlowDatabaseEncryption.WinterFlowSerializerStructure;
        long j2 = WinterFlowDatabaseEncryption.WinterFlowUserManagerUserManager;
        WinterFlowVariableVersionControl = j2;
        WinterFlowTransactionManagerStrategy = WinterFlowDatabaseEncryption.WinterFlowThreadListener;
        long j3 = WinterFlowDatabaseEncryption.WinterFlowSyntax;
        WinterFlowUnitTestResponse = j3;
        WinterFlowRouterRouter = WinterFlowDatabaseEncryption.WinterFlowHookDataSource;
        WinterFlowSyntax = WinterFlowDatabaseEncryption.WinterFlowRouterStructure;
        WinterFlowResponseEngine = WinterFlowDatabaseEncryption.WinterFlowStrategyTool;
        long j4 = WinterFlowDatabaseEncryption.WinterFlowConfigurationSubsystem;
        WinterFlowTransactionAgent = j4;
        WinterFlowServerProtocol = j4;
        WinterFlowThreadListener = WinterFlowDatabaseEncryption.WinterFlowPackageIDE;
        WinterFlowServiceUtility = WinterFlowDatabaseEncryption.WinterFlowTestingNode;
        long j5 = WinterFlowDatabaseEncryption.WinterFlowSyntaxSubsystem;
        WinterFlowBandwidthObject = j5;
        WinterFlowOrchestrationSubsystem = j5;
        WinterFlowConcurrencyThread = WinterFlowDatabaseEncryption.WinterFlowFrontendBackend;
        WinterFlowSingletonPlatform = j3;
        WinterFlowVariableBandwidth = WinterFlowDatabaseEncryption.WinterFlowConsumerUserManager;
        WinterFlowBatchUI = WinterFlowDatabaseEncryption.WinterFlowProxyStructure;
        long j6 = WinterFlowDatabaseEncryption.WinterFlowCacheTool;
        WinterFlowRouterAdapter = j6;
        WinterFlowSerializerStructure = j6;
        WinterFlowMapperProtocol = WinterFlowDatabaseEncryption.WinterFlowValidatorHandler;
        WinterFlowResolverController = WinterFlowDatabaseEncryption.WinterFlowBackendCacheManager;
        WinterFlowConsumerUserManager = WinterFlowDatabaseEncryption.WinterFlowArrayHelper;
        WinterFlowBackendCacheManager = WinterFlowDatabaseEncryption.WinterFlowSoftwareProtocol;
        long j7 = WinterFlowDatabaseEncryption.WinterFlowSoftwareEngine;
        WinterFlowEventEmitterController = j7;
        WinterFlowArrayHelper = j7;
        WinterFlowCompilerVariable = j2;
        WinterFlowConfigurationSubsystem = WinterFlowDatabaseEncryption.WinterFlowRouterRouter;
        WinterFlowStrategyTool = WinterFlowDatabaseEncryption.WinterFlowCloudMicroservice;
        long j8 = WinterFlowDatabaseEncryption.WinterFlowQueueService;
        WinterFlowCacheManagerListener = j8;
        WinterFlowPackageIDE = j8;
        WinterFlowSoftwareProtocol = WinterFlowDatabaseEncryption.WinterFlowUIMiddleware;
        WinterFlowUserManagerUserManager = j;
        WinterFlowSoftwareEngine = j;
        WinterFlowSyntaxSubsystem = WinterFlowDatabaseEncryption.WinterFlowRouterAdapter;
        WinterFlowTestingNode = WinterFlowDatabaseEncryption.WinterFlowBatchUI;
        WinterFlowCompilerHandler = WinterFlowDatabaseEncryption.WinterFlowVariableBandwidth;
        WinterFlowFrontendBackend = WinterFlowDatabaseEncryption.WinterFlowMapperProtocol;
        WinterFlowCloudMicroservice = WinterFlowDatabaseEncryption.WinterFlowResponseEngine;
        WinterFlowUIMiddleware = WinterFlowDatabaseEncryption.WinterFlowSingletonPlatform;
        WinterFlowQueueService = WinterFlowDatabaseEncryption.WinterFlowCompilerVariable;
        WinterFlowCacheTool = WinterFlowDatabaseEncryption.WinterFlowCompilerDataSource;
        long j9 = WinterFlowDatabaseEncryption.WinterFlowOrchestrationConfiguration;
        WinterFlowProxyStructure = j9;
        WinterFlowConfiguration = j9;
        WinterFlowValidatorHandler = WinterFlowDatabaseEncryption.WinterFlowFrameworkTransaction;
    }
}
