package com.android.billingclient.api;

/* compiled from: com.android.billingclient:billing@@7.0.0 */
/* loaded from: classes2.dex */
final class zzce {
    static final com.android.billingclient.api.BillingResult zzA;
    static final com.android.billingclient.api.BillingResult zzB;
    static final com.android.billingclient.api.BillingResult zzC;
    static final com.android.billingclient.api.BillingResult zzD;
    static final com.android.billingclient.api.BillingResult zzE;
    static final com.android.billingclient.api.BillingResult zzF;
    public static final /* synthetic */ int zzG = 0;
    static final com.android.billingclient.api.BillingResult zza;
    static final com.android.billingclient.api.BillingResult zzb;
    static final com.android.billingclient.api.BillingResult zzc;
    static final com.android.billingclient.api.BillingResult zzd;
    static final com.android.billingclient.api.BillingResult zze;
    static final com.android.billingclient.api.BillingResult zzf;
    static final com.android.billingclient.api.BillingResult zzg;
    static final com.android.billingclient.api.BillingResult zzh;
    static final com.android.billingclient.api.BillingResult zzi;
    static final com.android.billingclient.api.BillingResult zzj;
    static final com.android.billingclient.api.BillingResult zzk;
    static final com.android.billingclient.api.BillingResult zzl;
    static final com.android.billingclient.api.BillingResult zzm;
    static final com.android.billingclient.api.BillingResult zzn;
    static final com.android.billingclient.api.BillingResult zzo;
    static final com.android.billingclient.api.BillingResult zzp;
    static final com.android.billingclient.api.BillingResult zzq;
    static final com.android.billingclient.api.BillingResult zzr;
    static final com.android.billingclient.api.BillingResult zzs;
    static final com.android.billingclient.api.BillingResult zzt;
    static final com.android.billingclient.api.BillingResult zzu;
    static final com.android.billingclient.api.BillingResult zzv;
    static final com.android.billingclient.api.BillingResult zzw;
    static final com.android.billingclient.api.BillingResult zzx;
    static final com.android.billingclient.api.BillingResult zzy;
    static final com.android.billingclient.api.BillingResult zzz;

    static {
        com.android.billingclient.api.BillingResult.Builder newBuilder = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder.setResponseCode(3);
        newBuilder.setDebugMessage("Google Play In-app Billing API version is less than 3");
        zza = newBuilder.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder2 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder2.setResponseCode(3);
        newBuilder2.setDebugMessage("Google Play In-app Billing API version is less than 9");
        zzb = newBuilder2.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder3 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder3.setResponseCode(3);
        newBuilder3.setDebugMessage("Billing service unavailable on device.");
        zzc = newBuilder3.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder4 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder4.setResponseCode(5);
        newBuilder4.setDebugMessage("Client is already in the process of connecting to billing service.");
        zzd = newBuilder4.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder5 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder5.setResponseCode(5);
        newBuilder5.setDebugMessage("The list of SKUs can't be empty.");
        zze = newBuilder5.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder6 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder6.setResponseCode(5);
        newBuilder6.setDebugMessage("SKU type can't be empty.");
        zzf = newBuilder6.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder7 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder7.setResponseCode(5);
        newBuilder7.setDebugMessage("Product type can't be empty.");
        zzg = newBuilder7.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder8 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder8.setResponseCode(-2);
        newBuilder8.setDebugMessage("Client does not support extra params.");
        zzh = newBuilder8.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder9 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder9.setResponseCode(5);
        newBuilder9.setDebugMessage("Invalid purchase token.");
        zzi = newBuilder9.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder10 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder10.setResponseCode(6);
        newBuilder10.setDebugMessage("An internal error occurred.");
        zzj = newBuilder10.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder11 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder11.setResponseCode(5);
        newBuilder11.setDebugMessage("SKU can't be null.");
        zzk = newBuilder11.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder12 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder12.setResponseCode(0);
        zzl = newBuilder12.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder13 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder13.setResponseCode(-1);
        newBuilder13.setDebugMessage("Service connection is disconnected.");
        zzm = newBuilder13.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder14 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder14.setResponseCode(2);
        newBuilder14.setDebugMessage("Timeout communicating with service.");
        zzn = newBuilder14.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder15 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder15.setResponseCode(-2);
        newBuilder15.setDebugMessage("Client does not support subscriptions.");
        zzo = newBuilder15.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder16 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder16.setResponseCode(-2);
        newBuilder16.setDebugMessage("Client does not support subscriptions update.");
        zzp = newBuilder16.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder17 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder17.setResponseCode(-2);
        newBuilder17.setDebugMessage("Client does not support get purchase history.");
        zzq = newBuilder17.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder18 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder18.setResponseCode(-2);
        newBuilder18.setDebugMessage("Client does not support price change confirmation.");
        zzr = newBuilder18.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder19 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder19.setResponseCode(-2);
        newBuilder19.setDebugMessage("Play Store version installed does not support cross selling products.");
        zzs = newBuilder19.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder20 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder20.setResponseCode(-2);
        newBuilder20.setDebugMessage("Client does not support multi-item purchases.");
        zzt = newBuilder20.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder21 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder21.setResponseCode(-2);
        newBuilder21.setDebugMessage("Client does not support offer_id_token.");
        zzu = newBuilder21.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder22 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder22.setResponseCode(-2);
        newBuilder22.setDebugMessage("Client does not support ProductDetails.");
        zzv = newBuilder22.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder23 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder23.setResponseCode(-2);
        newBuilder23.setDebugMessage("Client does not support in-app messages.");
        zzw = newBuilder23.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder24 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder24.setResponseCode(-2);
        newBuilder24.setDebugMessage("Client does not support user choice billing.");
        zzx = newBuilder24.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder25 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder25.setResponseCode(-2);
        newBuilder25.setDebugMessage("Play Store version installed does not support external offer.");
        zzy = newBuilder25.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder26 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder26.setResponseCode(5);
        newBuilder26.setDebugMessage("Unknown feature");
        zzz = newBuilder26.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder27 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder27.setResponseCode(-2);
        newBuilder27.setDebugMessage("Play Store version installed does not support get billing config.");
        zzA = newBuilder27.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder28 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder28.setResponseCode(-2);
        newBuilder28.setDebugMessage("Query product details with serialized docid is not supported.");
        zzB = newBuilder28.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder29 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder29.setResponseCode(4);
        newBuilder29.setDebugMessage("Item is unavailable for purchase.");
        zzC = newBuilder29.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder30 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder30.setResponseCode(-2);
        newBuilder30.setDebugMessage("Query product details with developer specified account is not supported.");
        zzD = newBuilder30.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder31 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder31.setResponseCode(-2);
        newBuilder31.setDebugMessage("Play Store version installed does not support alternative billing only.");
        zzE = newBuilder31.build();
        com.android.billingclient.api.BillingResult.Builder newBuilder32 = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder32.setResponseCode(5);
        newBuilder32.setDebugMessage("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        zzF = newBuilder32.build();
    }

    static com.android.billingclient.api.BillingResult zza(int i, java.lang.String str) {
        com.android.billingclient.api.BillingResult.Builder newBuilder = com.android.billingclient.api.BillingResult.newBuilder();
        newBuilder.setResponseCode(i);
        newBuilder.setDebugMessage(str);
        return newBuilder.build();
    }
}
