package com.fyber.inneractive.sdk.player.exoplayer2.extractor.mp4;

import com.coremedia.iso.boxes.ChunkOffset64BitBox;
import com.coremedia.iso.boxes.CompositionTimeToSample;
import com.coremedia.iso.boxes.EditBox;
import com.coremedia.iso.boxes.EditListBox;
import com.coremedia.iso.boxes.FileTypeBox;
import com.coremedia.iso.boxes.HandlerBox;
import com.coremedia.iso.boxes.MediaBox;
import com.coremedia.iso.boxes.MediaHeaderBox;
import com.coremedia.iso.boxes.MediaInformationBox;
import com.coremedia.iso.boxes.MetaBox;
import com.coremedia.iso.boxes.MovieBox;
import com.coremedia.iso.boxes.MovieHeaderBox;
import com.coremedia.iso.boxes.OriginalFormatBox;
import com.coremedia.iso.boxes.ProtectionSchemeInformationBox;
import com.coremedia.iso.boxes.SampleDescriptionBox;
import com.coremedia.iso.boxes.SampleSizeBox;
import com.coremedia.iso.boxes.SampleTableBox;
import com.coremedia.iso.boxes.SampleToChunkBox;
import com.coremedia.iso.boxes.SchemeInformationBox;
import com.coremedia.iso.boxes.SchemeTypeBox;
import com.coremedia.iso.boxes.StaticChunkOffsetBox;
import com.coremedia.iso.boxes.SyncSampleBox;
import com.coremedia.iso.boxes.TimeToSampleBox;
import com.coremedia.iso.boxes.TrackBox;
import com.coremedia.iso.boxes.TrackHeaderBox;
import com.coremedia.iso.boxes.UserDataBox;
import com.coremedia.iso.boxes.VideoMediaHeaderBox;
import com.coremedia.iso.boxes.apple.AppleItemListBox;
import com.coremedia.iso.boxes.apple.AppleWaveBox;
import com.coremedia.iso.boxes.fragment.MovieExtendsBox;
import com.coremedia.iso.boxes.fragment.MovieExtendsHeaderBox;
import com.coremedia.iso.boxes.fragment.MovieFragmentBox;
import com.coremedia.iso.boxes.fragment.TrackExtendsBox;
import com.coremedia.iso.boxes.fragment.TrackFragmentBaseMediaDecodeTimeBox;
import com.coremedia.iso.boxes.fragment.TrackFragmentBox;
import com.coremedia.iso.boxes.fragment.TrackFragmentHeaderBox;
import com.coremedia.iso.boxes.fragment.TrackRunBox;
import com.coremedia.iso.boxes.mdat.MediaDataBox;
import com.coremedia.iso.boxes.sampleentry.AudioSampleEntry;
import com.coremedia.iso.boxes.sampleentry.TextSampleEntry;
import com.coremedia.iso.boxes.sampleentry.VisualSampleEntry;
import com.fyber.inneractive.sdk.player.exoplayer2.util.z;
import com.googlecode.mp4parser.boxes.AC3SpecificBox;
import com.googlecode.mp4parser.boxes.DTSSpecificBox;
import com.googlecode.mp4parser.boxes.EC3SpecificBox;
import com.googlecode.mp4parser.boxes.apple.PixelAspectRationAtom;
import com.googlecode.mp4parser.boxes.dece.SampleEncryptionBox;
import com.googlecode.mp4parser.boxes.mp4.ESDescriptorBox;
import com.googlecode.mp4parser.boxes.mp4.samplegrouping.SampleGroupDescriptionBox;
import com.googlecode.mp4parser.boxes.mp4.samplegrouping.SampleToGroupBox;
import com.googlecode.mp4parser.boxes.threegpp26244.SegmentIndexBox;
import com.mp4parser.iso14496.part12.SampleAuxiliaryInformationOffsetsBox;
import com.mp4parser.iso14496.part12.SampleAuxiliaryInformationSizesBox;
import com.mp4parser.iso14496.part15.AvcConfigurationBox;
import com.mp4parser.iso14496.part15.HevcConfigurationBox;
import com.mp4parser.iso14496.part30.WebVTTSampleEntry;
import com.mp4parser.iso14496.part30.XMLSubtitleSampleEntry;
import com.mp4parser.iso23001.part7.ProtectionSystemSpecificHeaderBox;
import com.mp4parser.iso23001.part7.TrackEncryptionBox;
import com.mp4parser.iso23009.part1.EventMessageBox;

/* loaded from: classes12.dex */
public abstract class c {
    public static final int A0;
    public static final int B0;
    public static final int C0;
    public static final int D0;
    public static final int E0;
    public static final int F0;
    public static final int G0;
    public static final int H0;
    public static final int I0;
    public static final int J0;
    public static final int K0;
    public static final int L0;
    public static final int M0;
    public static final int N0;
    public static final int O0;
    public static final int l0;
    public static final int m0;
    public static final int n0;
    public static final int o0;
    public static final int p0;
    public static final int q0;
    public static final int r0;
    public static final int s0;
    public static final int t0;
    public static final int u0;
    public static final int v0;
    public static final int w0;
    public static final int x0;
    public static final int y0;
    public static final int z0;
    public final int a;
    public static final int b = z.a(FileTypeBox.TYPE);
    public static final int c = z.a(VisualSampleEntry.TYPE3);
    public static final int d = z.a(VisualSampleEntry.TYPE4);
    public static final int e = z.a(VisualSampleEntry.TYPE6);
    public static final int f = z.a(VisualSampleEntry.TYPE7);
    public static final int g = z.a(VisualSampleEntry.TYPE2);
    public static final int h = z.a("d263");
    public static final int i = z.a(MediaDataBox.TYPE);
    public static final int j = z.a(AudioSampleEntry.TYPE3);
    public static final int k = z.a(".mp3");
    public static final int l = z.a(AppleWaveBox.TYPE);
    public static final int m = z.a("lpcm");
    public static final int n = z.a("sowt");
    public static final int o = z.a(AudioSampleEntry.TYPE8);
    public static final int p = z.a(AC3SpecificBox.TYPE);
    public static final int q = z.a(AudioSampleEntry.TYPE9);
    public static final int r = z.a(EC3SpecificBox.TYPE);
    public static final int s = z.a("dtsc");
    public static final int t = z.a(AudioSampleEntry.TYPE12);
    public static final int u = z.a(AudioSampleEntry.TYPE11);
    public static final int v = z.a(AudioSampleEntry.TYPE13);
    public static final int w = z.a(DTSSpecificBox.TYPE);
    public static final int x = z.a(TrackFragmentBaseMediaDecodeTimeBox.TYPE);
    public static final int y = z.a(TrackFragmentHeaderBox.TYPE);
    public static final int z = z.a(TrackExtendsBox.TYPE);
    public static final int A = z.a(TrackRunBox.TYPE);
    public static final int B = z.a(SegmentIndexBox.TYPE);
    public static final int C = z.a(MovieBox.TYPE);
    public static final int D = z.a(MovieHeaderBox.TYPE);
    public static final int E = z.a(TrackBox.TYPE);
    public static final int F = z.a(MediaBox.TYPE);
    public static final int G = z.a(MediaInformationBox.TYPE);
    public static final int H = z.a(SampleTableBox.TYPE);
    public static final int I = z.a(AvcConfigurationBox.TYPE);
    public static final int J = z.a(HevcConfigurationBox.TYPE);
    public static final int K = z.a(ESDescriptorBox.TYPE);
    public static final int L = z.a(MovieFragmentBox.TYPE);
    public static final int M = z.a(TrackFragmentBox.TYPE);
    public static final int N = z.a(MovieExtendsBox.TYPE);
    public static final int O = z.a(MovieExtendsHeaderBox.TYPE);
    public static final int P = z.a(TrackHeaderBox.TYPE);
    public static final int Q = z.a(EditBox.TYPE);
    public static final int R = z.a(EditListBox.TYPE);
    public static final int S = z.a(MediaHeaderBox.TYPE);
    public static final int T = z.a(HandlerBox.TYPE);
    public static final int U = z.a(SampleDescriptionBox.TYPE);
    public static final int V = z.a(ProtectionSystemSpecificHeaderBox.TYPE);
    public static final int W = z.a(ProtectionSchemeInformationBox.TYPE);
    public static final int X = z.a(SchemeTypeBox.TYPE);
    public static final int Y = z.a(SchemeInformationBox.TYPE);
    public static final int Z = z.a(TrackEncryptionBox.TYPE);
    public static final int a0 = z.a(VisualSampleEntry.TYPE_ENCRYPTED);
    public static final int b0 = z.a(AudioSampleEntry.TYPE_ENCRYPTED);
    public static final int c0 = z.a(OriginalFormatBox.TYPE);
    public static final int d0 = z.a(SampleAuxiliaryInformationSizesBox.TYPE);
    public static final int e0 = z.a(SampleAuxiliaryInformationOffsetsBox.TYPE);
    public static final int f0 = z.a(SampleToGroupBox.TYPE);
    public static final int g0 = z.a(SampleGroupDescriptionBox.TYPE);
    public static final int h0 = z.a("uuid");
    public static final int i0 = z.a(SampleEncryptionBox.TYPE);
    public static final int j0 = z.a(PixelAspectRationAtom.TYPE);
    public static final int k0 = z.a("TTML");

    static {
        z.a(VideoMediaHeaderBox.TYPE);
        l0 = z.a(VisualSampleEntry.TYPE1);
        m0 = z.a(TimeToSampleBox.TYPE);
        n0 = z.a(SyncSampleBox.TYPE);
        o0 = z.a(CompositionTimeToSample.TYPE);
        p0 = z.a(SampleToChunkBox.TYPE);
        q0 = z.a(SampleSizeBox.TYPE);
        r0 = z.a("stz2");
        s0 = z.a(StaticChunkOffsetBox.TYPE);
        t0 = z.a(ChunkOffset64BitBox.TYPE);
        u0 = z.a(TextSampleEntry.TYPE1);
        v0 = z.a(WebVTTSampleEntry.TYPE);
        w0 = z.a(XMLSubtitleSampleEntry.TYPE);
        x0 = z.a("c608");
        y0 = z.a(AudioSampleEntry.TYPE1);
        z0 = z.a(AudioSampleEntry.TYPE2);
        A0 = z.a(UserDataBox.TYPE);
        B0 = z.a(MetaBox.TYPE);
        C0 = z.a(AppleItemListBox.TYPE);
        D0 = z.a("mean");
        E0 = z.a("name");
        F0 = z.a("data");
        G0 = z.a(EventMessageBox.TYPE);
        H0 = z.a("st3d");
        I0 = z.a("sv3d");
        J0 = z.a("proj");
        K0 = z.a("vp08");
        L0 = z.a("vp09");
        M0 = z.a("vpcC");
        N0 = z.a("camm");
        O0 = z.a("alac");
    }

    public c(int i2) {
        this.a = i2;
    }

    public static String a(int i2) {
        return "" + ((char) ((i2 >> 24) & 255)) + ((char) ((i2 >> 16) & 255)) + ((char) ((i2 >> 8) & 255)) + ((char) (i2 & 255));
    }

    public String toString() {
        return a(this.a);
    }
}
