package com.bytedance.sdk.openadsdk.jr;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.tz;
import com.bytedance.sdk.openadsdk.core.wh.kj;
import com.bytedance.sdk.openadsdk.core.wh.qf;
import com.bytedance.sdk.openadsdk.core.wh.wh;
import com.bytedance.sdk.openadsdk.utils.nac;
import com.bytedance.sdk.openadsdk.utils.rj;
import com.bytedance.sdk.openadsdk.utils.vh;
import com.mbridge.msdk.foundation.entity.CampaignEx;

/* compiled from: r8-map-id-820aebbf04e3f76f83859749e000e999e94bc7aa15ea120a09e9f3ed9aa09d5a */
/* loaded from: classes2.dex */
public class gm extends qf {
    public gm(Context context, AttributeSet attributeSet, int i) {
        super(context, attributeSet, i);
        pcc(context);
    }

    private void pcc(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        qf qfVar = new qf(context);
        qfVar.setId(nac.pzh);
        qfVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        qfVar.setBackgroundColor(0);
        qfVar.setGravity(17);
        addView(qfVar);
        View ooVar = new com.bytedance.sdk.openadsdk.core.wh.oo(context);
        ooVar.setId(nac.gmh);
        ooVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        qfVar.addView(ooVar);
        wh whVar = new wh(context);
        whVar.setId(nac.lc);
        int sf = rj.sf(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(sf, sf);
        layoutParams.addRule(13);
        whVar.setLayoutParams(layoutParams);
        whVar.setIndeterminateDrawable(vh.pcc(context, "tt_video_loading_progress_bar"));
        qfVar.addView(whVar);
        com.bytedance.sdk.openadsdk.core.wh.vj vjVar = new com.bytedance.sdk.openadsdk.core.wh.vj(context);
        vjVar.setId(nac.dp);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        vjVar.setLayoutParams(layoutParams2);
        vjVar.setGravity(1);
        vjVar.setOrientation(1);
        vjVar.setVisibility(8);
        qfVar.addView(vjVar);
        com.bytedance.sdk.openadsdk.core.wh.oo ooVar2 = new com.bytedance.sdk.openadsdk.core.wh.oo(context);
        ooVar2.setId(nac.esn);
        ooVar2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        ooVar2.setImageDrawable(vh.pcc(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        ooVar2.setScaleType(scaleType);
        vjVar.addView(ooVar2);
        kj kjVar = new kj(context);
        kjVar.setId(nac.bq);
        kjVar.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        kjVar.setText(tz.pcc(context, "tt_video_retry_des_txt"));
        kjVar.setTextColor(Color.parseColor("#999999"));
        vjVar.addView(kjVar);
        com.bytedance.sdk.openadsdk.core.wh.oo ooVar3 = new com.bytedance.sdk.openadsdk.core.wh.oo(context);
        ooVar3.setId(nac.bgf);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        ooVar3.setLayoutParams(layoutParams3);
        ooVar3.setScaleType(scaleType);
        ooVar3.setImageDrawable(vh.pcc(context, "tt_play_movebar_textpage"));
        ooVar3.setVisibility(8);
        addView(ooVar3);
        com.bytedance.sdk.openadsdk.core.wh.oo ooVar4 = new com.bytedance.sdk.openadsdk.core.wh.oo(context);
        ooVar4.setId(nac.gye);
        int sf2 = rj.sf(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(sf2, sf2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int sf3 = rj.sf(context, 7.0f);
        layoutParams4.setMarginEnd(sf3);
        layoutParams4.rightMargin = sf3;
        layoutParams4.topMargin = sf3;
        ooVar4.setLayoutParams(layoutParams4);
        ooVar4.setBackground(vh.pcc(context, "tt_detail_video_btn_bg"));
        ooVar4.setScaleType(scaleType);
        ooVar4.setImageDrawable(vh.pcc(context, "tt_close_move_detail"));
        addView(ooVar4);
        kj kjVar2 = new kj(context);
        kjVar2.setId(nac.xfm);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        kjVar2.setLayoutParams(layoutParams5);
        kjVar2.setBackground(vh.pcc(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        kjVar2.setEllipsize(truncateAt);
        kjVar2.setMaxLines(2);
        int sf4 = rj.sf(context, 15.0f);
        kjVar2.setPadding(sf4, rj.sf(context, 14.0f), sf4, 0);
        kjVar2.setSingleLine(false);
        kjVar2.setTextColor(-1);
        kjVar2.setTextSize(2, 17.0f);
        kjVar2.setVisibility(8);
        addView(kjVar2);
        qf qfVar2 = new qf(context);
        qfVar2.setId(nac.dt);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        qfVar2.setLayoutParams(layoutParams6);
        qfVar2.setBackground(vh.pcc(context, "tt_video_black_desc_gradient"));
        qfVar2.setGravity(16);
        qfVar2.setVisibility(8);
        addView(qfVar2);
        com.bytedance.sdk.openadsdk.core.wh.oo ooVar5 = new com.bytedance.sdk.openadsdk.core.wh.oo(context);
        int i = nac.hl;
        ooVar5.setId(i);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int sf5 = rj.sf(context, 12.0f);
        layoutParams7.leftMargin = sf5;
        layoutParams7.setMarginStart(sf5);
        ooVar5.setLayoutParams(layoutParams7);
        ooVar5.setScaleType(scaleType);
        ooVar5.setImageDrawable(vh.pcc(context, "tt_leftbackbutton_titlebar_photo_preview"));
        qfVar2.addView(ooVar5);
        kj kjVar3 = new kj(context);
        kjVar3.setId(nac.ct);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int sf6 = rj.sf(context, 16.0f);
        layoutParams8.leftMargin = sf6;
        layoutParams8.rightMargin = sf;
        layoutParams8.setMarginStart(sf6);
        layoutParams8.setMarginEnd(sf);
        layoutParams8.addRule(17, i);
        int i2 = nac.ywc;
        layoutParams8.addRule(0, i2);
        layoutParams8.addRule(1, i);
        layoutParams8.addRule(16, i2);
        kjVar3.setLayoutParams(layoutParams8);
        kjVar3.setEllipsize(truncateAt);
        kjVar3.setGravity(16);
        kjVar3.setMaxLines(1);
        kjVar3.setSingleLine(true);
        kjVar3.setTextColor(-1);
        kjVar3.setTextSize(2, 17.0f);
        qfVar2.addView(kjVar3);
        com.bytedance.sdk.openadsdk.core.wh.vj vjVar2 = new com.bytedance.sdk.openadsdk.core.wh.vj(context);
        vjVar2.setId(i2);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int sf7 = rj.sf(context, 14.0f);
        layoutParams9.rightMargin = sf7;
        layoutParams9.setMarginEnd(sf7);
        vjVar2.setLayoutParams(layoutParams9);
        vjVar2.setGravity(16);
        vjVar2.setOrientation(1);
        qfVar2.addView(vjVar2);
        kj kjVar4 = new kj(context);
        kjVar4.setId(nac.cz);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        kjVar4.setLayoutParams(layoutParams10);
        kjVar4.setGravity(16);
        kjVar4.setMaxLines(1);
        kjVar4.setSingleLine(true);
        kjVar4.setTextColor(-1);
        kjVar4.setTextSize(2, 12.0f);
        vjVar2.addView(kjVar4);
        com.bytedance.sdk.openadsdk.core.wh.vj vjVar3 = new com.bytedance.sdk.openadsdk.core.wh.vj(context);
        vjVar3.setId(nac.wjv);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, rj.sf(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        vjVar3.setLayoutParams(layoutParams11);
        vjVar3.setGravity(16);
        vjVar3.setOrientation(0);
        vjVar3.setVisibility(8);
        addView(vjVar3);
        kj kjVar5 = new kj(context);
        kjVar5.setId(nac.qxq);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = sf6;
        layoutParams12.rightMargin = sf5;
        layoutParams12.setMarginEnd(sf5);
        layoutParams12.setMarginStart(sf6);
        kjVar5.setLayoutParams(layoutParams12);
        kjVar5.setText(tz.pcc(context, "tt_00_00"));
        kjVar5.setTextColor(-1);
        kjVar5.setTextSize(2, 10.0f);
        vjVar3.addView(kjVar5);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(nac.oa);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, rj.sf(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(vh.pcc(context, "tt_seek_progress"));
        seekBar.setThumb(vh.pcc(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        vjVar3.addView(seekBar);
        kj kjVar6 = new kj(context);
        kjVar6.setId(nac.luz);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = sf5;
        layoutParams14.rightMargin = sf6;
        layoutParams14.setMarginEnd(sf6);
        layoutParams14.setMarginStart(sf5);
        kjVar6.setLayoutParams(layoutParams14);
        kjVar6.setText(tz.pcc(context, "tt_00_00"));
        kjVar6.setTextColor(-1);
        kjVar6.setTextSize(2, 10.0f);
        vjVar3.addView(kjVar6);
        com.bytedance.sdk.openadsdk.core.wh.oo ooVar6 = new com.bytedance.sdk.openadsdk.core.wh.oo(context);
        ooVar6.setId(nac.jkz);
        ooVar6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        ooVar6.setPadding(sf6, 0, sf6, 0);
        ooVar6.setScaleType(scaleType);
        ooVar6.setVisibility(8);
        ooVar6.setImageDrawable(tz.gm(context, "tt_enlarge_video"));
        vjVar3.addView(ooVar6);
        View sfVar = new sf(context);
        sfVar.setId(nac.ln);
        sfVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(sfVar);
        kj kjVar7 = new kj(context);
        kjVar7.setId(nac.ial);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = sf5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        kjVar7.setLayoutParams(layoutParams15);
        kjVar7.setBackgroundColor(Color.parseColor("#00000000"));
        kjVar7.setText(CampaignEx.JSON_NATIVE_VIDEO_CLOSE);
        kjVar7.setMinHeight(rj.sf(context, 44.0f));
        kjVar7.setCompoundDrawablesWithIntrinsicBounds(vh.pcc(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(kjVar7);
    }

    public gm(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public gm(Context context) {
        this(context, null);
    }
}
