package com.sofascore.model.newNetwork.topperformance.response;

import androidx.core.app.NotificationCompat;
import com.ironsource.U3;
import com.ironsource.mediationsdk.metadata.a;
import com.mbridge.msdk.playercommon.exoplayer2.C;
import com.mbridge.msdk.playercommon.exoplayer2.source.ExtractorMediaSource;
import defpackage.dy4;
import defpackage.iw8;
import defpackage.joa;
import defpackage.l98;
import defpackage.uf3;
import defpackage.uye;
import defpackage.wf3;
import defpackage.wx4;
import defpackage.yhk;
import defpackage.z8e;
import java.util.List;
import kotlin.Metadata;
import kotlin.Unit;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import org.jetbrains.annotations.NotNull;

/* compiled from: r8-map-id-820aebbf04e3f76f83859749e000e999e94bc7aa15ea120a09e9f3ed9aa09d5a */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/sofascore/model/newNetwork/topperformance/response/BaseballTopPlayersStatistics.$serializer", "Liw8;", "Lcom/sofascore/model/newNetwork/topperformance/response/BaseballTopPlayersStatistics;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", U3.i.X, "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/sofascore/model/newNetwork/topperformance/response/BaseballTopPlayersStatistics;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/sofascore/model/newNetwork/topperformance/response/BaseballTopPlayersStatistics;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "model_release"}, k = 1, mv = {2, 3, 0}, xi = 48)
@wx4
/* loaded from: classes5.dex */
public final /* synthetic */ class BaseballTopPlayersStatistics$$serializer implements iw8 {

    @NotNull
    public static final BaseballTopPlayersStatistics$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        BaseballTopPlayersStatistics$$serializer baseballTopPlayersStatistics$$serializer = new BaseballTopPlayersStatistics$$serializer();
        INSTANCE = baseballTopPlayersStatistics$$serializer;
        uye uyeVar = new uye("com.sofascore.model.newNetwork.topperformance.response.BaseballTopPlayersStatistics", baseballTopPlayersStatistics$$serializer, 27);
        uyeVar.j("battingAtBats", false);
        uyeVar.j("battingHits", false);
        uyeVar.j("battingHomeRuns", false);
        uyeVar.j("battingAvg", false);
        uyeVar.j("battingRuns", false);
        uyeVar.j("battingRbi", false);
        uyeVar.j("battingStolenBases", false);
        uyeVar.j("battingOnBasePercentage", false);
        uyeVar.j("battingSluggingPercentage", false);
        uyeVar.j("war", false);
        uyeVar.j("pitchingGamesPlayed", false);
        uyeVar.j("pitchingWins", false);
        uyeVar.j("pitchingLosses", false);
        uyeVar.j("pitchingSaves", false);
        uyeVar.j("pitchingInningsPitched", false);
        uyeVar.j("pitchingEarnedRunsAverage", false);
        uyeVar.j("pitchingStrikeOuts", false);
        uyeVar.j("pitchingQualityStarts", false);
        uyeVar.j("pitchingWhip", false);
        uyeVar.j("pitchingWar", false);
        uyeVar.j("pitchingFieldingIndependentPitching", false);
        uyeVar.j("pitchingOpponentBattingAvg", false);
        uyeVar.j("fieldingPutOuts", false);
        uyeVar.j("fieldingAssists", false);
        uyeVar.j("fieldingTotalErrors", false);
        uyeVar.j("fieldingDoublePlays", false);
        uyeVar.j("fieldingChances", false);
        descriptor = uyeVar;
    }

    private BaseballTopPlayersStatistics$$serializer() {
    }

    @Override // defpackage.iw8
    @NotNull
    public final KSerializer[] childSerializers() {
        joa[] joaVarArr;
        joaVarArr = BaseballTopPlayersStatistics.$childSerializers;
        return new KSerializer[]{l98.W((KSerializer) joaVarArr[0].getValue()), l98.W((KSerializer) joaVarArr[1].getValue()), l98.W((KSerializer) joaVarArr[2].getValue()), l98.W((KSerializer) joaVarArr[3].getValue()), l98.W((KSerializer) joaVarArr[4].getValue()), l98.W((KSerializer) joaVarArr[5].getValue()), l98.W((KSerializer) joaVarArr[6].getValue()), l98.W((KSerializer) joaVarArr[7].getValue()), l98.W((KSerializer) joaVarArr[8].getValue()), l98.W((KSerializer) joaVarArr[9].getValue()), l98.W((KSerializer) joaVarArr[10].getValue()), l98.W((KSerializer) joaVarArr[11].getValue()), l98.W((KSerializer) joaVarArr[12].getValue()), l98.W((KSerializer) joaVarArr[13].getValue()), l98.W((KSerializer) joaVarArr[14].getValue()), l98.W((KSerializer) joaVarArr[15].getValue()), l98.W((KSerializer) joaVarArr[16].getValue()), l98.W((KSerializer) joaVarArr[17].getValue()), l98.W((KSerializer) joaVarArr[18].getValue()), l98.W((KSerializer) joaVarArr[19].getValue()), l98.W((KSerializer) joaVarArr[20].getValue()), l98.W((KSerializer) joaVarArr[21].getValue()), l98.W((KSerializer) joaVarArr[22].getValue()), l98.W((KSerializer) joaVarArr[23].getValue()), l98.W((KSerializer) joaVarArr[24].getValue()), l98.W((KSerializer) joaVarArr[25].getValue()), l98.W((KSerializer) joaVarArr[26].getValue())};
    }

    @Override // defpackage.dy4
    @NotNull
    public final BaseballTopPlayersStatistics deserialize(@NotNull Decoder decoder) {
        joa[] joaVarArr;
        List list;
        int i;
        List list2;
        List list3;
        List list4;
        List list5;
        List list6;
        List list7;
        List list8;
        List list9;
        List list10;
        List list11;
        List list12;
        List list13;
        List list14;
        List list15;
        List list16;
        int i2;
        List list17;
        int i3;
        decoder.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        uf3 b = decoder.b(serialDescriptor);
        joaVarArr = BaseballTopPlayersStatistics.$childSerializers;
        int i4 = 0;
        List list18 = null;
        List list19 = null;
        List list20 = null;
        List list21 = null;
        List list22 = null;
        List list23 = null;
        int i5 = 0;
        List list24 = null;
        List list25 = null;
        List list26 = null;
        List list27 = null;
        List list28 = null;
        List list29 = null;
        List list30 = null;
        int i6 = 1;
        List list31 = null;
        List list32 = null;
        List list33 = null;
        List list34 = null;
        List list35 = null;
        List list36 = null;
        List list37 = null;
        List list38 = null;
        List list39 = null;
        List list40 = null;
        List list41 = null;
        List list42 = null;
        List list43 = null;
        List list44 = null;
        while (i6 != 0) {
            int o = b.o(serialDescriptor);
            switch (o) {
                case -1:
                    List list45 = list18;
                    List list46 = list19;
                    List list47 = list31;
                    list = list20;
                    i = i4;
                    Unit unit = Unit.a;
                    list2 = list47;
                    list19 = list46;
                    list3 = list44;
                    list4 = list43;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    i6 = i;
                    list15 = list32;
                    list18 = list45;
                    list25 = list25;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 0:
                    list16 = list18;
                    List list48 = list19;
                    List list49 = list33;
                    List list50 = list31;
                    list = list20;
                    i = i4;
                    List list51 = (List) b.i(serialDescriptor, i, (dy4) joaVarArr[i4].getValue(), list50);
                    i5 |= 1;
                    Unit unit2 = Unit.a;
                    list15 = list32;
                    list19 = list48;
                    list25 = list25;
                    list3 = list44;
                    list4 = list43;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list49;
                    list2 = list51;
                    list18 = list16;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 1:
                    List list52 = list18;
                    List list53 = list19;
                    List list54 = list25;
                    List list55 = list33;
                    List list56 = (List) b.i(serialDescriptor, 1, (dy4) joaVarArr[1].getValue(), list32);
                    i5 |= 2;
                    Unit unit3 = Unit.a;
                    list15 = list56;
                    list19 = list53;
                    list18 = list52;
                    list25 = list54;
                    list3 = list44;
                    list4 = list43;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list55;
                    list2 = list31;
                    list = list20;
                    i = i4;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 2:
                    list16 = list18;
                    List list57 = list19;
                    List list58 = (List) b.i(serialDescriptor, 2, (dy4) joaVarArr[2].getValue(), list33);
                    i5 |= 4;
                    Unit unit4 = Unit.a;
                    list2 = list31;
                    list15 = list32;
                    list19 = list57;
                    list25 = list25;
                    list = list20;
                    list3 = list44;
                    i = i4;
                    list4 = list43;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list58;
                    list18 = list16;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 3:
                    list16 = list18;
                    List list59 = list19;
                    List list60 = (List) b.i(serialDescriptor, 3, (dy4) joaVarArr[3].getValue(), list34);
                    i5 |= 8;
                    Unit unit5 = Unit.a;
                    list2 = list31;
                    list14 = list33;
                    list19 = list59;
                    list25 = list25;
                    list = list20;
                    list15 = list32;
                    list3 = list44;
                    i = i4;
                    list4 = list43;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list60;
                    list18 = list16;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 4:
                    list16 = list18;
                    List list61 = list19;
                    List list62 = (List) b.i(serialDescriptor, 4, (dy4) joaVarArr[4].getValue(), list35);
                    i5 |= 16;
                    Unit unit6 = Unit.a;
                    list2 = list31;
                    list13 = list34;
                    list19 = list61;
                    list25 = list25;
                    list = list20;
                    list14 = list33;
                    list3 = list44;
                    i = i4;
                    list15 = list32;
                    list4 = list43;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list62;
                    list18 = list16;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 5:
                    list16 = list18;
                    List list63 = list19;
                    List list64 = (List) b.i(serialDescriptor, 5, (dy4) joaVarArr[5].getValue(), list36);
                    i5 |= 32;
                    Unit unit7 = Unit.a;
                    list2 = list31;
                    list12 = list35;
                    list19 = list63;
                    list25 = list25;
                    list = list20;
                    list13 = list34;
                    list3 = list44;
                    i = i4;
                    list14 = list33;
                    list4 = list43;
                    list15 = list32;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list64;
                    list18 = list16;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 6:
                    list16 = list18;
                    List list65 = list19;
                    List list66 = (List) b.i(serialDescriptor, 6, (dy4) joaVarArr[6].getValue(), list37);
                    i5 |= 64;
                    Unit unit8 = Unit.a;
                    list2 = list31;
                    list11 = list36;
                    list19 = list65;
                    list25 = list25;
                    list = list20;
                    list12 = list35;
                    list3 = list44;
                    i = i4;
                    list13 = list34;
                    list4 = list43;
                    list14 = list33;
                    list5 = list42;
                    list15 = list32;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list66;
                    list18 = list16;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 7:
                    list16 = list18;
                    List list67 = list19;
                    List list68 = (List) b.i(serialDescriptor, 7, (dy4) joaVarArr[7].getValue(), list38);
                    i5 |= 128;
                    Unit unit9 = Unit.a;
                    list2 = list31;
                    list10 = list37;
                    list19 = list67;
                    list25 = list25;
                    list = list20;
                    list11 = list36;
                    list3 = list44;
                    i = i4;
                    list12 = list35;
                    list4 = list43;
                    list13 = list34;
                    list5 = list42;
                    list14 = list33;
                    list6 = list41;
                    list15 = list32;
                    list7 = list40;
                    list8 = list39;
                    list9 = list68;
                    list18 = list16;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 8:
                    list16 = list18;
                    List list69 = list19;
                    List list70 = (List) b.i(serialDescriptor, 8, (dy4) joaVarArr[8].getValue(), list39);
                    i5 |= NotificationCompat.FLAG_LOCAL_ONLY;
                    Unit unit10 = Unit.a;
                    list2 = list31;
                    list9 = list38;
                    list19 = list69;
                    list25 = list25;
                    list = list20;
                    list10 = list37;
                    list3 = list44;
                    i = i4;
                    list11 = list36;
                    list4 = list43;
                    list12 = list35;
                    list5 = list42;
                    list13 = list34;
                    list6 = list41;
                    list14 = list33;
                    list7 = list40;
                    list8 = list70;
                    list15 = list32;
                    list18 = list16;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 9:
                    List list71 = list18;
                    List list72 = list19;
                    List list73 = (List) b.i(serialDescriptor, 9, (dy4) joaVarArr[9].getValue(), list40);
                    i5 |= 512;
                    Unit unit11 = Unit.a;
                    list2 = list31;
                    list8 = list39;
                    list19 = list72;
                    list25 = list25;
                    list = list20;
                    list9 = list38;
                    list3 = list44;
                    i = i4;
                    list10 = list37;
                    list4 = list43;
                    list11 = list36;
                    list5 = list42;
                    list12 = list35;
                    list6 = list41;
                    list7 = list73;
                    list13 = list34;
                    list18 = list71;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 10:
                    List list74 = list18;
                    List list75 = list19;
                    List list76 = (List) b.i(serialDescriptor, 10, (dy4) joaVarArr[10].getValue(), list41);
                    i5 |= 1024;
                    Unit unit12 = Unit.a;
                    List list77 = list42;
                    list6 = list76;
                    list19 = list75;
                    list3 = list44;
                    list4 = list43;
                    list5 = list77;
                    list2 = list31;
                    list7 = list40;
                    list18 = list74;
                    list25 = list25;
                    list = list20;
                    list8 = list39;
                    i = i4;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 11:
                    List list78 = list18;
                    List list79 = list19;
                    List list80 = (List) b.i(serialDescriptor, 11, (dy4) joaVarArr[11].getValue(), list42);
                    i5 |= a.o;
                    Unit unit13 = Unit.a;
                    list2 = list31;
                    list6 = list41;
                    list19 = list79;
                    list25 = list25;
                    list = list20;
                    list7 = list40;
                    list3 = list44;
                    i = i4;
                    list8 = list39;
                    list4 = list43;
                    list5 = list80;
                    list9 = list38;
                    list18 = list78;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 12:
                    List list81 = list18;
                    List list82 = list19;
                    List list83 = (List) b.i(serialDescriptor, 12, (dy4) joaVarArr[12].getValue(), list43);
                    i5 |= 4096;
                    Unit unit14 = Unit.a;
                    list2 = list31;
                    list5 = list42;
                    list19 = list82;
                    list25 = list25;
                    list = list20;
                    list6 = list41;
                    list3 = list44;
                    i = i4;
                    list4 = list83;
                    list7 = list40;
                    list18 = list81;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 13:
                    List list84 = list18;
                    List list85 = list19;
                    List list86 = (List) b.i(serialDescriptor, 13, (dy4) joaVarArr[13].getValue(), list44);
                    i5 |= 8192;
                    Unit unit15 = Unit.a;
                    list2 = list31;
                    list4 = list43;
                    list19 = list85;
                    list25 = list25;
                    list3 = list86;
                    list = list20;
                    list5 = list42;
                    list18 = list84;
                    i = i4;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 14:
                    List list87 = list18;
                    list25 = (List) b.i(serialDescriptor, 14, (dy4) joaVarArr[14].getValue(), list25);
                    i5 |= 16384;
                    Unit unit16 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list18 = list87;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 15:
                    i2 = i5;
                    list17 = list25;
                    list26 = (List) b.i(serialDescriptor, 15, (dy4) joaVarArr[15].getValue(), list26);
                    i3 = 32768;
                    i5 = i2 | i3;
                    Unit unit17 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 16:
                    i2 = i5;
                    list17 = list25;
                    list27 = (List) b.i(serialDescriptor, 16, (dy4) joaVarArr[16].getValue(), list27);
                    i3 = C.DEFAULT_BUFFER_SEGMENT_SIZE;
                    i5 = i2 | i3;
                    Unit unit172 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 17:
                    i2 = i5;
                    list17 = list25;
                    list28 = (List) b.i(serialDescriptor, 17, (dy4) joaVarArr[17].getValue(), list28);
                    i3 = 131072;
                    i5 = i2 | i3;
                    Unit unit1722 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 18:
                    i2 = i5;
                    list17 = list25;
                    list29 = (List) b.i(serialDescriptor, 18, (dy4) joaVarArr[18].getValue(), list29);
                    i3 = 262144;
                    i5 = i2 | i3;
                    Unit unit17222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 19:
                    i2 = i5;
                    list17 = list25;
                    list30 = (List) b.i(serialDescriptor, 19, (dy4) joaVarArr[19].getValue(), list30);
                    i3 = 524288;
                    i5 = i2 | i3;
                    Unit unit172222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 20:
                    i2 = i5;
                    list17 = list25;
                    list23 = (List) b.i(serialDescriptor, 20, (dy4) joaVarArr[20].getValue(), list23);
                    i3 = ExtractorMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES;
                    i5 = i2 | i3;
                    Unit unit1722222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 21:
                    i2 = i5;
                    list17 = list25;
                    list21 = (List) b.i(serialDescriptor, 21, (dy4) joaVarArr[21].getValue(), list21);
                    i3 = 2097152;
                    i5 = i2 | i3;
                    Unit unit17222222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 22:
                    i2 = i5;
                    list17 = list25;
                    list20 = (List) b.i(serialDescriptor, 22, (dy4) joaVarArr[22].getValue(), list20);
                    i3 = 4194304;
                    i5 = i2 | i3;
                    Unit unit172222222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 23:
                    i2 = i5;
                    list17 = list25;
                    list19 = (List) b.i(serialDescriptor, 23, (dy4) joaVarArr[23].getValue(), list19);
                    i3 = 8388608;
                    i5 = i2 | i3;
                    Unit unit1722222222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 24:
                    i2 = i5;
                    list17 = list25;
                    list18 = (List) b.i(serialDescriptor, 24, (dy4) joaVarArr[24].getValue(), list18);
                    i3 = C.DEFAULT_MUXED_BUFFER_SIZE;
                    i5 = i2 | i3;
                    Unit unit17222222222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 25:
                    i2 = i5;
                    list17 = list25;
                    list22 = (List) b.i(serialDescriptor, 25, (dy4) joaVarArr[25].getValue(), list22);
                    i3 = 33554432;
                    i5 = i2 | i3;
                    Unit unit172222222222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                case 26:
                    i2 = i5;
                    list17 = list25;
                    list24 = (List) b.i(serialDescriptor, 26, (dy4) joaVarArr[26].getValue(), list24);
                    i3 = 67108864;
                    i5 = i2 | i3;
                    Unit unit1722222222222 = Unit.a;
                    list2 = list31;
                    list3 = list44;
                    list25 = list17;
                    list = list20;
                    list4 = list43;
                    i = i4;
                    list5 = list42;
                    list6 = list41;
                    list7 = list40;
                    list8 = list39;
                    list9 = list38;
                    list10 = list37;
                    list11 = list36;
                    list12 = list35;
                    list13 = list34;
                    list14 = list33;
                    list15 = list32;
                    i4 = i;
                    list20 = list;
                    list32 = list15;
                    list33 = list14;
                    list34 = list13;
                    list35 = list12;
                    list36 = list11;
                    list37 = list10;
                    list38 = list9;
                    list39 = list8;
                    list40 = list7;
                    list41 = list6;
                    list42 = list5;
                    list43 = list4;
                    list44 = list3;
                    list31 = list2;
                default:
                    yhk.e(o);
                    return null;
            }
        }
        List list88 = list19;
        List list89 = list25;
        List list90 = list31;
        List list91 = list32;
        List list92 = list33;
        List list93 = list20;
        b.c(serialDescriptor);
        List list94 = list39;
        List list95 = list40;
        List list96 = list29;
        List list97 = list30;
        List list98 = list37;
        List list99 = list27;
        List list100 = list38;
        List list101 = list28;
        return new BaseballTopPlayersStatistics(i5, list90, list91, list92, list34, list35, list36, list98, list100, list94, list95, list41, list42, list43, list44, list89, list26, list99, list101, list96, list97, list23, list21, list93, list88, list18, list22, list24, null);
    }

    @Override // defpackage.dy4
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull BaseballTopPlayersStatistics value) {
        encoder.getClass();
        value.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        wf3 b = encoder.b(serialDescriptor);
        BaseballTopPlayersStatistics.write$Self$model_release(value, b, serialDescriptor);
        b.c(serialDescriptor);
    }

    @Override // defpackage.iw8
    @NotNull
    public /* bridge */ KSerializer[] typeParametersSerializers() {
        return z8e.e;
    }
}
