package com.sofascore.model.newNetwork.topperformance.response;

import androidx.core.app.NotificationCompat;
import com.ironsource.U3;
import com.ironsource.mediationsdk.metadata.a;
import com.mbridge.msdk.foundation.entity.CampaignEx;
import com.mbridge.msdk.playercommon.exoplayer2.C;
import com.mbridge.msdk.playercommon.exoplayer2.source.ExtractorMediaSource;
import defpackage.dy4;
import defpackage.iw8;
import defpackage.joa;
import defpackage.l98;
import defpackage.uf3;
import defpackage.uye;
import defpackage.wf3;
import defpackage.wx4;
import defpackage.yhk;
import defpackage.z8e;
import java.util.List;
import kotlin.Metadata;
import kotlin.Unit;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import org.jetbrains.annotations.NotNull;

/* compiled from: r8-map-id-820aebbf04e3f76f83859749e000e999e94bc7aa15ea120a09e9f3ed9aa09d5a */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/sofascore/model/newNetwork/topperformance/response/BasketballTopPlayersStatistics.$serializer", "Liw8;", "Lcom/sofascore/model/newNetwork/topperformance/response/BasketballTopPlayersStatistics;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", U3.i.X, "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/sofascore/model/newNetwork/topperformance/response/BasketballTopPlayersStatistics;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/sofascore/model/newNetwork/topperformance/response/BasketballTopPlayersStatistics;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "model_release"}, k = 1, mv = {2, 3, 0}, xi = 48)
@wx4
/* loaded from: classes5.dex */
public final /* synthetic */ class BasketballTopPlayersStatistics$$serializer implements iw8 {

    @NotNull
    public static final BasketballTopPlayersStatistics$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        BasketballTopPlayersStatistics$$serializer basketballTopPlayersStatistics$$serializer = new BasketballTopPlayersStatistics$$serializer();
        INSTANCE = basketballTopPlayersStatistics$$serializer;
        uye uyeVar = new uye("com.sofascore.model.newNetwork.topperformance.response.BasketballTopPlayersStatistics", basketballTopPlayersStatistics$$serializer, 25);
        uyeVar.j("points", false);
        uyeVar.j("rebounds", false);
        uyeVar.j("assists", false);
        uyeVar.j("secondsPlayed", false);
        uyeVar.j("fieldGoalsPercentage", false);
        uyeVar.j("freeThrowsPercentage", false);
        uyeVar.j("threePointsPercentage", false);
        uyeVar.j("threePointsMade", false);
        uyeVar.j("defensiveRebounds", false);
        uyeVar.j("offensiveRebounds", false);
        uyeVar.j("steals", false);
        uyeVar.j("turnovers", false);
        uyeVar.j("blocks", false);
        uyeVar.j("assistTurnoverRatio", false);
        uyeVar.j("plusMinus", false);
        uyeVar.j("pir", false);
        uyeVar.j("doubleDoubles", false);
        uyeVar.j("tripleDoubles", false);
        uyeVar.j(CampaignEx.JSON_KEY_STAR, false);
        uyeVar.j("trueShootingPercentage", false);
        uyeVar.j("effectiveFieldGoalPercentage", false);
        uyeVar.j("usage", false);
        uyeVar.j("individualOffensiveRating", false);
        uyeVar.j("individualDefensiveRating", false);
        uyeVar.j("playerEfficiencyRating", false);
        descriptor = uyeVar;
    }

    private BasketballTopPlayersStatistics$$serializer() {
    }

    @Override // defpackage.iw8
    @NotNull
    public final KSerializer[] childSerializers() {
        joa[] joaVarArr;
        joaVarArr = BasketballTopPlayersStatistics.$childSerializers;
        return new KSerializer[]{l98.W((KSerializer) joaVarArr[0].getValue()), l98.W((KSerializer) joaVarArr[1].getValue()), l98.W((KSerializer) joaVarArr[2].getValue()), l98.W((KSerializer) joaVarArr[3].getValue()), l98.W((KSerializer) joaVarArr[4].getValue()), l98.W((KSerializer) joaVarArr[5].getValue()), l98.W((KSerializer) joaVarArr[6].getValue()), l98.W((KSerializer) joaVarArr[7].getValue()), l98.W((KSerializer) joaVarArr[8].getValue()), l98.W((KSerializer) joaVarArr[9].getValue()), l98.W((KSerializer) joaVarArr[10].getValue()), l98.W((KSerializer) joaVarArr[11].getValue()), l98.W((KSerializer) joaVarArr[12].getValue()), l98.W((KSerializer) joaVarArr[13].getValue()), l98.W((KSerializer) joaVarArr[14].getValue()), l98.W((KSerializer) joaVarArr[15].getValue()), l98.W((KSerializer) joaVarArr[16].getValue()), l98.W((KSerializer) joaVarArr[17].getValue()), l98.W((KSerializer) joaVarArr[18].getValue()), l98.W((KSerializer) joaVarArr[19].getValue()), l98.W((KSerializer) joaVarArr[20].getValue()), l98.W((KSerializer) joaVarArr[21].getValue()), l98.W((KSerializer) joaVarArr[22].getValue()), l98.W((KSerializer) joaVarArr[23].getValue()), l98.W((KSerializer) joaVarArr[24].getValue())};
    }

    @Override // defpackage.dy4
    @NotNull
    public final BasketballTopPlayersStatistics deserialize(@NotNull Decoder decoder) {
        joa[] joaVarArr;
        List list;
        List list2;
        List list3;
        List list4;
        List list5;
        List list6;
        List list7;
        int i;
        List list8;
        List list9;
        List list10;
        List list11;
        List list12;
        List list13;
        List list14;
        List list15;
        List list16;
        List list17;
        List list18;
        List list19;
        List list20;
        List list21;
        int i2;
        decoder.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        uf3 b = decoder.b(serialDescriptor);
        joaVarArr = BasketballTopPlayersStatistics.$childSerializers;
        int i3 = 0;
        List list22 = null;
        List list23 = null;
        List list24 = null;
        List list25 = null;
        List list26 = null;
        List list27 = null;
        int i4 = 0;
        List list28 = null;
        List list29 = null;
        List list30 = null;
        List list31 = null;
        List list32 = null;
        List list33 = null;
        List list34 = null;
        int i5 = 1;
        List list35 = null;
        List list36 = null;
        List list37 = null;
        List list38 = null;
        List list39 = null;
        List list40 = null;
        List list41 = null;
        List list42 = null;
        List list43 = null;
        List list44 = null;
        List list45 = null;
        List list46 = null;
        while (i5 != 0) {
            int o = b.o(serialDescriptor);
            switch (o) {
                case -1:
                    list = list22;
                    list2 = list26;
                    list3 = list28;
                    list4 = list35;
                    list5 = list36;
                    list6 = list37;
                    list7 = list23;
                    i = i3;
                    Unit unit = Unit.a;
                    i5 = i;
                    list8 = list5;
                    list26 = list2;
                    list28 = list3;
                    list9 = list46;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list6;
                    list19 = list4;
                    list22 = list;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 0:
                    list = list22;
                    list2 = list26;
                    list3 = list28;
                    list5 = list36;
                    list6 = list37;
                    dy4 dy4Var = (dy4) joaVarArr[i3].getValue();
                    List list47 = list35;
                    list7 = list23;
                    i = i3;
                    list4 = (List) b.i(serialDescriptor, i, dy4Var, list47);
                    i4 |= 1;
                    Unit unit2 = Unit.a;
                    list8 = list5;
                    list26 = list2;
                    list28 = list3;
                    list9 = list46;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list6;
                    list19 = list4;
                    list22 = list;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 1:
                    List list48 = list22;
                    List list49 = list26;
                    List list50 = list28;
                    List list51 = list37;
                    List list52 = (List) b.i(serialDescriptor, 1, (dy4) joaVarArr[1].getValue(), list36);
                    i4 |= 2;
                    Unit unit3 = Unit.a;
                    list8 = list52;
                    list26 = list49;
                    list22 = list48;
                    list28 = list50;
                    list9 = list46;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list51;
                    list19 = list35;
                    list7 = list23;
                    i = i3;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 2:
                    list = list22;
                    List list53 = list26;
                    List list54 = (List) b.i(serialDescriptor, 2, (dy4) joaVarArr[2].getValue(), list37);
                    i4 |= 4;
                    Unit unit4 = Unit.a;
                    list19 = list35;
                    list8 = list36;
                    list26 = list53;
                    list28 = list28;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list54;
                    list22 = list;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 3:
                    list = list22;
                    List list55 = list26;
                    List list56 = (List) b.i(serialDescriptor, 3, (dy4) joaVarArr[3].getValue(), list38);
                    i4 |= 8;
                    Unit unit5 = Unit.a;
                    list19 = list35;
                    list18 = list37;
                    list26 = list55;
                    list28 = list28;
                    list7 = list23;
                    list8 = list36;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list56;
                    list22 = list;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 4:
                    list = list22;
                    List list57 = list26;
                    List list58 = (List) b.i(serialDescriptor, 4, (dy4) joaVarArr[4].getValue(), list39);
                    i4 |= 16;
                    Unit unit6 = Unit.a;
                    list19 = list35;
                    list17 = list38;
                    list26 = list57;
                    list28 = list28;
                    list7 = list23;
                    list18 = list37;
                    list9 = list46;
                    i = i3;
                    list8 = list36;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list58;
                    list22 = list;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 5:
                    list = list22;
                    List list59 = list26;
                    List list60 = (List) b.i(serialDescriptor, 5, (dy4) joaVarArr[5].getValue(), list40);
                    i4 |= 32;
                    Unit unit7 = Unit.a;
                    list19 = list35;
                    list16 = list39;
                    list26 = list59;
                    list28 = list28;
                    list7 = list23;
                    list17 = list38;
                    list9 = list46;
                    i = i3;
                    list18 = list37;
                    list10 = list45;
                    list8 = list36;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list60;
                    list22 = list;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 6:
                    list = list22;
                    List list61 = list26;
                    List list62 = (List) b.i(serialDescriptor, 6, (dy4) joaVarArr[6].getValue(), list41);
                    i4 |= 64;
                    Unit unit8 = Unit.a;
                    list19 = list35;
                    list15 = list40;
                    list26 = list61;
                    list28 = list28;
                    list7 = list23;
                    list16 = list39;
                    list9 = list46;
                    i = i3;
                    list17 = list38;
                    list10 = list45;
                    list18 = list37;
                    list11 = list44;
                    list8 = list36;
                    list12 = list43;
                    list13 = list42;
                    list14 = list62;
                    list22 = list;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 7:
                    list = list22;
                    List list63 = list26;
                    List list64 = (List) b.i(serialDescriptor, 7, (dy4) joaVarArr[7].getValue(), list42);
                    i4 |= 128;
                    Unit unit9 = Unit.a;
                    list19 = list35;
                    list14 = list41;
                    list26 = list63;
                    list28 = list28;
                    list7 = list23;
                    list15 = list40;
                    list9 = list46;
                    i = i3;
                    list16 = list39;
                    list10 = list45;
                    list17 = list38;
                    list11 = list44;
                    list18 = list37;
                    list12 = list43;
                    list13 = list64;
                    list8 = list36;
                    list22 = list;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 8:
                    List list65 = list22;
                    List list66 = list26;
                    List list67 = (List) b.i(serialDescriptor, 8, (dy4) joaVarArr[8].getValue(), list43);
                    i4 |= NotificationCompat.FLAG_LOCAL_ONLY;
                    Unit unit10 = Unit.a;
                    list19 = list35;
                    list13 = list42;
                    list26 = list66;
                    list28 = list28;
                    list7 = list23;
                    list14 = list41;
                    list9 = list46;
                    i = i3;
                    list15 = list40;
                    list10 = list45;
                    list16 = list39;
                    list11 = list44;
                    list12 = list67;
                    list17 = list38;
                    list22 = list65;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 9:
                    List list68 = list22;
                    List list69 = list26;
                    List list70 = (List) b.i(serialDescriptor, 9, (dy4) joaVarArr[9].getValue(), list44);
                    i4 |= 512;
                    Unit unit11 = Unit.a;
                    list19 = list35;
                    list12 = list43;
                    list26 = list69;
                    list28 = list28;
                    list7 = list23;
                    list13 = list42;
                    list9 = list46;
                    i = i3;
                    list14 = list41;
                    list10 = list45;
                    list11 = list70;
                    list15 = list40;
                    list22 = list68;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 10:
                    List list71 = list22;
                    List list72 = list26;
                    List list73 = (List) b.i(serialDescriptor, 10, (dy4) joaVarArr[10].getValue(), list45);
                    i4 |= 1024;
                    Unit unit12 = Unit.a;
                    list19 = list35;
                    list11 = list44;
                    list26 = list72;
                    list28 = list28;
                    list7 = list23;
                    list12 = list43;
                    list9 = list46;
                    i = i3;
                    list10 = list73;
                    list13 = list42;
                    list22 = list71;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 11:
                    List list74 = list22;
                    List list75 = list26;
                    List list76 = (List) b.i(serialDescriptor, 11, (dy4) joaVarArr[11].getValue(), list46);
                    i4 |= a.o;
                    Unit unit13 = Unit.a;
                    list19 = list35;
                    list10 = list45;
                    list26 = list75;
                    list28 = list28;
                    list9 = list76;
                    list7 = list23;
                    list11 = list44;
                    list22 = list74;
                    i = i3;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 12:
                    List list77 = list22;
                    List list78 = list28;
                    list26 = (List) b.i(serialDescriptor, 12, (dy4) joaVarArr[12].getValue(), list26);
                    i4 |= 4096;
                    Unit unit14 = Unit.a;
                    list19 = list35;
                    list9 = list46;
                    list22 = list77;
                    list28 = list78;
                    list7 = list23;
                    list10 = list45;
                    i = i3;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 13:
                    List list79 = list22;
                    list28 = (List) b.i(serialDescriptor, 13, (dy4) joaVarArr[13].getValue(), list28);
                    i4 |= 8192;
                    Unit unit15 = Unit.a;
                    list19 = list35;
                    list26 = list26;
                    list22 = list79;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 14:
                    list20 = list26;
                    list21 = list28;
                    list29 = (List) b.i(serialDescriptor, 14, (dy4) joaVarArr[14].getValue(), list29);
                    i4 |= 16384;
                    Unit unit16 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 15:
                    list20 = list26;
                    list21 = list28;
                    list30 = (List) b.i(serialDescriptor, 15, (dy4) joaVarArr[15].getValue(), list30);
                    i2 = 32768;
                    i4 |= i2;
                    Unit unit162 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 16:
                    list20 = list26;
                    list21 = list28;
                    list31 = (List) b.i(serialDescriptor, 16, (dy4) joaVarArr[16].getValue(), list31);
                    i2 = C.DEFAULT_BUFFER_SEGMENT_SIZE;
                    i4 |= i2;
                    Unit unit1622 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 17:
                    list20 = list26;
                    list21 = list28;
                    list32 = (List) b.i(serialDescriptor, 17, (dy4) joaVarArr[17].getValue(), list32);
                    i2 = 131072;
                    i4 |= i2;
                    Unit unit16222 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 18:
                    list20 = list26;
                    list21 = list28;
                    list33 = (List) b.i(serialDescriptor, 18, (dy4) joaVarArr[18].getValue(), list33);
                    i2 = 262144;
                    i4 |= i2;
                    Unit unit162222 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 19:
                    list20 = list26;
                    list21 = list28;
                    list34 = (List) b.i(serialDescriptor, 19, (dy4) joaVarArr[19].getValue(), list34);
                    i2 = 524288;
                    i4 |= i2;
                    Unit unit1622222 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 20:
                    list20 = list26;
                    list21 = list28;
                    list27 = (List) b.i(serialDescriptor, 20, (dy4) joaVarArr[20].getValue(), list27);
                    i2 = ExtractorMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES;
                    i4 |= i2;
                    Unit unit16222222 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 21:
                    list20 = list26;
                    list21 = list28;
                    list25 = (List) b.i(serialDescriptor, 21, (dy4) joaVarArr[21].getValue(), list25);
                    i2 = 2097152;
                    i4 |= i2;
                    Unit unit162222222 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 22:
                    list20 = list26;
                    list21 = list28;
                    list24 = (List) b.i(serialDescriptor, 22, (dy4) joaVarArr[22].getValue(), list24);
                    i2 = 4194304;
                    i4 |= i2;
                    Unit unit1622222222 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 23:
                    list20 = list26;
                    list21 = list28;
                    list23 = (List) b.i(serialDescriptor, 23, (dy4) joaVarArr[23].getValue(), list23);
                    i2 = 8388608;
                    i4 |= i2;
                    Unit unit16222222222 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                case 24:
                    list20 = list26;
                    list21 = list28;
                    list22 = (List) b.i(serialDescriptor, 24, (dy4) joaVarArr[24].getValue(), list22);
                    i2 = C.DEFAULT_MUXED_BUFFER_SIZE;
                    i4 |= i2;
                    Unit unit162222222222 = Unit.a;
                    list19 = list35;
                    list26 = list20;
                    list28 = list21;
                    list7 = list23;
                    list9 = list46;
                    i = i3;
                    list10 = list45;
                    list11 = list44;
                    list12 = list43;
                    list13 = list42;
                    list14 = list41;
                    list15 = list40;
                    list16 = list39;
                    list17 = list38;
                    list18 = list37;
                    list8 = list36;
                    i3 = i;
                    list23 = list7;
                    list36 = list8;
                    list37 = list18;
                    list38 = list17;
                    list39 = list16;
                    list40 = list15;
                    list41 = list14;
                    list42 = list13;
                    list43 = list12;
                    list44 = list11;
                    list45 = list10;
                    list46 = list9;
                    list35 = list19;
                default:
                    yhk.e(o);
                    return null;
            }
        }
        List list80 = list22;
        List list81 = list28;
        List list82 = list35;
        List list83 = list36;
        List list84 = list37;
        b.c(serialDescriptor);
        List list85 = list44;
        List list86 = list34;
        List list87 = list41;
        List list88 = list31;
        List list89 = list43;
        List list90 = list33;
        List list91 = list42;
        List list92 = list32;
        return new BasketballTopPlayersStatistics(i4, list82, list83, list84, list38, list39, list40, list87, list91, list89, list85, list45, list46, list26, list81, list29, list30, list88, list92, list90, list86, list27, list25, list24, list23, list80, null);
    }

    @Override // defpackage.dy4
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull BasketballTopPlayersStatistics value) {
        encoder.getClass();
        value.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        wf3 b = encoder.b(serialDescriptor);
        BasketballTopPlayersStatistics.write$Self$model_release(value, b, serialDescriptor);
        b.c(serialDescriptor);
    }

    @Override // defpackage.iw8
    @NotNull
    public /* bridge */ KSerializer[] typeParametersSerializers() {
        return z8e.e;
    }
}
