package ru.ozon.app.android.travel.feature.railway.widgets.travelCarriageSelect.v3.presentation.view;

import androidx.constraintlayout.widget.Barrier;
import androidx.constraintlayout.widget.d;
import androidx.recyclerview.widget.RecyclerView;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;
import kotlin.jvm.internal.AbstractC7737t;
import kotlin.jvm.internal.Intrinsics;
import ru.ozon.app.android.atoms.af.layout.HorizontalAtomsLayout;
import ru.ozon.app.android.travel.molecules.view.priceCard.PriceCardView;
import ru.ozon.app.android.travel.utils.extensions.ConstraintLayoutExtensionsKt;
import ru.ozon.uni.android.atom.badge.BadgeView;
import ru.ozon.uni.android.atom.price.ui.PriceAtomView;
import ru.ozon.uni.android.atom.text.TextAtomV2View;

@Metadata(d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0010\u0002\n\u0002\b\u0003\u0010\u0004\u001a\u00020\u0001*\u00020\u0000H\n¢\u0006\u0004\b\u0002\u0010\u0003"}, d2 = {"Landroidx/constraintlayout/widget/d;", "", "invoke", "(Landroidx/constraintlayout/widget/d;)V", "<anonymous>"}, k = 3, mv = {2, 0, 0})
/* loaded from: classes4.dex */
final class TravelCarriageSelectV3View$setConstraints$1 extends AbstractC7737t implements Function1<d, Unit> {
    final /* synthetic */ TravelCarriageSelectV3View this$0;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    TravelCarriageSelectV3View$setConstraints$1(TravelCarriageSelectV3View travelCarriageSelectV3View) {
        super(1);
        this.this$0 = travelCarriageSelectV3View;
    }

    @Override // kotlin.jvm.functions.Function1
    public /* bridge */ /* synthetic */ Unit invoke(d dVar) {
        invoke2(dVar);
        return Unit.f71690a;
    }

    /* renamed from: invoke, reason: avoid collision after fix types in other method */
    public final void invoke2(d applyConstraint) {
        TextAtomV2View textAtomV2View;
        TextAtomV2View textAtomV2View2;
        TextAtomV2View textAtomV2View3;
        TextAtomV2View textAtomV2View4;
        TextAtomV2View textAtomV2View5;
        TextAtomV2View textAtomV2View6;
        TextAtomV2View textAtomV2View7;
        TextAtomV2View textAtomV2View8;
        int i11;
        RecyclerView recyclerView;
        TextAtomV2View textAtomV2View9;
        RecyclerView recyclerView2;
        RecyclerView recyclerView3;
        TextAtomV2View textAtomV2View10;
        RecyclerView recyclerView4;
        int i12;
        TextAtomV2View textAtomV2View11;
        TextAtomV2View textAtomV2View12;
        HorizontalAtomsLayout horizontalAtomsLayout;
        TextAtomV2View textAtomV2View13;
        int i13;
        HorizontalAtomsLayout horizontalAtomsLayout2;
        HorizontalAtomsLayout horizontalAtomsLayout3;
        TextAtomV2View textAtomV2View14;
        HorizontalAtomsLayout horizontalAtomsLayout4;
        int i14;
        TextAtomV2View textAtomV2View15;
        TextAtomV2View textAtomV2View16;
        TextAtomV2View textAtomV2View17;
        TextAtomV2View textAtomV2View18;
        TextAtomV2View textAtomV2View19;
        int i15;
        TextAtomV2View textAtomV2View20;
        PriceCardView priceCardView;
        TextAtomV2View textAtomV2View21;
        int i16;
        PriceCardView priceCardView2;
        PriceCardView priceCardView3;
        PriceCardView priceCardView4;
        PriceCardView priceCardView5;
        PriceCardView priceCardView6;
        PriceCardView priceCardView7;
        PriceCardView priceCardView8;
        PriceCardView priceCardView9;
        int i17;
        PriceCardView priceCardView10;
        BadgeView badgeView;
        PriceAtomView priceAtomView;
        TextAtomV2View textAtomV2View22;
        int i18;
        PriceAtomView priceAtomView2;
        PriceAtomView priceAtomView3;
        PriceAtomView priceAtomView4;
        BadgeView badgeView2;
        BadgeView badgeView3;
        Barrier barrier;
        BadgeView badgeView4;
        Barrier barrier2;
        BadgeView badgeView5;
        Intrinsics.checkNotNullParameter(applyConstraint, "$this$applyConstraint");
        textAtomV2View = this.this$0.numberTAV;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, textAtomV2View);
        textAtomV2View2 = this.this$0.numberTAV;
        ConstraintLayoutExtensionsKt.topToParent(applyConstraint, textAtomV2View2);
        textAtomV2View3 = this.this$0.typeTAV;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, textAtomV2View3);
        textAtomV2View4 = this.this$0.typeTAV;
        ConstraintLayoutExtensionsKt.topToParent(applyConstraint, textAtomV2View4);
        textAtomV2View5 = this.this$0.serviceTypeTAV;
        textAtomV2View6 = this.this$0.typeTAV;
        ConstraintLayoutExtensionsKt.baselineToBaseline(applyConstraint, textAtomV2View5, textAtomV2View6);
        textAtomV2View7 = this.this$0.serviceTypeTAV;
        textAtomV2View8 = this.this$0.typeTAV;
        i11 = this.this$0.dp4;
        ConstraintLayoutExtensionsKt.startToEnd(applyConstraint, textAtomV2View7, textAtomV2View8, i11);
        recyclerView = this.this$0.storeysRV;
        textAtomV2View9 = this.this$0.typeTAV;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, recyclerView, textAtomV2View9);
        recyclerView2 = this.this$0.storeysRV;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, recyclerView2);
        recyclerView3 = this.this$0.storeysRV;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, recyclerView3);
        textAtomV2View10 = this.this$0.additionalInfoTAV;
        recyclerView4 = this.this$0.storeysRV;
        i12 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, textAtomV2View10, recyclerView4, i12);
        textAtomV2View11 = this.this$0.additionalInfoTAV;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, textAtomV2View11);
        textAtomV2View12 = this.this$0.additionalInfoTAV;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, textAtomV2View12);
        horizontalAtomsLayout = this.this$0.railwayServicesHAL;
        textAtomV2View13 = this.this$0.additionalInfoTAV;
        i13 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, horizontalAtomsLayout, textAtomV2View13, i13);
        horizontalAtomsLayout2 = this.this$0.railwayServicesHAL;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, horizontalAtomsLayout2);
        horizontalAtomsLayout3 = this.this$0.railwayServicesHAL;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, horizontalAtomsLayout3);
        textAtomV2View14 = this.this$0.seatsCountTAV;
        horizontalAtomsLayout4 = this.this$0.railwayServicesHAL;
        i14 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, textAtomV2View14, horizontalAtomsLayout4, i14);
        textAtomV2View15 = this.this$0.seatsCountTAV;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, textAtomV2View15);
        textAtomV2View16 = this.this$0.seatsDetailsTAV;
        textAtomV2View17 = this.this$0.seatsCountTAV;
        ConstraintLayoutExtensionsKt.baselineToBaseline(applyConstraint, textAtomV2View16, textAtomV2View17);
        textAtomV2View18 = this.this$0.seatsDetailsTAV;
        textAtomV2View19 = this.this$0.seatsCountTAV;
        i15 = this.this$0.dp4;
        ConstraintLayoutExtensionsKt.startToEnd(applyConstraint, textAtomV2View18, textAtomV2View19, i15);
        textAtomV2View20 = this.this$0.seatsDetailsTAV;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, textAtomV2View20);
        priceCardView = this.this$0.discountPriceCardPCV;
        textAtomV2View21 = this.this$0.seatsCountTAV;
        i16 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, priceCardView, textAtomV2View21, i16);
        priceCardView2 = this.this$0.discountPriceCardPCV;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, priceCardView2);
        priceCardView3 = this.this$0.discountPriceCardPCV;
        ConstraintLayoutExtensionsKt.bottomToParent(applyConstraint, priceCardView3);
        priceCardView4 = this.this$0.originalPriceCardPCV;
        priceCardView5 = this.this$0.discountPriceCardPCV;
        ConstraintLayoutExtensionsKt.topToTop(applyConstraint, priceCardView4, priceCardView5);
        priceCardView6 = this.this$0.originalPriceCardPCV;
        priceCardView7 = this.this$0.discountPriceCardPCV;
        ConstraintLayoutExtensionsKt.bottomToBottom(applyConstraint, priceCardView6, priceCardView7);
        priceCardView8 = this.this$0.originalPriceCardPCV;
        priceCardView9 = this.this$0.discountPriceCardPCV;
        i17 = this.this$0.dp12;
        ConstraintLayoutExtensionsKt.startToEnd(applyConstraint, priceCardView8, priceCardView9, i17);
        priceCardView10 = this.this$0.originalPriceCardPCV;
        badgeView = this.this$0.premiumBadgeBV;
        ConstraintLayoutExtensionsKt.endToStart(applyConstraint, priceCardView10, badgeView);
        priceAtomView = this.this$0.originalPricePV;
        textAtomV2View22 = this.this$0.seatsCountTAV;
        i18 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, priceAtomView, textAtomV2View22, i18);
        priceAtomView2 = this.this$0.originalPricePV;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, priceAtomView2);
        priceAtomView3 = this.this$0.originalPricePV;
        ConstraintLayoutExtensionsKt.bottomToParent(applyConstraint, priceAtomView3);
        priceAtomView4 = this.this$0.originalPricePV;
        badgeView2 = this.this$0.premiumBadgeBV;
        ConstraintLayoutExtensionsKt.endToStart(applyConstraint, priceAtomView4, badgeView2);
        badgeView3 = this.this$0.premiumBadgeBV;
        barrier = this.this$0.priceTopBarrier;
        ConstraintLayoutExtensionsKt.topToTop(applyConstraint, badgeView3, barrier);
        badgeView4 = this.this$0.premiumBadgeBV;
        barrier2 = this.this$0.priceBottomBarrier;
        ConstraintLayoutExtensionsKt.bottomToBottom(applyConstraint, badgeView4, barrier2);
        badgeView5 = this.this$0.premiumBadgeBV;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, badgeView5);
    }
}
