package xsna;

import com.mbridge.msdk.playercommon.exoplayer2.C;
import com.mbridge.msdk.playercommon.exoplayer2.source.ExtractorMediaSource;
import com.vk.api.generated.wall.dto.WallAttachmentsListAttachmentDto;
import com.vk.dto.common.id.UserId;
import com.vk.newsfeed.api.posting.dto.PostingPrimaryMode;
import io.requery.android.database.sqlite.SQLiteDatabase;
import java.util.ArrayList;
import java.util.List;
import kotlin.collections.EmptyList;

/* compiled from: WallPublishParams.kt */
/* loaded from: classes4.dex */
public final class bax0 {
    public final String A;
    public final String B;
    public final String C;
    public final String D;
    public final String E;
    public final String F;
    public final Boolean G;
    public final Integer H;
    public final Integer I;
    public final boolean J;
    public final UserId K;
    public final boolean L;
    public final boolean M;
    public final boolean N;
    public final Integer O;
    public final Integer P;
    public final Boolean Q;
    public final Long R;
    public final Integer S;
    public final String T;
    public final String U;
    public final List<WallAttachmentsListAttachmentDto> V;
    public final Integer W;
    public final UserId X;
    public final String Y;
    public final UserId a;
    public final String b;
    public final List<String> c;
    public final Boolean d;
    public final Boolean e;
    public final boolean f;
    public final boolean g;
    public final boolean h;
    public final boolean i;
    public final boolean j;
    public final boolean k;
    public final boolean l;
    public final Integer m;
    public final Double n;
    public final Double o;
    public final Integer p;
    public final String q;
    public final Integer r;
    public final String s;
    public final String t;
    public final PostingPrimaryMode u;
    public final List<UserId> v;
    public final String w;
    public final String x;
    public final String y;
    public final String z;

    public bax0() {
        throw null;
    }

    public bax0(UserId userId, String str, List list, Boolean bool, Boolean bool2, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, Integer num, Double d, Double d2, Integer num2, String str2, Integer num3, String str3, String str4, PostingPrimaryMode postingPrimaryMode, ArrayList arrayList, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, Boolean bool3, Integer num4, Integer num5, boolean z8, UserId userId2, boolean z9, boolean z10, boolean z11, Integer num6, Integer num7, Boolean bool4, Long l, Integer num8, String str15, String str16, List list2, Integer num9, UserId userId3, String str17, int i, int i2) {
        String str18 = (i & 2) != 0 ? null : str;
        List list3 = (i & 4) != 0 ? EmptyList.b : list;
        Boolean bool5 = (i & 8) != 0 ? null : bool;
        Boolean bool6 = (i & 16) != 0 ? null : bool2;
        boolean z12 = (i & 32) != 0 ? false : z;
        boolean z13 = (i & 64) != 0 ? false : z2;
        boolean z14 = (i & 128) != 0 ? false : z3;
        boolean z15 = (i & 256) != 0 ? false : z4;
        boolean z16 = (i & 512) != 0 ? false : z5;
        boolean z17 = (i & 1024) != 0 ? false : z6;
        boolean z18 = (i & 2048) != 0 ? false : z7;
        Integer num10 = (i & 4096) != 0 ? null : num;
        Double d3 = (i & 8192) != 0 ? null : d;
        Double d4 = (i & 16384) != 0 ? null : d2;
        Integer num11 = (i & 32768) != 0 ? null : num2;
        String str19 = (i & 65536) != 0 ? null : str2;
        Integer num12 = (i & 131072) != 0 ? null : num3;
        String str20 = (i & SQLiteDatabase.OPEN_PRIVATECACHE) != 0 ? null : str3;
        String str21 = (i & 524288) != 0 ? null : str4;
        PostingPrimaryMode postingPrimaryMode2 = (i & ExtractorMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES) != 0 ? null : postingPrimaryMode;
        ArrayList arrayList2 = (i & 2097152) != 0 ? null : arrayList;
        String str22 = (i & 4194304) != 0 ? null : str5;
        String str23 = (i & 8388608) != 0 ? null : str6;
        String str24 = (i & C.DEFAULT_MUXED_BUFFER_SIZE) != 0 ? null : str7;
        String str25 = (i & 33554432) != 0 ? null : str8;
        String str26 = (i & 67108864) != 0 ? null : str9;
        String str27 = (i & 268435456) != 0 ? null : str11;
        String str28 = (i & SQLiteDatabase.ENABLE_WRITE_AHEAD_LOGGING) != 0 ? null : str12;
        String str29 = (i & 1073741824) != 0 ? null : str13;
        String str30 = (i & Integer.MIN_VALUE) != 0 ? null : str14;
        Boolean bool7 = (i2 & 1) != 0 ? null : bool3;
        Integer num13 = (i2 & 2) != 0 ? null : num4;
        Integer num14 = (i2 & 4) != 0 ? null : num5;
        boolean z19 = (i2 & 8) != 0 ? false : z8;
        UserId userId4 = (i2 & 16) != 0 ? null : userId2;
        boolean z20 = (i2 & 32) != 0 ? false : z9;
        boolean z21 = (i2 & 64) != 0 ? false : z10;
        Integer num15 = num11;
        boolean z22 = (i2 & 128) != 0 ? false : z11;
        Integer num16 = (i2 & 256) != 0 ? null : num6;
        Integer num17 = (i2 & 512) != 0 ? null : num7;
        Boolean bool8 = (i2 & 1024) != 0 ? null : bool4;
        Long l2 = (i2 & 2048) != 0 ? null : l;
        Integer num18 = (i2 & 4096) != 0 ? null : num8;
        String str31 = (i2 & 8192) != 0 ? null : str15;
        String str32 = (i2 & 16384) != 0 ? null : str16;
        List list4 = (i2 & 32768) != 0 ? null : list2;
        Integer num19 = (i2 & 65536) != 0 ? null : num9;
        UserId userId5 = (i2 & 131072) != 0 ? null : userId3;
        String str33 = (i2 & SQLiteDatabase.OPEN_PRIVATECACHE) != 0 ? null : str17;
        this.a = userId;
        this.b = str18;
        this.c = list3;
        this.d = bool5;
        this.e = bool6;
        this.f = z12;
        this.g = z13;
        this.h = z14;
        this.i = z15;
        this.j = z16;
        this.k = z17;
        this.l = z18;
        this.m = num10;
        this.n = d3;
        this.o = d4;
        this.p = num15;
        this.q = str19;
        this.r = num12;
        this.s = str20;
        this.t = str21;
        this.u = postingPrimaryMode2;
        this.v = arrayList2;
        this.w = str22;
        this.x = str23;
        this.y = str24;
        this.z = str25;
        this.A = str26;
        this.B = str10;
        this.C = str27;
        this.D = str28;
        this.E = str29;
        this.F = str30;
        this.G = bool7;
        this.H = num13;
        this.I = num14;
        this.J = z19;
        this.K = userId4;
        this.L = z20;
        this.M = z21;
        this.N = z22;
        this.O = num16;
        this.P = num17;
        this.Q = bool8;
        this.R = l2;
        this.S = num18;
        this.T = str31;
        this.U = str32;
        this.V = list4;
        this.W = num19;
        this.X = userId5;
        this.Y = str33;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof bax0)) {
            return false;
        }
        bax0 bax0Var = (bax0) obj;
        return epx.f(this.a, bax0Var.a) && epx.f(this.b, bax0Var.b) && epx.f(this.c, bax0Var.c) && epx.f(this.d, bax0Var.d) && epx.f(this.e, bax0Var.e) && this.f == bax0Var.f && this.g == bax0Var.g && this.h == bax0Var.h && this.i == bax0Var.i && this.j == bax0Var.j && this.k == bax0Var.k && this.l == bax0Var.l && epx.f(this.m, bax0Var.m) && epx.f(this.n, bax0Var.n) && epx.f(this.o, bax0Var.o) && epx.f(this.p, bax0Var.p) && epx.f(this.q, bax0Var.q) && epx.f(this.r, bax0Var.r) && epx.f(this.s, bax0Var.s) && epx.f(this.t, bax0Var.t) && this.u == bax0Var.u && epx.f(this.v, bax0Var.v) && epx.f(this.w, bax0Var.w) && epx.f(this.x, bax0Var.x) && epx.f(this.y, bax0Var.y) && epx.f(this.z, bax0Var.z) && epx.f(this.A, bax0Var.A) && epx.f(this.B, bax0Var.B) && epx.f(this.C, bax0Var.C) && epx.f(this.D, bax0Var.D) && epx.f(this.E, bax0Var.E) && epx.f(this.F, bax0Var.F) && epx.f(this.G, bax0Var.G) && epx.f(this.H, bax0Var.H) && epx.f(this.I, bax0Var.I) && this.J == bax0Var.J && epx.f(this.K, bax0Var.K) && this.L == bax0Var.L && this.M == bax0Var.M && this.N == bax0Var.N && epx.f(this.O, bax0Var.O) && epx.f(this.P, bax0Var.P) && epx.f(this.Q, bax0Var.Q) && epx.f(this.R, bax0Var.R) && epx.f(this.S, bax0Var.S) && epx.f(this.T, bax0Var.T) && epx.f(this.U, bax0Var.U) && epx.f(this.V, bax0Var.V) && epx.f(this.W, bax0Var.W) && epx.f(this.X, bax0Var.X) && epx.f(this.Y, bax0Var.Y);
    }

    public final int hashCode() {
        int hashCode = Long.hashCode(this.a.b) * 31;
        String str = this.b;
        int a = fw3.a((hashCode + (str == null ? 0 : str.hashCode())) * 31, 31, this.c);
        Boolean bool = this.d;
        int hashCode2 = (a + (bool == null ? 0 : bool.hashCode())) * 31;
        Boolean bool2 = this.e;
        int b = qoy.b(qoy.b(qoy.b(qoy.b(qoy.b(qoy.b(qoy.b((hashCode2 + (bool2 == null ? 0 : bool2.hashCode())) * 31, 31, this.f), 31, this.g), 31, this.h), 31, this.i), 31, this.j), 31, this.k), 31, this.l);
        Integer num = this.m;
        int hashCode3 = (b + (num == null ? 0 : num.hashCode())) * 31;
        Double d = this.n;
        int hashCode4 = (hashCode3 + (d == null ? 0 : d.hashCode())) * 31;
        Double d2 = this.o;
        int hashCode5 = (hashCode4 + (d2 == null ? 0 : d2.hashCode())) * 31;
        Integer num2 = this.p;
        int hashCode6 = (hashCode5 + (num2 == null ? 0 : num2.hashCode())) * 31;
        String str2 = this.q;
        int hashCode7 = (hashCode6 + (str2 == null ? 0 : str2.hashCode())) * 31;
        Integer num3 = this.r;
        int hashCode8 = (hashCode7 + (num3 == null ? 0 : num3.hashCode())) * 31;
        String str3 = this.s;
        int hashCode9 = (hashCode8 + (str3 == null ? 0 : str3.hashCode())) * 31;
        String str4 = this.t;
        int hashCode10 = (hashCode9 + (str4 == null ? 0 : str4.hashCode())) * 31;
        PostingPrimaryMode postingPrimaryMode = this.u;
        int hashCode11 = (hashCode10 + (postingPrimaryMode == null ? 0 : postingPrimaryMode.hashCode())) * 31;
        List<UserId> list = this.v;
        int hashCode12 = (hashCode11 + (list == null ? 0 : list.hashCode())) * 31;
        String str5 = this.w;
        int hashCode13 = (hashCode12 + (str5 == null ? 0 : str5.hashCode())) * 31;
        String str6 = this.x;
        int hashCode14 = (hashCode13 + (str6 == null ? 0 : str6.hashCode())) * 31;
        String str7 = this.y;
        int hashCode15 = (hashCode14 + (str7 == null ? 0 : str7.hashCode())) * 31;
        String str8 = this.z;
        int hashCode16 = (hashCode15 + (str8 == null ? 0 : str8.hashCode())) * 31;
        String str9 = this.A;
        int hashCode17 = (hashCode16 + (str9 == null ? 0 : str9.hashCode())) * 31;
        String str10 = this.B;
        int hashCode18 = (hashCode17 + (str10 == null ? 0 : str10.hashCode())) * 31;
        String str11 = this.C;
        int hashCode19 = (hashCode18 + (str11 == null ? 0 : str11.hashCode())) * 31;
        String str12 = this.D;
        int hashCode20 = (hashCode19 + (str12 == null ? 0 : str12.hashCode())) * 31;
        String str13 = this.E;
        int hashCode21 = (hashCode20 + (str13 == null ? 0 : str13.hashCode())) * 31;
        String str14 = this.F;
        int hashCode22 = (hashCode21 + (str14 == null ? 0 : str14.hashCode())) * 31;
        Boolean bool3 = this.G;
        int hashCode23 = (hashCode22 + (bool3 == null ? 0 : bool3.hashCode())) * 31;
        Integer num4 = this.H;
        int hashCode24 = (hashCode23 + (num4 == null ? 0 : num4.hashCode())) * 31;
        Integer num5 = this.I;
        int b2 = qoy.b((hashCode24 + (num5 == null ? 0 : num5.hashCode())) * 31, 31, this.J);
        UserId userId = this.K;
        int b3 = qoy.b(qoy.b(qoy.b((b2 + (userId == null ? 0 : Long.hashCode(userId.b))) * 31, 31, this.L), 31, this.M), 31, this.N);
        Integer num6 = this.O;
        int hashCode25 = (b3 + (num6 == null ? 0 : num6.hashCode())) * 31;
        Integer num7 = this.P;
        int hashCode26 = (hashCode25 + (num7 == null ? 0 : num7.hashCode())) * 31;
        Boolean bool4 = this.Q;
        int hashCode27 = (hashCode26 + (bool4 == null ? 0 : bool4.hashCode())) * 31;
        Long l = this.R;
        int hashCode28 = (hashCode27 + (l == null ? 0 : l.hashCode())) * 31;
        Integer num8 = this.S;
        int hashCode29 = (hashCode28 + (num8 == null ? 0 : num8.hashCode())) * 31;
        String str15 = this.T;
        int hashCode30 = (hashCode29 + (str15 == null ? 0 : str15.hashCode())) * 31;
        String str16 = this.U;
        int hashCode31 = (hashCode30 + (str16 == null ? 0 : str16.hashCode())) * 31;
        List<WallAttachmentsListAttachmentDto> list2 = this.V;
        int hashCode32 = (hashCode31 + (list2 == null ? 0 : list2.hashCode())) * 31;
        Integer num9 = this.W;
        int hashCode33 = (hashCode32 + (num9 == null ? 0 : num9.hashCode())) * 31;
        UserId userId2 = this.X;
        int hashCode34 = (hashCode33 + (userId2 == null ? 0 : Long.hashCode(userId2.b))) * 31;
        String str17 = this.Y;
        return hashCode34 + (str17 != null ? str17.hashCode() : 0);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("WallPublishParams(ownerId=");
        sb.append(this.a);
        sb.append(", message=");
        sb.append(this.b);
        sb.append(", attachments=");
        sb.append(this.c);
        sb.append(", fromGroup=");
        sb.append(this.d);
        sb.append(", signed=");
        sb.append(this.e);
        sb.append(", checkSign=");
        sb.append(this.f);
        sb.append(", isOnlyForFriends=");
        sb.append(this.g);
        sb.append(", isOnlyForBestFriends=");
        sb.append(this.h);
        sb.append(", closeComments=");
        sb.append(this.i);
        sb.append(", muteNotifications=");
        sb.append(this.j);
        sb.append(", newPosting=");
        sb.append(this.k);
        sb.append(", skipRepostToStory=");
        sb.append(this.l);
        sb.append(", publishDateSec=");
        sb.append(this.m);
        sb.append(", locationLat=");
        sb.append(this.n);
        sb.append(", locationLng=");
        sb.append(this.o);
        sb.append(", locationPlaceId=");
        sb.append(this.p);
        sb.append(", copyright=");
        sb.append(this.q);
        sb.append(", donutPaidDuration=");
        sb.append(this.r);
        sb.append(", cropData=");
        sb.append(this.s);
        sb.append(", cropRatioMeta=");
        sb.append(this.t);
        sb.append(", primaryAttachmentsMode=");
        sb.append(this.u);
        sb.append(", coOwnerIds=");
        sb.append(this.v);
        sb.append(", linkTitle=");
        sb.append(this.w);
        sb.append(", linkImage=");
        sb.append(this.x);
        sb.append(", linkButton=");
        sb.append(this.y);
        sb.append(", linkPhotoId=");
        sb.append(this.z);
        sb.append(", guid=");
        sb.append(this.A);
        sb.append(", entryPoint=");
        sb.append(this.B);
        sb.append(", ref=");
        sb.append(this.C);
        sb.append(", trackCode=");
        sb.append(this.D);
        sb.append(", ordExternalId=");
        sb.append(this.E);
        sb.append(", ordErid=");
        sb.append(this.F);
        sb.append(", isActionButtonRemembered=");
        sb.append(this.G);
        sb.append(", publishSuggestId=");
        sb.append(this.H);
        sb.append(", postId=");
        sb.append(this.I);
        sb.append(", isSignedFromGroup=");
        sb.append(this.J);
        sb.append(", postAuthorUid=");
        sb.append(this.K);
        sb.append(", isExportToFacebook=");
        sb.append(this.L);
        sb.append(", isExportToTwitter=");
        sb.append(this.M);
        sb.append(", draft=");
        sb.append(this.N);
        sb.append(", creationSessionId=");
        sb.append(this.O);
        sb.append(", suggestPostId=");
        sb.append(this.P);
        sb.append(", markAsAds=");
        sb.append(this.Q);
        sb.append(", donutPaidUntil=");
        sb.append(this.R);
        sb.append(", donutLevelId=");
        sb.append(this.S);
        sb.append(", donutTeaserText=");
        sb.append(this.T);
        sb.append(", services=");
        sb.append(this.U);
        sb.append(", attachmentsList=");
        sb.append(this.V);
        sb.append(", posterBkgId=");
        sb.append(this.W);
        sb.append(", posterBkgOwnerId=");
        sb.append(this.X);
        sb.append(", posterBkgAccessHash=");
        return ho8.a(sb, this.Y, ')');
    }
}
