package xsna;

import com.vk.im.engine.models.dialogs.Dialog;
import com.vk.im.engine.models.messages.MessagesType;
import com.vk.im.reporters.api.msg.OpenMessagesHistoryReporter;
import kotlin.Lazy;

/* compiled from: MsgListComponentConfig.kt */
/* loaded from: classes2.dex */
public final class il30 {
    public final h1l A;
    public final gmm B;
    public final e2l0 C;
    public final sxd0 D;
    public final fv9 E;
    public final g5v F;
    public final bbi0 G;
    public final o6p H;
    public final mpo0 I;
    public final izm0 J;
    public final boolean K;
    public final int L;
    public final Integer M;
    public final bof N;
    public final no O;
    public final jmd P;
    public final v1o Q;
    public final ql30 R;
    public final long a;
    public final u90 b;
    public final a1w c;
    public final com.vk.im.engine.models.c d;
    public final f1w e;
    public final lzv f;
    public final mxv g;
    public final zdw h;
    public final js4 i;
    public final Lazy<ir4> j;
    public final Dialog k;
    public final int l;
    public final int m;
    public final boolean n;
    public final boolean o;
    public final boolean p;
    public final boolean q;
    public String r;
    public final kkm s;
    public final w530 t;
    public final z9x0 u;
    public final OpenMessagesHistoryReporter v;
    public final mdz<OpenMessagesHistoryReporter.Span> w;
    public final i2n0 x;
    public final h34 y;
    public final lq4 z;

    public il30(long j, jbs jbsVar, a1w a1wVar, com.vk.im.engine.models.c cVar, f1w f1wVar, lzv lzvVar, mxv mxvVar, zdw zdwVar, js4 js4Var, Lazy lazy, Dialog dialog, int i, boolean z, boolean z2, boolean z3, boolean z4, String str, kkm kkmVar, w530 w530Var, OpenMessagesHistoryReporter openMessagesHistoryReporter, mdz mdzVar, i2n0 i2n0Var, boolean z5, int i2, Integer num, bof bofVar, no noVar, jmd jmdVar, v1o v1oVar, ql30 ql30Var) {
        z9x0 z9x0Var = new z9x0(zdwVar.d.e(), MessagesType.DIALOG, a1wVar, null);
        h34 h34Var = new h34();
        lq4 lq4Var = new lq4();
        h1l h1lVar = new h1l();
        gmm gmmVar = new gmm(new com.vk.movika.sdk.android.defaultplayer.layout.a(jbsVar.a.kn().getApplicationContext()));
        e2l0 e2l0Var = new e2l0();
        sxd0 sxd0Var = new sxd0();
        fv9 fv9Var = new fv9();
        g5v g5vVar = new g5v();
        bbi0 bbi0Var = new bbi0();
        o6p o6pVar = new o6p();
        mpo0 mpo0Var = new mpo0();
        izm0 izm0Var = new izm0();
        this.a = j;
        this.b = jbsVar;
        this.c = a1wVar;
        this.d = cVar;
        this.e = f1wVar;
        this.f = lzvVar;
        this.g = mxvVar;
        this.h = zdwVar;
        this.i = js4Var;
        this.j = lazy;
        this.k = dialog;
        this.l = 50;
        this.m = i;
        this.n = z;
        this.o = z2;
        this.p = z3;
        this.q = z4;
        this.r = str;
        this.s = kkmVar;
        this.t = w530Var;
        this.u = z9x0Var;
        this.v = openMessagesHistoryReporter;
        this.w = mdzVar;
        this.x = i2n0Var;
        this.y = h34Var;
        this.z = lq4Var;
        this.A = h1lVar;
        this.B = gmmVar;
        this.C = e2l0Var;
        this.D = sxd0Var;
        this.E = fv9Var;
        this.F = g5vVar;
        this.G = bbi0Var;
        this.H = o6pVar;
        this.I = mpo0Var;
        this.J = izm0Var;
        this.K = z5;
        this.L = i2;
        this.M = num;
        this.N = bofVar;
        this.O = noVar;
        this.P = jmdVar;
        this.Q = v1oVar;
        this.R = ql30Var;
    }
}
