package xsna;

import com.vk.dto.user.ObsceneTextFilter;
import com.vk.dto.user.UserNameType;
import com.vk.dto.user.UserSex;

/* compiled from: AuthBridge.kt */
/* loaded from: classes.dex */
public final class ms {
    private static final ms STUB = new ms(false, false, false, false, 0, 0, UserSex.UNKNOWN, 0, false, false, false, false, false, 3, 10, 1, 10, false, false, "RUB", 50, 10000, false, false, false, "", "", 0, true, false, 30, false, 0, 0, false, true, true, false, false, false, UserNameType.values()[0], md20.e.getSTUB(), false, ObsceneTextFilter.UNAVAILABLE, null, false, false, false, 8192);
    public final String A;
    public final int B;
    public final boolean C;
    public final boolean D;
    public final int E;
    public final boolean F;
    public final long G;
    public final int H;
    public final boolean I;
    public final boolean J;
    public final boolean L;
    public final boolean M;
    public final boolean N;
    public final boolean O;
    public final UserNameType P;
    public final md20 Q;
    public final boolean R;
    public final ObsceneTextFilter U;
    public final or00 V;
    public final boolean W;
    public final boolean X;
    public final boolean Y;
    public final boolean a;
    public final boolean b;
    public final boolean c;
    public final boolean d;
    public final long e;
    public final long f;
    public final UserSex g;
    public final int h;
    public final boolean i;
    public final boolean j;
    public final boolean k;
    public final boolean l;
    public final boolean m;
    public final int n;
    public final int o;
    public final int p;
    public final int q;
    public final boolean r;
    public final boolean s;
    public final String t;
    public final int u;
    public final int v;
    public final boolean w;
    public final boolean x;
    public final boolean y;
    public final String z;
    public final boolean K = true;
    public final boolean S = true;
    public final boolean T = false;

    public ms(boolean z, boolean z2, boolean z3, boolean z4, long j, long j2, UserSex userSex, int i, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, int i2, int i3, int i4, int i5, boolean z10, boolean z11, String str, int i6, int i7, boolean z12, boolean z13, boolean z14, String str2, String str3, int i8, boolean z15, boolean z16, int i9, boolean z17, long j3, int i10, boolean z18, boolean z19, boolean z20, boolean z21, boolean z22, boolean z23, UserNameType userNameType, md20 md20Var, boolean z24, ObsceneTextFilter obsceneTextFilter, or00 or00Var, boolean z25, boolean z26, boolean z27, int i11) {
        this.a = z;
        this.b = z2;
        this.c = z3;
        this.d = z4;
        this.e = j;
        this.f = j2;
        this.g = userSex;
        this.h = i;
        this.i = z5;
        this.j = z6;
        this.k = z7;
        this.l = z8;
        this.m = z9;
        this.n = i2;
        this.o = i3;
        this.p = i4;
        this.q = i5;
        this.r = z10;
        this.s = z11;
        this.t = str;
        this.u = i6;
        this.v = i7;
        this.w = z12;
        this.x = z13;
        this.y = z14;
        this.z = str2;
        this.A = str3;
        this.B = i8;
        this.C = z15;
        this.D = z16;
        this.E = i9;
        this.F = z17;
        this.G = j3;
        this.H = i10;
        this.I = z18;
        this.J = z19;
        this.L = z20;
        this.M = z21;
        this.N = z22;
        this.O = z23;
        this.P = userNameType;
        this.Q = md20Var;
        this.R = z24;
        this.U = obsceneTextFilter;
        this.V = or00Var;
        this.W = z25;
        this.X = z26;
        this.Y = z27;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof ms)) {
            return false;
        }
        ms msVar = (ms) obj;
        return this.a == msVar.a && this.b == msVar.b && this.c == msVar.c && this.d == msVar.d && this.e == msVar.e && this.f == msVar.f && this.g == msVar.g && this.h == msVar.h && this.i == msVar.i && this.j == msVar.j && this.k == msVar.k && this.l == msVar.l && this.m == msVar.m && this.n == msVar.n && this.o == msVar.o && this.p == msVar.p && this.q == msVar.q && this.r == msVar.r && this.s == msVar.s && epx.f(this.t, msVar.t) && this.u == msVar.u && this.v == msVar.v && this.w == msVar.w && this.x == msVar.x && this.y == msVar.y && epx.f(this.z, msVar.z) && epx.f(this.A, msVar.A) && this.B == msVar.B && this.C == msVar.C && this.D == msVar.D && this.E == msVar.E && this.F == msVar.F && this.G == msVar.G && this.H == msVar.H && this.I == msVar.I && this.J == msVar.J && this.K == msVar.K && this.L == msVar.L && this.M == msVar.M && this.N == msVar.N && this.O == msVar.O && this.P == msVar.P && epx.f(this.Q, msVar.Q) && this.R == msVar.R && this.S == msVar.S && this.T == msVar.T && this.U == msVar.U && epx.f(this.V, msVar.V) && this.W == msVar.W && this.X == msVar.X && this.Y == msVar.Y;
    }

    public final int hashCode() {
        int hashCode = (this.U.hashCode() + qoy.b(qoy.b(qoy.b(qoy.b((this.Q.hashCode() + ((this.P.hashCode() + qoy.b(qoy.b(qoy.b(qoy.b(qoy.b(qoy.b(qoy.b(qoy.b(shy.a(this.H, bh10.a(qoy.b(shy.a(this.E, qoy.b(qoy.b(shy.a(this.B, urd0.a(urd0.a(qoy.b(qoy.b(qoy.b(shy.a(this.v, shy.a(this.u, urd0.a(qoy.b(qoy.b(shy.a(this.q, shy.a(this.p, shy.a(this.o, shy.a(this.n, qoy.b(qoy.b(qoy.b(qoy.b(qoy.b(shy.a(this.h, (this.g.hashCode() + bh10.a(bh10.a(qoy.b(qoy.b(qoy.b(Boolean.hashCode(this.a) * 31, 31, this.b), 31, this.c), 31, this.d), 31, this.e), 31, this.f)) * 31, 31), 31, this.i), 31, this.j), 31, this.k), 31, this.l), 31, this.m), 31), 31), 31), 31), 31, this.r), 31, this.s), 31, this.t), 31), 31), 31, this.w), 31, this.x), 31, this.y), 31, this.z), 31, this.A), 31), 31, this.C), 31, this.D), 31), 31, this.F), 31, this.G), 31), 31, this.I), 31, this.J), 31, this.K), 31, false), 31, this.L), 31, this.M), 31, this.N), 31, this.O)) * 31)) * 31, 31, this.R), 31, false), 31, this.S), 31, this.T)) * 31;
        or00 or00Var = this.V;
        return Boolean.hashCode(this.Y) + qoy.b(qoy.b((hashCode + (or00Var != null ? or00Var.hashCode() : 0)) * 31, 31, this.W), 31, this.X);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("AccountSettings(isAppDeveloper=");
        sb.append(this.a);
        sb.append(", isTester=");
        sb.append(this.b);
        sb.append(", isDebugAvailable=");
        sb.append(this.c);
        sb.append(", isCustomDomainsEnabled=");
        sb.append(this.d);
        sb.append(", sendCommonNetworkStatUntil=");
        sb.append(this.e);
        sb.append(", sendImagesNetworkStatUntil=");
        sb.append(this.f);
        sb.append(", sex=");
        sb.append(this.g);
        sb.append(", country=");
        sb.append(this.h);
        sb.append(", riseToRecordAvailable=");
        sb.append(this.i);
        sb.append(", liveMasksAvailable=");
        sb.append(this.j);
        sb.append(", liveStreamingAvailable=");
        sb.append(this.k);
        sb.append(", cameraPingPong=");
        sb.append(this.l);
        sb.append(", masksAvailable=");
        sb.append(this.m);
        sb.append(", storyMaxHashtags=");
        sb.append(this.n);
        sb.append(", storyMaxMentions=");
        sb.append(this.o);
        sb.append(", storyMaxMusicStickers=");
        sb.append(this.p);
        sb.append(", storyMaxMarketItems=");
        sb.append(this.q);
        sb.append(", storyRepostsAvailable=");
        sb.append(this.r);
        sb.append(", storyRepliesAvailable=");
        sb.append(this.s);
        sb.append(", moneyCurrency=");
        sb.append(this.t);
        sb.append(", moneyTransferMinAmount=");
        sb.append(this.u);
        sb.append(", moneyTransferMaxAmount=");
        sb.append(this.v);
        sb.append(", moneyTransferEnabled=");
        sb.append(this.w);
        sb.append(", moneyTransferToGroupsEnabled=");
        sb.append(this.x);
        sb.append(", vkPayEnabled=");
        sb.append(this.y);
        sb.append(", vkPayEndpoint=");
        sb.append(this.z);
        sb.append(", vkPayEndpointV2=");
        sb.append(this.A);
        sb.append(", vkPayAppId=");
        sb.append(this.B);
        sb.append(", isMusicRestricted=");
        sb.append(this.C);
        sb.append(", hasMusicSubscription=");
        sb.append(this.D);
        sb.append(", audioBackgroundLimit=");
        sb.append(this.E);
        sb.append(", subscriptionComboAllowed=");
        sb.append(this.F);
        sb.append(", musicSubscriptionExpiresDate=");
        sb.append(this.G);
        sb.append(", musicIntroVersion=");
        sb.append(this.H);
        sb.append(", webViewAuthorizationAllowed=");
        sb.append(this.I);
        sb.append(", callsAvailable=");
        sb.append(this.J);
        sb.append(", showCallsMenu=");
        sb.append(this.K);
        sb.append(", videoCallButtonFirst=false, animatedStickersAvailable=");
        sb.append(this.L);
        sb.append(", shareViaFacebookAvailable=");
        sb.append(this.M);
        sb.append(", shareViaTwitterAvailable=");
        sb.append(this.N);
        sb.append(", bugsVkUiAvailable=");
        sb.append(this.O);
        sb.append(", userNameType=");
        sb.append(this.P);
        sb.append(", messagesCounterSettings=");
        sb.append(this.Q);
        sb.append(", isClosedAccount=");
        sb.append(this.R);
        sb.append(", isServiceAccount=false, isMessengerContactsImportEnabled=");
        sb.append(this.S);
        sb.append(", isTeacherVerificationAvailable=");
        sb.append(this.T);
        sb.append(", obsceneTextFilter=");
        sb.append(this.U);
        sb.append(", marketAdultConfig=");
        sb.append(this.V);
        sb.append(", isFollowersModeOn=");
        sb.append(this.W);
        sb.append(", isFollowersModeAvailable=");
        sb.append(this.X);
        sb.append(", canChangePassword=");
        return defpackage.q0.a(sb, this.Y, ')');
    }
}
