package com.yandex.plus.core.graphql.type;

import com.yandex.go.sql.BaseDatabaseHelper;
import defpackage.k4o;
import defpackage.mll0;
import defpackage.p4o;
import defpackage.scc;
import io.appmetrica.analytics.BuildConfig;
import kotlin.Metadata;
import kotlin.enums.a;
import ru.CryptoPro.JCSP.MSCAPI.HProv;
import ru.cprocsp.NGate.tools.Constants;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
@Metadata(d1 = {"\u0000\u0011\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0010\u000e\n\u0003\b\u0081\u0001\b\u0087\u0081\u0002\u0018\u0000 \u00072\b\u0012\u0004\u0012\u00020\u00000\u0001:\u0001\bR\u0017\u0010\u0003\u001a\u00020\u00028\u0006¢\u0006\f\n\u0004\b\u0003\u0010\u0004\u001a\u0004\b\u0005\u0010\u0006j\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bEj\u0002\bFj\u0002\bGj\u0002\bHj\u0002\bIj\u0002\bJj\u0002\bKj\u0002\bLj\u0002\bMj\u0002\bNj\u0002\bOj\u0002\bPj\u0002\bQj\u0002\bRj\u0002\bSj\u0002\bTj\u0002\bUj\u0002\bVj\u0002\bWj\u0002\bXj\u0002\bYj\u0002\bZj\u0002\b[j\u0002\b\\j\u0002\b]j\u0002\b^j\u0002\b_j\u0002\b`j\u0002\baj\u0002\bbj\u0002\bcj\u0002\bdj\u0002\bej\u0002\bfj\u0002\bgj\u0002\bhj\u0002\bij\u0002\bjj\u0002\bkj\u0002\blj\u0002\bmj\u0002\bnj\u0002\boj\u0002\bpj\u0002\bqj\u0002\brj\u0002\bsj\u0002\btj\u0002\buj\u0002\bvj\u0002\bwj\u0002\bxj\u0002\byj\u0002\bzj\u0002\b{j\u0002\b|j\u0002\b}j\u0002\b~j\u0002\b\u007fj\u0003\b\u0080\u0001j\u0003\b\u0081\u0001j\u0003\b\u0082\u0001¨\u0006\u0083\u0001"}, d2 = {"Lcom/yandex/plus/core/graphql/type/SECTION_VIEW_TYPE;", "", "", "rawValue", "Ljava/lang/String;", "a", "()Ljava/lang/String;", "Companion", "mll0", "ACHIEVEMENTS", "ACQUISITION", "ACQUISITION_UNIVERSAL_CARD", "ADVERTISING_AUTOSCROLLER", "BIG_PROMO_CARD", "CASHBACK_HORIZONTAL_CARDS", "CASHBACK_INFO", "CASHBACK_LEVEL", "CASHBACK_LIMITS", "CASHBACK_LOST_BENEFITS", "CASHBACK_PERIOD_PICKER", "CASHBACK_SQUARE_CARDS", "CHECK_LIST", "COLLECT_EMAIL", "COUPONS", "DAILY_DYNAMIC_WIDGET_FULL", "DAILY_DYNAMIC_WIDGET_MINI", "DAILY_INTERNATIONAL_MISSIONS", "DAILY_INTRO", "DAILY_MOMENTS", "DAILY_REWARDS", "DAILY_SUPER_PAGE", "DAILY_SUPER_WIDGET", "DIVIDER", "DOUBLE_CAROUSEL", "DYNAMIC_SQUARE_BLOCKS", "FACTS", "FAMILY_MEMBERS", "FAQ", "FLOATING_BANNER", "FLOATING_BUTTON", "FLOATING_SIDEBUTTON", "HOME_BONUSES_PILL", "HOME_DAILY_BIG_REWARDS", "HOME_DAILY_MISSIONS", "HOME_DAILY_REWARDS", "HOME_EXPERIMENTS", "INFINITE_OFFERS", "INFORMER", "INFORMER_V2", "INFORMER_V3", "LAYOUT_OPTIONS", "LEVELS_MAIN", "LEVELS_QUESTS", "LK_INFORMER", "LOGO", "L_SQUARE_BLOCKS", "MARKET_CATEGORIES", "MARKET_SQUARE_BLOCKS", "MISSIONS", "MOMENTS", "MOSAIC", "M_SQUARE_BLOCKS", "NAV_ANCHORS", "NEWS", "OFFERS", "OFFER_BANNER", "ONBOARDING", "PARTNER_PROMOCODE", "PAYMENT_SELECTION", "PAYWALL", "PAYWALL_BANNER", "PAYWALL_BLOCKS", "PAYWALL_CASHBACK", "PAYWALL_FAQ", "PAYWALL_GET_APP", "PAYWALL_GRID", "PAYWALL_LEGAL", "PAYWALL_OPK_WAITING", "PAYWALL_PROMO", "PAYWALL_SLIDER", "PAYWALL_TABS", "PAY_BUTTON", "PIXEL", "PLUSOMETER_EXPERIENCE_EARNING_INFO", "PLUSOMETER_MISSIONS", "PLUSOMETER_MULTIPLIERS_BRIEF", "PLUSOMETER_MULTIPLIERS_DETAILED", "PLUSOMETER_PRESENTS", "PLUSOMETER_PROGRESS_BAR", "PLUSOMETER_TOOLTIPS", "PLUSUI_CARD_BLOCKS", "PLUSUI_HEADER", "PLUS_BENEFITS", "PLUS_CARD", "PLUS_SERVICES", "PROMOCODE", "PROMOCODE_GRANTOR", "PULT", "QUIZ", "RECTANGLE_BLOCKS", "REFERRAL", "SHOWCASE_FREE", "SPECIAL", "SPEND_SWITCH", "SP_BENEFITS", "SP_BLOCKS", "SP_CONTEST", "SP_HOME_WIDGET", "SP_LEVELS_PROGRESS_BAR", "STATISTICS_FACTS", "STATISTICS_HEADING", "STATISTICS_LOST_BENEFITS", "STATISTICS_MOMENTS_CARD", "STATISTICS_NY", "STATISTICS_SERVICE", "STICKY_BUTTON", "STICKY_MENU", "SUBSCRIPTION_MANAGEMENT", "SUBSCRIPTION_SERVICES_BUTTONS", "S_SQUARE_BLOCKS", "TABLE", BaseDatabaseHelper.TYPE_TEXT, "TITLE", "TOP_OFFERS", "TOP_OFFERS_V2", "UNIVERSAL_CARD", "UNKNOWN", "VERTICAL_INFO_CARDS", "WELCOME", "YANDEX_PAY", "UNKNOWN__", "plus-shared-data-graphql-queries_release"}, k = 1, mv = {2, 2, 0}, xi = 48)
/* loaded from: classes2.dex */
public final class SECTION_VIEW_TYPE {
    private static final /* synthetic */ k4o $ENTRIES;
    private static final /* synthetic */ SECTION_VIEW_TYPE[] $VALUES;
    public static final SECTION_VIEW_TYPE ACHIEVEMENTS;
    public static final SECTION_VIEW_TYPE ACQUISITION;
    public static final SECTION_VIEW_TYPE ACQUISITION_UNIVERSAL_CARD;
    public static final SECTION_VIEW_TYPE ADVERTISING_AUTOSCROLLER;
    public static final SECTION_VIEW_TYPE BIG_PROMO_CARD;
    public static final SECTION_VIEW_TYPE CASHBACK_HORIZONTAL_CARDS;
    public static final SECTION_VIEW_TYPE CASHBACK_INFO;
    public static final SECTION_VIEW_TYPE CASHBACK_LEVEL;
    public static final SECTION_VIEW_TYPE CASHBACK_LIMITS;
    public static final SECTION_VIEW_TYPE CASHBACK_LOST_BENEFITS;
    public static final SECTION_VIEW_TYPE CASHBACK_PERIOD_PICKER;
    public static final SECTION_VIEW_TYPE CASHBACK_SQUARE_CARDS;
    public static final SECTION_VIEW_TYPE CHECK_LIST;
    public static final SECTION_VIEW_TYPE COLLECT_EMAIL;
    public static final SECTION_VIEW_TYPE COUPONS;
    public static final mll0 Companion;
    public static final SECTION_VIEW_TYPE DAILY_DYNAMIC_WIDGET_FULL;
    public static final SECTION_VIEW_TYPE DAILY_DYNAMIC_WIDGET_MINI;
    public static final SECTION_VIEW_TYPE DAILY_INTERNATIONAL_MISSIONS;
    public static final SECTION_VIEW_TYPE DAILY_INTRO;
    public static final SECTION_VIEW_TYPE DAILY_MOMENTS;
    public static final SECTION_VIEW_TYPE DAILY_REWARDS;
    public static final SECTION_VIEW_TYPE DAILY_SUPER_PAGE;
    public static final SECTION_VIEW_TYPE DAILY_SUPER_WIDGET;
    public static final SECTION_VIEW_TYPE DIVIDER;
    public static final SECTION_VIEW_TYPE DOUBLE_CAROUSEL;
    public static final SECTION_VIEW_TYPE DYNAMIC_SQUARE_BLOCKS;
    public static final SECTION_VIEW_TYPE FACTS;
    public static final SECTION_VIEW_TYPE FAMILY_MEMBERS;
    public static final SECTION_VIEW_TYPE FAQ;
    public static final SECTION_VIEW_TYPE FLOATING_BANNER;
    public static final SECTION_VIEW_TYPE FLOATING_BUTTON;
    public static final SECTION_VIEW_TYPE FLOATING_SIDEBUTTON;
    public static final SECTION_VIEW_TYPE HOME_BONUSES_PILL;
    public static final SECTION_VIEW_TYPE HOME_DAILY_BIG_REWARDS;
    public static final SECTION_VIEW_TYPE HOME_DAILY_MISSIONS;
    public static final SECTION_VIEW_TYPE HOME_DAILY_REWARDS;
    public static final SECTION_VIEW_TYPE HOME_EXPERIMENTS;
    public static final SECTION_VIEW_TYPE INFINITE_OFFERS;
    public static final SECTION_VIEW_TYPE INFORMER;
    public static final SECTION_VIEW_TYPE INFORMER_V2;
    public static final SECTION_VIEW_TYPE INFORMER_V3;
    public static final SECTION_VIEW_TYPE LAYOUT_OPTIONS;
    public static final SECTION_VIEW_TYPE LEVELS_MAIN;
    public static final SECTION_VIEW_TYPE LEVELS_QUESTS;
    public static final SECTION_VIEW_TYPE LK_INFORMER;
    public static final SECTION_VIEW_TYPE LOGO;
    public static final SECTION_VIEW_TYPE L_SQUARE_BLOCKS;
    public static final SECTION_VIEW_TYPE MARKET_CATEGORIES;
    public static final SECTION_VIEW_TYPE MARKET_SQUARE_BLOCKS;
    public static final SECTION_VIEW_TYPE MISSIONS;
    public static final SECTION_VIEW_TYPE MOMENTS;
    public static final SECTION_VIEW_TYPE MOSAIC;
    public static final SECTION_VIEW_TYPE M_SQUARE_BLOCKS;
    public static final SECTION_VIEW_TYPE NAV_ANCHORS;
    public static final SECTION_VIEW_TYPE NEWS;
    public static final SECTION_VIEW_TYPE OFFERS;
    public static final SECTION_VIEW_TYPE OFFER_BANNER;
    public static final SECTION_VIEW_TYPE ONBOARDING;
    public static final SECTION_VIEW_TYPE PARTNER_PROMOCODE;
    public static final SECTION_VIEW_TYPE PAYMENT_SELECTION;
    public static final SECTION_VIEW_TYPE PAYWALL;
    public static final SECTION_VIEW_TYPE PAYWALL_BANNER;
    public static final SECTION_VIEW_TYPE PAYWALL_BLOCKS;
    public static final SECTION_VIEW_TYPE PAYWALL_CASHBACK;
    public static final SECTION_VIEW_TYPE PAYWALL_FAQ;
    public static final SECTION_VIEW_TYPE PAYWALL_GET_APP;
    public static final SECTION_VIEW_TYPE PAYWALL_GRID;
    public static final SECTION_VIEW_TYPE PAYWALL_LEGAL;
    public static final SECTION_VIEW_TYPE PAYWALL_OPK_WAITING;
    public static final SECTION_VIEW_TYPE PAYWALL_PROMO;
    public static final SECTION_VIEW_TYPE PAYWALL_SLIDER;
    public static final SECTION_VIEW_TYPE PAYWALL_TABS;
    public static final SECTION_VIEW_TYPE PAY_BUTTON;
    public static final SECTION_VIEW_TYPE PIXEL;
    public static final SECTION_VIEW_TYPE PLUSOMETER_EXPERIENCE_EARNING_INFO;
    public static final SECTION_VIEW_TYPE PLUSOMETER_MISSIONS;
    public static final SECTION_VIEW_TYPE PLUSOMETER_MULTIPLIERS_BRIEF;
    public static final SECTION_VIEW_TYPE PLUSOMETER_MULTIPLIERS_DETAILED;
    public static final SECTION_VIEW_TYPE PLUSOMETER_PRESENTS;
    public static final SECTION_VIEW_TYPE PLUSOMETER_PROGRESS_BAR;
    public static final SECTION_VIEW_TYPE PLUSOMETER_TOOLTIPS;
    public static final SECTION_VIEW_TYPE PLUSUI_CARD_BLOCKS;
    public static final SECTION_VIEW_TYPE PLUSUI_HEADER;
    public static final SECTION_VIEW_TYPE PLUS_BENEFITS;
    public static final SECTION_VIEW_TYPE PLUS_CARD;
    public static final SECTION_VIEW_TYPE PLUS_SERVICES;
    public static final SECTION_VIEW_TYPE PROMOCODE;
    public static final SECTION_VIEW_TYPE PROMOCODE_GRANTOR;
    public static final SECTION_VIEW_TYPE PULT;
    public static final SECTION_VIEW_TYPE QUIZ;
    public static final SECTION_VIEW_TYPE RECTANGLE_BLOCKS;
    public static final SECTION_VIEW_TYPE REFERRAL;
    public static final SECTION_VIEW_TYPE SHOWCASE_FREE;
    public static final SECTION_VIEW_TYPE SPECIAL;
    public static final SECTION_VIEW_TYPE SPEND_SWITCH;
    public static final SECTION_VIEW_TYPE SP_BENEFITS;
    public static final SECTION_VIEW_TYPE SP_BLOCKS;
    public static final SECTION_VIEW_TYPE SP_CONTEST;
    public static final SECTION_VIEW_TYPE SP_HOME_WIDGET;
    public static final SECTION_VIEW_TYPE SP_LEVELS_PROGRESS_BAR;
    public static final SECTION_VIEW_TYPE STATISTICS_FACTS;
    public static final SECTION_VIEW_TYPE STATISTICS_HEADING;
    public static final SECTION_VIEW_TYPE STATISTICS_LOST_BENEFITS;
    public static final SECTION_VIEW_TYPE STATISTICS_MOMENTS_CARD;
    public static final SECTION_VIEW_TYPE STATISTICS_NY;
    public static final SECTION_VIEW_TYPE STATISTICS_SERVICE;
    public static final SECTION_VIEW_TYPE STICKY_BUTTON;
    public static final SECTION_VIEW_TYPE STICKY_MENU;
    public static final SECTION_VIEW_TYPE SUBSCRIPTION_MANAGEMENT;
    public static final SECTION_VIEW_TYPE SUBSCRIPTION_SERVICES_BUTTONS;
    public static final SECTION_VIEW_TYPE S_SQUARE_BLOCKS;
    public static final SECTION_VIEW_TYPE TABLE;
    public static final SECTION_VIEW_TYPE TEXT;
    public static final SECTION_VIEW_TYPE TITLE;
    public static final SECTION_VIEW_TYPE TOP_OFFERS;
    public static final SECTION_VIEW_TYPE TOP_OFFERS_V2;
    public static final SECTION_VIEW_TYPE UNIVERSAL_CARD;
    public static final SECTION_VIEW_TYPE UNKNOWN;
    public static final SECTION_VIEW_TYPE UNKNOWN__;
    public static final SECTION_VIEW_TYPE VERTICAL_INFO_CARDS;
    public static final SECTION_VIEW_TYPE WELCOME;
    public static final SECTION_VIEW_TYPE YANDEX_PAY;
    private static final p4o type;
    private final String rawValue;

    static {
        SECTION_VIEW_TYPE section_view_type = new SECTION_VIEW_TYPE("ACHIEVEMENTS", 0, "ACHIEVEMENTS");
        ACHIEVEMENTS = section_view_type;
        SECTION_VIEW_TYPE section_view_type2 = new SECTION_VIEW_TYPE("ACQUISITION", 1, "ACQUISITION");
        ACQUISITION = section_view_type2;
        SECTION_VIEW_TYPE section_view_type3 = new SECTION_VIEW_TYPE("ACQUISITION_UNIVERSAL_CARD", 2, "ACQUISITION_UNIVERSAL_CARD");
        ACQUISITION_UNIVERSAL_CARD = section_view_type3;
        SECTION_VIEW_TYPE section_view_type4 = new SECTION_VIEW_TYPE("ADVERTISING_AUTOSCROLLER", 3, "ADVERTISING_AUTOSCROLLER");
        ADVERTISING_AUTOSCROLLER = section_view_type4;
        SECTION_VIEW_TYPE section_view_type5 = new SECTION_VIEW_TYPE("BIG_PROMO_CARD", 4, "BIG_PROMO_CARD");
        BIG_PROMO_CARD = section_view_type5;
        SECTION_VIEW_TYPE section_view_type6 = new SECTION_VIEW_TYPE("CASHBACK_HORIZONTAL_CARDS", 5, "CASHBACK_HORIZONTAL_CARDS");
        CASHBACK_HORIZONTAL_CARDS = section_view_type6;
        SECTION_VIEW_TYPE section_view_type7 = new SECTION_VIEW_TYPE("CASHBACK_INFO", 6, "CASHBACK_INFO");
        CASHBACK_INFO = section_view_type7;
        SECTION_VIEW_TYPE section_view_type8 = new SECTION_VIEW_TYPE("CASHBACK_LEVEL", 7, "CASHBACK_LEVEL");
        CASHBACK_LEVEL = section_view_type8;
        SECTION_VIEW_TYPE section_view_type9 = new SECTION_VIEW_TYPE("CASHBACK_LIMITS", 8, "CASHBACK_LIMITS");
        CASHBACK_LIMITS = section_view_type9;
        SECTION_VIEW_TYPE section_view_type10 = new SECTION_VIEW_TYPE("CASHBACK_LOST_BENEFITS", 9, "CASHBACK_LOST_BENEFITS");
        CASHBACK_LOST_BENEFITS = section_view_type10;
        SECTION_VIEW_TYPE section_view_type11 = new SECTION_VIEW_TYPE("CASHBACK_PERIOD_PICKER", 10, "CASHBACK_PERIOD_PICKER");
        CASHBACK_PERIOD_PICKER = section_view_type11;
        SECTION_VIEW_TYPE section_view_type12 = new SECTION_VIEW_TYPE("CASHBACK_SQUARE_CARDS", 11, "CASHBACK_SQUARE_CARDS");
        CASHBACK_SQUARE_CARDS = section_view_type12;
        SECTION_VIEW_TYPE section_view_type13 = new SECTION_VIEW_TYPE("CHECK_LIST", 12, "CHECK_LIST");
        CHECK_LIST = section_view_type13;
        SECTION_VIEW_TYPE section_view_type14 = new SECTION_VIEW_TYPE("COLLECT_EMAIL", 13, "COLLECT_EMAIL");
        COLLECT_EMAIL = section_view_type14;
        SECTION_VIEW_TYPE section_view_type15 = new SECTION_VIEW_TYPE("COUPONS", 14, "COUPONS");
        COUPONS = section_view_type15;
        SECTION_VIEW_TYPE section_view_type16 = new SECTION_VIEW_TYPE("DAILY_DYNAMIC_WIDGET_FULL", 15, "DAILY_DYNAMIC_WIDGET_FULL");
        DAILY_DYNAMIC_WIDGET_FULL = section_view_type16;
        SECTION_VIEW_TYPE section_view_type17 = new SECTION_VIEW_TYPE("DAILY_DYNAMIC_WIDGET_MINI", 16, "DAILY_DYNAMIC_WIDGET_MINI");
        DAILY_DYNAMIC_WIDGET_MINI = section_view_type17;
        SECTION_VIEW_TYPE section_view_type18 = new SECTION_VIEW_TYPE("DAILY_INTERNATIONAL_MISSIONS", 17, "DAILY_INTERNATIONAL_MISSIONS");
        DAILY_INTERNATIONAL_MISSIONS = section_view_type18;
        SECTION_VIEW_TYPE section_view_type19 = new SECTION_VIEW_TYPE("DAILY_INTRO", 18, "DAILY_INTRO");
        DAILY_INTRO = section_view_type19;
        SECTION_VIEW_TYPE section_view_type20 = new SECTION_VIEW_TYPE("DAILY_MOMENTS", 19, "DAILY_MOMENTS");
        DAILY_MOMENTS = section_view_type20;
        SECTION_VIEW_TYPE section_view_type21 = new SECTION_VIEW_TYPE("DAILY_REWARDS", 20, "DAILY_REWARDS");
        DAILY_REWARDS = section_view_type21;
        SECTION_VIEW_TYPE section_view_type22 = new SECTION_VIEW_TYPE("DAILY_SUPER_PAGE", 21, "DAILY_SUPER_PAGE");
        DAILY_SUPER_PAGE = section_view_type22;
        SECTION_VIEW_TYPE section_view_type23 = new SECTION_VIEW_TYPE("DAILY_SUPER_WIDGET", 22, "DAILY_SUPER_WIDGET");
        DAILY_SUPER_WIDGET = section_view_type23;
        SECTION_VIEW_TYPE section_view_type24 = new SECTION_VIEW_TYPE("DIVIDER", 23, "DIVIDER");
        DIVIDER = section_view_type24;
        SECTION_VIEW_TYPE section_view_type25 = new SECTION_VIEW_TYPE("DOUBLE_CAROUSEL", 24, "DOUBLE_CAROUSEL");
        DOUBLE_CAROUSEL = section_view_type25;
        SECTION_VIEW_TYPE section_view_type26 = new SECTION_VIEW_TYPE("DYNAMIC_SQUARE_BLOCKS", 25, "DYNAMIC_SQUARE_BLOCKS");
        DYNAMIC_SQUARE_BLOCKS = section_view_type26;
        SECTION_VIEW_TYPE section_view_type27 = new SECTION_VIEW_TYPE("FACTS", 26, "FACTS");
        FACTS = section_view_type27;
        SECTION_VIEW_TYPE section_view_type28 = new SECTION_VIEW_TYPE("FAMILY_MEMBERS", 27, "FAMILY_MEMBERS");
        FAMILY_MEMBERS = section_view_type28;
        SECTION_VIEW_TYPE section_view_type29 = new SECTION_VIEW_TYPE("FAQ", 28, "FAQ");
        FAQ = section_view_type29;
        SECTION_VIEW_TYPE section_view_type30 = new SECTION_VIEW_TYPE("FLOATING_BANNER", 29, "FLOATING_BANNER");
        FLOATING_BANNER = section_view_type30;
        SECTION_VIEW_TYPE section_view_type31 = new SECTION_VIEW_TYPE("FLOATING_BUTTON", 30, "FLOATING_BUTTON");
        FLOATING_BUTTON = section_view_type31;
        SECTION_VIEW_TYPE section_view_type32 = new SECTION_VIEW_TYPE("FLOATING_SIDEBUTTON", 31, "FLOATING_SIDEBUTTON");
        FLOATING_SIDEBUTTON = section_view_type32;
        SECTION_VIEW_TYPE section_view_type33 = new SECTION_VIEW_TYPE("HOME_BONUSES_PILL", 32, "HOME_BONUSES_PILL");
        HOME_BONUSES_PILL = section_view_type33;
        SECTION_VIEW_TYPE section_view_type34 = new SECTION_VIEW_TYPE("HOME_DAILY_BIG_REWARDS", 33, "HOME_DAILY_BIG_REWARDS");
        HOME_DAILY_BIG_REWARDS = section_view_type34;
        SECTION_VIEW_TYPE section_view_type35 = new SECTION_VIEW_TYPE("HOME_DAILY_MISSIONS", 34, "HOME_DAILY_MISSIONS");
        HOME_DAILY_MISSIONS = section_view_type35;
        SECTION_VIEW_TYPE section_view_type36 = new SECTION_VIEW_TYPE("HOME_DAILY_REWARDS", 35, "HOME_DAILY_REWARDS");
        HOME_DAILY_REWARDS = section_view_type36;
        SECTION_VIEW_TYPE section_view_type37 = new SECTION_VIEW_TYPE("HOME_EXPERIMENTS", 36, "HOME_EXPERIMENTS");
        HOME_EXPERIMENTS = section_view_type37;
        SECTION_VIEW_TYPE section_view_type38 = new SECTION_VIEW_TYPE("INFINITE_OFFERS", 37, "INFINITE_OFFERS");
        INFINITE_OFFERS = section_view_type38;
        SECTION_VIEW_TYPE section_view_type39 = new SECTION_VIEW_TYPE("INFORMER", 38, "INFORMER");
        INFORMER = section_view_type39;
        SECTION_VIEW_TYPE section_view_type40 = new SECTION_VIEW_TYPE("INFORMER_V2", 39, "INFORMER_V2");
        INFORMER_V2 = section_view_type40;
        SECTION_VIEW_TYPE section_view_type41 = new SECTION_VIEW_TYPE("INFORMER_V3", 40, "INFORMER_V3");
        INFORMER_V3 = section_view_type41;
        SECTION_VIEW_TYPE section_view_type42 = new SECTION_VIEW_TYPE("LAYOUT_OPTIONS", 41, "LAYOUT_OPTIONS");
        LAYOUT_OPTIONS = section_view_type42;
        SECTION_VIEW_TYPE section_view_type43 = new SECTION_VIEW_TYPE("LEVELS_MAIN", 42, "LEVELS_MAIN");
        LEVELS_MAIN = section_view_type43;
        SECTION_VIEW_TYPE section_view_type44 = new SECTION_VIEW_TYPE("LEVELS_QUESTS", 43, "LEVELS_QUESTS");
        LEVELS_QUESTS = section_view_type44;
        SECTION_VIEW_TYPE section_view_type45 = new SECTION_VIEW_TYPE("LK_INFORMER", 44, "LK_INFORMER");
        LK_INFORMER = section_view_type45;
        SECTION_VIEW_TYPE section_view_type46 = new SECTION_VIEW_TYPE("LOGO", 45, "LOGO");
        LOGO = section_view_type46;
        SECTION_VIEW_TYPE section_view_type47 = new SECTION_VIEW_TYPE("L_SQUARE_BLOCKS", 46, "L_SQUARE_BLOCKS");
        L_SQUARE_BLOCKS = section_view_type47;
        SECTION_VIEW_TYPE section_view_type48 = new SECTION_VIEW_TYPE("MARKET_CATEGORIES", 47, "MARKET_CATEGORIES");
        MARKET_CATEGORIES = section_view_type48;
        SECTION_VIEW_TYPE section_view_type49 = new SECTION_VIEW_TYPE("MARKET_SQUARE_BLOCKS", 48, "MARKET_SQUARE_BLOCKS");
        MARKET_SQUARE_BLOCKS = section_view_type49;
        SECTION_VIEW_TYPE section_view_type50 = new SECTION_VIEW_TYPE("MISSIONS", 49, "MISSIONS");
        MISSIONS = section_view_type50;
        SECTION_VIEW_TYPE section_view_type51 = new SECTION_VIEW_TYPE("MOMENTS", 50, "MOMENTS");
        MOMENTS = section_view_type51;
        SECTION_VIEW_TYPE section_view_type52 = new SECTION_VIEW_TYPE("MOSAIC", 51, "MOSAIC");
        MOSAIC = section_view_type52;
        SECTION_VIEW_TYPE section_view_type53 = new SECTION_VIEW_TYPE("M_SQUARE_BLOCKS", 52, "M_SQUARE_BLOCKS");
        M_SQUARE_BLOCKS = section_view_type53;
        SECTION_VIEW_TYPE section_view_type54 = new SECTION_VIEW_TYPE("NAV_ANCHORS", 53, "NAV_ANCHORS");
        NAV_ANCHORS = section_view_type54;
        SECTION_VIEW_TYPE section_view_type55 = new SECTION_VIEW_TYPE("NEWS", 54, "NEWS");
        NEWS = section_view_type55;
        SECTION_VIEW_TYPE section_view_type56 = new SECTION_VIEW_TYPE("OFFERS", 55, "OFFERS");
        OFFERS = section_view_type56;
        SECTION_VIEW_TYPE section_view_type57 = new SECTION_VIEW_TYPE("OFFER_BANNER", 56, "OFFER_BANNER");
        OFFER_BANNER = section_view_type57;
        SECTION_VIEW_TYPE section_view_type58 = new SECTION_VIEW_TYPE("ONBOARDING", 57, "ONBOARDING");
        ONBOARDING = section_view_type58;
        SECTION_VIEW_TYPE section_view_type59 = new SECTION_VIEW_TYPE("PARTNER_PROMOCODE", 58, "PARTNER_PROMOCODE");
        PARTNER_PROMOCODE = section_view_type59;
        SECTION_VIEW_TYPE section_view_type60 = new SECTION_VIEW_TYPE("PAYMENT_SELECTION", 59, "PAYMENT_SELECTION");
        PAYMENT_SELECTION = section_view_type60;
        SECTION_VIEW_TYPE section_view_type61 = new SECTION_VIEW_TYPE("PAYWALL", 60, "PAYWALL");
        PAYWALL = section_view_type61;
        SECTION_VIEW_TYPE section_view_type62 = new SECTION_VIEW_TYPE("PAYWALL_BANNER", 61, "PAYWALL_BANNER");
        PAYWALL_BANNER = section_view_type62;
        SECTION_VIEW_TYPE section_view_type63 = new SECTION_VIEW_TYPE("PAYWALL_BLOCKS", 62, "PAYWALL_BLOCKS");
        PAYWALL_BLOCKS = section_view_type63;
        SECTION_VIEW_TYPE section_view_type64 = new SECTION_VIEW_TYPE("PAYWALL_CASHBACK", 63, "PAYWALL_CASHBACK");
        PAYWALL_CASHBACK = section_view_type64;
        SECTION_VIEW_TYPE section_view_type65 = new SECTION_VIEW_TYPE("PAYWALL_FAQ", 64, "PAYWALL_FAQ");
        PAYWALL_FAQ = section_view_type65;
        SECTION_VIEW_TYPE section_view_type66 = new SECTION_VIEW_TYPE("PAYWALL_GET_APP", 65, "PAYWALL_GET_APP");
        PAYWALL_GET_APP = section_view_type66;
        SECTION_VIEW_TYPE section_view_type67 = new SECTION_VIEW_TYPE("PAYWALL_GRID", 66, "PAYWALL_GRID");
        PAYWALL_GRID = section_view_type67;
        SECTION_VIEW_TYPE section_view_type68 = new SECTION_VIEW_TYPE("PAYWALL_LEGAL", 67, "PAYWALL_LEGAL");
        PAYWALL_LEGAL = section_view_type68;
        SECTION_VIEW_TYPE section_view_type69 = new SECTION_VIEW_TYPE("PAYWALL_OPK_WAITING", 68, "PAYWALL_OPK_WAITING");
        PAYWALL_OPK_WAITING = section_view_type69;
        SECTION_VIEW_TYPE section_view_type70 = new SECTION_VIEW_TYPE("PAYWALL_PROMO", 69, "PAYWALL_PROMO");
        PAYWALL_PROMO = section_view_type70;
        SECTION_VIEW_TYPE section_view_type71 = new SECTION_VIEW_TYPE("PAYWALL_SLIDER", 70, "PAYWALL_SLIDER");
        PAYWALL_SLIDER = section_view_type71;
        SECTION_VIEW_TYPE section_view_type72 = new SECTION_VIEW_TYPE("PAYWALL_TABS", 71, "PAYWALL_TABS");
        PAYWALL_TABS = section_view_type72;
        SECTION_VIEW_TYPE section_view_type73 = new SECTION_VIEW_TYPE("PAY_BUTTON", 72, "PAY_BUTTON");
        PAY_BUTTON = section_view_type73;
        SECTION_VIEW_TYPE section_view_type74 = new SECTION_VIEW_TYPE("PIXEL", 73, "PIXEL");
        PIXEL = section_view_type74;
        SECTION_VIEW_TYPE section_view_type75 = new SECTION_VIEW_TYPE("PLUSOMETER_EXPERIENCE_EARNING_INFO", 74, "PLUSOMETER_EXPERIENCE_EARNING_INFO");
        PLUSOMETER_EXPERIENCE_EARNING_INFO = section_view_type75;
        SECTION_VIEW_TYPE section_view_type76 = new SECTION_VIEW_TYPE("PLUSOMETER_MISSIONS", 75, "PLUSOMETER_MISSIONS");
        PLUSOMETER_MISSIONS = section_view_type76;
        SECTION_VIEW_TYPE section_view_type77 = new SECTION_VIEW_TYPE("PLUSOMETER_MULTIPLIERS_BRIEF", 76, "PLUSOMETER_MULTIPLIERS_BRIEF");
        PLUSOMETER_MULTIPLIERS_BRIEF = section_view_type77;
        SECTION_VIEW_TYPE section_view_type78 = new SECTION_VIEW_TYPE("PLUSOMETER_MULTIPLIERS_DETAILED", 77, "PLUSOMETER_MULTIPLIERS_DETAILED");
        PLUSOMETER_MULTIPLIERS_DETAILED = section_view_type78;
        SECTION_VIEW_TYPE section_view_type79 = new SECTION_VIEW_TYPE("PLUSOMETER_PRESENTS", 78, "PLUSOMETER_PRESENTS");
        PLUSOMETER_PRESENTS = section_view_type79;
        SECTION_VIEW_TYPE section_view_type80 = new SECTION_VIEW_TYPE("PLUSOMETER_PROGRESS_BAR", 79, "PLUSOMETER_PROGRESS_BAR");
        PLUSOMETER_PROGRESS_BAR = section_view_type80;
        SECTION_VIEW_TYPE section_view_type81 = new SECTION_VIEW_TYPE("PLUSOMETER_TOOLTIPS", 80, "PLUSOMETER_TOOLTIPS");
        PLUSOMETER_TOOLTIPS = section_view_type81;
        SECTION_VIEW_TYPE section_view_type82 = new SECTION_VIEW_TYPE("PLUSUI_CARD_BLOCKS", 81, "PLUSUI_CARD_BLOCKS");
        PLUSUI_CARD_BLOCKS = section_view_type82;
        SECTION_VIEW_TYPE section_view_type83 = new SECTION_VIEW_TYPE("PLUSUI_HEADER", 82, "PLUSUI_HEADER");
        PLUSUI_HEADER = section_view_type83;
        SECTION_VIEW_TYPE section_view_type84 = new SECTION_VIEW_TYPE("PLUS_BENEFITS", 83, "PLUS_BENEFITS");
        PLUS_BENEFITS = section_view_type84;
        SECTION_VIEW_TYPE section_view_type85 = new SECTION_VIEW_TYPE("PLUS_CARD", 84, "PLUS_CARD");
        PLUS_CARD = section_view_type85;
        SECTION_VIEW_TYPE section_view_type86 = new SECTION_VIEW_TYPE("PLUS_SERVICES", 85, "PLUS_SERVICES");
        PLUS_SERVICES = section_view_type86;
        SECTION_VIEW_TYPE section_view_type87 = new SECTION_VIEW_TYPE("PROMOCODE", 86, "PROMOCODE");
        PROMOCODE = section_view_type87;
        SECTION_VIEW_TYPE section_view_type88 = new SECTION_VIEW_TYPE("PROMOCODE_GRANTOR", 87, "PROMOCODE_GRANTOR");
        PROMOCODE_GRANTOR = section_view_type88;
        SECTION_VIEW_TYPE section_view_type89 = new SECTION_VIEW_TYPE("PULT", 88, "PULT");
        PULT = section_view_type89;
        SECTION_VIEW_TYPE section_view_type90 = new SECTION_VIEW_TYPE("QUIZ", 89, "QUIZ");
        QUIZ = section_view_type90;
        SECTION_VIEW_TYPE section_view_type91 = new SECTION_VIEW_TYPE("RECTANGLE_BLOCKS", 90, "RECTANGLE_BLOCKS");
        RECTANGLE_BLOCKS = section_view_type91;
        SECTION_VIEW_TYPE section_view_type92 = new SECTION_VIEW_TYPE("REFERRAL", 91, "REFERRAL");
        REFERRAL = section_view_type92;
        SECTION_VIEW_TYPE section_view_type93 = new SECTION_VIEW_TYPE("SHOWCASE_FREE", 92, "SHOWCASE_FREE");
        SHOWCASE_FREE = section_view_type93;
        SECTION_VIEW_TYPE section_view_type94 = new SECTION_VIEW_TYPE("SPECIAL", 93, "SPECIAL");
        SPECIAL = section_view_type94;
        SECTION_VIEW_TYPE section_view_type95 = new SECTION_VIEW_TYPE("SPEND_SWITCH", 94, "SPEND_SWITCH");
        SPEND_SWITCH = section_view_type95;
        SECTION_VIEW_TYPE section_view_type96 = new SECTION_VIEW_TYPE("SP_BENEFITS", 95, "SP_BENEFITS");
        SP_BENEFITS = section_view_type96;
        SECTION_VIEW_TYPE section_view_type97 = new SECTION_VIEW_TYPE("SP_BLOCKS", 96, "SP_BLOCKS");
        SP_BLOCKS = section_view_type97;
        SECTION_VIEW_TYPE section_view_type98 = new SECTION_VIEW_TYPE("SP_CONTEST", 97, "SP_CONTEST");
        SP_CONTEST = section_view_type98;
        SECTION_VIEW_TYPE section_view_type99 = new SECTION_VIEW_TYPE("SP_HOME_WIDGET", 98, "SP_HOME_WIDGET");
        SP_HOME_WIDGET = section_view_type99;
        SECTION_VIEW_TYPE section_view_type100 = new SECTION_VIEW_TYPE("SP_LEVELS_PROGRESS_BAR", 99, "SP_LEVELS_PROGRESS_BAR");
        SP_LEVELS_PROGRESS_BAR = section_view_type100;
        SECTION_VIEW_TYPE section_view_type101 = new SECTION_VIEW_TYPE("STATISTICS_FACTS", 100, "STATISTICS_FACTS");
        STATISTICS_FACTS = section_view_type101;
        SECTION_VIEW_TYPE section_view_type102 = new SECTION_VIEW_TYPE("STATISTICS_HEADING", 101, "STATISTICS_HEADING");
        STATISTICS_HEADING = section_view_type102;
        SECTION_VIEW_TYPE section_view_type103 = new SECTION_VIEW_TYPE("STATISTICS_LOST_BENEFITS", 102, "STATISTICS_LOST_BENEFITS");
        STATISTICS_LOST_BENEFITS = section_view_type103;
        SECTION_VIEW_TYPE section_view_type104 = new SECTION_VIEW_TYPE("STATISTICS_MOMENTS_CARD", 103, "STATISTICS_MOMENTS_CARD");
        STATISTICS_MOMENTS_CARD = section_view_type104;
        SECTION_VIEW_TYPE section_view_type105 = new SECTION_VIEW_TYPE("STATISTICS_NY", 104, "STATISTICS_NY");
        STATISTICS_NY = section_view_type105;
        SECTION_VIEW_TYPE section_view_type106 = new SECTION_VIEW_TYPE("STATISTICS_SERVICE", 105, "STATISTICS_SERVICE");
        STATISTICS_SERVICE = section_view_type106;
        SECTION_VIEW_TYPE section_view_type107 = new SECTION_VIEW_TYPE("STICKY_BUTTON", 106, "STICKY_BUTTON");
        STICKY_BUTTON = section_view_type107;
        SECTION_VIEW_TYPE section_view_type108 = new SECTION_VIEW_TYPE("STICKY_MENU", HProv.PP_SET_PIN, "STICKY_MENU");
        STICKY_MENU = section_view_type108;
        SECTION_VIEW_TYPE section_view_type109 = new SECTION_VIEW_TYPE("SUBSCRIPTION_MANAGEMENT", 108, "SUBSCRIPTION_MANAGEMENT");
        SUBSCRIPTION_MANAGEMENT = section_view_type109;
        SECTION_VIEW_TYPE section_view_type110 = new SECTION_VIEW_TYPE("SUBSCRIPTION_SERVICES_BUTTONS", 109, "SUBSCRIPTION_SERVICES_BUTTONS");
        SUBSCRIPTION_SERVICES_BUTTONS = section_view_type110;
        SECTION_VIEW_TYPE section_view_type111 = new SECTION_VIEW_TYPE("S_SQUARE_BLOCKS", 110, "S_SQUARE_BLOCKS");
        S_SQUARE_BLOCKS = section_view_type111;
        SECTION_VIEW_TYPE section_view_type112 = new SECTION_VIEW_TYPE("TABLE", 111, "TABLE");
        TABLE = section_view_type112;
        SECTION_VIEW_TYPE section_view_type113 = new SECTION_VIEW_TYPE(BaseDatabaseHelper.TYPE_TEXT, 112, BaseDatabaseHelper.TYPE_TEXT);
        TEXT = section_view_type113;
        SECTION_VIEW_TYPE section_view_type114 = new SECTION_VIEW_TYPE("TITLE", 113, "TITLE");
        TITLE = section_view_type114;
        SECTION_VIEW_TYPE section_view_type115 = new SECTION_VIEW_TYPE("TOP_OFFERS", 114, "TOP_OFFERS");
        TOP_OFFERS = section_view_type115;
        SECTION_VIEW_TYPE section_view_type116 = new SECTION_VIEW_TYPE("TOP_OFFERS_V2", HProv.PP_CACHE_SIZE, "TOP_OFFERS_V2");
        TOP_OFFERS_V2 = section_view_type116;
        SECTION_VIEW_TYPE section_view_type117 = new SECTION_VIEW_TYPE("UNIVERSAL_CARD", BuildConfig.API_LEVEL, "UNIVERSAL_CARD");
        UNIVERSAL_CARD = section_view_type117;
        SECTION_VIEW_TYPE section_view_type118 = new SECTION_VIEW_TYPE("UNKNOWN", HProv.PP_NK_SYNC, "UNKNOWN");
        UNKNOWN = section_view_type118;
        SECTION_VIEW_TYPE section_view_type119 = new SECTION_VIEW_TYPE("VERTICAL_INFO_CARDS", HProv.PP_INFO, "VERTICAL_INFO_CARDS");
        VERTICAL_INFO_CARDS = section_view_type119;
        SECTION_VIEW_TYPE section_view_type120 = new SECTION_VIEW_TYPE("WELCOME", 119, "WELCOME");
        WELCOME = section_view_type120;
        SECTION_VIEW_TYPE section_view_type121 = new SECTION_VIEW_TYPE("YANDEX_PAY", 120, "YANDEX_PAY");
        YANDEX_PAY = section_view_type121;
        SECTION_VIEW_TYPE section_view_type122 = new SECTION_VIEW_TYPE("UNKNOWN__", Constants.VPN_TRAFFIC, "UNKNOWN__");
        UNKNOWN__ = section_view_type122;
        SECTION_VIEW_TYPE[] section_view_typeArr = {section_view_type, section_view_type2, section_view_type3, section_view_type4, section_view_type5, section_view_type6, section_view_type7, section_view_type8, section_view_type9, section_view_type10, section_view_type11, section_view_type12, section_view_type13, section_view_type14, section_view_type15, section_view_type16, section_view_type17, section_view_type18, section_view_type19, section_view_type20, section_view_type21, section_view_type22, section_view_type23, section_view_type24, section_view_type25, section_view_type26, section_view_type27, section_view_type28, section_view_type29, section_view_type30, section_view_type31, section_view_type32, section_view_type33, section_view_type34, section_view_type35, section_view_type36, section_view_type37, section_view_type38, section_view_type39, section_view_type40, section_view_type41, section_view_type42, section_view_type43, section_view_type44, section_view_type45, section_view_type46, section_view_type47, section_view_type48, section_view_type49, section_view_type50, section_view_type51, section_view_type52, section_view_type53, section_view_type54, section_view_type55, section_view_type56, section_view_type57, section_view_type58, section_view_type59, section_view_type60, section_view_type61, section_view_type62, section_view_type63, section_view_type64, section_view_type65, section_view_type66, section_view_type67, section_view_type68, section_view_type69, section_view_type70, section_view_type71, section_view_type72, section_view_type73, section_view_type74, section_view_type75, section_view_type76, section_view_type77, section_view_type78, section_view_type79, section_view_type80, section_view_type81, section_view_type82, section_view_type83, section_view_type84, section_view_type85, section_view_type86, section_view_type87, section_view_type88, section_view_type89, section_view_type90, section_view_type91, section_view_type92, section_view_type93, section_view_type94, section_view_type95, section_view_type96, section_view_type97, section_view_type98, section_view_type99, section_view_type100, section_view_type101, section_view_type102, section_view_type103, section_view_type104, section_view_type105, section_view_type106, section_view_type107, section_view_type108, section_view_type109, section_view_type110, section_view_type111, section_view_type112, section_view_type113, section_view_type114, section_view_type115, section_view_type116, section_view_type117, section_view_type118, section_view_type119, section_view_type120, section_view_type121, section_view_type122};
        $VALUES = section_view_typeArr;
        $ENTRIES = a.a(section_view_typeArr);
        Companion = new mll0();
        scc.g("ACHIEVEMENTS", "ACQUISITION", "ACQUISITION_UNIVERSAL_CARD", "ADVERTISING_AUTOSCROLLER", "BIG_PROMO_CARD", "CASHBACK_HORIZONTAL_CARDS", "CASHBACK_INFO", "CASHBACK_LEVEL", "CASHBACK_LIMITS", "CASHBACK_LOST_BENEFITS", "CASHBACK_PERIOD_PICKER", "CASHBACK_SQUARE_CARDS", "CHECK_LIST", "COLLECT_EMAIL", "COUPONS", "DAILY_DYNAMIC_WIDGET_FULL", "DAILY_DYNAMIC_WIDGET_MINI", "DAILY_INTERNATIONAL_MISSIONS", "DAILY_INTRO", "DAILY_MOMENTS", "DAILY_REWARDS", "DAILY_SUPER_PAGE", "DAILY_SUPER_WIDGET", "DIVIDER", "DOUBLE_CAROUSEL", "DYNAMIC_SQUARE_BLOCKS", "FACTS", "FAMILY_MEMBERS", "FAQ", "FLOATING_BANNER", "FLOATING_BUTTON", "FLOATING_SIDEBUTTON", "HOME_BONUSES_PILL", "HOME_DAILY_BIG_REWARDS", "HOME_DAILY_MISSIONS", "HOME_DAILY_REWARDS", "HOME_EXPERIMENTS", "INFINITE_OFFERS", "INFORMER", "INFORMER_V2", "INFORMER_V3", "LAYOUT_OPTIONS", "LEVELS_MAIN", "LEVELS_QUESTS", "LK_INFORMER", "LOGO", "L_SQUARE_BLOCKS", "MARKET_CATEGORIES", "MARKET_SQUARE_BLOCKS", "MISSIONS", "MOMENTS", "MOSAIC", "M_SQUARE_BLOCKS", "NAV_ANCHORS", "NEWS", "OFFERS", "OFFER_BANNER", "ONBOARDING", "PARTNER_PROMOCODE", "PAYMENT_SELECTION", "PAYWALL", "PAYWALL_BANNER", "PAYWALL_BLOCKS", "PAYWALL_CASHBACK", "PAYWALL_FAQ", "PAYWALL_GET_APP", "PAYWALL_GRID", "PAYWALL_LEGAL", "PAYWALL_OPK_WAITING", "PAYWALL_PROMO", "PAYWALL_SLIDER", "PAYWALL_TABS", "PAY_BUTTON", "PIXEL", "PLUSOMETER_EXPERIENCE_EARNING_INFO", "PLUSOMETER_MISSIONS", "PLUSOMETER_MULTIPLIERS_BRIEF", "PLUSOMETER_MULTIPLIERS_DETAILED", "PLUSOMETER_PRESENTS", "PLUSOMETER_PROGRESS_BAR", "PLUSOMETER_TOOLTIPS", "PLUSUI_CARD_BLOCKS", "PLUSUI_HEADER", "PLUS_BENEFITS", "PLUS_CARD", "PLUS_SERVICES", "PROMOCODE", "PROMOCODE_GRANTOR", "PULT", "QUIZ", "RECTANGLE_BLOCKS", "REFERRAL", "SHOWCASE_FREE", "SPECIAL", "SPEND_SWITCH", "SP_BENEFITS", "SP_BLOCKS", "SP_CONTEST", "SP_HOME_WIDGET", "SP_LEVELS_PROGRESS_BAR", "STATISTICS_FACTS", "STATISTICS_HEADING", "STATISTICS_LOST_BENEFITS", "STATISTICS_MOMENTS_CARD", "STATISTICS_NY", "STATISTICS_SERVICE", "STICKY_BUTTON", "STICKY_MENU", "SUBSCRIPTION_MANAGEMENT", "SUBSCRIPTION_SERVICES_BUTTONS", "S_SQUARE_BLOCKS", "TABLE", BaseDatabaseHelper.TYPE_TEXT, "TITLE", "TOP_OFFERS", "TOP_OFFERS_V2", "UNIVERSAL_CARD", "UNKNOWN", "VERTICAL_INFO_CARDS", "WELCOME", "YANDEX_PAY");
        type = new p4o("SECTION_VIEW_TYPE");
    }

    public SECTION_VIEW_TYPE(String str, int i, String str2) {
        this.rawValue = str2;
    }

    public static SECTION_VIEW_TYPE valueOf(String str) {
        return (SECTION_VIEW_TYPE) Enum.valueOf(SECTION_VIEW_TYPE.class, str);
    }

    public static SECTION_VIEW_TYPE[] values() {
        return (SECTION_VIEW_TYPE[]) $VALUES.clone();
    }

    /* renamed from: a, reason: from getter */
    public final String getRawValue() {
        return this.rawValue;
    }
}
