package org.maplibre.android;

import ru.ozon.app.android.R;

/* loaded from: classes10.dex */
public final class e {

    /* renamed from: a, reason: collision with root package name */
    public static int[] f79622a = {R.attr.maplibre_bl_arrowDirection, R.attr.maplibre_bl_arrowHeight, R.attr.maplibre_bl_arrowPosition, R.attr.maplibre_bl_arrowWidth, R.attr.maplibre_bl_bubbleColor, R.attr.maplibre_bl_cornersRadius, R.attr.maplibre_bl_strokeColor, R.attr.maplibre_bl_strokeWidth};

    /* renamed from: b, reason: collision with root package name */
    public static int[] f79623b = {R.attr.maplibre_actionJournalEnabled, R.attr.maplibre_actionJournalLogFileCount, R.attr.maplibre_actionJournalLogFileSize, R.attr.maplibre_actionJournalRenderingReportInterval, R.attr.maplibre_apiBaseUri, R.attr.maplibre_apiBaseUrl, R.attr.maplibre_cameraBearing, R.attr.maplibre_cameraCenterAltitude, R.attr.maplibre_cameraFov, R.attr.maplibre_cameraPitchMax, R.attr.maplibre_cameraPitchMin, R.attr.maplibre_cameraRoll, R.attr.maplibre_cameraTargetLat, R.attr.maplibre_cameraTargetLng, R.attr.maplibre_cameraTilt, R.attr.maplibre_cameraZoom, R.attr.maplibre_cameraZoomMax, R.attr.maplibre_cameraZoomMin, R.attr.maplibre_cross_source_collisions, R.attr.maplibre_enableTilePrefetch, R.attr.maplibre_enableZMediaOverlay, R.attr.maplibre_foregroundLoadColor, R.attr.maplibre_localIdeographEnabled, R.attr.maplibre_localIdeographFontFamilies, R.attr.maplibre_localIdeographFontFamily, R.attr.maplibre_pixelRatio, R.attr.maplibre_prefetchZoomDelta, R.attr.maplibre_renderTextureMode, R.attr.maplibre_renderTextureTranslucentSurface, R.attr.maplibre_uiAttribution, R.attr.maplibre_uiAttributionGravity, R.attr.maplibre_uiAttributionMarginBottom, R.attr.maplibre_uiAttributionMarginLeft, R.attr.maplibre_uiAttributionMarginRight, R.attr.maplibre_uiAttributionMarginTop, R.attr.maplibre_uiAttributionTintColor, R.attr.maplibre_uiCompass, R.attr.maplibre_uiCompassDrawable, R.attr.maplibre_uiCompassFadeFacingNorth, R.attr.maplibre_uiCompassGravity, R.attr.maplibre_uiCompassMarginBottom, R.attr.maplibre_uiCompassMarginLeft, R.attr.maplibre_uiCompassMarginRight, R.attr.maplibre_uiCompassMarginTop, R.attr.maplibre_uiDoubleTapGestures, R.attr.maplibre_uiHorizontalScrollGestures, R.attr.maplibre_uiLogo, R.attr.maplibre_uiLogoGravity, R.attr.maplibre_uiLogoMarginBottom, R.attr.maplibre_uiLogoMarginLeft, R.attr.maplibre_uiLogoMarginRight, R.attr.maplibre_uiLogoMarginTop, R.attr.maplibre_uiQuickZoomGestures, R.attr.maplibre_uiRotateGestures, R.attr.maplibre_uiScrollGestures, R.attr.maplibre_uiTiltGestures, R.attr.maplibre_uiZoomGestures};
}
