package ru.ozon.app.android.travel.feature.avia.widgets.aviaSearchResult.v4.view;

import androidx.constraintlayout.widget.d;
import androidx.recyclerview.widget.RecyclerView;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;
import kotlin.jvm.internal.AbstractC7737t;
import kotlin.jvm.internal.Intrinsics;
import ru.ozon.app.android.atoms.af.layout.HorizontalAtomsLayout;
import ru.ozon.app.android.travel.utils.extensions.ConstraintLayoutExtensionsKt;
import ru.ozon.uni.android.atom.badge.BadgeView;
import ru.ozon.uni.android.atom.price.ui.PriceAtomView;
import ru.ozon.uni.android.atom.text.TextAtomV2View;

@Metadata(d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0010\u0002\n\u0002\b\u0003\u0010\u0004\u001a\u00020\u0001*\u00020\u0000H\n¢\u0006\u0004\b\u0002\u0010\u0003"}, d2 = {"Landroidx/constraintlayout/widget/d;", "", "invoke", "(Landroidx/constraintlayout/widget/d;)V", "<anonymous>"}, k = 3, mv = {2, 0, 0})
/* loaded from: classes10.dex */
final class AviaSearchResultV4FlightView$setConstraints$1 extends AbstractC7737t implements Function1<d, Unit> {
    final /* synthetic */ AviaSearchResultV4FlightView this$0;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    AviaSearchResultV4FlightView$setConstraints$1(AviaSearchResultV4FlightView aviaSearchResultV4FlightView) {
        super(1);
        this.this$0 = aviaSearchResultV4FlightView;
    }

    @Override // kotlin.jvm.functions.Function1
    public /* bridge */ /* synthetic */ Unit invoke(d dVar) {
        invoke2(dVar);
        return Unit.f71690a;
    }

    /* renamed from: invoke, reason: avoid collision after fix types in other method */
    public final void invoke2(d applyConstraint) {
        RecyclerView recyclerView;
        int i11;
        RecyclerView recyclerView2;
        int i12;
        RecyclerView recyclerView3;
        PriceAtomView priceAtomView;
        RecyclerView recyclerView4;
        int i13;
        PriceAtomView priceAtomView2;
        int i14;
        PriceAtomView priceAtomView3;
        BadgeView premiumBadgeBV;
        BadgeView premiumBadgeBV2;
        PriceAtomView priceAtomView4;
        BadgeView premiumBadgeBV3;
        PriceAtomView priceAtomView5;
        int i15;
        BadgeView premiumBadgeBV4;
        HorizontalAtomsLayout horizontalAtomsLayout;
        int i16;
        BadgeView premiumBadgeBV5;
        PriceAtomView priceAtomView6;
        HorizontalAtomsLayout horizontalAtomsLayout2;
        RecyclerView recyclerView5;
        int i17;
        HorizontalAtomsLayout horizontalAtomsLayout3;
        int i18;
        TextAtomV2View luggageTextTAV;
        PriceAtomView priceAtomView7;
        int i19;
        TextAtomV2View luggageTextTAV2;
        int i21;
        TextAtomV2View airlinesTextTAV;
        TextAtomV2View luggageTextTAV3;
        TextAtomV2View airlinesTextTAV2;
        TextAtomV2View luggageTextTAV4;
        int i22;
        TextAtomV2View airlinesTextTAV3;
        int i23;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView;
        TextAtomV2View luggageTextTAV5;
        int i24;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView2;
        int i25;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView3;
        int i26;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView4;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView5;
        int i27;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView6;
        int i28;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView7;
        int i29;
        TextAtomV2View additionalInfoTextTAV;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView8;
        int i31;
        TextAtomV2View additionalInfoTextTAV2;
        int i32;
        TextAtomV2View additionalInfoTextTAV3;
        BadgeView additionalInfoBadgeBV;
        BadgeView additionalInfoBadgeBV2;
        AviaSearchResultV4TripRouteView aviaSearchResultV4TripRouteView9;
        int i33;
        BadgeView additionalInfoBadgeBV3;
        TextAtomV2View additionalInfoTextTAV4;
        BadgeView additionalInfoBadgeBV4;
        int i34;
        Intrinsics.checkNotNullParameter(applyConstraint, "$this$applyConstraint");
        recyclerView = this.this$0.badgesHFAL;
        i11 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, recyclerView, i11);
        recyclerView2 = this.this$0.badgesHFAL;
        i12 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, recyclerView2, i12);
        recyclerView3 = this.this$0.badgesHFAL;
        ConstraintLayoutExtensionsKt.topToParent(applyConstraint, recyclerView3);
        priceAtomView = this.this$0.pricePAV;
        recyclerView4 = this.this$0.badgesHFAL;
        i13 = this.this$0.dp12;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, priceAtomView, recyclerView4, i13);
        priceAtomView2 = this.this$0.pricePAV;
        i14 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, priceAtomView2, i14);
        priceAtomView3 = this.this$0.pricePAV;
        premiumBadgeBV = this.this$0.getPremiumBadgeBV();
        ConstraintLayoutExtensionsKt.endToStart(applyConstraint, priceAtomView3, premiumBadgeBV);
        premiumBadgeBV2 = this.this$0.getPremiumBadgeBV();
        priceAtomView4 = this.this$0.pricePAV;
        ConstraintLayoutExtensionsKt.topToTop(applyConstraint, premiumBadgeBV2, priceAtomView4);
        premiumBadgeBV3 = this.this$0.getPremiumBadgeBV();
        priceAtomView5 = this.this$0.pricePAV;
        i15 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.startToEnd(applyConstraint, premiumBadgeBV3, priceAtomView5, i15);
        premiumBadgeBV4 = this.this$0.getPremiumBadgeBV();
        horizontalAtomsLayout = this.this$0.airlineIconsHAL;
        i16 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.endToStart(applyConstraint, premiumBadgeBV4, horizontalAtomsLayout, i16);
        premiumBadgeBV5 = this.this$0.getPremiumBadgeBV();
        priceAtomView6 = this.this$0.pricePAV;
        ConstraintLayoutExtensionsKt.bottomToBottom(applyConstraint, premiumBadgeBV5, priceAtomView6);
        horizontalAtomsLayout2 = this.this$0.airlineIconsHAL;
        recyclerView5 = this.this$0.badgesHFAL;
        i17 = this.this$0.dp12;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, horizontalAtomsLayout2, recyclerView5, i17);
        horizontalAtomsLayout3 = this.this$0.airlineIconsHAL;
        i18 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, horizontalAtomsLayout3, i18);
        luggageTextTAV = this.this$0.getLuggageTextTAV();
        priceAtomView7 = this.this$0.pricePAV;
        i19 = this.this$0.dp4;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, luggageTextTAV, priceAtomView7, i19);
        luggageTextTAV2 = this.this$0.getLuggageTextTAV();
        i21 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, luggageTextTAV2, i21);
        airlinesTextTAV = this.this$0.getAirlinesTextTAV();
        luggageTextTAV3 = this.this$0.getLuggageTextTAV();
        ConstraintLayoutExtensionsKt.baselineToBaseline(applyConstraint, airlinesTextTAV, luggageTextTAV3);
        airlinesTextTAV2 = this.this$0.getAirlinesTextTAV();
        luggageTextTAV4 = this.this$0.getLuggageTextTAV();
        i22 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.startToEnd(applyConstraint, airlinesTextTAV2, luggageTextTAV4, i22);
        airlinesTextTAV3 = this.this$0.getAirlinesTextTAV();
        i23 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, airlinesTextTAV3, i23);
        aviaSearchResultV4TripRouteView = this.this$0.wayThereDetailsASRFL;
        luggageTextTAV5 = this.this$0.getLuggageTextTAV();
        i24 = this.this$0.dp12;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, aviaSearchResultV4TripRouteView, luggageTextTAV5, i24);
        aviaSearchResultV4TripRouteView2 = this.this$0.wayThereDetailsASRFL;
        i25 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, aviaSearchResultV4TripRouteView2, i25);
        aviaSearchResultV4TripRouteView3 = this.this$0.wayThereDetailsASRFL;
        i26 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, aviaSearchResultV4TripRouteView3, i26);
        aviaSearchResultV4TripRouteView4 = this.this$0.wayBackDetailsASRFL;
        aviaSearchResultV4TripRouteView5 = this.this$0.wayThereDetailsASRFL;
        i27 = this.this$0.dp12;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, aviaSearchResultV4TripRouteView4, aviaSearchResultV4TripRouteView5, i27);
        aviaSearchResultV4TripRouteView6 = this.this$0.wayBackDetailsASRFL;
        i28 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, aviaSearchResultV4TripRouteView6, i28);
        aviaSearchResultV4TripRouteView7 = this.this$0.wayBackDetailsASRFL;
        i29 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, aviaSearchResultV4TripRouteView7, i29);
        additionalInfoTextTAV = this.this$0.getAdditionalInfoTextTAV();
        aviaSearchResultV4TripRouteView8 = this.this$0.wayBackDetailsASRFL;
        i31 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, additionalInfoTextTAV, aviaSearchResultV4TripRouteView8, i31);
        additionalInfoTextTAV2 = this.this$0.getAdditionalInfoTextTAV();
        i32 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, additionalInfoTextTAV2, i32);
        additionalInfoTextTAV3 = this.this$0.getAdditionalInfoTextTAV();
        additionalInfoBadgeBV = this.this$0.getAdditionalInfoBadgeBV();
        ConstraintLayoutExtensionsKt.endToStart(applyConstraint, additionalInfoTextTAV3, additionalInfoBadgeBV);
        additionalInfoBadgeBV2 = this.this$0.getAdditionalInfoBadgeBV();
        aviaSearchResultV4TripRouteView9 = this.this$0.wayBackDetailsASRFL;
        i33 = this.this$0.dp4;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, additionalInfoBadgeBV2, aviaSearchResultV4TripRouteView9, i33);
        additionalInfoBadgeBV3 = this.this$0.getAdditionalInfoBadgeBV();
        additionalInfoTextTAV4 = this.this$0.getAdditionalInfoTextTAV();
        ConstraintLayoutExtensionsKt.startToEnd(applyConstraint, additionalInfoBadgeBV3, additionalInfoTextTAV4);
        additionalInfoBadgeBV4 = this.this$0.getAdditionalInfoBadgeBV();
        i34 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, additionalInfoBadgeBV4, i34);
    }
}
