package defpackage;

/* loaded from: classes.dex */
public final class fe {
    public final long AARZUJiTa;
    public defpackage.u61 AQHddgaEX;
    public defpackage.da AsxAYCCkb3Hi;
    public final long C0U8sNJm;
    public defpackage.he1 CGXpA9s3RjIa;
    public final long D2vUnMij;
    public final long DFo87pBq1E5;
    public final long EXtogiMhuM;
    public final long EgCjBq0SZwJ;
    public final long EoOhNTTfIN7K;
    public final long F7NU4MC0GW;
    public final long G3OKOH3wZRC;
    public final long IHQe1A4L2xu;
    public final long JlrlGoKF;
    public final long NHJTzaLwkd;
    public final long PAEGRtP0bX;
    public final long QPwENk36pDC;
    public final long QQUzIjv3iOC5;
    public defpackage.da QUKZkWRtw6;
    public final long QoRHpC4k;
    public defpackage.da RmCzwkUxICV;
    public final long SH1y5HwkJhh;
    public final long SiPhmbmu;
    public final long SyNS6RMn;
    public final long TFRaUu83X3E;
    public final long UsuH8pd5P;
    public final long Uv8CGu3G;
    public final long V7bD7b8KA;
    public final long WLpAkxCo;
    public final long XZx205DYe;
    public final long Ye0N2xE9Hc;
    public final long abhbClRa;
    public final long adDC3e2L;
    public final long cnag84Bm;
    public final long ez2rX8ReCYw;
    public final long fnWB2E7cs;
    public final long frpfPPIgqM9O;
    public final long hkbnNdmy;
    public final long hyxIchWRW;
    public final long kNAkVymC;
    public final long kd6TUFXn;
    public final long lpprD5VAS;
    public final long mAr5m2L7gYDP;
    public final long nBH8hAHy;
    public defpackage.lb nVhUznk1t;
    public final long oh6vYeIP;
    public final long p4kuH6PDtgom;
    public final long r1MBDhnF;
    public final long riuEU0zW4;
    public final long v5iciZok;
    public final long wKlPRKlRnfqr;
    public final long wll2JLbTBC2;
    public final long xiZrDbcSW0;
    public final long yIx6ChFVk;

    public fe(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.IHQe1A4L2xu = j;
        this.oh6vYeIP = j2;
        this.r1MBDhnF = j3;
        this.F7NU4MC0GW = j4;
        this.adDC3e2L = j5;
        this.xiZrDbcSW0 = j6;
        this.AARZUJiTa = j7;
        this.EXtogiMhuM = j8;
        this.riuEU0zW4 = j9;
        this.SH1y5HwkJhh = j10;
        this.ez2rX8ReCYw = j11;
        this.JlrlGoKF = j12;
        this.DFo87pBq1E5 = j13;
        this.SyNS6RMn = j14;
        this.cnag84Bm = j15;
        this.QoRHpC4k = j16;
        this.G3OKOH3wZRC = j17;
        this.kd6TUFXn = j18;
        this.EgCjBq0SZwJ = j19;
        this.fnWB2E7cs = j20;
        this.kNAkVymC = j21;
        this.V7bD7b8KA = j22;
        this.PAEGRtP0bX = j23;
        this.abhbClRa = j24;
        this.NHJTzaLwkd = j25;
        this.QQUzIjv3iOC5 = j26;
        this.C0U8sNJm = j27;
        this.UsuH8pd5P = j28;
        this.nBH8hAHy = j29;
        this.v5iciZok = j30;
        this.D2vUnMij = j31;
        this.frpfPPIgqM9O = j32;
        this.SiPhmbmu = j33;
        this.p4kuH6PDtgom = j34;
        this.yIx6ChFVk = j35;
        this.wll2JLbTBC2 = j36;
        this.XZx205DYe = j37;
        this.mAr5m2L7gYDP = j38;
        this.hyxIchWRW = j39;
        this.Uv8CGu3G = j40;
        this.lpprD5VAS = j41;
        this.hkbnNdmy = j42;
        this.TFRaUu83X3E = j43;
        this.WLpAkxCo = j44;
        this.QPwENk36pDC = j45;
        this.Ye0N2xE9Hc = j46;
        this.EoOhNTTfIN7K = j47;
        this.wKlPRKlRnfqr = j48;
    }

    public final java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("ColorScheme(primary=");
        defpackage.fx0.cnag84Bm(this.IHQe1A4L2xu, sb, "onPrimary=");
        defpackage.fx0.cnag84Bm(this.oh6vYeIP, sb, "primaryContainer=");
        defpackage.fx0.cnag84Bm(this.r1MBDhnF, sb, "onPrimaryContainer=");
        long j = this.F7NU4MC0GW;
        defpackage.fx0.cnag84Bm(j, sb, "inversePrimary=");
        defpackage.fx0.cnag84Bm(this.adDC3e2L, sb, "secondary=");
        defpackage.fx0.cnag84Bm(this.xiZrDbcSW0, sb, "onSecondary=");
        defpackage.fx0.cnag84Bm(this.AARZUJiTa, sb, "secondaryContainer=");
        defpackage.fx0.cnag84Bm(this.EXtogiMhuM, sb, "onSecondaryContainer=");
        defpackage.fx0.cnag84Bm(this.riuEU0zW4, sb, "tertiary=");
        defpackage.fx0.cnag84Bm(this.SH1y5HwkJhh, sb, "onTertiary=");
        defpackage.fx0.cnag84Bm(this.ez2rX8ReCYw, sb, "tertiaryContainer=");
        defpackage.fx0.cnag84Bm(this.JlrlGoKF, sb, "onTertiaryContainer=");
        defpackage.fx0.cnag84Bm(this.DFo87pBq1E5, sb, "background=");
        defpackage.fx0.cnag84Bm(this.SyNS6RMn, sb, "onBackground=");
        defpackage.fx0.cnag84Bm(this.cnag84Bm, sb, "surface=");
        defpackage.fx0.cnag84Bm(this.QoRHpC4k, sb, "onSurface=");
        defpackage.fx0.cnag84Bm(this.G3OKOH3wZRC, sb, "surfaceVariant=");
        defpackage.fx0.cnag84Bm(this.kd6TUFXn, sb, "onSurfaceVariant=");
        defpackage.fx0.cnag84Bm(this.EgCjBq0SZwJ, sb, "surfaceTint=");
        defpackage.fx0.cnag84Bm(this.fnWB2E7cs, sb, "inverseSurface=");
        defpackage.fx0.cnag84Bm(this.kNAkVymC, sb, "inverseOnSurface=");
        defpackage.fx0.cnag84Bm(this.V7bD7b8KA, sb, "error=");
        defpackage.fx0.cnag84Bm(this.PAEGRtP0bX, sb, "onError=");
        defpackage.fx0.cnag84Bm(this.abhbClRa, sb, "errorContainer=");
        defpackage.fx0.cnag84Bm(this.NHJTzaLwkd, sb, "onErrorContainer=");
        defpackage.fx0.cnag84Bm(this.QQUzIjv3iOC5, sb, "outline=");
        defpackage.fx0.cnag84Bm(this.C0U8sNJm, sb, "outlineVariant=");
        defpackage.fx0.cnag84Bm(this.UsuH8pd5P, sb, "scrim=");
        defpackage.fx0.cnag84Bm(this.nBH8hAHy, sb, "surfaceBright=");
        defpackage.fx0.cnag84Bm(this.v5iciZok, sb, "surfaceDim=");
        defpackage.fx0.cnag84Bm(this.D2vUnMij, sb, "surfaceContainer=");
        defpackage.fx0.cnag84Bm(this.frpfPPIgqM9O, sb, "surfaceContainerHigh=");
        defpackage.fx0.cnag84Bm(this.SiPhmbmu, sb, "surfaceContainerHighest=");
        defpackage.fx0.cnag84Bm(this.p4kuH6PDtgom, sb, "surfaceContainerLow=");
        defpackage.fx0.cnag84Bm(this.yIx6ChFVk, sb, "surfaceContainerLowest=");
        defpackage.fx0.cnag84Bm(this.wll2JLbTBC2, sb, "primaryFixed=");
        defpackage.fx0.cnag84Bm(this.XZx205DYe, sb, "primaryFixedDim=");
        defpackage.fx0.cnag84Bm(this.mAr5m2L7gYDP, sb, "onPrimaryFixed=");
        defpackage.fx0.cnag84Bm(j, sb, "onPrimaryFixedVariant=");
        defpackage.fx0.cnag84Bm(this.Uv8CGu3G, sb, "secondaryFixed=");
        defpackage.fx0.cnag84Bm(this.lpprD5VAS, sb, "secondaryFixedDim=");
        defpackage.fx0.cnag84Bm(this.hkbnNdmy, sb, "onSecondaryFixed=");
        defpackage.fx0.cnag84Bm(this.TFRaUu83X3E, sb, "onSecondaryFixedVariant=");
        defpackage.fx0.cnag84Bm(this.WLpAkxCo, sb, "tertiaryFixed=");
        defpackage.fx0.cnag84Bm(this.QPwENk36pDC, sb, "tertiaryFixedDim=");
        defpackage.fx0.cnag84Bm(this.Ye0N2xE9Hc, sb, "onTertiaryFixed=");
        defpackage.fx0.cnag84Bm(this.EoOhNTTfIN7K, sb, "onTertiaryFixedVariant=");
        sb.append((java.lang.Object) defpackage.ae.riuEU0zW4(this.wKlPRKlRnfqr));
        sb.append(')');
        return sb.toString();
    }
}
