package defpackage;

/* compiled from: r8-map-id-dd5e919efaf02f4d8ff55d6a5e2559a4e7180bda542179c0d9d8fc6a077876b4 */
/* loaded from: classes.dex */
public abstract class ii {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = pu0.q;
        a = j2;
        b = pu0.f;
        c = pu0.d;
        d = pu0.m;
        e = pu0.H;
        long j3 = pu0.s;
        f = j3;
        g = j3;
        h = pu0.c;
        i = pu0.g;
        j = pu0.F;
        long j4 = pu0.J;
        k = j4;
        l = pu0.D;
        long j5 = pu0.G;
        m = j5;
        n = pu0.M;
        long j6 = pu0.Q;
        o = j6;
        p = pu0.K;
        long j7 = pu0.N;
        q = j7;
        r = j3;
        s = pu0.B;
        t = pu0.T;
        long j8 = pu0.X;
        u = j8;
        v = pu0.R;
        long j9 = pu0.U;
        w = j9;
        x = pu0.A;
        long j10 = pu0.y;
        y = j10;
        long j11 = pu0.I;
        z = j5;
        A = j4;
        B = j11;
        C = pu0.h;
        long j12 = pu0.P;
        D = j7;
        E = j6;
        F = j12;
        G = j2;
        H = pu0.o;
        I = pu0.k;
        J = pu0.l;
        K = pu0.n;
        L = pu0.i;
        M = pu0.p;
        N = j2;
        O = j10;
        long j13 = pu0.W;
        P = j9;
        Q = j8;
        R = j13;
    }
}
