package android.content.Context;

/* compiled from: r8-map-id-ad53bc00775cc49f3760de3ef5ee15f0f7d4eb373264baa1785c3fa1a15d54ed */
/* loaded from: classes.dex */
public final class FrostHunterPermissionCelestialAurora5978 implements FrostHunterPagingDataBetaGammaSolar8478 {
    public static final FrostHunterPermissionCelestialAurora5978 FrostHunterAlphaAnimationNeoCosmos5761 = new FrostHunterPermissionCelestialAurora5978();
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterConstraintSetCloneMasterUltraRogue2633 = FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896.FrostHunterAlphaAnimationNeoCosmos5761("eventTimeMs");
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterBundlePulseFusionHero2475 = FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896.FrostHunterAlphaAnimationNeoCosmos5761("eventCode");
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterServiceEliteCelestialThunder1757 = FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896.FrostHunterAlphaAnimationNeoCosmos5761("eventUptimeMs");
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterLifecycleBlazeGammaElite2889 = FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896.FrostHunterAlphaAnimationNeoCosmos5761("sourceExtension");
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterLevelListDrawableFusionDragonHero2232 = FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896.FrostHunterAlphaAnimationNeoCosmos5761("sourceExtensionJsonProto3");
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterRemoteConfigSpeedSpeed8566 = FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896.FrostHunterAlphaAnimationNeoCosmos5761("timezoneOffsetSeconds");
    public static final FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896 FrostHunterCameraXPixelTurboCosmos9814 = FrostHunterPaintFlagsDrawFilterUltraTurboEclipse9896.FrostHunterAlphaAnimationNeoCosmos5761("networkConnectionInfo");

    @Override // android.content.Context.FrostHunterDrawableEpicHero6631
    public final void FrostHunterAlphaAnimationNeoCosmos5761(Object obj, Object obj2) {
        FrostHunterInsetDrawableNebulaForcePrime4535 frostHunterInsetDrawableNebulaForcePrime4535 = (FrostHunterInsetDrawableNebulaForcePrime4535) obj;
        FrostHunterGestureDetectorNovaXStormSpark6209 frostHunterGestureDetectorNovaXStormSpark6209 = (FrostHunterGestureDetectorNovaXStormSpark6209) obj2;
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterConstraintSetCloneMasterUltraRogue2633(FrostHunterConstraintSetCloneMasterUltraRogue2633, ((FrostHunterRoomEntityBetaAlphaEclipse3282) frostHunterInsetDrawableNebulaForcePrime4535).FrostHunterAlphaAnimationNeoCosmos5761);
        FrostHunterRoomEntityBetaAlphaEclipse3282 frostHunterRoomEntityBetaAlphaEclipse3282 = (FrostHunterRoomEntityBetaAlphaEclipse3282) frostHunterInsetDrawableNebulaForcePrime4535;
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterAlphaAnimationNeoCosmos5761(FrostHunterBundlePulseFusionHero2475, frostHunterRoomEntityBetaAlphaEclipse3282.FrostHunterConstraintSetCloneMasterUltraRogue2633);
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterConstraintSetCloneMasterUltraRogue2633(FrostHunterServiceEliteCelestialThunder1757, frostHunterRoomEntityBetaAlphaEclipse3282.FrostHunterBundlePulseFusionHero2475);
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterAlphaAnimationNeoCosmos5761(FrostHunterLifecycleBlazeGammaElite2889, frostHunterRoomEntityBetaAlphaEclipse3282.FrostHunterServiceEliteCelestialThunder1757);
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterAlphaAnimationNeoCosmos5761(FrostHunterLevelListDrawableFusionDragonHero2232, frostHunterRoomEntityBetaAlphaEclipse3282.FrostHunterLifecycleBlazeGammaElite2889);
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterConstraintSetCloneMasterUltraRogue2633(FrostHunterRemoteConfigSpeedSpeed8566, frostHunterRoomEntityBetaAlphaEclipse3282.FrostHunterLevelListDrawableFusionDragonHero2232);
        frostHunterGestureDetectorNovaXStormSpark6209.FrostHunterAlphaAnimationNeoCosmos5761(FrostHunterCameraXPixelTurboCosmos9814, frostHunterRoomEntityBetaAlphaEclipse3282.FrostHunterRemoteConfigSpeedSpeed8566);
    }
}
