package com.gamericefishpro.space.s0;

/* JADX INFO: compiled from: r8-map-id-020a1517951ead57be77a6b773195444ecc812bf491d4c7c9fe6933b01540740 */
/* JADX INFO: loaded from: classes.dex */
public abstract class a {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = d.o;
        a = j2;
        b = d.c;
        c = d.d;
        d = d.m;
        long j3 = d.x;
        e = j3;
        f = d.h;
        long j4 = d.f;
        g = j4;
        h = d.b;
        i = d.a;
        j = d.u;
        long j5 = d.t;
        k = j5;
        l = j5;
        m = d.v;
        n = d.A;
        long j6 = d.z;
        o = j6;
        p = j6;
        q = d.B;
        r = j4;
        s = d.p;
        t = d.G;
        long j7 = d.F;
        u = j7;
        v = j7;
        w = d.H;
        x = d.q;
        y = d.r;
        z = d.w;
        long j8 = d.y;
        A = j8;
        B = j8;
        C = j3;
        D = d.e;
        E = d.C;
        long j9 = d.E;
        F = j9;
        G = j9;
        H = d.D;
        I = j2;
        J = j2;
        K = d.l;
        L = d.k;
        M = d.j;
        N = d.n;
        O = d.g;
        P = d.i;
        Q = d.s;
        R = d.I;
        long j10 = d.K;
        S = j10;
        T = j10;
        U = d.J;
    }
}
