package defpackage;

import android.R;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class fgf {
    public static final int[] a = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.google.android.apps.authenticator2.R.attr.backgroundTint, com.google.android.apps.authenticator2.R.attr.behavior_autoExpandOnRequestChildRectangleOffscreen, com.google.android.apps.authenticator2.R.attr.behavior_draggable, com.google.android.apps.authenticator2.R.attr.behavior_draggableOnNestedScroll, com.google.android.apps.authenticator2.R.attr.behavior_expandedOffset, com.google.android.apps.authenticator2.R.attr.behavior_fitToContents, com.google.android.apps.authenticator2.R.attr.behavior_halfExpandedRatio, com.google.android.apps.authenticator2.R.attr.behavior_hideable, com.google.android.apps.authenticator2.R.attr.behavior_multipleScrollingChildrenSupported, com.google.android.apps.authenticator2.R.attr.behavior_peekHeight, com.google.android.apps.authenticator2.R.attr.behavior_saveFlags, com.google.android.apps.authenticator2.R.attr.behavior_significantVelocityThreshold, com.google.android.apps.authenticator2.R.attr.behavior_skipCollapsed, com.google.android.apps.authenticator2.R.attr.gestureInsetBottomIgnored, com.google.android.apps.authenticator2.R.attr.marginLeftSystemWindowInsets, com.google.android.apps.authenticator2.R.attr.marginRightSystemWindowInsets, com.google.android.apps.authenticator2.R.attr.marginTopSystemWindowInsets, com.google.android.apps.authenticator2.R.attr.paddingBottomSystemWindowInsets, com.google.android.apps.authenticator2.R.attr.paddingLeftSystemWindowInsets, com.google.android.apps.authenticator2.R.attr.paddingRightSystemWindowInsets, com.google.android.apps.authenticator2.R.attr.paddingTopSystemWindowInsets, com.google.android.apps.authenticator2.R.attr.shapeAppearance, com.google.android.apps.authenticator2.R.attr.shapeAppearanceOverlay, com.google.android.apps.authenticator2.R.attr.shouldRemoveExpandedCorners};
}
