package ee;

import kotlin.jvm.internal.Intrinsics;

/* compiled from: r8-map-id-1007347d93e945b62163496d2b3d545e4cec50eb5f7054b93987970dfadb4b15 */
/* loaded from: classes.dex */
public final class c {

    /* renamed from: a, reason: collision with root package name */
    public final String[] f9113a = {"Стратегия под названием “Флэт” очень популярна в мире беттинга. Это объясняется простотой понимания смысла данной стратегии, а также пониженными рисками при правильном использовании. Данная схема имеет несколько разновидностей, все зависит от размера имеющегося банка, личных знаний в том или ином виде спорте, персональных предпочтений.", "Объясняем суть", "Смысл данной стратегии заключается в использовании фиксированной ставки. Сумма не должна превышать 2% от общего банка - поэтому, в принципе, не имеет значения, сколько денег сейчас у игрока. Главным преимуществом данной стратегии является минимальный риск потерять деньги. Однако существуют 4 разновидности этой схемы, каждая из которых обладает своими чертами и рисками.", "Статичный флэт", "Самый простой и классический флэт. Суть данного вида проста: игрок использует весь банк, разбивая его на определенное количество одинаковых по размеру ставок. Например, если ставка составляет 1%, то таких ставок будет 100, если 2%, то 50, если 4% - 25 и так далее. Все ставки одинаковы по размеру. Для новичков такая разновидность флэта позволяет приобрести большой опыт, более опытные игроки используют ее для получения крупного выигрыша.", "Академический флэт", "Возможно, самый популярный флэт у игроков. Здесь размер ставки уже не фиксированный, а определяется предполагаемой вероятностью захода. Если игрок уверен в победе, то сумма ставки может быть и 3% от общего банка, если сомневается - то 1%. Можно выбрать и больший размер ставки - все зависит о того, насколько хорошо вы разбираетесь в виде спорта.", "Агрессивный флэт", "Само название уже говорит за себя. Суть агрессивного флэта в большем размере ставки, обычно он составляет 2-3%. Даже если наступают поражения, при агрессивном флэте нельзя изменять размер ставки. Одним из минусов данной разновидности является большая проверка психологической прочности игроков. После нескольких минусов многие начинают увеличивать размер ставки, пытаясь как бы “догнать” себя самого. Из-за этого очень часто банк сливается в кратчайшие сроки, а также возникает большой риск “заиграться” и вложить гораздо больше финансовых средств в ушедшую из-под контроля игру.", "Хаотичный флэт", "Главными особенностями хаотичного флэта являются растянутость во времени и повышенный процент ставки. Например, игрок делает 20 ставок по 5% не сразу, а в течение какого-то периода: недели, месяца, года - по усмотрению. Риски при данном флэте увеличиваются, особенно если выбирать события с коэффициентом выше 1.5-1.6.", "Следует заметить, что все разновидности флэт-стратегии являются наименее рисковыми и более безопасными, чем все остальные. Это связано с низким процентом ставки и невысокими соответственно коэффициентами на события."};

    /* renamed from: b, reason: collision with root package name */
    public final String[] f9114b = {"La stratégie Flat est très populaire dans le monde des paris grâce à sa simplicité et à ses risques réduits. Le principe repose sur l’utilisation d’une mise fixe. Il est interdit de miser plus de 2 % de la bankroll sur un seul événement, ce qui signifie que la taille du budget n’a pas d’importance. Le principal avantage de cette stratégie est le risque minimal de perdre rapidement tout son capital. Il existe plusieurs types de cette méthode.", "", "", "Flat statique", "Le type de flat le plus simple. Le joueur divise sa bankroll en parts égales : si une mise représente 1 % de la bankroll, il y aura 100 paris, si 2 % — 50 paris, si 4 % — 25 paris, etc. Toutes les mises sont identiques. Ce système permet aux débutants d’acquérir de l’expérience sans risquer de perdre tout leur capital.", "Flat académique", "Probablement le type de flat le plus populaire. Dans le flat académique, le montant de la mise peut varier de 1 % à 3 % — tout dépend des connaissances du joueur dans le sport concerné. Bien sûr, il est possible d’augmenter la mise si le résultat semble très probable.", "Flat agressif", "Le principe du flat agressif repose sur des mises élevées (4–5 %). Le montant de la mise ne doit pas être modifié même en cas de pertes, ce qui exige une grande stabilité psychologique. Certains joueurs augmentent leurs mises après une série de pertes, ce qui conduit très rapidement à la perte totale de la bankroll.", "Flat chaotique", "Les principales caractéristiques du flat chaotique sont des mises élevées et une stratégie à long terme. Par exemple, le joueur effectue 20 paris de 5 % de la bankroll non pas immédiatement, mais sur une certaine période : une semaine, un mois ou une année. Les risques augmentent, mais le gain total potentiel augmente également.", ""};

    /* renamed from: c, reason: collision with root package name */
    public final String[] f9115c = {"Die Flat-Strategie ist im Wettbereich sehr beliebt, da sie einfach zu verstehen ist und geringere Risiken bietet. Dabei wird immer mit einem festen Einsatz gespielt. Pro Ereignis darf nicht mehr als 2 % der Bankroll gesetzt werden, weshalb die Höhe des Budgets keine große Rolle spielt. Der größte Vorteil dieser Strategie ist das minimale Risiko, das gesamte Kapital schnell zu verlieren. Es gibt mehrere Varianten dieses Systems.", "", "", "Statischer Flat", "Die einfachste Form der Flat-Strategie. Der Spieler teilt seine Bankroll in gleich große Einsätze auf: Beträgt ein Einsatz 1 % der Bankroll, gibt es 100 Wetten, bei 2 % — 50 Wetten, bei 4 % — 25 Wetten usw. Alle Einsätze sind gleich hoch. Diese Variante eignet sich besonders für Anfänger, um erste Erfahrungen ohne hohes Verlustrisiko zu sammeln.", "Akademischer Flat", "Möglicherweise die beliebteste Flat-Variante. Beim akademischen Flat kann der Einsatz zwischen 1 % und 3 % variieren — abhängig von den Kenntnissen des Spielers im jeweiligen Sport. Bei hoher Sicherheit über das Ergebnis kann der Einsatz erhöht werden.", "Aggressiver Flat", "Der aggressive Flat zeichnet sich durch hohe Einsätze (4–5 %) aus. Der Einsatz darf auch bei Verlusten nicht verändert werden, weshalb eine hohe psychologische Stabilität erforderlich ist. Viele Spieler erhöhen nach Verlustserien ihre Einsätze, wodurch die gesamte Bankroll sehr schnell verloren geht.", "Chaotischer Flat", "Die Hauptmerkmale des chaotischen Flats sind hohe Einsätze und ein langfristiger Ansatz. Zum Beispiel platziert der Spieler 20 Wetten mit jeweils 5 % der Bankroll nicht sofort, sondern über einen längeren Zeitraum — eine Woche, einen Monat oder ein Jahr. Das Risiko steigt, aber auch der potenzielle Gesamtertrag.", ""};

    /* renamed from: d, reason: collision with root package name */
    public final String[] f9116d = {"La estrategia Flat es muy popular en las apuestas debido a su simplicidad y a sus menores riesgos. Se basa en el uso de una apuesta fija. No se permite apostar más del 2 % del bankroll en un solo evento, por lo que el tamaño del presupuesto no es crucial. La principal ventaja de esta estrategia es el bajo riesgo de perder todo el dinero rápidamente. Existen varios tipos de este sistema.", "", "", "Flat estático", "El tipo más simple de la estrategia Flat. El jugador divide su bankroll en apuestas iguales: si una apuesta es del 1 %, habrá 100 apuestas; si es del 2 %, 50 apuestas; si es del 4 %, 25 apuestas, etc. Todas las apuestas tienen el mismo importe. Este sistema permite a los principiantes ganar experiencia sin un alto riesgo de pérdida.", "Flat académico", "Probablemente el tipo de Flat más popular. En el Flat académico, el tamaño de la apuesta puede variar entre el 1 % y el 3 %, dependiendo del conocimiento del jugador sobre el deporte. Si se tiene mucha confianza en el resultado, la apuesta puede aumentarse.", "Flat agresivo", "El Flat agresivo se basa en apuestas de gran tamaño (4–5 %). El importe de la apuesta no debe cambiarse incluso en caso de pérdidas, por lo que se requiere una gran estabilidad psicológica. Muchos jugadores aumentan las apuestas tras una mala racha, lo que suele llevar a perder rápidamente todo el bankroll.", "Flat caótico", "Las principales características del Flat caótico son las apuestas altas y el enfoque a largo plazo. Por ejemplo, el jugador realiza 20 apuestas del 5 % del bankroll no de inmediato, sino durante un periodo determinado: una semana, un mes o un año. El riesgo aumenta, pero también lo hace el beneficio total potencial.", ""};

    /* renamed from: e, reason: collision with root package name */
    public final String[] f9117e = {"A estratégia Flat é muito popular nas apostas devido à sua simplicidade e aos riscos reduzidos. Ela se baseia no uso de um valor fixo de aposta. Não é permitido apostar mais de 2 % da banca em um único evento, por isso o tamanho do orçamento não é tão importante. A principal vantagem dessa estratégia é o baixo risco de perder todo o dinheiro rapidamente. Existem vários tipos desse sistema.", "", "", "Flat estático", "O tipo mais simples da estratégia Flat. O jogador divide sua banca em apostas iguais: se uma aposta for de 1 %, haverá 100 apostas; se for de 2 %, 50 apostas; se for de 4 %, 25 apostas, e assim por diante. Todas as apostas têm o mesmo valor. Esse sistema permite que iniciantes ganhem experiência sem grandes riscos.", "Flat acadêmico", "Talvez o tipo de Flat mais popular. No Flat acadêmico, o valor da aposta pode variar entre 1 % e 3 %, dependendo do conhecimento do jogador no esporte. Caso haja muita confiança no resultado, o valor da aposta pode ser aumentado.", "Flat agressivo", "O Flat agressivo se caracteriza por apostas de valores elevados (4–5 %). O valor da aposta não deve ser alterado mesmo em caso de perdas, o que exige grande estabilidade psicológica. Muitos jogadores aumentam as apostas após uma sequência negativa, fazendo com que a banca se esgote rapidamente.", "Flat caótico", "As principais características do Flat caótico são apostas altas e uma abordagem de longo prazo. Por exemplo, o jogador faz 20 apostas de 5 % da banca não imediatamente, mas ao longo de um período: uma semana, um mês ou um ano. Os riscos aumentam, mas o ganho total potencial também.", ""};

    /* renamed from: f, reason: collision with root package name */
    public final String[] f9118f = {"Flat stratejisi, basit yapısı ve düşük riskleri nedeniyle bahis dünyasında oldukça popülerdir. Bu strateji sabit bahis miktarına dayanır. Tek bir etkinlik için bakiyenin %2’sinden fazlasını yatırmak yasaktır, bu nedenle toplam bütçenin büyüklüğü çok önemli değildir. Bu stratejinin en büyük avantajı, tüm parayı kısa sürede kaybetme riskinin düşük olmasıdır. Bu sistemin birkaç türü bulunmaktadır.", "", "", "Statik Flat", "Flat stratejisinin en basit türüdür. Oyuncu bakiyesini eşit bahis parçalarına böler: tek bahis bakiyenin %1’i ise 100 bahis olur, %2 ise 50 bahis, %4 ise 25 bahis olur. Tüm bahisler aynı miktardadır. Bu sistem, yeni başlayanların yüksek risk almadan deneyim kazanmasını sağlar.", "Akademik Flat", "Muhtemelen en popüler Flat türüdür. Akademik Flat’te bahis miktarı %1 ile %3 arasında değişebilir ve bu tamamen oyuncunun spor bilgisine bağlıdır. Sonuçtan emin olunması durumunda bahis miktarı artırılabilir.", "Agresif Flat", "Agresif Flat, yüksek bahis miktarlarıyla (%4–5) öne çıkar. Kayıplar yaşansa bile bahis miktarı değiştirilmez, bu da güçlü bir psikolojik dayanıklılık gerektirir. Bazı oyuncular kayıp serilerinden sonra bahis miktarını artırır ve bu durum bakiyenin çok kısa sürede sıfırlanmasına yol açar.", "Kaotik Flat", "Kaotik Flat’in temel özellikleri yüksek bahis oranları ve uzun vadeli oyundur. Örneğin oyuncu, bakiyenin %5’i ile yapılan 20 bahsi hemen değil, bir hafta, bir ay veya bir yıl gibi bir süreye yayarak oynar. Riskler artar, ancak toplam potansiyel kazanç da artar.", ""};

    /* renamed from: g, reason: collision with root package name */
    public final String[] f9119g = {"Flat strategy is very popular in betting because of its clear point and lower risks – you use fixed bet value only. You’re not allowed to bet more than 2% of your bank for one event, that’s why it doesn’t matter how big your budget is. The main advantage of this strategy is minimal risks to lose all your money quickly. There are some types of this system.", "", "", "Static flat", "The simplest type of flat strategy. Player splits his bank into equal money stacks: if amount of one bet just 1% of bank, there will be 100 bets, if 2% - 50 bets, if 4% - 25 bets etc. All bets should be equal in terms of amount. This kind of system allows beginners to gain first experience in betting without high risks to lose all money.", "Academic flat", "Maybe, this is the most popular flat type. In case of academic flat, the amount of bet can vary from 1% to 3% - all depend on player’s knowledges in sports. For sure, you can raise amount of bet, if you’re sure about result.", "Aggressive flat", "The main point of aggressive flat is in big amounts of bets (4-5%). You can’t change amount of bet even if you lose, that’s why you need to have a massive psychological stability here. Some players after losing streak raise amounts of their bets and initial bank goes to zero very soon. ", "Chaotic flat", "The main features of chaotic flat are high amounts of bets and long-term game. For example, player makes 20 bets with 5% of bank each not right now, but during some time: week, month, year. Risks to lose all money are increasing, but total income is increasing as well.", ""};

    public final String a(int i5, String language) {
        String[] strArr;
        Intrinsics.checkNotNullParameter(language, "language");
        int hashCode = language.hashCode();
        if (hashCode == 3201) {
            if (language.equals("de")) {
                strArr = this.f9115c;
            }
            strArr = this.f9119g;
        } else if (hashCode == 3246) {
            if (language.equals("es")) {
                strArr = this.f9116d;
            }
            strArr = this.f9119g;
        } else if (hashCode == 3276) {
            if (language.equals("fr")) {
                strArr = this.f9114b;
            }
            strArr = this.f9119g;
        } else if (hashCode == 3588) {
            if (language.equals("pt")) {
                strArr = this.f9117e;
            }
            strArr = this.f9119g;
        } else if (hashCode != 3651) {
            if (hashCode == 3710 && language.equals("tr")) {
                strArr = this.f9118f;
            }
            strArr = this.f9119g;
        } else {
            if (language.equals("ru")) {
                strArr = this.f9113a;
            }
            strArr = this.f9119g;
        }
        int i10 = i5 - 1;
        return (i10 >= strArr.length || i10 < 0) ? "" : strArr[i10];
    }
}
