package com.AboSamour.Project.adih;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int activityAction = 0x7f010000;
        public static final int activityName = 0x7f010001;
        public static final int adSize = 0x7f010002;
        public static final int adSizes = 0x7f010003;
        public static final int adUnitId = 0x7f010004;
        public static final int alpha = 0x7f010005;
        public static final int alwaysExpand = 0x7f010006;
        public static final int buttonSize = 0x7f010007;
        public static final int circleCrop = 0x7f010008;
        public static final int clearTop = 0x7f010009;
        public static final int colorScheme = 0x7f01000a;
        public static final int coordinatorLayoutStyle = 0x7f01000b;
        public static final int finishPrimaryWithSecondary = 0x7f01000c;
        public static final int finishSecondaryWithPrimary = 0x7f01000d;
        public static final int font = 0x7f01000e;
        public static final int fontProviderAuthority = 0x7f01000f;
        public static final int fontProviderCerts = 0x7f010010;
        public static final int fontProviderFetchStrategy = 0x7f010011;
        public static final int fontProviderFetchTimeout = 0x7f010012;
        public static final int fontProviderPackage = 0x7f010013;
        public static final int fontProviderQuery = 0x7f010014;
        public static final int fontProviderSystemFontFamily = 0x7f010015;
        public static final int fontStyle = 0x7f010016;
        public static final int fontVariationSettings = 0x7f010017;
        public static final int fontWeight = 0x7f010018;
        public static final int imageAspectRatio = 0x7f010019;
        public static final int imageAspectRatioAdjust = 0x7f01001a;
        public static final int keylines = 0x7f01001b;
        public static final int lStar = 0x7f01001c;
        public static final int layout_anchor = 0x7f01001d;
        public static final int layout_anchorGravity = 0x7f01001e;
        public static final int layout_behavior = 0x7f01001f;
        public static final int layout_dodgeInsetEdges = 0x7f010020;
        public static final int layout_insetEdge = 0x7f010021;
        public static final int layout_keyline = 0x7f010022;
        public static final int nestedScrollViewStyle = 0x7f010023;
        public static final int placeholderActivityName = 0x7f010024;
        public static final int primaryActivityName = 0x7f010025;
        public static final int queryPatterns = 0x7f010026;
        public static final int scopeUris = 0x7f010027;
        public static final int secondaryActivityAction = 0x7f010028;
        public static final int secondaryActivityName = 0x7f010029;
        public static final int shortcutMatchRequired = 0x7f01002a;
        public static final int splitLayoutDirection = 0x7f01002b;
        public static final int splitMinSmallestWidth = 0x7f01002c;
        public static final int splitMinWidth = 0x7f01002d;
        public static final int splitRatio = 0x7f01002e;
        public static final int statusBarBackground = 0x7f01002f;
        public static final int ttcIndex = 0x7f010030;
    }

    public static final class bool {
        public static final int enable_system_alarm_service_default = 0x7f020000;
        public static final int enable_system_foreground_service_default = 0x7f020001;
        public static final int enable_system_job_service_default = 0x7f020002;
        public static final int workmanager_test_configuration = 0x7f020003;
    }

    public static final class color {
        public static final int androidx_core_ripple_material_light = 0x7f030000;
        public static final int androidx_core_secondary_text_default_material_light = 0x7f030001;
        public static final int browser_actions_bg_grey = 0x7f030002;
        public static final int browser_actions_divider_color = 0x7f030003;
        public static final int browser_actions_text_color = 0x7f030004;
        public static final int browser_actions_title_color = 0x7f030005;
        public static final int common_google_signin_btn_text_dark = 0x7f030006;
        public static final int common_google_signin_btn_text_dark_default = 0x7f030007;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f030008;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f030009;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f03000a;
        public static final int common_google_signin_btn_text_light = 0x7f03000b;
        public static final int common_google_signin_btn_text_light_default = 0x7f03000c;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f03000d;
        public static final int common_google_signin_btn_text_light_focused = 0x7f03000e;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f03000f;
        public static final int common_google_signin_btn_tint = 0x7f030010;
        public static final int notification_action_color_filter = 0x7f030011;
        public static final int notification_icon_bg_color = 0x7f030012;
        public static final int notification_material_background_media_default_color = 0x7f030013;
        public static final int primary_text_default_material_dark = 0x7f030014;
        public static final int secondary_text_default_material_dark = 0x7f030015;
    }

    public static final class dimen {
        public static final int browser_actions_context_menu_max_width = 0x7f040000;
        public static final int browser_actions_context_menu_min_padding = 0x7f040001;
        public static final int compat_button_inset_horizontal_material = 0x7f040002;
        public static final int compat_button_inset_vertical_material = 0x7f040003;
        public static final int compat_button_padding_horizontal_material = 0x7f040004;
        public static final int compat_button_padding_vertical_material = 0x7f040005;
        public static final int compat_control_corner_material = 0x7f040006;
        public static final int compat_notification_large_icon_max_height = 0x7f040007;
        public static final int compat_notification_large_icon_max_width = 0x7f040008;
        public static final int notification_action_icon_size = 0x7f040009;
        public static final int notification_action_text_size = 0x7f04000a;
        public static final int notification_big_circle_margin = 0x7f04000b;
        public static final int notification_content_margin_start = 0x7f04000c;
        public static final int notification_large_icon_height = 0x7f04000d;
        public static final int notification_large_icon_width = 0x7f04000e;
        public static final int notification_main_column_padding_top = 0x7f04000f;
        public static final int notification_media_narrow_margin = 0x7f040010;
        public static final int notification_right_icon_size = 0x7f040011;
        public static final int notification_right_side_padding_top = 0x7f040012;
        public static final int notification_small_icon_background_padding = 0x7f040013;
        public static final int notification_small_icon_size_as_large = 0x7f040014;
        public static final int notification_subtext_size = 0x7f040015;
        public static final int notification_top_pad = 0x7f040016;
        public static final int notification_top_pad_large_text = 0x7f040017;
    }

    public static final class drawable {
        public static final int admob_close_button_black_circle_white_cross = 0x7f050000;
        public static final int admob_close_button_white_circle_black_cross = 0x7f050001;
        public static final int common_google_signin_btn_icon_dark = 0x7f05000a;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f05000b;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f05000c;
        public static final int common_google_signin_btn_icon_disabled = 0x7f05000e;
        public static final int common_google_signin_btn_icon_light = 0x7f05000f;
        public static final int common_google_signin_btn_icon_light_focused = 0x7f050010;
        public static final int common_google_signin_btn_icon_light_normal = 0x7f050011;
        public static final int common_google_signin_btn_text_dark = 0x7f050013;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f050014;
        public static final int common_google_signin_btn_text_dark_normal = 0x7f050015;
        public static final int common_google_signin_btn_text_disabled = 0x7f050017;
        public static final int common_google_signin_btn_text_light = 0x7f050018;
        public static final int common_google_signin_btn_text_light_focused = 0x7f050019;
        public static final int common_google_signin_btn_text_light_normal = 0x7f05001a;
        public static final int launch_background = 0x7f05001e;
        public static final int media_session_service_notification_ic_music_note = 0x7f05001f;
        public static final int media_session_service_notification_ic_pause = 0x7f050020;
        public static final int media_session_service_notification_ic_play = 0x7f050021;
        public static final int media_session_service_notification_ic_skip_to_next = 0x7f050022;
        public static final int media_session_service_notification_ic_skip_to_previous = 0x7f050023;
        public static final int notification_action_background = 0x7f050024;
        public static final int notification_bg = 0x7f050025;
        public static final int notification_bg_low = 0x7f050026;
        public static final int notification_icon_background = 0x7f05002b;
        public static final int notification_template_icon_bg = 0x7f05002c;
        public static final int notification_template_icon_low_bg = 0x7f05002d;
        public static final int notification_tile_bg = 0x7f05002e;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f060000;
        public static final int accessibility_custom_action_0 = 0x7f060001;
        public static final int accessibility_custom_action_1 = 0x7f060002;
        public static final int accessibility_custom_action_10 = 0x7f060003;
        public static final int accessibility_custom_action_11 = 0x7f060004;
        public static final int accessibility_custom_action_12 = 0x7f060005;
        public static final int accessibility_custom_action_13 = 0x7f060006;
        public static final int accessibility_custom_action_14 = 0x7f060007;
        public static final int accessibility_custom_action_15 = 0x7f060008;
        public static final int accessibility_custom_action_16 = 0x7f060009;
        public static final int accessibility_custom_action_17 = 0x7f06000a;
        public static final int accessibility_custom_action_18 = 0x7f06000b;
        public static final int accessibility_custom_action_19 = 0x7f06000c;
        public static final int accessibility_custom_action_2 = 0x7f06000d;
        public static final int accessibility_custom_action_20 = 0x7f06000e;
        public static final int accessibility_custom_action_21 = 0x7f06000f;
        public static final int accessibility_custom_action_22 = 0x7f060010;
        public static final int accessibility_custom_action_23 = 0x7f060011;
        public static final int accessibility_custom_action_24 = 0x7f060012;
        public static final int accessibility_custom_action_25 = 0x7f060013;
        public static final int accessibility_custom_action_26 = 0x7f060014;
        public static final int accessibility_custom_action_27 = 0x7f060015;
        public static final int accessibility_custom_action_28 = 0x7f060016;
        public static final int accessibility_custom_action_29 = 0x7f060017;
        public static final int accessibility_custom_action_3 = 0x7f060018;
        public static final int accessibility_custom_action_30 = 0x7f060019;
        public static final int accessibility_custom_action_31 = 0x7f06001a;
        public static final int accessibility_custom_action_4 = 0x7f06001b;
        public static final int accessibility_custom_action_5 = 0x7f06001c;
        public static final int accessibility_custom_action_6 = 0x7f06001d;
        public static final int accessibility_custom_action_7 = 0x7f06001e;
        public static final int accessibility_custom_action_8 = 0x7f06001f;
        public static final int accessibility_custom_action_9 = 0x7f060020;
        public static final int action0 = 0x7f060021;
        public static final int action_container = 0x7f060022;
        public static final int action_divider = 0x7f060023;
        public static final int action_image = 0x7f060024;
        public static final int action_text = 0x7f060025;
        public static final int actions = 0x7f060026;
        public static final int adjust_height = 0x7f060027;
        public static final int adjust_width = 0x7f060028;
        public static final int all = 0x7f060029;
        public static final int androidx_window_activity_scope = 0x7f06002a;
        public static final int async = 0x7f06002b;
        public static final int auto = 0x7f06002c;
        public static final int blocking = 0x7f06002d;
        public static final int bottom = 0x7f06002e;
        public static final int browser_actions_header_text = 0x7f06002f;
        public static final int browser_actions_menu_item_icon = 0x7f060030;
        public static final int browser_actions_menu_item_text = 0x7f060031;
        public static final int browser_actions_menu_items = 0x7f060032;
        public static final int browser_actions_menu_view = 0x7f060033;
        public static final int cancel_action = 0x7f060034;
        public static final int center = 0x7f060035;
        public static final int center_horizontal = 0x7f060036;
        public static final int center_vertical = 0x7f060037;
        public static final int chronometer = 0x7f060038;
        public static final int clip_horizontal = 0x7f060039;
        public static final int clip_vertical = 0x7f06003a;
        public static final int dark = 0x7f06003b;
        public static final int dialog_button = 0x7f06003c;
        public static final int end = 0x7f06003d;
        public static final int end_padder = 0x7f06003e;
        public static final int fill = 0x7f06003f;
        public static final int fill_horizontal = 0x7f060040;
        public static final int fill_vertical = 0x7f060041;
        public static final int forever = 0x7f060042;
        public static final int icon = 0x7f060043;
        public static final int icon_group = 0x7f060044;
        public static final int icon_only = 0x7f060045;
        public static final int info = 0x7f060046;
        public static final int italic = 0x7f060047;
        public static final int item1 = 0x7f060048;
        public static final int item2 = 0x7f060049;
        public static final int item3 = 0x7f06004a;
        public static final int item4 = 0x7f06004b;
        public static final int left = 0x7f06004c;
        public static final int light = 0x7f06004d;
        public static final int line1 = 0x7f06004e;
        public static final int line3 = 0x7f06004f;
        public static final int locale = 0x7f060050;
        public static final int ltr = 0x7f060051;
        public static final int media_actions = 0x7f060052;
        public static final int media_controller_compat_view_tag = 0x7f060053;
        public static final int none = 0x7f060054;
        public static final int normal = 0x7f060055;
        public static final int notification_background = 0x7f060056;
        public static final int notification_main_column = 0x7f060057;
        public static final int notification_main_column_container = 0x7f060058;
        public static final int right = 0x7f060059;
        public static final int right_icon = 0x7f06005a;
        public static final int right_side = 0x7f06005b;
        public static final int rtl = 0x7f06005c;
        public static final int standard = 0x7f06005d;
        public static final int start = 0x7f06005e;
        public static final int status_bar_latest_event_content = 0x7f06005f;
        public static final int tag_accessibility_actions = 0x7f060060;
        public static final int tag_accessibility_clickable_spans = 0x7f060061;
        public static final int tag_accessibility_heading = 0x7f060062;
        public static final int tag_accessibility_pane_title = 0x7f060063;
        public static final int tag_on_apply_window_listener = 0x7f060064;
        public static final int tag_on_receive_content_listener = 0x7f060065;
        public static final int tag_on_receive_content_mime_types = 0x7f060066;
        public static final int tag_screen_reader_focusable = 0x7f060067;
        public static final int tag_state_description = 0x7f060068;
        public static final int tag_transition_group = 0x7f060069;
        public static final int tag_unhandled_key_event_manager = 0x7f06006a;
        public static final int tag_unhandled_key_listeners = 0x7f06006b;
        public static final int tag_window_insets_animation_callback = 0x7f06006c;
        public static final int text = 0x7f06006d;
        public static final int text2 = 0x7f06006e;
        public static final int time = 0x7f06006f;
        public static final int title = 0x7f060070;
        public static final int top = 0x7f060071;
        public static final int view_tree_lifecycle_owner = 0x7f060072;
        public static final int wide = 0x7f060073;
    }

    public static final class integer {
        public static final int cancel_button_image_alpha = 0x7f070000;
        public static final int google_play_services_version = 0x7f070001;
        public static final int status_bar_notification_info_maxnum = 0x7f070002;
    }

    public static final class layout {
        public static final int browser_actions_context_menu_page = 0x7f080000;
        public static final int browser_actions_context_menu_row = 0x7f080001;
        public static final int custom_dialog = 0x7f080002;
        public static final int notification_action = 0x7f080003;
        public static final int notification_action_tombstone = 0x7f080004;
        public static final int notification_media_action = 0x7f080005;
        public static final int notification_media_cancel_action = 0x7f080006;
        public static final int notification_template_big_media = 0x7f080007;
        public static final int notification_template_big_media_custom = 0x7f080008;
        public static final int notification_template_big_media_narrow = 0x7f080009;
        public static final int notification_template_big_media_narrow_custom = 0x7f08000a;
        public static final int notification_template_custom_big = 0x7f08000b;
        public static final int notification_template_icon_group = 0x7f08000c;
        public static final int notification_template_lines_media = 0x7f08000d;
        public static final int notification_template_media = 0x7f08000e;
        public static final int notification_template_media_custom = 0x7f08000f;
        public static final int notification_template_part_chronometer = 0x7f080010;
        public static final int notification_template_part_time = 0x7f080011;
    }

    public static final class menu {
        public static final int example_menu = 0x7f090000;
        public static final int example_menu2 = 0x7f090001;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f0a0000;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f0b0000;
        public static final int common_google_play_services_enable_button = 0x7f0b0001;
        public static final int common_google_play_services_enable_text = 0x7f0b0002;
        public static final int common_google_play_services_enable_title = 0x7f0b0003;
        public static final int common_google_play_services_install_button = 0x7f0b0004;
        public static final int common_google_play_services_install_text = 0x7f0b0005;
        public static final int common_google_play_services_install_title = 0x7f0b0006;
        public static final int common_google_play_services_notification_channel_name = 0x7f0b0007;
        public static final int common_google_play_services_notification_ticker = 0x7f0b0008;
        public static final int common_google_play_services_unknown_issue = 0x7f0b0009;
        public static final int common_google_play_services_unsupported_text = 0x7f0b000a;
        public static final int common_google_play_services_update_button = 0x7f0b000b;
        public static final int common_google_play_services_update_text = 0x7f0b000c;
        public static final int common_google_play_services_update_title = 0x7f0b000d;
        public static final int common_google_play_services_updating_text = 0x7f0b000e;
        public static final int common_google_play_services_wear_update_text = 0x7f0b000f;
        public static final int common_open_on_phone = 0x7f0b0010;
        public static final int common_signin_button_text = 0x7f0b0011;
        public static final int common_signin_button_text_long = 0x7f0b0012;
        public static final int default_notification_channel_name = 0x7f0b0013;
        public static final int exo_download_completed = 0x7f0b0014;
        public static final int exo_download_description = 0x7f0b0015;
        public static final int exo_download_downloading = 0x7f0b0016;
        public static final int exo_download_failed = 0x7f0b0017;
        public static final int exo_download_notification_channel_name = 0x7f0b0018;
        public static final int exo_download_paused = 0x7f0b0019;
        public static final int exo_download_paused_for_network = 0x7f0b001a;
        public static final int exo_download_paused_for_wifi = 0x7f0b001b;
        public static final int exo_download_removing = 0x7f0b001c;
        public static final int offline_notification_text = 0x7f0b001d;
        public static final int offline_notification_title = 0x7f0b001e;
        public static final int offline_opt_in_confirm = 0x7f0b001f;
        public static final int offline_opt_in_confirmation = 0x7f0b0020;
        public static final int offline_opt_in_decline = 0x7f0b0021;
        public static final int offline_opt_in_message = 0x7f0b0022;
        public static final int offline_opt_in_title = 0x7f0b0023;
        public static final int pause_button_content_description = 0x7f0b0024;
        public static final int play_button_content_description = 0x7f0b0025;

        /* renamed from: s1, reason: collision with root package name */
        public static final int f23732s1 = 0x7f0b0026;

        /* renamed from: s2, reason: collision with root package name */
        public static final int f23733s2 = 0x7f0b0027;

        /* renamed from: s3, reason: collision with root package name */
        public static final int f23734s3 = 0x7f0b0028;

        /* renamed from: s4, reason: collision with root package name */
        public static final int f23735s4 = 0x7f0b0029;

        /* renamed from: s5, reason: collision with root package name */
        public static final int f23736s5 = 0x7f0b002a;

        /* renamed from: s6, reason: collision with root package name */
        public static final int f23737s6 = 0x7f0b002b;
        public static final int s7 = 0x7f0b002c;
        public static final int skip_to_next_item_button_content_description = 0x7f0b002d;
        public static final int skip_to_previous_item_button_content_description = 0x7f0b002e;
        public static final int status_bar_notification_info_overflow = 0x7f0b002f;
    }

    public static final class style {
        public static final int LaunchTheme = 0x7f0c0000;
        public static final int NormalTheme = 0x7f0c0001;
        public static final int TextAppearance_Compat_Notification = 0x7f0c0002;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0c0003;
        public static final int TextAppearance_Compat_Notification_Info_Media = 0x7f0c0004;
        public static final int TextAppearance_Compat_Notification_Line2 = 0x7f0c0005;
        public static final int TextAppearance_Compat_Notification_Line2_Media = 0x7f0c0006;
        public static final int TextAppearance_Compat_Notification_Media = 0x7f0c0007;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0c0008;
        public static final int TextAppearance_Compat_Notification_Time_Media = 0x7f0c0009;
        public static final int TextAppearance_Compat_Notification_Title = 0x7f0c000a;
        public static final int TextAppearance_Compat_Notification_Title_Media = 0x7f0c000b;
        public static final int Theme_IAPTheme = 0x7f0c000c;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0c000d;
        public static final int Widget_Compat_NotificationActionText = 0x7f0c000e;
        public static final int Widget_Support_CoordinatorLayout = 0x7f0c000f;
    }

    public static final class xml {
        public static final int splits0 = 0x7f0e0000;
    }
}
