package com.chicken.road.kedro.laqer;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int action = 0x7f030000;
        public static final int alpha = 0x7f030001;
        public static final int argType = 0x7f030002;
        public static final int buttonSize = 0x7f030003;
        public static final int circleCrop = 0x7f030004;
        public static final int colorScheme = 0x7f030005;
        public static final int data = 0x7f030006;
        public static final int dataPattern = 0x7f030007;
        public static final int destination = 0x7f030008;
        public static final int enterAnim = 0x7f030009;
        public static final int exitAnim = 0x7f03000a;
        public static final int font = 0x7f03000b;
        public static final int fontProviderAuthority = 0x7f03000c;
        public static final int fontProviderCerts = 0x7f03000d;
        public static final int fontProviderFetchStrategy = 0x7f03000e;
        public static final int fontProviderFetchTimeout = 0x7f03000f;
        public static final int fontProviderPackage = 0x7f030010;
        public static final int fontProviderQuery = 0x7f030011;
        public static final int fontProviderSystemFontFamily = 0x7f030012;
        public static final int fontStyle = 0x7f030013;
        public static final int fontVariationSettings = 0x7f030014;
        public static final int fontWeight = 0x7f030015;
        public static final int graph = 0x7f030016;
        public static final int imageAspectRatio = 0x7f030017;
        public static final int imageAspectRatioAdjust = 0x7f030018;
        public static final int lStar = 0x7f030019;
        public static final int launchSingleTop = 0x7f03001a;
        public static final int mimeType = 0x7f03001b;
        public static final int navGraph = 0x7f03001c;
        public static final int nestedScrollViewStyle = 0x7f03001d;
        public static final int nullable = 0x7f03001e;
        public static final int popEnterAnim = 0x7f03001f;
        public static final int popExitAnim = 0x7f030020;
        public static final int popUpTo = 0x7f030021;
        public static final int popUpToInclusive = 0x7f030022;
        public static final int popUpToSaveState = 0x7f030023;
        public static final int postSplashScreenTheme = 0x7f030024;
        public static final int queryPatterns = 0x7f030025;
        public static final int restoreState = 0x7f030026;
        public static final int route = 0x7f030027;
        public static final int scopeUris = 0x7f030028;
        public static final int shortcutMatchRequired = 0x7f030029;
        public static final int splashScreenIconSize = 0x7f03002a;
        public static final int startDestination = 0x7f03002b;
        public static final int targetPackage = 0x7f03002c;
        public static final int ttcIndex = 0x7f03002d;
        public static final int uri = 0x7f03002e;
        public static final int windowSplashScreenAnimatedIcon = 0x7f03002f;
        public static final int windowSplashScreenAnimationDuration = 0x7f030030;
        public static final int windowSplashScreenBackground = 0x7f030031;
        public static final int windowSplashScreenIconBackgroundColor = 0x7f030032;
    }

    public static final class color {
        public static final int androidx_core_ripple_material_light = 0x7f040000;
        public static final int androidx_core_secondary_text_default_material_light = 0x7f040001;
        public static final int call_notification_answer_color = 0x7f040002;
        public static final int call_notification_decline_color = 0x7f040003;
        public static final int notification_action_color_filter = 0x7f04000f;
        public static final int notification_icon_bg_color = 0x7f040010;
        public static final int vector_tint_color = 0x7f040011;
        public static final int vector_tint_theme_color = 0x7f040012;
    }

    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 0x7f050000;
        public static final int compat_button_inset_vertical_material = 0x7f050001;
        public static final int compat_button_padding_horizontal_material = 0x7f050002;
        public static final int compat_button_padding_vertical_material = 0x7f050003;
        public static final int compat_control_corner_material = 0x7f050004;
        public static final int notification_action_icon_size = 0x7f050007;
        public static final int notification_action_text_size = 0x7f050008;
        public static final int notification_big_circle_margin = 0x7f050009;
        public static final int notification_content_margin_start = 0x7f05000a;
        public static final int notification_large_icon_height = 0x7f05000b;
        public static final int notification_large_icon_width = 0x7f05000c;
        public static final int notification_main_column_padding_top = 0x7f05000d;
        public static final int notification_media_narrow_margin = 0x7f05000e;
        public static final int notification_right_icon_size = 0x7f05000f;
        public static final int notification_right_side_padding_top = 0x7f050010;
        public static final int notification_small_icon_background_padding = 0x7f050011;
        public static final int notification_small_icon_size_as_large = 0x7f050012;
        public static final int notification_subtext_size = 0x7f050013;
        public static final int notification_top_pad = 0x7f050014;
        public static final int notification_top_pad_large_text = 0x7f050015;
    }

    public static final class drawable {
        public static final int icon_background = 0x7f06001e;
        public static final int notification_action_background = 0x7f06001f;
        public static final int notification_bg = 0x7f060020;
        public static final int notification_bg_low = 0x7f060021;
        public static final int notification_icon_background = 0x7f060026;
        public static final int notification_oversize_large_icon_bg = 0x7f060027;
        public static final int notification_template_icon_bg = 0x7f060028;
        public static final int notification_template_icon_low_bg = 0x7f060029;
        public static final int notification_tile_bg = 0x7f06002a;
        public static final int splash_background = 0x7f06002c;
        public static final int splash_logo = 0x7f06002d;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f070000;
        public static final int accessibility_custom_action_0 = 0x7f070001;
        public static final int accessibility_custom_action_1 = 0x7f070002;
        public static final int accessibility_custom_action_10 = 0x7f070003;
        public static final int accessibility_custom_action_11 = 0x7f070004;
        public static final int accessibility_custom_action_12 = 0x7f070005;
        public static final int accessibility_custom_action_13 = 0x7f070006;
        public static final int accessibility_custom_action_14 = 0x7f070007;
        public static final int accessibility_custom_action_15 = 0x7f070008;
        public static final int accessibility_custom_action_16 = 0x7f070009;
        public static final int accessibility_custom_action_17 = 0x7f07000a;
        public static final int accessibility_custom_action_18 = 0x7f07000b;
        public static final int accessibility_custom_action_19 = 0x7f07000c;
        public static final int accessibility_custom_action_2 = 0x7f07000d;
        public static final int accessibility_custom_action_20 = 0x7f07000e;
        public static final int accessibility_custom_action_21 = 0x7f07000f;
        public static final int accessibility_custom_action_22 = 0x7f070010;
        public static final int accessibility_custom_action_23 = 0x7f070011;
        public static final int accessibility_custom_action_24 = 0x7f070012;
        public static final int accessibility_custom_action_25 = 0x7f070013;
        public static final int accessibility_custom_action_26 = 0x7f070014;
        public static final int accessibility_custom_action_27 = 0x7f070015;
        public static final int accessibility_custom_action_28 = 0x7f070016;
        public static final int accessibility_custom_action_29 = 0x7f070017;
        public static final int accessibility_custom_action_3 = 0x7f070018;
        public static final int accessibility_custom_action_30 = 0x7f070019;
        public static final int accessibility_custom_action_31 = 0x7f07001a;
        public static final int accessibility_custom_action_4 = 0x7f07001b;
        public static final int accessibility_custom_action_5 = 0x7f07001c;
        public static final int accessibility_custom_action_6 = 0x7f07001d;
        public static final int accessibility_custom_action_7 = 0x7f07001e;
        public static final int accessibility_custom_action_8 = 0x7f07001f;
        public static final int accessibility_custom_action_9 = 0x7f070020;
        public static final int action_container = 0x7f070021;
        public static final int action_divider = 0x7f070022;
        public static final int action_image = 0x7f070023;
        public static final int action_text = 0x7f070024;
        public static final int actions = 0x7f070025;
        public static final int adjust_height = 0x7f070026;
        public static final int adjust_width = 0x7f070027;
        public static final int androidx_compose_ui_view_composition_context = 0x7f070028;
        public static final int async = 0x7f070029;
        public static final int auto = 0x7f07002a;
        public static final int blocking = 0x7f07002b;
        public static final int chronometer = 0x7f07002c;
        public static final int compose_view_saveable_id_tag = 0x7f07002d;
        public static final int consume_window_insets_tag = 0x7f07002e;
        public static final int dark = 0x7f07002f;
        public static final int dialog_button = 0x7f070030;
        public static final int edit_text_id = 0x7f070031;
        public static final int forever = 0x7f070032;
        public static final int fragment_container_view_tag = 0x7f070033;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f070034;
        public static final int hide_ime_id = 0x7f070035;
        public static final int hide_in_inspector_tag = 0x7f070036;
        public static final int icon = 0x7f070037;
        public static final int icon_group = 0x7f070038;
        public static final int icon_only = 0x7f070039;
        public static final int info = 0x7f07003a;
        public static final int inspection_slot_table_set = 0x7f07003b;
        public static final int is_pooling_container_tag = 0x7f07003c;
        public static final int italic = 0x7f07003d;
        public static final int light = 0x7f07003e;
        public static final int line1 = 0x7f07003f;
        public static final int line3 = 0x7f070040;
        public static final int nav_controller_view_tag = 0x7f070041;
        public static final int none = 0x7f070042;
        public static final int normal = 0x7f070043;
        public static final int notification_background = 0x7f070044;
        public static final int notification_main_column = 0x7f070045;
        public static final int notification_main_column_container = 0x7f070046;
        public static final int pooling_container_listener_holder_tag = 0x7f070047;
        public static final int report_drawn = 0x7f070048;
        public static final int right_icon = 0x7f070049;
        public static final int right_side = 0x7f07004a;
        public static final int special_effects_controller_view_tag = 0x7f07004b;
        public static final int splashscreen_icon_view = 0x7f07004c;
        public static final int standard = 0x7f07004d;
        public static final int tag_accessibility_actions = 0x7f07004e;
        public static final int tag_accessibility_clickable_spans = 0x7f07004f;
        public static final int tag_accessibility_heading = 0x7f070050;
        public static final int tag_accessibility_pane_title = 0x7f070051;
        public static final int tag_on_apply_window_listener = 0x7f070052;
        public static final int tag_on_receive_content_listener = 0x7f070053;
        public static final int tag_on_receive_content_mime_types = 0x7f070054;
        public static final int tag_screen_reader_focusable = 0x7f070055;
        public static final int tag_state_description = 0x7f070056;
        public static final int tag_transition_group = 0x7f070057;
        public static final int tag_unhandled_key_event_manager = 0x7f070058;
        public static final int tag_unhandled_key_listeners = 0x7f070059;
        public static final int tag_window_insets_animation_callback = 0x7f07005a;
        public static final int text = 0x7f07005b;
        public static final int text2 = 0x7f07005c;
        public static final int time = 0x7f07005d;
        public static final int title = 0x7f07005e;
        public static final int view_tree_lifecycle_owner = 0x7f07005f;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f070060;
        public static final int view_tree_saved_state_registry_owner = 0x7f070061;
        public static final int view_tree_view_model_store_owner = 0x7f070062;
        public static final int visible_removing_fragment_view_tag = 0x7f070063;
        public static final int wide = 0x7f070064;
        public static final int wrapped_composition_tag = 0x7f070065;
    }

    public static final class integer {
        public static final int default_icon_animation_duration = 0x7f080000;
        public static final int google_play_services_version = 0x7f080001;
        public static final int status_bar_notification_info_maxnum = 0x7f080003;
    }

    public static final class layout {
        public static final int custom_dialog = 0x7f090000;
        public static final int ime_base_split_test_activity = 0x7f090001;
        public static final int ime_secondary_split_test_activity = 0x7f090002;
        public static final int notification_action = 0x7f090003;
        public static final int notification_action_tombstone = 0x7f090004;
        public static final int notification_template_custom_big = 0x7f090005;
        public static final int notification_template_icon_group = 0x7f090006;
        public static final int notification_template_part_chronometer = 0x7f090007;
        public static final int notification_template_part_time = 0x7f090008;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f0a0000;
        public static final int ic_launcher_round = 0x7f0a0001;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f0c0000;
        public static final int app_name = 0x7f0c0001;
        public static final int call_notification_answer_action = 0x7f0c0002;
        public static final int call_notification_answer_video_action = 0x7f0c0003;
        public static final int call_notification_decline_action = 0x7f0c0004;
        public static final int call_notification_hang_up_action = 0x7f0c0005;
        public static final int call_notification_incoming_text = 0x7f0c0006;
        public static final int call_notification_ongoing_text = 0x7f0c0007;
        public static final int call_notification_screening_text = 0x7f0c0008;
        public static final int close_drawer = 0x7f0c0009;
        public static final int close_sheet = 0x7f0c000a;
        public static final int common_google_play_services_enable_button = 0x7f0c000b;
        public static final int common_google_play_services_enable_text = 0x7f0c000c;
        public static final int common_google_play_services_enable_title = 0x7f0c000d;
        public static final int common_google_play_services_install_button = 0x7f0c000e;
        public static final int common_google_play_services_install_text = 0x7f0c000f;
        public static final int common_google_play_services_install_title = 0x7f0c0010;
        public static final int common_google_play_services_notification_channel_name = 0x7f0c0011;
        public static final int common_google_play_services_notification_ticker = 0x7f0c0012;
        public static final int common_google_play_services_unknown_issue = 0x7f0c0013;
        public static final int common_google_play_services_unsupported_text = 0x7f0c0014;
        public static final int common_google_play_services_update_button = 0x7f0c0015;
        public static final int common_google_play_services_update_text = 0x7f0c0016;
        public static final int common_google_play_services_update_title = 0x7f0c0017;
        public static final int common_google_play_services_updating_text = 0x7f0c0018;
        public static final int common_google_play_services_wear_update_text = 0x7f0c0019;
        public static final int common_open_on_phone = 0x7f0c001a;
        public static final int consent_accept = 0x7f0c001d;
        public static final int consent_title = 0x7f0c001e;
        public static final int default_error_message = 0x7f0c001f;
        public static final int default_popup_window_title = 0x7f0c0020;
        public static final int firebase_database_url = 0x7f0c0022;
        public static final int gcm_defaultSenderId = 0x7f0c0023;
        public static final int google_api_key = 0x7f0c0024;
        public static final int google_app_id = 0x7f0c0025;
        public static final int google_crash_reporting_api_key = 0x7f0c0026;
        public static final int google_storage_bucket = 0x7f0c0027;
        public static final int in_progress = 0x7f0c0028;
        public static final int indeterminate = 0x7f0c0029;
        public static final int m3c_dialog = 0x7f0c004e;
        public static final int navigation_menu = 0x7f0c0063;
        public static final int not_selected = 0x7f0c0064;
        public static final int project_id = 0x7f0c0065;
        public static final int range_end = 0x7f0c0066;
        public static final int range_start = 0x7f0c0067;
        public static final int selected = 0x7f0c0068;
        public static final int state_empty = 0x7f0c0069;
        public static final int state_off = 0x7f0c006a;
        public static final int state_on = 0x7f0c006b;
        public static final int status_bar_notification_info_overflow = 0x7f0c006c;
        public static final int switch_role = 0x7f0c006d;
        public static final int tab = 0x7f0c006e;
        public static final int template_percent = 0x7f0c006f;
        public static final int web_download_failed = 0x7f0c0072;
        public static final int web_download_progress = 0x7f0c0073;
        public static final int web_download_saved = 0x7f0c0074;
        public static final int web_error_generic_body = 0x7f0c0075;
        public static final int web_error_generic_title = 0x7f0c0076;
        public static final int web_error_offline_body = 0x7f0c0077;
        public static final int web_error_offline_title = 0x7f0c0078;
        public static final int web_error_retry = 0x7f0c0079;
        public static final int web_no_app = 0x7f0c007a;
    }

    public static final class style {
        public static final int DialogWindowTheme = 0x7f0d0007;
        public static final int TextAppearance_Compat_Notification = 0x7f0d000c;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0d000d;
        public static final int TextAppearance_Compat_Notification_Line2 = 0x7f0d000e;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0d000f;
        public static final int TextAppearance_Compat_Notification_Title = 0x7f0d0010;
        public static final int Theme_TrackRunVillage = 0x7f0d0014;
        public static final int Theme_Village = 0x7f0d0015;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0d0016;
        public static final int Widget_Compat_NotificationActionText = 0x7f0d0017;
    }

    public static final class xml {
        public static final int appsflyer_backup_rules = 0x7f0f0000;
        public static final int network_security_config = 0x7f0f0001;
        public static final int splits0 = 0x7f0f0002;
    }
}
