package ru.ozon.app.android.travel.feature.avia.widgets.aviaCheckTariffs.view;

import androidx.constraintlayout.widget.d;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;
import kotlin.jvm.internal.AbstractC7737t;
import kotlin.jvm.internal.Intrinsics;
import ru.ozon.app.android.travel.molecules.view.priceCard.PriceCardView;
import ru.ozon.app.android.travel.utils.extensions.ConstraintLayoutExtensionsKt;
import ru.ozon.uni.android.atom.badge.BadgeView;
import ru.ozon.uni.android.atom.image.Image;
import ru.ozon.uni.android.atom.price.ui.PriceAtomView;
import ru.ozon.uni.android.atom.text.TextAtomV2View;

@Metadata(d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0010\u0002\n\u0002\b\u0003\u0010\u0004\u001a\u00020\u0001*\u00020\u0000H\n¢\u0006\u0004\b\u0002\u0010\u0003"}, d2 = {"Landroidx/constraintlayout/widget/d;", "", "invoke", "(Landroidx/constraintlayout/widget/d;)V", "<anonymous>"}, k = 3, mv = {2, 0, 0})
/* loaded from: classes10.dex */
final class AviaCheckTariffsView$setConstraints$1 extends AbstractC7737t implements Function1<d, Unit> {
    final /* synthetic */ AviaCheckTariffsView this$0;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    AviaCheckTariffsView$setConstraints$1(AviaCheckTariffsView aviaCheckTariffsView) {
        super(1);
        this.this$0 = aviaCheckTariffsView;
    }

    @Override // kotlin.jvm.functions.Function1
    public /* bridge */ /* synthetic */ Unit invoke(d dVar) {
        invoke2(dVar);
        return Unit.f71690a;
    }

    /* renamed from: invoke, reason: avoid collision after fix types in other method */
    public final void invoke2(d applyConstraint) {
        Image image;
        Image image2;
        TextAtomV2View titleTAV;
        int i11;
        TextAtomV2View titleTAV2;
        int i12;
        TextAtomV2View titleTAV3;
        Image image3;
        int i13;
        PriceCardView priceCardView;
        int i14;
        PriceCardView priceCardView2;
        TextAtomV2View titleTAV4;
        int i15;
        PriceCardView priceCardView3;
        PriceCardView priceCardView4;
        int i16;
        PriceCardView priceCardView5;
        PriceCardView priceCardView6;
        PriceCardView priceCardView7;
        PriceCardView priceCardView8;
        PriceCardView priceCardView9;
        int i17;
        PriceCardView priceCardView10;
        PriceAtomView pricePAV;
        int i18;
        PriceAtomView pricePAV2;
        PriceCardView priceCardView11;
        int i19;
        BadgeView milesBadgeBV;
        int i21;
        BadgeView milesBadgeBV2;
        PriceAtomView pricePAV3;
        int i22;
        BadgeView milesBadgeBV3;
        int i23;
        BadgeView milesBadgeBV4;
        TextAtomV2View routeTAV;
        BadgeView milesBadgeBV5;
        int i24;
        TextAtomV2View routeTAV2;
        int i25;
        TextAtomV2View routeTAV3;
        int i26;
        AviaCheckTariffsView$benefitsListRV$1 aviaCheckTariffsView$benefitsListRV$1;
        TextAtomV2View routeTAV4;
        int i27;
        AviaCheckTariffsView$benefitsListRV$1 aviaCheckTariffsView$benefitsListRV$12;
        AviaCheckTariffsShowMoreButtonView aviaCheckTariffsShowMoreButtonView;
        AviaCheckTariffsView$benefitsListRV$1 aviaCheckTariffsView$benefitsListRV$13;
        int i28;
        AviaCheckTariffsView$benefitsListRV$1 aviaCheckTariffsView$benefitsListRV$14;
        int i29;
        AviaCheckTariffsView$benefitsListRV$1 aviaCheckTariffsView$benefitsListRV$15;
        AviaCheckTariffsView$benefitsListRV$1 aviaCheckTariffsView$benefitsListRV$16;
        int i31;
        AviaCheckTariffsView$benefitsListRV$1 aviaCheckTariffsView$benefitsListRV$17;
        AviaCheckTariffsShowMoreButtonView aviaCheckTariffsShowMoreButtonView2;
        AviaCheckTariffsView$benefitsListRV$1 aviaCheckTariffsView$benefitsListRV$18;
        int i32;
        AviaCheckTariffsShowMoreButtonView aviaCheckTariffsShowMoreButtonView3;
        int i33;
        AviaCheckTariffsShowMoreButtonView aviaCheckTariffsShowMoreButtonView4;
        int i34;
        AviaCheckTariffsShowMoreButtonView aviaCheckTariffsShowMoreButtonView5;
        int i35;
        AviaCheckTariffsShowMoreButtonView aviaCheckTariffsShowMoreButtonView6;
        AviaCheckTariffsShowMoreButtonView aviaCheckTariffsShowMoreButtonView7;
        Intrinsics.checkNotNullParameter(applyConstraint, "$this$applyConstraint");
        image = this.this$0.imageI;
        ConstraintLayoutExtensionsKt.topToParent(applyConstraint, image);
        image2 = this.this$0.imageI;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, image2);
        titleTAV = this.this$0.getTitleTAV();
        i11 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.topToParent(applyConstraint, titleTAV, i11);
        titleTAV2 = this.this$0.getTitleTAV();
        i12 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, titleTAV2, i12);
        titleTAV3 = this.this$0.getTitleTAV();
        image3 = this.this$0.imageI;
        i13 = this.this$0.dp2;
        ConstraintLayoutExtensionsKt.endToStart(applyConstraint, titleTAV3, image3, i13);
        priceCardView = this.this$0.discountPriceCard;
        i14 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, priceCardView, i14);
        priceCardView2 = this.this$0.discountPriceCard;
        titleTAV4 = this.this$0.getTitleTAV();
        i15 = this.this$0.dp4;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, priceCardView2, titleTAV4, i15);
        priceCardView3 = this.this$0.originalPriceCard;
        priceCardView4 = this.this$0.discountPriceCard;
        i16 = this.this$0.dp12;
        ConstraintLayoutExtensionsKt.startToEnd(applyConstraint, priceCardView3, priceCardView4, i16);
        priceCardView5 = this.this$0.originalPriceCard;
        priceCardView6 = this.this$0.discountPriceCard;
        ConstraintLayoutExtensionsKt.topToTop(applyConstraint, priceCardView5, priceCardView6);
        priceCardView7 = this.this$0.originalPriceCard;
        priceCardView8 = this.this$0.discountPriceCard;
        ConstraintLayoutExtensionsKt.bottomToBottom(applyConstraint, priceCardView7, priceCardView8);
        priceCardView9 = this.this$0.originalPriceCard;
        i17 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, priceCardView9, i17);
        priceCardView10 = this.this$0.originalPriceCard;
        applyConstraint.c0(0.0f, priceCardView10.getId());
        pricePAV = this.this$0.getPricePAV();
        i18 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, pricePAV, i18);
        pricePAV2 = this.this$0.getPricePAV();
        priceCardView11 = this.this$0.discountPriceCard;
        i19 = this.this$0.dp4;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, pricePAV2, priceCardView11, i19);
        milesBadgeBV = this.this$0.getMilesBadgeBV();
        i21 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, milesBadgeBV, i21);
        milesBadgeBV2 = this.this$0.getMilesBadgeBV();
        pricePAV3 = this.this$0.getPricePAV();
        i22 = this.this$0.dp4;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, milesBadgeBV2, pricePAV3, i22);
        milesBadgeBV3 = this.this$0.getMilesBadgeBV();
        i23 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, milesBadgeBV3, i23);
        milesBadgeBV4 = this.this$0.getMilesBadgeBV();
        applyConstraint.c0(0.0f, milesBadgeBV4.getId());
        routeTAV = this.this$0.getRouteTAV();
        milesBadgeBV5 = this.this$0.getMilesBadgeBV();
        i24 = this.this$0.dp12;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, routeTAV, milesBadgeBV5, i24);
        routeTAV2 = this.this$0.getRouteTAV();
        i25 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, routeTAV2, i25);
        routeTAV3 = this.this$0.getRouteTAV();
        i26 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, routeTAV3, i26);
        aviaCheckTariffsView$benefitsListRV$1 = this.this$0.benefitsListRV;
        routeTAV4 = this.this$0.getRouteTAV();
        i27 = this.this$0.dp8;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, aviaCheckTariffsView$benefitsListRV$1, routeTAV4, i27);
        aviaCheckTariffsView$benefitsListRV$12 = this.this$0.benefitsListRV;
        aviaCheckTariffsShowMoreButtonView = this.this$0.showMoreButtonView;
        ConstraintLayoutExtensionsKt.bottomToTop(applyConstraint, aviaCheckTariffsView$benefitsListRV$12, aviaCheckTariffsShowMoreButtonView);
        aviaCheckTariffsView$benefitsListRV$13 = this.this$0.benefitsListRV;
        i28 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, aviaCheckTariffsView$benefitsListRV$13, i28);
        aviaCheckTariffsView$benefitsListRV$14 = this.this$0.benefitsListRV;
        i29 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, aviaCheckTariffsView$benefitsListRV$14, i29);
        aviaCheckTariffsView$benefitsListRV$15 = this.this$0.benefitsListRV;
        applyConstraint.f0(0.0f, aviaCheckTariffsView$benefitsListRV$15.getId());
        aviaCheckTariffsView$benefitsListRV$16 = this.this$0.benefitsListRV;
        int id2 = aviaCheckTariffsView$benefitsListRV$16.getId();
        i31 = this.this$0.dp16;
        applyConstraint.Z(id2, 4, i31);
        aviaCheckTariffsView$benefitsListRV$17 = this.this$0.benefitsListRV;
        applyConstraint.g0(aviaCheckTariffsView$benefitsListRV$17.getId(), 2);
        aviaCheckTariffsShowMoreButtonView2 = this.this$0.showMoreButtonView;
        aviaCheckTariffsView$benefitsListRV$18 = this.this$0.benefitsListRV;
        i32 = this.this$0.dp4;
        ConstraintLayoutExtensionsKt.topToBottom(applyConstraint, aviaCheckTariffsShowMoreButtonView2, aviaCheckTariffsView$benefitsListRV$18, i32);
        aviaCheckTariffsShowMoreButtonView3 = this.this$0.showMoreButtonView;
        i33 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.bottomToParent(applyConstraint, aviaCheckTariffsShowMoreButtonView3, i33);
        aviaCheckTariffsShowMoreButtonView4 = this.this$0.showMoreButtonView;
        i34 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.startToParent(applyConstraint, aviaCheckTariffsShowMoreButtonView4, i34);
        aviaCheckTariffsShowMoreButtonView5 = this.this$0.showMoreButtonView;
        i35 = this.this$0.dp16;
        ConstraintLayoutExtensionsKt.endToParent(applyConstraint, aviaCheckTariffsShowMoreButtonView5, i35);
        aviaCheckTariffsShowMoreButtonView6 = this.this$0.showMoreButtonView;
        applyConstraint.f0(0.0f, aviaCheckTariffsShowMoreButtonView6.getId());
        aviaCheckTariffsShowMoreButtonView7 = this.this$0.showMoreButtonView;
        applyConstraint.c0(0.0f, aviaCheckTariffsShowMoreButtonView7.getId());
    }
}
