package com.icewinter.flow.winter.icecatch;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int alpha = 0x7f030003;
        public static final int font = 0x7f030018;
        public static final int fontProviderAuthority = 0x7f030019;
        public static final int fontProviderCerts = 0x7f03001a;
        public static final int fontProviderFallbackQuery = 0x7f03001b;
        public static final int fontProviderFetchStrategy = 0x7f03001c;
        public static final int fontProviderFetchTimeout = 0x7f03001d;
        public static final int fontProviderPackage = 0x7f03001e;
        public static final int fontProviderQuery = 0x7f03001f;
        public static final int fontProviderSystemFontFamily = 0x7f030020;
        public static final int fontStyle = 0x7f030021;
        public static final int fontVariationSettings = 0x7f030022;
        public static final int fontWeight = 0x7f030023;
        public static final int lStar = 0x7f030028;
        public static final int ttcIndex = 0x7f03004a;
    }

    public static final class dimen {
        public static final int compat_notification_large_icon_max_height = 0x7f050005;
        public static final int compat_notification_large_icon_max_width = 0x7f050006;
    }

    public static final class drawable {
        public static final int app_logo = 0x7f060001;
        public static final int bg = 0x7f060003;
        public static final int blue_fish = 0x7f060004;
        public static final int bucket = 0x7f060005;
        public static final int button = 0x7f060006;
        public static final int exit = 0x7f06001a;
        public static final int green_fish = 0x7f06001d;
        public static final int ic_launcher_background = 0x7f060024;
        public static final int load1 = 0x7f060026;
        public static final int load2 = 0x7f060027;
        public static final int ok = 0x7f060035;
        public static final int orange_fish = 0x7f060036;
        public static final int purple_fish = 0x7f060037;
        public static final int red_fish = 0x7f060038;
        public static final int yellow_fish = 0x7f060039;
    }

    public static final class font {
        public static final int winter_app_font = 0x7f070000;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f080000;
        public static final int accessibility_custom_action_0 = 0x7f080001;
        public static final int accessibility_custom_action_1 = 0x7f080002;
        public static final int accessibility_custom_action_10 = 0x7f080003;
        public static final int accessibility_custom_action_11 = 0x7f080004;
        public static final int accessibility_custom_action_12 = 0x7f080005;
        public static final int accessibility_custom_action_13 = 0x7f080006;
        public static final int accessibility_custom_action_14 = 0x7f080007;
        public static final int accessibility_custom_action_15 = 0x7f080008;
        public static final int accessibility_custom_action_16 = 0x7f080009;
        public static final int accessibility_custom_action_17 = 0x7f08000a;
        public static final int accessibility_custom_action_18 = 0x7f08000b;
        public static final int accessibility_custom_action_19 = 0x7f08000c;
        public static final int accessibility_custom_action_2 = 0x7f08000d;
        public static final int accessibility_custom_action_20 = 0x7f08000e;
        public static final int accessibility_custom_action_21 = 0x7f08000f;
        public static final int accessibility_custom_action_22 = 0x7f080010;
        public static final int accessibility_custom_action_23 = 0x7f080011;
        public static final int accessibility_custom_action_24 = 0x7f080012;
        public static final int accessibility_custom_action_25 = 0x7f080013;
        public static final int accessibility_custom_action_26 = 0x7f080014;
        public static final int accessibility_custom_action_27 = 0x7f080015;
        public static final int accessibility_custom_action_28 = 0x7f080016;
        public static final int accessibility_custom_action_29 = 0x7f080017;
        public static final int accessibility_custom_action_3 = 0x7f080018;
        public static final int accessibility_custom_action_30 = 0x7f080019;
        public static final int accessibility_custom_action_31 = 0x7f08001a;
        public static final int accessibility_custom_action_4 = 0x7f08001b;
        public static final int accessibility_custom_action_5 = 0x7f08001c;
        public static final int accessibility_custom_action_6 = 0x7f08001d;
        public static final int accessibility_custom_action_7 = 0x7f08001e;
        public static final int accessibility_custom_action_8 = 0x7f08001f;
        public static final int accessibility_custom_action_9 = 0x7f080020;
        public static final int action_container = 0x7f080021;
        public static final int action_divider = 0x7f080022;
        public static final int action_image = 0x7f080023;
        public static final int action_text = 0x7f080024;
        public static final int actions = 0x7f080025;
        public static final int adjacent = 0x7f080026;
        public static final int adjust_height = 0x7f080027;
        public static final int adjust_width = 0x7f080028;
        public static final int always = 0x7f080029;
        public static final int alwaysAllow = 0x7f08002a;
        public static final int alwaysDisallow = 0x7f08002b;
        public static final int androidx_compose_ui_view_compose_view_context = 0x7f08002c;
        public static final int androidx_compose_ui_view_composition_context = 0x7f08002d;
        public static final int androidx_window_activity_scope = 0x7f08002e;
        public static final int async = 0x7f08002f;
        public static final int auto = 0x7f080030;
        public static final int auto_clear_focus_behavior_tag = 0x7f080031;
        public static final int blocking = 0x7f080032;
        public static final int bottomToTop = 0x7f080033;
        public static final int chronometer = 0x7f080034;
        public static final int compose_prefetch_scheduler = 0x7f080035;
        public static final int compose_view_saveable_id_tag = 0x7f080036;
        public static final int consume_window_insets_tag = 0x7f080037;
        public static final int dark = 0x7f080038;
        public static final int dialog_button = 0x7f080039;
        public static final int draggable = 0x7f08003a;
        public static final int edit_text_id = 0x7f08003b;
        public static final int fixed = 0x7f08003c;
        public static final int forever = 0x7f08003d;
        public static final int fragment_container_view_tag = 0x7f08003e;
        public static final int ghost_view = 0x7f08003f;
        public static final int ghost_view_holder = 0x7f080040;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f080041;
        public static final int hide_ime_id = 0x7f080042;
        public static final int hide_in_inspector_tag = 0x7f080043;
        public static final int icon = 0x7f080044;
        public static final int icon_group = 0x7f080045;
        public static final int icon_only = 0x7f080046;
        public static final int info = 0x7f080047;
        public static final int inspection_slot_table_set = 0x7f080048;
        public static final int is_pooling_container_tag = 0x7f080049;
        public static final int italic = 0x7f08004a;
        public static final int jumpCut = 0x7f08004b;
        public static final int light = 0x7f08004c;
        public static final int line1 = 0x7f08004d;
        public static final int line3 = 0x7f08004e;
        public static final int locale = 0x7f08004f;
        public static final int ltr = 0x7f080050;
        public static final int nav_controller_view_tag = 0x7f080051;
        public static final int never = 0x7f080052;
        public static final int none = 0x7f080053;
        public static final int normal = 0x7f080054;
        public static final int notification_background = 0x7f080055;
        public static final int notification_main_column = 0x7f080056;
        public static final int notification_main_column_container = 0x7f080057;
        public static final int parent_matrix = 0x7f080058;
        public static final int pooling_container_listener_holder_tag = 0x7f080059;
        public static final int report_drawn = 0x7f08005a;
        public static final int right_icon = 0x7f08005b;
        public static final int right_side = 0x7f08005c;
        public static final int rtl = 0x7f08005d;
        public static final int save_non_transition_alpha = 0x7f08005e;
        public static final int save_overlay_view = 0x7f08005f;
        public static final int special_effects_controller_view_tag = 0x7f080060;
        public static final int standard = 0x7f080061;
        public static final int systemDefault = 0x7f080062;
        public static final int tag_accessibility_actions = 0x7f080063;
        public static final int tag_accessibility_clickable_spans = 0x7f080064;
        public static final int tag_accessibility_heading = 0x7f080065;
        public static final int tag_accessibility_pane_title = 0x7f080066;
        public static final int tag_compat_insets_dispatch = 0x7f080067;
        public static final int tag_on_apply_window_listener = 0x7f080068;
        public static final int tag_on_receive_content_listener = 0x7f080069;
        public static final int tag_on_receive_content_mime_types = 0x7f08006a;
        public static final int tag_screen_reader_focusable = 0x7f08006b;
        public static final int tag_state_description = 0x7f08006c;
        public static final int tag_system_bar_state_monitor = 0x7f08006d;
        public static final int tag_transition_group = 0x7f08006e;
        public static final int tag_unhandled_key_event_manager = 0x7f08006f;
        public static final int tag_unhandled_key_listeners = 0x7f080070;
        public static final int tag_window_insets_animation_callback = 0x7f080071;
        public static final int text = 0x7f080072;
        public static final int text2 = 0x7f080073;
        public static final int time = 0x7f080074;
        public static final int title = 0x7f080075;
        public static final int topToBottom = 0x7f080076;
        public static final int transition_clip = 0x7f080077;
        public static final int transition_current_scene = 0x7f080078;
        public static final int transition_image_transform = 0x7f080079;
        public static final int transition_layout_save = 0x7f08007a;
        public static final int transition_pause_alpha = 0x7f08007b;
        public static final int transition_position = 0x7f08007c;
        public static final int transition_scene_layoutid_cache = 0x7f08007d;
        public static final int transition_transform = 0x7f08007e;
        public static final int view_tree_disjoint_parent = 0x7f08007f;
        public static final int view_tree_lifecycle_owner = 0x7f080080;
        public static final int view_tree_navigation_event_dispatcher_owner = 0x7f080081;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f080082;
        public static final int view_tree_saved_state_registry_owner = 0x7f080083;
        public static final int view_tree_view_model_store_owner = 0x7f080084;
        public static final int visible_removing_fragment_view_tag = 0x7f080085;
        public static final int wide = 0x7f080086;
        public static final int wrapped_composition_tag = 0x7f080087;
    }

    public static final class integer {
        public static final int google_play_services_version = 0x7f090000;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f0b0000;
        public static final int ic_launcher_foreground = 0x7f0b0001;
        public static final int ic_launcher_round = 0x7f0b0002;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f0d0002;
        public static final int app_name = 0x7f0d0003;
        public static final int common_google_play_services_enable_button = 0x7f0d000d;
        public static final int common_google_play_services_enable_text = 0x7f0d000e;
        public static final int common_google_play_services_enable_title = 0x7f0d000f;
        public static final int common_google_play_services_install_button = 0x7f0d0010;
        public static final int common_google_play_services_install_text = 0x7f0d0011;
        public static final int common_google_play_services_install_title = 0x7f0d0012;
        public static final int common_google_play_services_notification_channel_name = 0x7f0d0013;
        public static final int common_google_play_services_notification_ticker = 0x7f0d0014;
        public static final int common_google_play_services_unknown_issue = 0x7f0d0015;
        public static final int common_google_play_services_unsupported_text = 0x7f0d0016;
        public static final int common_google_play_services_update_button = 0x7f0d0017;
        public static final int common_google_play_services_update_text = 0x7f0d0018;
        public static final int common_google_play_services_update_title = 0x7f0d0019;
        public static final int common_google_play_services_updating_text = 0x7f0d001a;
        public static final int common_google_play_services_wear_update_text = 0x7f0d001b;
        public static final int common_open_on_phone = 0x7f0d001c;
        public static final int gcm_defaultSenderId = 0x7f0d0023;
        public static final int google_api_key = 0x7f0d0024;
        public static final int google_app_id = 0x7f0d0025;
        public static final int google_storage_bucket = 0x7f0d0027;
        public static final int in_progress = 0x7f0d0028;
        public static final int indeterminate = 0x7f0d0029;
        public static final int not_selected = 0x7f0d006d;
        public static final int project_id = 0x7f0d006e;
        public static final int selected = 0x7f0d0071;
        public static final int state_empty = 0x7f0d0073;
        public static final int template_percent = 0x7f0d0079;
        public static final int title_activity_cold = 0x7f0d007a;
        public static final int title_activity_winter_game = 0x7f0d007b;
    }

    public static final class style {
        public static final int DialogWindowTheme = 0x7f0e0000;
        public static final int Theme_WinterFlow = 0x7f0e0009;
    }

    public static final class xml {
        public static final int backup_rules = 0x7f100000;
        public static final int data_extraction_rules = 0x7f100001;
        public static final int splits0 = 0x7f100002;
    }
}
